### ISSUE TITLE
New version release process

### ISSUE THREAD

**Issue by timrwood** [moment/moment#1041]
Write documentation for all changes. Document changes in the `readme.md`. Make sure breaking changes are highly visible.

Edit the following files with the new version number.

```
bower.json
package.json
moment.js // lines 2 and 14
```

Run the release grunt task.

```
grunt release
```

Commit the changes

```
git commit -am "Bumping version to ..."
```

Merge into master

```
git checkout master
git merge develop
```

Tag the release

```
git tag -am "2.1.0" "2.1.0"
```

Push the tag to Github.

```
git push --tags
```

Publish on npm

```
npm publish
```

Release on momentjs.com.

**Comment by maggiepint** [comment]
Closing. I believe that this has been completely subsumed by #1816

**Comment by corydeppen** [comment]
It doesn't look like the current `nuget-publish` task publishes the [Moment Timezone package][1] to NuGet. Can that be included in #1816 as well?

[1]: https://www.nuget.org/packages/Moment.Timezone.js/

**Comment by maggiepint** [comment]
I'm so glad I closed this. We find things like this out.
Moment Timezone is on an entirely different release cycle from Moment. It seems like something is up here, because the current version of moment timezone is 0.5.3, but NuGet is on 0.5.0 - which really stinks for anybody in Russia.

@corydeppen , I'm new to the moment team, so you will have to bear with me on this. I just pinged @timrwood on Slack to see if he can clarify what is supposed to happen.

**Comment by corydeppen** [comment]
Sorry, I didn't mean to imply this should be published using the same build task. I'm not able to comment on #1816 and I just wanted to mention it'd be great if a similar build process could be added to the Timezone project to publish the NuGet package.

I just pushed 0.5.3, as well 0.5.1 and 0.5.2, to NuGet so all releases should be available there now.

**Comment by timrwood** [comment]
Tracking adding this to moment-timezone here: https://github.com/moment/moment-timezone/issues/326
