### ISSUE TITLE
How to compare only HH:mm?

### ISSUE THREAD

**Issue by artworkad** [moment/moment#1199]
I am using moment.js with my node.js project

```
isWithinTime: function(end) {

     var moment = require('moment');
     var now = moment(new Date()).format('HH:mm');
     var end = moment(new Date(end)).format('HH:mm');

     if (now.toString() > end.toString()) {
         return false;
     }
     return true;
}
```

I want to compare only time in HH:mm format. However it does not work because

```
'7:00' > '2:00'
```

returns false. Any ideas how to compare HH:mm?

**Comment by rfossella** [comment]
After looking through other MomentJS questions I'm still stumped as to how one would use moment to simply compare **two different times** 

**I need (want) the day/date to be ignored.** 

Use case:
    I'm reading a schedule w/ start & end times from a config file.  This is done using Node.js
> Start time = 6:30 PM  
> End time = 3:30 AM

    var currentTime= moment();    // e.g. 11:00 pm
    var startTime = moment('06:30 pm', "HH:mm a");
    var endTime = moment('03:30 am', "HH:mm a");
    
    amIBetween = currentTime.isBetween(startTime , endTime);
    console.log(amIBetween);   //  returns false.  if date ignored I expect TRUE

My scenario is technically **spanning two days** and I understand why it's false.

I need (expect) moment to return TRUE - i.e. that currentTime isBeteen startTime and endTime and falls in that range. 

I thought I had it solved by checking if endTime hour is > 12 then add a day to make moment understand it's the following day.  e.g.

```
if (startTime.hour() >=12 && endTime.hour() <=12 )
	{
		endTime.add(1, "days");       // handle spanning days
	}

	var isBetween = currentTime.isBetween(startTime, endTime);   // TRUE

```

But if currentTime is also after midnight then it breaks - e.g.

01:30am will not be considered between 06:30pm and 03:30am  - also because of different days

Any other suggestions for accomplishing this and simply ignoring the day/date?

I'm finding it hard to believe that it's this complex, but maybe it is :\

--

Here's further clarification that issue arises with spanning days, even when trying to be more explicit:

    var currentTime= moment('11:00p', "HH:mm a");
    var startTime = moment('06:00p', "HH:mm a");
    var endTime = moment('03:30a', "HH:mm a");

    currentTime.toString(); //"Fri Oct 28 2016 23:00:00 GMT-0400"
    startTime.toString();   // "Fri Oct 28 2016 18:00:00 GMT-0400"
    endTime.toString();    // "Fri Oct 28 2016 03:30:00 GMT-0400"

    currentTime.isBetween(startTime, endTime);  // false
    currentTime.isAfter(endTime) && currentTime.isBefore(startTime); //false
    currentTime.isAfter(startTime) && currentTime.isBefore(endTime); //false

Seems kind of obvious that they'd be false since the *day/date* is considered by moment.  This is what I'm trying to get around.

The following would work:

    endTime.add(1, "days");
    currentTime.isBetween(startTime, endTime);  // TRUE

This would mean however, that I'd need to check if the START TIME was before 12AM && the ENDTIME as after 12AM then add 1 day to ENDTIME.

**Comment by icambron** [comment]
I guess I don't quite understand what you mean by "ignoring the day". If you're comparing these two times

```js
var startTime = moment('06:00p', "HH:mm a");
var endTime = moment('03:30a', "HH:mm a");
```

somehow the system has to know that you mean 3:30 *tomorrow*. I mean, how could it ever work? Surely, you don't think that in the absence of day information that 3:30 AM is after 6:00 PM...The problem is that you have some extra context that Moment doesn't have, which is that the `endTime` is expected to be after the `startTime`; that's obvious from your variable names, but Moment doesn't and can't. You'll have to tell it.

So how about this:

```js
if (startTime.isAfter(endTime)){
  endTime.add(1, 'days');
}
```

**Comment by rfossella** [comment]
Yeah, I understand the confusion.  Without knowing that we mean "3:30am" is the next day it is tricky.

**Disregarding the day/date:**
_If I  ask, "is 11pm between 9pm and 3am" I expect the answer to be **true**.
If I  ask, "is 11pm between 3am and 9pm" I expect the answer to be **false**._

Since I can't simply ignore the date using moment I started checking for ALL times before/after 12 and ended up with:
```
if ( (startTime.hour() >=12 && endTime.hour() <=12 ) || endTime.isBefore(startTime) )
	{
		endTime.add(1, "days");       // handle spanning days endTime

		if (currentTime.hour() <=12 )
		{
			currentTime.add(1, "days");       // handle spanning days currentTime
		}
	}
```
The fiddle I have here displays my use case scenarios. Hope it's useful.
https://jsfiddle.net/rfossella/66wjtnvk/1/

Thanks again for your time (no pun intended :-)  )

**Comment by StefanRein** [comment]
Or just something like this function:

```javascript
function getTime(dateTime: Moment): Moment {
    return moment({h: dateTime.hours(), m: dateTime.minutes()});
}

const first: Moment = getTime( moment([2018, 5, 1, 18, 0, 0]) );
const second: Moment = getTime( moment([2013, 8, 2, 19, 0, 0]) );
const third: Moment = getTime( moment([2015, 3, 3, 17, 0, 0]) );

second.isAfter(first, 'minutes'); // true
first.isBefore(second, 'minutes'); // true
first.isAfter(second, 'minutes'); // false
second.isBefore(first, 'minutes'); // false

first.isBetween(second, third, 'minutes', '[]'); // true 
// => this is actually false if you try this => bug?!
// second.diff(first, 'minutes') => 60
// second.diff(third, 'minutes') => 120
// third.diff(first, 'minutes') => -60
// which is correct..

second.isBetween(first, third, 'minutes', '[]'); // false

```

So you could the is the MomentJS methods `isBetween, isAfter, isBefore` only with the time and not the date.

**Comment by nexkey-inc** [comment]
Still pretty stumped with this one too. I have spent more hours than I care to admit trying to work this out. @rfossella did you have any luck with a particular implementation? Thanks!

**Comment by rsmets** [comment]
Still pretty stumped by this one too. I have spent more on it than I care to admit! @Machibuse or @rfossella what implementation ended up working?

**Comment by kdavong** [comment]
I used to be stucked with same issue, and finally found a way to make it works 👍 formatting time in military time, I hope it might help...

`const isTimeBetween = function(startTime, endTime, serverTime) {
    let start = moment(startTime, "H:mm")
    let end = moment(endTime, "H:mm")
    let server = moment(serverTime, "H:mm")
    if (end < start) {
        return server>= start && server<= moment('23:59:59', "h:mm:ss") || serverTime >= moment('0:00:00', "h:mm:ss") && server< end;
    }
    return server>= start && server< end
}`

Then I can use this function like so:

`isTimeBetween('22:30', '3:00', '23:50')` return true
`isTimeBetween('22:30', '3:00', '1:50')` return true
`isTimeBetween('22:30', '3:00', '4:50')` return false

**Comment by googlicius** [comment]
@kdavong It's works very well, thank you!

**Comment by rfossella** [comment]
Hi,
I rechecked the fiddle I posted years ago and it is still active and still works.  FYI: My example does not introduce military time, in case you do need that.

The fiddle I have here displays my use case scenarios. Hope it's useful.
https://jsfiddle.net/rfossella/66wjtnvk/1/

Rob

**Comment by coderdave** [comment]
I'm late to the party, but what worked for me was to add an arbitrary date in the date string.

```
const startTime = "10:00 AM";
const endTime = "11:00 PM";
const startTimeWithDate = `2010-10-20 ${startTime}`;
const endTimeWithDate = `2010-10-20 ${endTime}`;

moment(startTimeWithDate).isAfter(endTimeWithDate, "minute"); // false

const startTime = "11:01 PM";
const endTime = "11:00 PM";
const startTimeWithDate = `2010-10-20 ${startTime}`;
const endTimeWithDate = `2010-10-20 ${endTime}`;

moment(startTimeWithDate).isAfter(endTimeWithDate, "minute"); // true
```

**Comment by SwapnilSoni1999** [comment]
Here's my approach after reading above comments
Usually we have different dates and different times 

Suppose we're filtering only from 4:00 PM to 5:00 PM dates but with different days doesn't matter 

Then what we can do is match it with same date


```js
const fromTime = '4:00 PM'
const toTime = '5:00 PM' 

myList.filter(ml => {
  const date = moment(ml.date)
  const sTime = moment(`${date.format('MM/DD/YYYY')} ${fromTime}`, 'MM/DD/YYYY HH:mm A')
  const eTime = moment(`${date.format('MM/DD/YYYY')} ${toTime}`, 'MM/DD/YYYY HH:mm A')
  return date.isBetween(sTime, eTime, 'minute', '[]')
})
```
