### ISSUE TITLE
Non-Gregorian calendars inside moment.js

### ISSUE THREAD

**Issue by ebraminio** [moment/moment#1454]
MediaWiki's date formatter can easily generates non-Gregorian calendars output.

This is a copy of the related parts of [the documentation](https://www.mediawiki.org/wiki/Help:Extension:ParserFunctions#.23time):

| Non-Gregorian calendars |  |
| --- | :-: |
| **Islamic** |  |
| xmj | Day of the month |
| xmF | Full month name |
| xmn | Month index |
| xmY | Full year |
| **Iranian (Jalaly)** |  |
| xij | Day of the month |
| xiF | Full month name |
| xin | Month index |
| xiY | Full year |
| xiy | 2-digit year |
| **Hebrew** |  |
| xjj | Day of the month |
| xjF | Full month name |
| xjt | Number of days in month |
| xjx | Genitive form of the month name |
| xjn | Month number |
| xjY | Full year |
| **Thai solar** |  |
| xkY | Full year |
| **Minguo/Juche year** |  |
| xoY | Full year |
| **Japanese nengo** |  |
| xtY | Full year |

With considering [this](https://github.com/wikimedia/mediawiki-core/blob/c2318e9d6b58d9191ce43588a82db8407e05170e/languages/Language.php#L1116) and [an example calendar algorithm](https://github.com/wikimedia/mediawiki-core/blob/c2318e9d6b58d9191ce43588a82db8407e05170e/languages/Language.php#L1434) from MediaWiki, this is my proposal:
- Define a separate folder/script inside moment.js project for actual calendar algorithm implementation (`xij`, `xiF`, . . .) but don't include that on moment.js core
- Original modules of extension calendars should just include the English translation and locales modules which handle the translation of needed calendars for a locale. A fallback to English (which provided by the algorithm itself) should be done also when translation is not available on a specific locale module
- Locale module should define their default date format with their related calendars
- Similar to MediaWiki date format convention, what available on above table (or same [moment-jalaali](https://github.com/jalaali/moment-jalaali)?)

With this design, using Iranian calendar on English and Gregorian calendar on Persian for example [both use-cases are important] would be easy.

I think if we decide about a design, implementing the needed change will be easier.

globalize also [has](https://github.com/jquery/globalize/blob/195f3f4b3725c9fd9cdc0014f61016de34b0076a/lib/cultures/globalize.culture.fa-IR.js) support of Persian calendar for example.

Thank you and sorry about spell/grammar/facts errors available

**Comment by Nate-Wilkins** [comment]
@ichernev How far along is this feature? This seems like it could be tied into extensibility with #1241

**Comment by glittle** [comment]
What is the status of pluggable calendar systems? Is it possible today? Is there documentation somewhere? Or does it still require plugins to implement?

**Comment by mj1856** [comment]
Still requires plugins.  A few are mentioned in the docs.

**Comment by mhf-ir** [comment]
For better algorithm of special calendars reference is here: with C,C++ and Java codes :
http://userguide.icu-project.org/datetime/calendar

 - Japanese
 - Buddhist
 - Chinese
 - Persian
 - Indian
 - Islamic
 - Hebrew
 - Indian
 - Coptic
 - Ethiopic

This will help for better i18n and l10n apps

**Comment by sandstrom** [comment]
How common are the other calendars? I know they are useful for traditional festivities and religious events, but to what extent are they really used in these countries in day-to-day activities? (like scheduling an appointment with a dentist) I'm just curious!

**Comment by glittle** [comment]
I don't know about others, but my interest is in the Wondrous calendar (Badí'). So far, it is a religious calendar used by the Baha'i Faith to schedule religious events, etc. However, at its core, it is a very practical solar calendar that will likely become better known in the years to come.

**Comment by ebraminio** [comment]
https://github.com/catull/calendariale is a complete and wonderful calendar converter implementation, I hope it could be used directly by this project someday.

**Comment by behrang** [comment]
Hello. I'm author of [moment-jalaali](https://github.com/jalaali/moment-jalaali) and some other Persian calendar implementations in [Jalaali](https://github.com/jalaali).

While developing `moment-jalaali`, my problem was `moment`'s lack of support for calendar systems. Since I needed to use both calendars (Gregorian and Jalaali) in my applications, I introduced new formatting/parsing tokens (like `jYY`, `jM`, `jD`). However, when people wanted to use `moment-jalaali` for date pickers, it was a very difficult task, since date pickers' codebase needed substantial changes and everywhere `.month()`, `.year()`, etc. were used needed to change. We tried a few times to fix this problem, but we failed and it is still an open issue.

I think if `moment` supports the concept of calendar systems and offloads the responsibility of calendar conversion to plugins, the problem will be fixed. For this, I don't think there is any need for new formatting/parsing tokens (at least for Persian calendar). However, everywhere calendar date is changed, should be refactored to support pluggable calendars. 

So for example, constructing new moment with a different calendar (`moment({calendar: 'Persian'})`), getting date part (`.year()`, `.dayOfYear()`, `.isLeapYear()`, `.daysInMonth()`), setting it (`.month(4)`), adding or subtracting (`.add(1, 'year')`, `.startOf('month')`), and formatting or parsing should be handled by plugins.

(@sandstrom Persian calendar is the official calendar in Iran and it is used everywhere, including scheduling appointments, banking, new year ceremony, ...).

**Comment by mj1856** [comment]
Relevent to this discussion also:  https://github.com/maggiepint/proposal-temporal/issues/5

**Comment by tomerm** [comment]
Support for non Gregorian calendars also assumes support for different types of numbering systems. For example:

- for Hijri (Islamic-civil, Islamic-tabular, Islamic-Umm al-Qura , Islamic-Religious) calendar support for Arabic -Indic (or Arabic-Eastern) digits (i.e. ٠,١,٢,٣,٤,٥,٦,٧,٨,٩) is required. For references please see:  https://en.wikipedia.org/wiki/Eastern_Arabic_numerals
- for Hebrew calendar (under Hebrew locale) support for Hebrew numerals (i.e. א, ב, ג, ד, ה, ו) is required. For references please see: https://en.wikipedia.org/wiki/Hebrew_numerals

Is there any plan to leverage http://numeraljs.com/ library for that purpose or moment.js envision development of local module / component for that purpose ?

**Comment by marwahaha** [comment]
I don't think we will pursue non-Gregorian calendars inside Moment.js 2.x, unless there are small ways we can help plugin authors. I'm worried that implementing @ichernev 's suggestions would require a large rewrite to the code.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
We will not support this feature.

**Comment by Cosmocruz** [comment]
any update on julian date
