### ISSUE TITLE
Parsing time to UTC ignores daylight saving time

### ISSUE THREAD

**Issue by mariusa** [moment/moment#1836]
Converting two times to UTC:

```
moment("2014-11-04 00:00 +02:00", "YYYY-MM-DD HH:mm Z").utc().format("YYYY-MM-DD HH:mm");
//"2014-11-03 22:00" 
moment("2014-08-04 00:00 +02:00", "YYYY-MM-DD HH:mm Z").utc().format("YYYY-MM-DD HH:mm");
//"2014-08-03 22:00"
```

The first one is correct during winter, the time difference being just 2hrs. However, during summer the time difference is 3 hrs. The 2nd should return "2014-08-03 21:00"

Should moment.js handle these, or the app? If the latter, is there anything in moment.js we could use to figure this out?

Saw there was some related discussion here: https://github.com/moment/moment/issues/1514

Thanks

**Comment by elgs** [comment]
Cannot moment be a bit smarter to take care of these things?

**Comment by mj1856** [comment]
@elgs in what way?  The issue here was incomplete information.  What would you expect it to do, make something up?

**Comment by elgs** [comment]
@mj1856 I apologize. I think I made a stupid mistake. I was trying to convert an UTC datetime to local datetime using moment. DST was not respected on conversion. Now I realized that the date is actually a date before DST started. It's my fault. Now I did some further tests, and found that actually moment takes care of DST correctly.

**Comment by mj1856** [comment]
@egls no problem.  :)

**Comment by nicoladj77** [comment]
@mj1856 I've got a different issue, always related to timezone and DST.

I'm parsing a utc date and then adding a Timezone

`var time      = momentjs.utc(startDate.full).tz('America/New_York');`

Timezone is defined as

```
moment.tz.add([
    'America/New_York|EST EDT|50 40|0101|1Lz50 1zb0 Op0'
]);

```

The problem is that it seems that moment it's not switching to it's not switching to EDT for dates which are later than the 6th of november. 

A live example: http://www.msgnetworks.com/teams/rangers/schedule/

You can see that on the 6th of November games are set as starting at 8PM instead of 7PM, it looks like momentjs is not realizing that it should switch to EDT.

**Comment by nicoladj77** [comment]
@mj1856 solved by updating the moment.timezone.js library.

**Comment by kamyarg** [comment]
btw, we had a similar problem. for anyone facing a similar issue:
we had:
`'America/Los_Angeles|PST PDT|80 70|0101|1Lzm0 1zb0 Op0'`
And It was not switching to PDT, after some debugging we found out that the hashes at the end (i.e. "1Lzm0 1zb0 Op0") where timestamps for the switch to next timezone.
we updates the zone info from [here](https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.9/moment-timezone-with-data.js).
now it is fixed.
Let me know if there is better solution.
hope it saves time for someone.
