### ISSUE TITLE
startOf confusion

### ISSUE THREAD

**Issue by RohovDmytro** [moment/moment#1847]
The docs are saying:

``` javascript
moment().startOf('year');    // set to January 1st, 12:00 am this year
```

The console is saying:

``` javascript
moment().startOf('year').toDate;    // Wed Jan 01 2014 00:00:00 GMT+0200 (EET)
```

It's not 12:00 am, it 00:00. 

And the second option is good for me. This is what I want and what seem logical. But then docs should be updated.

**Comment by adamreisnz** [comment]
> 12:00 am is 00:00/midnight -- 12:00 pm is noon

That is actually incorrect, because pm stands for [Post Meridiem](https://www.merriam-webster.com/dictionary/post%20meridiem), meaning "after noon", so 12pm technically means 12 hours after noon, which is midnight.

The fact that moment parses midday/noon as 12pm is pretty confusing. But then again, the whole 12 hour clock is pretty ridiculous and confusing, so 🤷🏼‍♂️
