### ISSUE TITLE
Time setter bug in Safari 8.0

### ISSUE THREAD

**Issue by Koosmann** [moment/moment#2040]
With this [JSBin](http://jsbin.com/giwivumazu/1/edit?html,js,console), I get the expected time on Nov 2 (last sunday; writing this on Nov 7, 2014) in Chrome, FF, ad Safari.  However, in Safari, the hour changes depending on how many time setters I'm using after the day setter (one hour is subtracted for every time setter used).

The (potential) bug doesn't seem to appear when setting the day to anything other than Sunday/0.  I'm not sure how the it behaves on other days/times.

This looks like a bug, but please let me know if I'm missing something!

**Comment by Koosmann** [comment]
I've updated the [JSBin](http://jsbin.com/jilazipuxi/1/edit?html,js,console) to be this year's daylight savings time switch in November and the bug still exists in moment 2.9.0 (& still only in Safari).  

This seems like a pretty big issue for dates to be set incorrectly on one day of the year.

**Comment by maggiepint** [comment]
I got out the good old IPad 2 since it was the only Safari running device I had around, Safari for Windows having been killed.
I am not seeing this on there, even with switching to November 6 2016.

The set operators in moment really don't do much when it gets down to it. They basically just pass through to the date object. 
I'm guessing what you are/were seeing here is an issue with the date object in Safari.

I know it's been over a year (whoops!), but can this be replicated? I would need more specific information about the environment than just Safari.

**Comment by icambron** [comment]
First, @Koosmann, sorry no one responded to this for so long.

I suspect this is a bug in iOS Safari's handling of DST for your time zone. It's notoriously bad at that. Like Maggie says, Moment is just setting things on the date object, which isn't handling it incorrectly. So unfortunately, there was never anything we could do about it.
