### ISSUE TITLE
moment ICU format

### ISSUE THREAD

**Issue by Erwane** [moment/moment#2050]
Hi,

Why moment does not follow the ICU, like intl extension ?

for the day, ICU said : dd for 01-31 but moment use DD for the same thing.
http://www.icu-project.org/apiref/icu4c/classSimpleDateFormat.html#details

Thanks

**Comment by RinkAttendant6** [comment]
+1 for this. Supporting ICU tokens would be really helpful as the ECMAScript Internationalization API falls short of allowing custom date/time formats to be specified and instead forces the use of predefined CLDR formats (short, medium, long, full) for each locale.

It would make things much easier for those that use ICU4J (Java) and `IntlDateFormatter` (PHP) to use their existing formats instead of redefining them using Moment.js tokens.
