### ISSUE TITLE
Using add('d', 1) in Firefox on 06 January gives Groundhog Day (any year)

### ISSUE THREAD

**Issue by amIwho** [moment/moment#2071]
Hello, I use momentjs for calendar and generate list of days via add('d', 1). 
I have an interesting issue in Firefox with it.

Here is fiddle for it (please run by Firefox): http://jsfiddle.net/zvp4L1ug/

It appears on Januaries (version momentjs 2.3.1, but latest too gives bug) when I set value (any) and format:

![7b97fedc5c9b60d3578bfff93343c30f](https://cloud.githubusercontent.com/assets/2650331/5227926/f6e1d022-7713-11e4-8225-bae84a755860.png)

But when I don't set value and format all is ok.

![image](https://cloud.githubusercontent.com/assets/2650331/5227942/4ed48644-7714-11e4-8374-4ed79c9b7b89.png)

**Comment by icambron** [comment]
We rely on the browsers to get this right, so if the browser is bugged, so is Moment. The bug is certainly odd; Russia never had a DST in January, but if swapping in the fixed Date object fixed it, then it's definitely browser-level TZ issue. And I'm guessing it's been fixed, so I'm closing this ticket.
