### ISSUE TITLE
Manipulating dates does not update value returned by toISOString and toJSON functions

### ISSUE THREAD

**Issue by dplarina** [moment/moment#2076]
Using toISOString and toJSON functions outputs the original date instead of the manipulated date.

http://jsfiddle.net/wdnomhr8/

**Comment by maggiepint** [comment]
So, this feedback is coming a year and a half later (sorry), but I think the problem that you are seeing here is that the original date being parsed is actually October 30 if you are in UTC -4 or further West. This is because when the default Moment constructor is used, it will convert from the offset, to the local time. Thus, for me in -5:

```js
//October 30 at 11 PM is actual day parsed
moment("2014-10-31T04:00:00.000Z").format()
"2014-10-30T23:00:00-05:00"

//add one day, October 31 at 11 PM
moment("2014-10-31T04:00:00.000Z").add(1, 'days').format()
"2014-10-31T23:00:00-05:00"

//Start of October 31
moment("2014-10-31T04:00:00.000Z").add(1, 'days').startOf('day').format()
"2014-10-31T00:00:00-05:00"
```

The parsing guide has a section on this:
http://momentjs.com/guides/#/parsing/local-utc-zone/
