### ISSUE TITLE
Problem with ISO_8601 parsing.

### ISSUE THREAD

**Issue by FrikkinLazer** [moment/moment#2078]
This used to work in 2.6.0:

var a = new moment('2014-11-30T00:00:00+02:00')
a.format(moment.ISO_8601)

It does not work in 2.8.2 anymore.

**Comment by kashifshamaz21** [comment]
@ichernev `moment. ISO_8601` use to be a constant string until 2.6.0, but looks like from commit https://github.com/moment/moment/commit/87f841c47cf737e8f66b7119274a79d7c3214136 onwards, it got changed to a no-op function.
Not sure about the history around that merge, you might have more idea!

**Comment by icambron** [comment]
@kashifshamaz21 I think your analysis is wrong. It looks like `moment.ISO_8601` was added in 2.7, and any case was never meant for `format`, just parsing. I think what's happening is that someone saw the reference to the parsing option in the docs and started using it as a formatter in 2.6. But in 2.6 `moment.ISO_8601` was undefined, so they were really calling:

```
> moment().format(moment.I_TOTALLY_MADE_UP_THIS_CONST)
'2015-04-01T02:59:57-04:00'

//aka

> moment().format(undefined)
'2015-04-01T02:53:19-04:00'

//aka

> moment().format()
'2015-04-01T02:53:19-04:00'
```

So it worked because ISO-8601 is the default, and the constant was undefined. It doesn't work now because it is defined. The workaround for the OP's specific issue is to just remove the argument altogether (or, if they need to pass in a format because of how their code is structured, pass in `null` or `undefined`)
