### ISSUE TITLE
AMD: Multiple anonymous defines in locale bundles

### ISSUE THREAD

**Issue by selfawaresoup** [moment/moment#2113]
This affects the following files:
- `min/locales.js`
- `min/locales.min.js`
- `min/moment-with-locales.js`
- `min/moment-with-locales.min.js`

These files each contain multiple anonymous `define`s which makes it impossible to load them AMD style (e.g. with require.js).

The sources for each locale are simply concatenated in those files. To make them work properly, the locale module's name would have to be included in each locale's `define` call.

**Comment by lnwdr** [comment]
@ichernev One solution would be to use [named `define` calls](http://requirejs.org/docs/api.html#modulename) instead of anonymous ones. E.g.:

```js
// in: locale/de.js
define("moment-locale-de", ["moment"], function() { /* ... */ });
```

I'm just not sure about the naming scheme of the locale modules but since moment itself is also hard coded in the locale modules, I guess it could be ok. Right now, the locale files don't work at all with AMD loaders, when you want bundle them into a bigger JS file and this change wouldn't break anything. So why not?

**Comment by GabiAxel** [comment]
This is not just a problem with the locales. Removing the name from the module definition in 2.9.0 makes it impossible to concatenate the file with other modules, breaking builds that do it. May I suggest reverting this change?

**Comment by marwahaha** [comment]
@selfawaresoup @GabiAxel - is this still an issue?

**Comment by GabiAxel** [comment]
I haven't consumed it as AMD for a while, so it's no longer an issue for me.

**Comment by marwahaha** [comment]
I'm going to close. If any current AMD users still have bugs, do open an issue!
