### ISSUE TITLE
Moment returns invalid time in Day light saving mode

### ISSUE THREAD

**Issue by sreejith-m-sreedharan1987** [moment/moment#2144]
My timezone is New york ( GMT-500 on EST and GMT-400 on EDT). In New york, Day light saving for 2015 starts at Mar 8, 2015 02:00:00 ,

That means, if we pass this datetime to momentjs , it should return isDST() as true.

But for me ,
moment('Sun Mar 08 2015 02:15:00 GMT-0400 (EDT)').isDST();  

it returns false, // means it is not DST, but actually it is DST

When i execute ,

moment('Sun Mar 08 2015 02:15:00 GMT-400').isDSTShifted();

it returns false // means time is not shifted, but it is shifted - shifted 1 hour back wards then change to GMT-500 (EST), now it shows Sun Mar 08 2015 01:15:00 GMT-0500 (EST) which is wrong, since 02:15:00 is an invalid datetime, it should move forward 1 hour ideally.

When i execute,
moment('Sun Mar 08 2015 02:15:00 GMT-400').isValid();

it returns true //means date is valid, actually the date is not valid since time 02:15:00  does not exist on that date (Mar 08,2015)

The issue occurs in the 1 hour in the beginning of the transition from Non-DST to DST.

Kindly suggest a solution.
 
I need to get Sun Mar 08 2015 02:15:00 GMT-400 (EDT) as Sun Mar 08 2015 03:15:00 GMT-400 (EDT).

**Comment by ichernev** [comment]
First, you're relying in native Date object parsing, so your results will vary. On the other hand we don't support the case where you give a timestamp that is in two timezones (when the clock moves back) and specify explicitly a zone.

`isValid` is also not very reliable when using native Date constructor -- it basically returns true all the time, because it has no idea about the format and validity of the string.

`isDSTShifted` is for 'invalid' dates (shifted), but it also only works with moment parsing (string + format) or if the string is in iso format.

Nevertheless, in my timezone (America/Los_Angeles), where there is DST 2015, nov 1 at 2:00 am -> 1:00 am, tz switching from -7 pdt to -8 pst, here's what I get (it works):

```javascript
> moment('Sun Nov 01 2015 01:30:00 GMT-0700 (PDT)').isDST()
true
> moment('Sun Nov 01 2015 01:30:00 GMT-0800 (PST)').isDST()
false
```

Does that make sense?

**Comment by sreejith-m-sreedharan1987** [comment]
So, What is the way out ? In the case of Day light saving, 2AM is in EDT and 1AM in EST -- two timezones, i agree, as per your idea how can i fix the issue? How can I specify time in moment so that i get the correct results even for daylight saving? Thanks for your reply and waiting for the response.

**Comment by mj1856** [comment]
Sorry, just reading this conversation now.   The problem here is that the hour from 2:00 to 02:59:59.999 is skipped, so 2:15 is not a valid local time on this day.   It's common to think of "DST starting at 2:00", but what really happens is that as the clock *approaches* 2:00, it springs forward to 3:00.

When given an invalid time in this "gap", the decision to shift backwards or forwards during parsing is entirely based on the parser.  Since you're relying on the browser's parser you will indeed get different results depending on which browser you run on.  There's nothing moment can do to control that.

If you want to use moment's parser, you have to supply a format, like so:

```javascript
var m = moment('Sun Mar 08 2015 02:15:00 GMT-0400 (EDT)','ddd MMM DD YYYY HH:mm:ss [GMT]ZZ');
```

This will no longer use the browser's behavior.  Instead, it will determine the instantaneous point in time as specified by the date, time, and offset.  Then it will place that into the local time zone at the appropriate "real" local time.

```javascript
m.format();   // "2015-03-08T01:15:00-05:00"
```

Notice how the time went back to 1:15 and the offset changed to -05:00.   That's the equivalent instant as the one we started with, because both of those equate to "2015-03-08T06:15:00Z"  (UTC).

Also notice:

```javascript
m.isDST(); // false
```
Since the transition doesn't occur for another 45 minutes, this instant in time is *not* in DST.   This is the accurate response.

**Comment by mj1856** [comment]
One minor clarification to the above.  Since you include an offset, even the browser will apply that offset and land you at the same instant in time.  It's only when an offset is *not* included in the input string that the behavior is different between browsers with regard to choosing 1:15 or 3:15.
