### ISSUE TITLE
GMT format question

### ISSUE THREAD

**Issue by maiolica** [moment/moment#2171]
Maybe a silly question, but why are the results different?
```javascript
moment("2015-01-29 04:00").subtract(60, "m").format("YYYY-MM-DD HH:mm");
"2015-01-29 03:00"
```

```javascript
moment("2015-01-29T04:00Z").subtract(60, "m").format("YYYY-MM-DD HH:mm");
"2015-01-29 04:00"
```

**Comment by mj1856** [comment]
In the first example, you didn't provide any indicator of time zone - so it is *assumed* to be in local time.  That is, the time zone of the machine that the code is running on.

In the second example, you included the `Z`, which indicated that the value provided is in UTC.  Since you just passed it to the `moment` function, it was then *converted* to local time.

So while in both cases the *output* is local, the input has varied by time zone.

I assume you are in a time zone where it is currently UTC+01:00, such as Central European Time.

**Comment by maiolica** [comment]
Thank you!
