### ISSUE TITLE
Question: How best to set the time of an already instantiated moment without individually having to set the hours and minutes?

### ISSUE THREAD

**Issue by u01jmg3** [moment/moment#2221]
Suppose you already have a moment and a separate time String, what is the best way to set the moment with the given time without having to split the time String into pieces or create another moment? Basically something like a `setTime()` function where you provide the input format.

```js
var d1 = moment(options.maxTime, 'HH:mm');
var d2 = moment(datetime.currentTime);
//d2 = d2.setTime(options.maxTime, 'HH:mm');
d2 = d2.hour(d1.get('hour'));
d2 = d2.minute(d1.get('minutes'));
```

**Comment by kashifshamaz21** [comment]
@u01jmg3 well, there isn't a setTime() API of sorts to change the properties of an already created moment, you would have to use the setters. 
Following are your options:
```
*Option 1 (same as what you menioned above, use individual setters):*
 d2 = d2.hour(d1.get('hour'));
d2 = d2.minute(d1.get('minute')); 
*Option 2(combined setter):*
d2 = d2.set({
           'minute': d1.get('minute'), 
           'second': d1.get('second')
        });

**Comment by u01jmg3** [comment]
Thanks for clarifying

Any scope for having such an API call?

**Comment by kashifshamaz21** [comment]
Nothing in the pipeline as of now, can  be looked at if there is really a case of needing it.
Because the setters seem to be enough for most of the cases.

**Comment by u01jmg3** [comment]
:+1:

**Comment by adambuczynski** [comment]
+1 for this feature actually. My use case is that I have a time string which comes from a time input / time picker component, and I have to create a moment from it, but creating a moment from only time seems to result in an Invalid date. So I have to pre-create a moment (for today), and then set the time on it. It would be nice if I can do something like:

```javascript
var time = '15:00';
var today = moment();
today.setTime(time, 'HH:mm');
```

Now, I have to split the time string in hours and minutes, which seems trivial but it's not when your time format is flexible/configurable. Time format might be 'hmm', 'HHmm', 'HH.mm', 'HH:mm' or even 'mm:HH'. Unless you know the time format, it's hard to convert the time string into separate hour/minute values without creating your own time format string parser. 

Since Moment already has such a parser, a `setTime()` method in Moment would be perfect for it, because you could just pass it the time string along with the time format string and it would parse it correctly for you.

Since it's an additional method, it wouldn't break any existing code, so hopefully this use case provides enough incentive to add it in.

**Comment by richfergus** [comment]
missing comma at d1.get('hour'):
should be:
`d2 = d2.set({
           'hour' : d1.get('hour'),
           'minute'  : d1.get('minute'), 
           'second' : d1.get('second')
        });`

**Comment by adamreisnz** [comment]
You could always add your own helper if needed:

```js
/**
 * Set time helper, accepts time string like HH:mm
 */
proto.setTime = function(time) {
  const [hour, minute] = time.split(':');
  return this.set({hour, minute});
};
```
