### ISSUE TITLE
Can we support the old and new way of doing add/subtract?

### ISSUE THREAD

**Issue by JemiloII** [moment/moment#2222]
Hey everyone, I've gotten into writing pure functions and currying functions. The new change to moment causes the data to come first, then the type. I have to write functions just to flip the arguments, can we just do a type check for the arguments, rather than just flipping the arguments around. I would also like to understand the change, as it had set me back a bit on a new project. I rather not have fork the moment for just argument changes.

For those new to currying, it simply lets me place part of a functions arguments in and it will return a new function that waits for the remaining arguments. It's great for chaining, and making simpler functions.

**Comment by ichernev** [comment]
First of all, moment 2.x supports both styles, we just deprecated the other one. 3.x will drop the old style, and you have many options :)

If you want to do currying anyway -- you'd have something like `m.addUnits('minutes')(5)` -- so you'd have to add a new function to do the currying anyway (or you just want to use a library for that?). Making a plugin that does `moment.fn.radd = function(a, b) { return this.add(b, a); }` is trivial.

So I don't consider this an API issue. Moreover "checking for types" is not ideal, because then people want to pass strings that represent integers ... oh well, so its good if the library behaves consistently.

**Comment by JemiloII** [comment]
thanks for the insight
