### ISSUE TITLE
utcOffset() doesn't work as expected

### ISSUE THREAD

**Issue by judepereira** [moment/moment#2250]
When I explicitly set the UTC offset using utcOffset(), I expect that the epoch returned should be the same across different timezones. However, here's what I've observed:

**In some Canadian timezone:**
moment("20150303", "YYYYMMDD").utcOffset(__TIMEZONE_OFFSET_MINUTES).unix()
**1425362400**

**In IST:**
moment("20150303", "YYYYMMDD").utcOffset(__TIMEZONE_OFFSET_MINUTES).unix()
**1425321000**

*__TIMEZONE_OFFSET_MINUTES is 330 (IST) in both cases.*

How can I get the same epoch in both cases? 1425321000 is the expected one.

**Comment by mj1856** [comment]
This is the expected behavior.

Calling `utcOffset` or `zone` only shifts the time zone offset that you see when you *output* values from the moment object.  It doesn't change the way moment processes the *input*.  Since you are calling `moment("20150303", "YYYYMMDD")` in both cases, it has the same behavior in both cases - which is to interpret the value in the *local* time zone.  When the local time zone is different, you get two different moments on the instantaneous timeline.

If you want the input value to always be interpreted as IST, you should include the zone offset in the input string.

    moment("20150303+0530", "YYYYMMDDZZ")

This will still use the local time zone for output, but that doesn't matter for `.unix`, as that function aligns to UTC.  If you needed both input and output to align (for other purposes), then use the `parseZone` method:

    moment.parseZone("20150303+0530", "YYYYMMDDZZ")

But what if you only have the offset as a number of whole minutes instead of a `+hhmm` string?  Then do this:

    var offset = 330;
    moment.utc("20150303", "YYYYMMDD").subtract(offset,'minutes').utcOffset(offset)

**Comment by hoomersinpsom** [comment]
![image](https://user-images.githubusercontent.com/1879104/37621506-e39b128e-2b9d-11e8-9972-ee581121d7ed.png)

@mj1856 im my case the first two vars `start` and `end` both work perfectly with `utcOffset("-03:00").unix()`, but if i call `moment.utc().utcOffset("-03:00").unix()` it will not calculate the right unix value, i think this behavior is very confusing and took me some hours until i found your answer, anyway thank you :)
