### ISSUE TITLE
Milliseconds since epoch are not formatted as integers.

### ISSUE THREAD

**Issue by tutuca** [moment/moment#2253]
Fiddle here http://jsfiddle.net/tutuca/e3s21Lab/, although it fails to run.
I have packaged the minimal case that you can run ([download](https://dl.dropboxusercontent.com/u/163405/tiempo.tar.gz))

So, the gist of it is that `moment().format('x')` doesn't return a valid integer so `sinon.fakeTimer` fails with a non obvious error (I'd probably report it there too.)

    describe("Test sinon.fakeTimes with Moment.js", function() {
        var today, tomorrow, ticks, clock;
        beforeEach(function(){
            // get milliseconds since UNIX epoch for this date.
            ticks = parseInt(moment('01/15/2015').format('x'));
            // set the timers to start at expected time.
            clock = sinon.useFakeTimers(ticks);

        });
        afterEach(function(){
            clock.restore();
        });
        it("date is set in some arbitrary time.", function() {
            today = new moment();
            tomorrow = today.add(1, 'days');
            expect(tomorrow.format('MM/DD/YYYY')).toBe('01/16/2015');
        });
    });

See how I needed to wrap the time with `parseInt`? 

Thing is, that format returns something that looks like a number, so it should be a number so I don't have to rely on `parseInt` for it to work, no?

Opinions?

**Comment by icambron** [comment]
It definitely needs to stay a string. `format()` returns a string representation of the date, and it would be really confusing if it did that for every format string except one. Further, a user might even combine "x" with some other piece of formatting and then it would have to be a string anyway, so the special case here would be "if the format string only contains 'x', return a number, otherwise a string", which is not a good idea.

However, getting an integer is really easy and doesn't require `parseInt`: use `moment().valueOf()` or even the cheekier but shorter `+moment()`. If you wanted seconds instead of millis, there's `moment.unix()`. We got you covered!

**Comment by imsovru** [comment]
interesting all of the methods moment().month() returns an integer
