### ISSUE TITLE
get('hour') incorrect?

### ISSUE THREAD

**Issue by theother1** [moment/moment#2269]
var aaa is a utc string with a zero hour offset, but moment(aaa).get('hour') adds one hour when there was DST at the time. Why?

I only want to read out the hour from aaa as the console.log shows when I log aaa. Why does it add one hour for the September date in 1966 and none for January? aaa = 14:00 but get('hour') says 15. This is driving me insane! :) Is there something I'm overlooking? Thanks

var ccc = insYear+"-"+pad(insMonth)+"-"+pad(insDay)+" "+pad(insHour)+":"+pad(insMinute);
            var aaa = moment.tz(ccc.toString(), insTZ).utc().format();
            console.log("aaa = "+aaa, " ccc = "+ccc, insTZ);
            insYear = moment(aaa).get('year');
            insMonth = moment(aaa).get('month')+1;
            insDay = moment(aaa).get('date');
            insHour = moment(aaa).get('hour');
            insMinute = moment(aaa).get('minute');
			var birthData = {
				Year: insYear,
				Month: insMonth,
				Day: insDay,
				Hour: insHour,
				Minute: insMinute,
}

-----------
console:
aaa = 1966-09-10T14:00:00+00:00  ccc = 1966-09-10 15:00 Europe/Vienna
Date sent:  {"Year":1966,"Month":9,"Day":10,"Hour":15,"Minute":0}

aaa = 1966-01-10T14:00:00+00:00  ccc = 1966-01-10 15:00 Europe/Vienna
Date sent:  {"Year":1966,"Month":1,"Day":10,"Hour":14,"Minute":0}

**Comment by theother1** [comment]
When I change it to .utc().get('...') it seems to be working. I'm puzzled how it even knows there was DTS? This info doesn't seem to be part of aaa

**Comment by icambron** [comment]
The weird offsets you're seeing is actually your *local* DST, which comes from you parsing the locally-parsed, to-UTCed date again with `moment(aaa)`, which says "take the string aaa and turn it into a date in my zone". Since the date is a UTC date (there's a +00:00 on the end), you end up with a local time offset according to your local rules. That's why converting it back to UTC did what you wanted.

Your code would be a lot easier to reason about if you parsed the date and then left it as a moment object; the issue comes from calling `.format()` to turn it into a string and then calling `moment()` to turn it back into a date.
