### ISSUE TITLE
Week date format anomaly

### ISSUE THREAD

**Issue by pjdevries** [moment/moment#2281]
Using Moment 2.9.0 moment('2014-12-29').format('YYYY-MM') should display 2014-52 but instead it displays 2014-01.

**Comment by talymo** [comment]
I believe what you are looking for is this...
moment('2014-12-22').format("YYYY-ww");

**Comment by pjdevries** [comment]
Thanks for the digging and the response. I agree that 2014-12-29 is considered a first week. And yes, I also tend to agree it is the first week of the **new** year. But shouldn't it be the first week of 2015 then
 and be formatted as 2015-01?

**Comment by pjdevries** [comment]
I'm not sure if 'bug' is the proper classification here. It all depends what one expects from the format() function. 

Obviously the behavior is caused only with the last week of a year overlaps to the new year. Apparently the format() function parses the template string token by token, without considering them in the logical context of the date. In my example it first parses the 'YYYY' token and establishes the year to be 2014. It then parses the 'MM' token and establishes the week to be 01. Literally speaking, both are absolutely correct. But when combined, the result is not what one would logically expect. At least I don't :)

Fortunately there is a simple workaround for my case. By applying an 'End of Time' operation before formatting, I get the proper result. So moment('2014-12-29').endOf('week').format('YYYY-MM') displays 2015-01, just as I expect.

**Comment by icambron** [comment]
I think there are a couple levels of confusion here. First, "MM" is months, not weeks, so it's never going to be 52. For me it's 12, as expected:

```
> moment('2014-12-29').format('YYYY-MM')
'2014-12'
```

If you want weeks, use "WW" or "ww"; one is ISO weeks and the other is local weeks. (I suspect you actually meant that but typed it into Github wrong.) Anyway, onto the real problem:

```
> moment('2014-12-29').format('YYYY-WW')
'2014-01'
```

That's not what you want, but it's caused by **mixing calendar years with weeks**. Think of the tokens in Moment as evaluating independently: the "YYYY" piece doesn't know you also care about weeks, just that it should display the year, which is 2014. The "WW" part says "It's the first week of the year!"; it has no idea that you're also printing the calendar year. Fortunately, Moment supports week years, which is exactly what you want:

```
> moment('2014-12-29').format('GGGG-WW')
'2015-01'
```

Which matches the results @talymo got. (If you used "ww" above instead, use "gggg" to use the local week year.) The lesson here is to be careful about what definition of "year" you're using.

**Comment by pjdevries** [comment]
Thanx for your elaborate reply and I apologize for the 'MM' vs 'WW' confusion. Thanx also for pointing me in the right direction with 'GGGG' for week years. I somehow missed that or perhaps the difference with 'YYYY' didn't quite sink in while reading the documentation.
