### ISSUE TITLE
moment().startOf('day') == moment.startOf('day').endOf('day')

### ISSUE THREAD

**Issue by MichaelJCole** [moment/moment#2301]
Hey, this code didn't do what I expected because `moment().startOf('day') == moment.startOf('day').endOf('day')`

The work-around is to use `var end = moment().endOf('day')` which will fail at midnight.
```
  function makeTimesForInterval (numMins) {
    var times = [];
    var time = moment().startOf('day');
    var end = time.endOf('day');
    console.log(time);
    console.log(end);

    if (numMins <= 0) throw Error('Your killing me smalls');

    while (time.isBefore(end)) { // one day
      times.push({ display: time.format('h:mm a'), time: time});
      time.add(numMins, 'm');
    }
    console.log(times);
    return times;
  }
```

**Comment by icambron** [comment]
`moment().startOf('day') == moment().startOf('day').endOf('day')` is `false` and I suspect it would be if you pasted it into your console. Your code doesn't work because `startOf` and `endOf` are *mutators*. This is non-obvious and IMO quite bad, but it's the way Moment works. So:

```
var time = moment().startOf('day');
var end = time.endOf('day');
```

`time` and `end` aren't different times; they're same time of `moment.startOf('day').endOf('day')`.

The more general issue of immutability in Moment has a long history, see e.g. #1754 and #390.

**Comment by MichaelJCole** [comment]
Yikes whatamess!  Thanks for the help.

```
moment().startOf('day') == moment().startOf('day').endOf('day')
false
moment().startOf('day').endOf('day')
Moment {_isAMomentObject: true, _isUTC: false, _pf: Object, _locale: Locale, _d: Thu Apr 02 2015 23:59:59 GMT+0700 (ICT)…}
moment().startOf('day')
Moment {_isAMomentObject: true, _isUTC: false, _pf: Object, _locale: Locale, _d: Thu Apr 02 2015 00:00:00 GMT+0700 (ICT)…}
```

**Comment by arled** [comment]
How in the world do you expect this to work??!! 
`moment().startOf('day') == moment.startOf('day').endOf('day') `
LOL
@MichaelJCole

**Comment by MichaelJCole** [comment]
@arled Why are you bothering me about a closed bug from 2015?  Stop criticizing and contribute.
