### ISSUE TITLE
floating point days in durations are trouble

### ISSUE THREAD

**Issue by welch** [moment/moment#2305]
I'm seeing some surprising behavior adding/subtracting a partial-day duration to a moment:

```
var moment = require('moment');
var now = new moment();
var halfday = moment.duration(1/2, 'd');
var fullday = moment.duration(1, 'd');
var day_ago = now.clone().subtract(fullday);
var halfday_ago = now.clone().subtract(halfday);
var otherhalf_ago = now.clone().subtract(halfday.as('ms'));
if (day_ago.isSame(halfday_ago)) { console.log("surprise!"); }
if (!halfday_ago.isSame(otherhalf_ago)) { console.log("surprise!"); }
```

examining the actual dates, subtracting halfday subtracts a full day (and adding halfday adds nothing). 
doing the computation with halfday.as('ms') produces the correct result. The momentjs code is pretty
opaque in this regard, is this expected behavior?

**Comment by icambron** [comment]
Yeah, floating point days aren't really supported there. The background here is that we need to set the date directly, as opposed to to boiling down to MS and adding them. Specifically, if you add a day across a DST barrier, you want the time to stay the same, even if it's actually 23 or 25 hours later. So what the code actually does is something like this:

```js
m.set('date', m.date() + howMuchYouAdded);
```

You can see it [here](https://github.com/moment/moment/blob/develop/src/lib/moment/add-subtract.js#L34).

So that doesn't really work with partial days, e.g.

```js
moment().set('date', 3.5); //=> three days in the future, same clock time
```

Just ends up translating to:

```js
> d = new Date()
Fri May 01 2015 21:11:44 GMT-0400 (EDT)
> d.setDate(3.5)
1430701904662
> d
Sun May 03 2015 21:11:44 GMT-0400 (EDT)
```

So it's very different from converting to millis and adding to the current number of millis, and with good reason. But with fractional dates it sure is confusing. One fix would be to break up day durations into whole and fractional parts, add the whole number as we do now, convert the fractional remainder to ms, and then tack that on top. Would need to do that with sizes other days, too, I guess? What do you think, @ichernev?

**Comment by welch** [comment]
I see. I missed that days also have some "calendarness" to them like months. Your fractional suggestion does allow the integer part of day to do that job, and is my local workaround.

**Comment by kearnmachine** [comment]
hi
Related Problem. I think the results here should be always 2:
```javascript
moment.duration().add(1.1,'days').hours()
0
moment.duration().add( (moment.duration().add(1.1,'days').asHours()) ,"hours").hours()
2
```

**Comment by maggiepint** [comment]
I'm going to close this issue as it's old, and I don't think it's a road we should go down. Ultimately, there is no conversion between date math and time math, and I don't think we should try to make one. Other date and time libraries don't do it. 
A while ago we did clean up the rounding so that it always goes towards zero, making adding negative 1.5 and subtracting 1.5 behave the same. I think that's as good as this is going to get.

**Comment by maggiepint** [comment]
Related documentation: http://momentjs.com/guides/#/lib-concepts/date-time-math/
