### ISSUE TITLE
moment().utcOffet(-5 * 60).day(5) resulting in *last* Friday

### ISSUE THREAD

**Issue by Panoplos** [moment/moment#2345]
I have the following code:

```js
d = moment() // -> '2015-04-26T13:46:22+09:00' (this is a Sunday (JST))
d.utcOffet(-5 * 60) // -> '2015-04-25T23:46:22-05:00' (this is a Saturday (EST))
d.day() // -> 6 (as I said, Saturday)
d.day(5) // -> '2015-04-24T23:46:22-05:00' (this is *last* Friday)
```

I thought `moment().day(5)` was supposed to set the date to _*next*_ Friday. If this is the case, then the above is exhibiting a bug.

If not, what is the correct way to go about this?

Cheers in advance!

**Comment by Pumpuli** [comment]
[`moment().day(5)`](http://momentjs.com/docs/#/get-set/day/) is supposed to set the date to the Friday of the current week, so starting from a Saturday it's the previous day.

I think you need to add a bit more logic to determine next Friday, because it could belong to the current week **or** the next week.

**Comment by icambron** [comment]
@Pumpuli is right: it takes you to the Friday of your current week, which you changed to last week. If you know you're in the previous week (or you find out that you are by comparing `week()`), then you can just use `d.day(5 + 7)`
