### ISSUE TITLE
Firefox and Chrome adds 1 day differently

### ISSUE THREAD

**Issue by fczuardi** [moment/moment#2353]
- I am using MacOSX 10.9.5, Chrome Version 42.0.2311.90 (64-bit) and Firefox Nightly 40.0a1 (2015-04-29).
- My computer timezone is set to Brasilia Standard Time, city São Paulo, Brazil

The result of adding one day to some dates in the months of October, is causing a bug in firefox that affects a calendar widget I am using, see https://github.com/gpbl/react-day-picker/issues/18

Here is a simplified test-case:

```javascript
var oct182014 = moment('2014-10-18');
var oct182014Plus1 = moment('2014-10-18').add(1,'d');
console.log('18 of october 2014:', oct182014.format(), oct182014.valueOf());
console.log('18 of october 2014 + 1 day:', oct182014Plus1.format(), oct182014Plus1.valueOf());
```

The output on Chrome:

```
18 of october 2014: 2014-10-18T00:00:00-03:00 1413601200000
18 of october 2014 + 1 day: 2014-10-19T01:00:00-02:00 1413687600000
```

And the output on Firefox:

```
"18 of october 2014:" "2014-10-18T00:00:00-03:00" 1413601200000
"18 of october 2014 + 1 day:" "2014-10-18T23:00:00-03:00" 1413684000000
```

**Comment by fczuardi** [comment]
I am not sure if this is a moment bug or a Mozilla bug. The fact is that october 18 + one day is still october 18 :(

**Comment by fczuardi** [comment]
The workaround is to force UTC date with (in the test-case above):

```javascript
var oct182014Plus1 = moment('2014-10-18').utc().add(1,'d');
```

**Comment by icambron** [comment]
It's probably a Mozilla bug. Try this:

```
var date = new Date(2014, 9, 18);
date.setDate(19);
console.log(date.toString());
```

What does that give you?

**Comment by mj1856** [comment]
It's not necessarily a "bug", but rather a design flaw.  The ECMAScript spec does not define the behavior for a local time value that falls into a DST transition.  For the gap of the spring-forward transition, some browsers skip forward, some skip backward.   Since Brazil transitions at midnight, a value of 00:00 will leap to 1:00 on some browsers, or jump back to 23:00 the prior day on others.

So you start with a valid value, add a day and land on an invalid value, which causes Firefox to jump backwards, and Chrome to jump forwards.

The fall-back transition behavior is also undefined in the spec.  Some browsers will chose the first (daylight-time) instance, while some will chose the second (standard-time) instance.

If you have a Pluralsight subscription (or can use a trial offer), I encourage you to watch my [Date and Time Fundamentals](http://www.pluralsight.com/courses/date-time-fundamentals) course.  I cover this exact issue in detail in the module "Date and Time in JavaScript", in the clip titled "Daylight Saving Time Issues".

There are two good workarounds:
- Use UTC instead of local time (as you suggested)
- Use noon instead of midnight.  No DST transitions ever occur in the middle of the day, in any time zone.

**Comment by icambron** [comment]
Ah, I'd forgotten that Brazil moves its clocks back at midnight, which is crazy. See also #1440.
