### ISSUE TITLE
Invalid, modified moments should not return true in `isSame`

### ISSUE THREAD

**Issue by Radagaisus** [moment/moment#2354]
Hi,

Noticed something odd:

```
coffee> moment.invalid().isSame(moment.invalid().year(2010))
false
coffee> moment.invalid().year(2010).isSame(moment.invalid().year(2010))
true
```

:cake:

**Comment by icambron** [comment]
Yeah, that's probably a bug. `isSame()` should make all invalid dates equal.

**Comment by brianwyantora** [comment]
For an alternative precedent, consider that `NaN === NaN` returns false.  Perhaps moment's `isSame` should follow a similar precedent, where `isSame`, `isBefore`, and `isAfter` all return false if either moment is invalid.

**Comment by ichernev** [comment]
@brianwyantora that makes sense. PRs welcome.

**Comment by cwohlman** [comment]
On closer examination `moment.invalid().year(2010).isSame(moment.invalid().year(2010))` returns true because `moment.invalid().year(2010)._d` returns a valid date (Jan 1, 2010) and `moment.valueOf` returns `+this._d - ((this._offset || 0) * 60000);`.

Should we fix `moment.valueOf` to return NaN if `moment.isValid() === false`?

**Comment by icambron** [comment]
@cwohlman Yeah, if we want the behavior to be consistent with `NaN`, it does seem like just having it return `NaN` is the right thing to do.

**Comment by cwohlman** [comment]
> @ichernev: would this "edge" case (invalid moment backed by valid date) happen if you create an invalid moment, but then modify it, in the current code? If yes, I'd say a lot of people "depend" on this functionality, i.e. we'll break a lot of code if we start propagating invalid moments. Also if there is valid date attached, all of the moment methods will just work correctly, and it will be almost unnoticeable (that the moment is invalid).

I think maybe this issue needs further discussion. Right now the implementation makes a lot of sense:

1. Moments are compared based on their underlying value (i.e. `_d`)
2. Moments with an invalid underlying value cannot be compared and return false when compared

The issue is this:

3. Invalid moments can have a valid underlying value.

The question is, if an invalid moment has a valid underlying value, what's the expected behavior?

For example:

```
> moment.invalid().year(2010).isSame(moment.invalid().year(2010), 'year')
true
> moment.invalid().year(2015).year()
2015
> moment.invalid().year(2015)._d.toISOString()
2015-01-01T00:00:00.000Z
```

Which makes a lot of sense, because the underlying date is valid, the years are the same, and intuitively you'd expect them to be equal. This doesn't work with any other unit though:

```
> moment.invalid().minute(10).isSame(moment.invalid().minute(10), 'minute')
false
> moment.invalid().minute(10).minute()
NaN
> moment.invalid().minute(10)._d
Invalid Date
```

**Comment by cwohlman** [comment]
The real question is: What does the user expect from an invalid date?

1. I've never used an invalid date on purpose, so my only use for invalid dates is to detect dates that are not valid - and reject them.
2. It's not currently possible to use invalid dates as fill in the blanks: this doesn't work, and returns `moment.invalid().month(6).year(2015).month()` 0, not 6 as you'd expect.
3. We currently treat invalid dates as unequivocally invalid in at least one other case: `moment.invalid().anythingYouWantToChange().format()` always returns `"Invalid date"`

**Comment by ichernev** [comment]
Hm, if formatting always returns `"Invalid Date"` I think we're good to make the `valueOf` change. I'd guess most users use format at the end, so they'd catch invalid moments.

**Comment by cwohlman** [comment]
Since I already split out those commits into a separate branch, I've opened another pull request: https://github.com/moment/moment/pull/2462, if you'd like me to squash them, I can.
