### ISSUE TITLE
incorrect diff in days

### ISSUE THREAD

**Issue by SamWhitby** [moment/moment#2361]
The difference in days is incorrect when running the snippet below and is returning 0.

moment("1900-04-01T00:00:00.000Z").diff(moment("1900-03-31T00:00:00.000Z"), "days");

I noticed this when the two lines of code below were both returning 89.

moment("1900-03-31T00:00:00.000Z").diff(moment("1900-01-01T00:00:00.000Z"), "days");
moment("1900-04-01T00:00:00.000Z").diff(moment("1900-01-01T00:00:00.000Z"), "days");

Any date comparisons that start before or on 1900-03-31T00:00:00.000Z and on or after 1900-04-01T00:00:00.000Z are then out by one day.

**Comment by mj1856** [comment]
I can't reproduce your results.

![image](https://cloud.githubusercontent.com/assets/1396388/7497592/3fc28c94-f3d0-11e4-9b5d-630a8089d5a8.png)

I checked Chrome and IE latest on Windows.  What browser/os are you running?   Also, what version of moment?

**Comment by SamWhitby** [comment]
My results
![momentbug](https://cloud.githubusercontent.com/assets/3334161/7502907/a188d39e-f3fc-11e4-972f-d2d0700805b2.PNG)
This is with the latest version of chrome on Windows 8.1 Pro with my computers time zone set to (UTC+12:00)Auckland Wellington

I did some further testing and changed my computers time zone to (UTC-06:00)Central America and I was able to reproduce the correct result.

This bug is also occurring in Firefox, Opera, and Safari for windows. IE however does give the correct result.

**Comment by mj1856** [comment]
Ahh.... That explains it.  I should always remember to ask for time zone. :)

Here's what's happening:

 1. Even though you're expressing the dates in terms of UTC, you're parsing them with `moment(string)`, which means the values are converted to local time.

 2. [ECMAScript has had a design flaw](http://codeofmatt.com/2013/06/07/javascript-date-type-is-horribly-broken/) which makes all past years use the current year's DST rule (see also #831).  However, some browsers (such as IE11) have already fixed this problem (by following new guidelines in ECMA-402 and ECMAScript 6) and implementing the correct behavior.  

 3. The current DST rule for New Zealand is to spring-forward on the last Sunday of September at 2:00 AM local time, and fall-back on the first Sunday of April at 3:00 AM local time. In 1900, the first Sunday of April fell on April 1st.  So even though there were [actually no DST changes in 1900](http://www.timeanddate.com/time/change/new-zealand/auckland?year=1900), JavaScript will think there was one.

 4. So the values are converted as follows in Chrome (which has the flaw):
![image](https://cloud.githubusercontent.com/assets/1396388/7506176/88453526-f4b0-11e4-946d-1b44dd935dd3.png)

   And they are converted differently in IE11 (which does not have the flaw):
![image](https://cloud.githubusercontent.com/assets/1396388/7506189/befd4aa4-f4b0-11e4-8056-4f7a53263e92.png)

 5. The `moment.diff` function was modified explicitly negates the effects of DST by subtracting the difference in offsets when calculating days or weeks (see `zoneDelta` [here](https://github.com/moment/moment/blob/81167a6f7e0dc3fdfbfb11d437a213707e8ff00c/moment.js#L1882)).  This makes sense when you look at the local time values.  If I started at 13:00 on the first day, and ended at 12:00 on the second day, then it hasn't yet been a full day by the local clock.  Remember, not all local-days are 24 hours long.  Due to the DST change, spring-forward days will have 23 hours and fall-back days (like this one) will have 25.

The workaround is to keep the values in UTC:

```javascript
moment.utc("1900-04-01T00:00:00.000Z").diff(moment.utc("1900-03-31T00:00:00.000Z"), "days");
```

By doing so, you're being explicit that you want the days to be measured in "UTC days", which will always be 24 hours long.

I'll mark this one up to "works as designed", as the only real issue is the ECMAScript bug in misidentifying this as a DST fall-back day, and that's out of our hands.

**Comment by mj1856** [comment]
Also, another workaround would be to measure in hours and then divide by 24, instead of measuring in days.

**Comment by SamWhitby** [comment]
Thanks for demystifying that issues for me Matt, you saved me a lot of headache.

**Comment by mj1856** [comment]
No Problem! :smile:
