### ISSUE TITLE
Support for time only in moment.js

### ISSUE THREAD

**Issue by mitar** [moment/moment#2397]
Currently, it seems it is not possible to work only with time partial using moment.js. With HTML5 time and date form elements, it is possible that you get both of that separably, so it would be great if you could parse both of them with moment.js and then combine them. So something like `combine(moment(date, 'YYYY-MM-DD'), moment(time, 'HH:mm:ss'))`. Currently the second `moment` object has date parts set to current date. This is problematic because it is unclear later on when you pass `moment` object around if the object represents just time, or full datetime.

**Comment by mj1856** [comment]
Moment is based on `Date`, so it will always be a date+time object.   It can't align perfectly with date-only or time-only objects, such as the `LocalDate` and `LocalTime` types found in Noda Time / Joda Time / Java 8.

However, you can still get the desired effect.  Just combine the strings ahead of time.  Since you already have ISO8601 strings from the HTML5 elements, then any of these will work:

    moment(date + 'T' + time)
    moment(date + ' ' + time)
    moment(date + 'T' + time, "YYYY-MM-DDTHH:mm:ss")
    moment(date + ' ' + time, "YYYY-MM-DD HH:mm:ss")

**Comment by schmod** [comment]
I just want to say that I think that this is a valid use-case, and something that is particularly awkward to handle with current versions of MomentJS.  

Handling things like birthdays and holidays tends to be very error-prone and awkward.  

I'm not sure how practical this would be to implement as a plugin or in core, because, as you say, Moment always has a backing `Date`.  However, it might be time to examine how this architectural decision is impeding other features and functionality that can't be reasonably viewed as simple extensions of JavaScript's `Date` type.

**Comment by mj1856** [comment]
@schmod - I agree completely.  Java 8's `java.time` or .Net's Noda Time are both good examples of complete models.  Moment only partially models the date-and-time domain.

Keep in mind that there is `moment.duration` which can support elapsed-absolute-time scenarios (like `Duration` in J8/NT).  There is no elapsed-civil-time type (like `Period` in J8/NT) or a time-of-day type (like `LocalTime` in J8/NT).

I'm not sure whether moment is the right project for this type of architecture or not.  It's something we could consider for v3, or it may end up as a separate library.  It just depends on how many breaking changes we want to introduce.

**Comment by msaspence** [comment]
Can moment not track internally whether the `Date` reference it holds represents just a date or time element of date time and throw an error if you attempt to do inappropriate with it. For example:

```
moment.time('17:21').format('h:mma') // 5:21pm
moment.time('17:21').format('YYYY h:mma') // throws error
```

**Comment by mj1856** [comment]
@msaspence - No, currently it cannot reliably do that.  At the heart of a `moment` object is a unique point in time, as returned by `.valueOf()`  (internally, a composite of `_d` and `_offset`).  We do keep the original input in the `_i` field, but we would have to re-evaluate that with every operation, which would be quite inefficient.

There is a hint of an alternative API design in what you propose though - that based on input, a moment could be sub-typed.  I've been thinking about prototyping that for awhile, but it would be a drastic change from what we have today.
