### ISSUE TITLE
Future and Past

### ISSUE THREAD

**Issue by DominoDev** [moment/moment#2407]
Add constants for undefined future and past dates.  the undefined future date should always test as greater than any date compared to it and the undefined past date should always test less than.

**Comment by mj1856** [comment]
Is there a use case that this would enable?  I'm not sure why this would be needed.

**Comment by DominoDev** [comment]
In the case of a Date range where the beginning or end date is undefined such as an employment application where the form asks for a start and end date of previous employment and you are still employed by your current employer.  the date range would be from 3/20/2003 to "Present"

**Comment by mj1856** [comment]
The range of a `moment` is the same as that of a `Date`, which is:

`moment.utc(-8640000000000000)` to `moment.utc(8640000000000000)`
or
`-271821-04-20T00:00:00Z` to `275760-09-13T00:00:00Z`

Anything outside of this range will fail with moment functions, such as `isBefore` and `isAfter`, but would still work with the `<` and `>` operators since they would compare the results of `.valueOf()` anyway.

In other words, you can use existing JavaScript constants like `Number.MIN_VALUE` and `Number.MAX_VALUE`, or `Number.NEGATIVE_INFINITY` and `Number.POSITIVE_INFINITY` as long as you are only doing comparisons with simple operators like `<`, `<=`, `>=`, and `>=`.

For the moment functions, I think it's reasonable just to assign these constants:

```javascript
var MIN_TIMESTAMP = -8640000000000000;
var MAX_TIMESTAMP = 8640000000000000;
```

Then just use those:

```javascript
if (someMoment.isBefore(MAX_TIMESTAMP)) { ... }
```

The only two values that would fail then are the actual moments at the min and max points.  However, I seriously doubt this would be a problem in the real world since they are so far in the distant past and distant future.   IMHO, modifying the moment object or the comparison functions to test these extremes would just add unnecessary overhead.

**Comment by mj1856** [comment]
@timrwood  - Do you think there's any value in incorporating these constants into the public API?

**Comment by ichernev** [comment]
This won't be enough. What if you add a second to these -- it should still be infinity, not overflow. You also need translations in case somebody tries to print them. Many centuries in the future looks like a bug to me.

@DominoDev just use a point in the future /past that is distant enough. Like 100 years +/-. We're based on Date and Date doesn't support infinity, so there is a strong no from me.
