### ISSUE TITLE
Date parsing broken on old webkit

### ISSUE THREAD

**Issue by iwiznia** [moment/moment#2410]
I tried this with safari 5.0.5 (uses webkit 533.21.1) and date parsing does not work.
It's a simple example, just: `moment("2015-06-08").isValid();` returns false, even if you pass the format `            moment("2015-06-08", "YYYY-MM-DD").isValid();`.

Here's the fiddle: http://jsfiddle.net/yuaw2ypt/8/

**Comment by wayofspark** [comment]
+1, Same issue on a safari 5.0.2 ( webkit 533.17.9) with moment 2.10.  Even using the format parameter ( moment("2015-06-08", "YYYY-MM-DD") ) results in invalid date parsing.

**Comment by wayofspark** [comment]
Also reproducing on chrome 12. Also reproducing on Android 4.0 native browser.

**Comment by nonmanifold** [comment]
android 4.0.4 all ok 
here is updated fiddle with moment.js version  2.10.6 from a https cdn:
https://jsfiddle.net/manifold/r7zogw60/2/

**Comment by ichernev** [comment]
Is anybody willing to debug this thing? I  don't have these platforms laying around. Also I'd assume you have some way to debug mobile browsers through your desktop. Otherwise it gets hard :)

**Comment by iwiznia** [comment]
I use browserstack for this kind of thing. You can select almost any browser and run/debug there.

**Comment by nonmanifold** [comment]
@ichernev 2.10.6 does not seem to be affected by this issue on my android 4.0.4 device.

**Comment by ichernev** [comment]
I tested on google chrome 12-0-742-91-1 on windows, and there were many errors in locales, but not basic parsing. The issue was that regexes were `typeof 'function'`, which is already fixed in #2543 (will be released in next version).

Also tried chrome 10 -- saw same issues.

I'm closing this for now, feel free to reopen if you feel its still broken (after new release, or build one manually from latest develop).
