### ISSUE TITLE
year, week, date -> month?

### ISSUE THREAD

**Issue by kinhbang89** [moment/moment#2426]
Hi.

I would like to get the month from following values: year, week, date. For example: I have year:2015, week: 27, date:29 so the month should be 6 but I always get 7 by following code "moment().set({'year': $scope.year, 'week': $scope.week, 'date': date}).month()"

**Comment by jisaacks** [comment]
When I run:
```javascript
moment().set({'year': 2015, 'week': 27, 'date': 29}).month();
``` 
I do get a `6`.

But I am expecting a `5`. The 27th week spans from **June 29** to **July 05**. So with a date of 29 it should be June which is 5 since `.month()` is zero indexed.

I can run: 
```javascript
moment().set({'year': 2015, 'week': 27, 'date': 29}).format('MMMM Do YYYY')
``` 
and get `"July 29th 2015"`, which should be **June** as July 29 would be week 31.

So it seems that moment is only using week to determine the month (week 27 -> July) then setting the date for that month (29 -> July 29)

**Comment by jisaacks** [comment]
I think it makes sense if you set both a `date` and a `week`, it should look at the range of dates that week spans, and choose the correct month. If the date is not in the span, I think it should return an invalid date.

**Comment by mj1856** [comment]
When you write:

```javascript
moment().set({'year': 2015, 'week': 27, 'date': 29})
```

That's identical to:

```javascript
moment().year(2015).week(27).date(29)
```

With either approach, the starting value is variable because it's *today*.  The `week` setter is designed to stay on the same day-of-week that it is invoked on.  If today is Thursday, the resulting day after changing the week will also be a Thursday.

Since this particular week crosses more than one month, the result could be at the end of June, or at the start of July, depending on what the current day of week is.  Then when you set the `date(29)`, you'll either get June 29th, or July 29th.

It sounds like what you're looking for is something like this:

```javascript
function CreateMomentByYearWeekDate(y,w,d) {
    var sw = moment([y,0,1]).week(w).startOf('week');
    var m = sw.clone().date(d);
    return m.isBefore(sw) ? sw.endOf('week').date(d) : m;
}
```

Also, keep in mind also that the 27th week isn't necessarily June 29 - July 05.  When you use `week`, it bases the starting weekday on the current locale (this is in the docs [here](http://momentjs.com/docs/#/get-set/week/)), so perhaps it's June 28  - July 04, or some other date.  If you need it to be predictable, use `isoWeek` instead.

**Comment by jisaacks** [comment]
@mj1856 Thanks for that clarification! :)

**Comment by kinhbang89** [comment]
Thanks @mj1856 for your answer

**Comment by mj1856** [comment]
No problem.  I'm closing this for now, as I don't think changes to the `set` function are necessary at this time.  Thanks.
