### ISSUE TITLE
isSame, isBefore & isAfter behavior with different offsets

### ISSUE THREAD

**Issue by ZloyDyadka** [moment/moment#2427]
Example:
var time1 = moment().utcOffset(12); 
var time2 = moment();

time1.isSame(time2, 'day')  // TRUE

console.log(time1.format('MM-DD-YYYY')); - 06-20-2015
console.log(time2.format('MM-DD-YYYY')); - 06-19-2015

**Comment by jisaacks** [comment]
I don't see an issue here.

They are the same if you compare them at the same offset:

```javascript
var time1 = moment().utcOffset(12); 
var time2 = moment();

time1.isSame(time2, 'day') // TRUE

console.log(time1.utc().format('MM-DD-YYYY')); // 06-20-2015
console.log(time2.utc().format('MM-DD-YYYY')); // 06-20-2015
```

In your example they are formatted differently because they are formatted to the offset.

**Comment by ZloyDyadka** [comment]
@jisaacks And how compare with utc?

**Comment by jisaacks** [comment]
I am not sure I understand your question. In my code example I set them to UTC before formatting which is why they show the same date. In your code example they are showing different dates because even though they are the same point in time, they are being formatted at different time zones. 

Does that answer your question?

**Comment by mj1856** [comment]
Hmmm...  I'm thinking through this one, and I perhaps there's something to this.

Consider:

```javascript
var m1 = moment.parseZone("2013-05-31T23:00-07:00");
var m2 = moment.parseZone("2013-06-01T06:00:00+00:00");

var a = m1.isSame(m2) // true
var b = m1.isSame(m2,'day')  // true
var c = m1.isSame(m2,'month') // true
```

I would expect `a` to be true, since these are identical moments in time.  However, I would expect both `b` and `c` to be false, since they fall on different months and days in their own time zones.

I would expect that supplying any granularity at all to the `isSame`, `isBefore`, or `isAfter` functions would evaluate the granularity within the moment's assigned UTC offset.  Only when no granularity is specified should they be compared by their UTC equivalents.

**Comment by jisaacks** [comment]
> I would expect that supplying any granularity at all to the isSame, isBefore, or isAfter functions would evaluate the granularity within the moment's assigned UTC offset.

Makes sense, I could get behind that! However, is it possible users could be relying on the existing way it works?

**Comment by ichernev** [comment]
We just need API to answer the different type of questions. One is -- format the given moment in local time up to the unit specified and compare lexicographically (like `2014-02` for february 2014, no matter the timezone).

The other one is translate the second moment to the first (make sure offset is the same) and then compare. This is what we currently do.

Maybe pass the string `local` as a final argument, that would mean both matched in local time (string format approach that you want).

One thing is certain -- we're not changing the existing semantics :)

**Comment by aij** [comment]
I was bitten by this recently, both with foundation-datepicker (which uses JS Date objects that I was converting to moment for comparisons), as well as with react-datepicker (which uses moment internally, as well as in it's API).

It was especially confusing the first time around, where it turned out I had two moments where `.toString()` would show the same date, and yet `m1.isSame(m2, 'day')` turned out to return false (sometimes... depending on the user's timezone).

Intuitively, I would expect `m1.isSame(m2, 'day')` to be equivalent to `m1.format('YYYY-MM-DD') === m2.format('YYYY-MM-DD')`, but more efficient (since it could avoid the string formatting). 

I was also surprised that `isSame` is not commutative. Ie: `m1.isSame(m2, 'day')` is not equivalent to `m2.isSame(m1, 'day')`

**Comment by kipruss** [comment]
I think, `isSame` function works incorrect with negative offsets from UTC. Examples:
`moment('2017-02-04T18:00:00-05:00').isSame('2017-02-04T00:00:00-05:00', 'day')
false
moment('2017-02-04T18:00:00+01:00').isSame('2017-02-04T00:00:00+01:00', 'day')
true
moment('2017-02-04T18:00:00Z').isSame('2017-02-04T00:00:00Z', 'day')
true`

**Comment by kipruss** [comment]
`function isSame (input, units) {
    console.log(this.format()); // 2017-02-05T00:00:00+01:00
    var localInput = isMoment(input) ? input : createLocal(input),
        inputMs;
    console.log(localInput.format()); // 2017-02-04T06:00:00+01:00
    if (!(this.isValid() && localInput.isValid())) {
        return false;
    }
    units = normalizeUnits(units || 'millisecond');
    if (units === 'millisecond') {
        return this.valueOf() === localInput.valueOf();
    } else {
        inputMs = localInput.valueOf();
        return this.clone().startOf(units).valueOf() <= inputMs && inputMs <= this.clone().endOf(units).valueOf();
    }
}`

**Comment by clayzermk1** [comment]
Seeing the same thing as @kipruss right now. I also blame the `createLocal()` aspect. A work-around for this odd behavior is to create a moment out of the input to `isSame()` instead of using a string.

Consider:
```javascript
$ node
> const Moment = require('moment')
undefined
> const someDay = Moment.utc('2017-04-27').endOf('day')
undefined
> someDay.isSame('2017-04-27', 'day')
false
> someDay.isSame(Moment.utc('2017-04-27'), 'day')
true
> Moment.version
'2.18.1'
```

**Comment by mmun** [comment]
I ran into the same issue that @kipruss and @clayzermk1 did.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
