### ISSUE TITLE
using string and a number in utcOffset do not have same effect.

### ISSUE THREAD

**Issue by ahmedali5530** [moment/moment#2432]
Hi There,
I used the utcOffset with number and a string and they both do not returns the same dates, you can also check the fiddle which i have linked.
http://jsfiddle.net/dpadmrr5/

For example if i use '05:00' and 5 in utcOffset the both shows the different times.
Here is my code;

var testDate = '2015-06-07T04:00:00';

var date_1 = moment(testDate).utcOffset('05:00').format('HH:mm:ss');
var date_2 = moment(testDate).utcOffset(5).format('HH:mm:ss');

alert('using offset as 05:00 the date is '+date_1);
alert('using offset as 5 the date is '+date_2);

**Comment by jisaacks** [comment]
According to the [documentation](http://momentjs.com/docs/#/manipulating/utc-offset/) they should both work, but it appears only the number is affecting the offset. Setting the offset using a string like `utcOffset('08:00')` it still showing the offset as `+00:00`:

```javascript
var testDate = '2015-06-07T04:00:00';

var date_1 = moment(testDate).utcOffset('08:00').format('HH:mm:ss Z');
var date_2 = moment(testDate).utcOffset(8).format('HH:mm:ss Z');

console.log('using offset as 08:00 the date is '+date_1);
console.log('using offset as 8 the date is '+date_2);
```

I got:

> using offset as 08:00 the date is 08:00:00 +00:00
> using offset as 8 the date is 16:00:00 +08:00

However, it works when I specify it with a plus/minus like so:

```javascript
moment(testDate).utcOffset('+08:00').format('HH:mm:ss Z');
// 16:00:00 +08:00
```

It works. 

It makes sense, because a number is either positive or negative, but the string does not specify.

So it may just be that the documentation needs updated.

**Comment by mj1856** [comment]
Updated documentation.  Thanks!

**Comment by Mithgol** [comment]
Why doesn't a positive number work for the current time?

I've just got the following in REPL:

![node](https://cloud.githubusercontent.com/assets/1088720/8890379/691fe340-3307-11e5-8691-eb3c43423977.png)

on CentOS 6.2 (as presented on this screenshot) and on Windows 7 (believe me, it's the same).

MomentJS version 2.10.3 (from npm).
