### ISSUE TITLE
moment(year)

### ISSUE THREAD

**Issue by Nekle** [moment/moment#2445]
Why I get different values on different timezones ?

```
moment('2015')

Thu Jan 01 2015 08:00:00 GMT+0800 (CST)
Wed Dec 31 2014 19:00:00 GMT-0500 (CST)
```

**Comment by mj1856** [comment]
You also should be getting a deprecation error pointing at #1407 that explains the problem.

Essentially, if you supply a string that is not one of the supported ISO8601 formats, it will fall back to the `Date` constructor.   You can see from calling `new Date('2015')` that you get similar results - because browsers will interpret that as 2015-01-01 UTC.

You should provide either a full ISO string:

```javascript
moment("2015-01-01")
```

Or, you should pass a format specifier:

```javascript
moment("2015","yyyy")
```
