### ISSUE TITLE
Parsing moment to javascript date.

### ISSUE THREAD

**Issue by vetonshala** [moment/moment#2485]
I had problem when converting moment to javascript date object.
The sample bellow will show the problem.

var m1 = moment.tz("2013-11-18 00:55","America/New_York");
var m2 = moment.tz(m1, "America/Los_Angeles");

var d1 = m1.toDate();
var d2 = m2.toDate();

var str1 = d1.toString(); // "Mon Nov 18 2013 06:55:00 GMT+0100 (CET)"
var str2 = d2.toString(); // "Mon Nov 18 2013 06:55:00 GMT+0100 (CET)"

I expected that str2 to be "Sun Nov 17 2013 22:55:00 GMT+0100 (CET)" because time zone change.
But I get str2 =   "Mon Nov 18 2013 06:55:00 GMT+0100 (CET)".

**Comment by mj1856** [comment]
Calling `,toDate()` uses only the instantaneous point in time, since the `Date` object is incapable of representing anything else.  The `Date` object uses the local time zone when you call `.toString()`.  There's nothing moment could do to change that behavior.

You should instead be using the `format` functions from the moment instances.  They will properly account for the time zone change.

Also, the conversion for this particular time would actually be `21:55`, not `22:55`, as Pacific time has exited daylight saving time and returned to UTC-8 for the date provided.
