### ISSUE TITLE
diff() sets today as 0 and tomorrow as -0

### ISSUE THREAD

**Issue by bensinclair** [moment/moment#2503]
In MomentJS when using `diff()` the difference between today and today is 0. The difference between today and tomorrow is -0. 

Why -0 and not -1?

<a href="http://jsfiddle.net/cs1jxwmt/1/ ">Here's an example.</a> (adjust the today and tomorrow date according to what the date is for you at the time of viewing)

Is this a bug or do I misunderstand the logic behind this?

The main problem I faced was that JavaScript treats 0 and -0 the same. I posted a question on <a href="http://stackoverflow.com/questions/31599665/javascript-detecting-the-difference-between-0-and-0">StackOverflow</a> and luckily I was able to overcome the issue. I'm sure others will face this same issue.

**Comment by alburthoffman** [comment]
not able to see ur example. would you mind fixing it? thx

**Comment by bensinclair** [comment]
Sorry there was an extra character in the URL. Try this link: http://jsfiddle.net/cs1jxwmt/1/

The results are shown in the console so simply open your developer tools to see the result.

**Comment by mj1856** [comment]
It doesn't return `-1` because a full day has not occurred between "now" and "tomorrow at midnight".  The "now" value returned by `moment()` includes the time, not just the date.

If you want to count whole days, you would first need to normalize the time.   I suggest using noon instead of midnight, to avoid issues with DST transitions (not every local day has a midnight in every time zone).

```javascript
var today = moment().startOf('day').hour(12).diff([2015, 6, 26, 12], 'days');
var tomorrow = moment().startOf('day').hour(12).diff([2015, 6, 27, 12], 'days');
```

With regard to `-0`, the docs state:

> If the moment is earlier than the moment you are passing to `moment.fn.diff`, the return value will be negative.

This appears to be implemented quite literally.  Even when the value is zero, it returns `-0` when the first moment is earlier.  @ichernev - Is this intentional?

**Comment by ichernev** [comment]
@bensinclair you should use begining of day (00:00:00) to count day differences, because as @mj1856 mentioned, if now is mid-day (any value not 00:00:00) diffing against another day (midnight), after rounding might not yield the result you expect.

```javascript
> moment()
'2015-07-30T22:18:45-07:00'
> moment().startOf("day").diff([2015, 6, 25], "days")
5
```

@mj1856 you don't have to get middle of day, it handles DST good:
```javascript
> moment([2015, 10, 1]).diff([2015, 10, 2], 'days')
-1
> moment([2015, 10, 1]).diff([2015, 9, 31], 'days')
1
> moment([2015, 10, 2]).diff([2015, 10, 1], 'days')
1
```
There is DST switch on 1st Nov 2015 (in USA).

**Comment by mj1856** [comment]
@ichernev - Except... not all days have a local midnight.  Some time zones start the day at 1:00 on the spring-forward DST transition.

**Comment by ichernev** [comment]
@mj1856 correct. We might consider that a separate bug/feature.
