### ISSUE TITLE
moment(undefined, format) create unexpected result

### ISSUE THREAD

**Issue by inDream** [moment/moment#2525]
For example, in version 2.8.3
`moment(undefined, 'D/M/YYYY H:mm:ss')`
`> Sat Jan 01 0 00:00:00 GMT+0800`
`moment(undefined, 'D')`, `moment(undefined, 'M')` or any other format
`> Thu Jul 30 2015 00:00:00 GMT+0800`
But in version 2.10.6, both of them output
`> Thu Jul 30 2015 00:00:00 GMT+0800`

I wonder is there any change in the api caused this.
As I first thought I've reset the date at some part of the code,
but turns out I've passed wrong parameter into the constructor.
This behavior make debug more difficult.

**Comment by ichernev** [comment]
I can probably debug and tell you why ... but why? I mean -- it is not documented, so at best its undefined .... and it is :) Do you want us to put special code to handle undefined input string? And return what -- invalid moment?

Part of what you're seeing is that we default to today, if some fields are not passed. So if you have YYYY in the format, it tries to read it and gets ... 0, so that would explain results in version 2.8.3. In 2.10.6 we did change a bunch of things, but all tests passed, so we called it a day.

I'm closing this, if you have more constructive feedback (what should behave how, and why), feel free to reopen.

**Comment by inDream** [comment]
My problem is there's no reason that start of today (i.e. `Thu Jul 30 2015 00:00:00 GMT+0800`) will be returned if there's exception input, this is a misleading output which caused a lots of time to debug.

**Comment by danny-andrews** [comment]
I agree. Why is it that `moment(null)` returns invalid moment and `moment(undefined)` returns today. Very misleading indeed.
