### ISSUE TITLE
moment().diff returns negative value

### ISSUE THREAD

**Issue by btmdave** [moment/moment#255]
`//Wed, 04 Apr 2012 21:09:16 GMT
to   = moment.utc().add('m', 60).toDate();
seconds = moment.diff(to, 'seconds');
`
I'm trying to get the seconds from the current time in UTC and another date that is set in UTC.

I'm using `moment.diff`\- the above code returns a negative value of -3600 instead of 3600.  

Is this the correct way to do this? Shouldn't the negative only be if the date has passed?

**Comment by neaucode** [comment]
I just want to point out that this is returning a 'sort comparison value' rather than a positive diff about the gap in time, unlike `git diff` which displays positive / green lines for additions made going forward in time.

Saw it used in a coworkers PR so I had to check but yea -- `git diff @~ @` from past till now is a "positive" change (additions are green and deletions are red)

The gap from the previous date to the future date is what I would expect it to return, but as mentioned, it's giving a 'sort order' value / sort comparison value eg `-1` `0` or `1` for `Array.prototype.sort` indicating which should come first
