### ISSUE TITLE
Moment Truck Factor

### ISSUE THREAD

**Issue by gavelino** [moment/moment#2552]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Moment** and obtained a value of **19**.

The developers responsible for this TF are:

Iskren Chernev - author of 79% of the files
Tim Wood - author of 32% of the files
Abdel Said - author of 4% of the files
Isaac Cambron - author of 3% of the files
Menelion ElensÃºle (Andre Polykanine) - author of 3% of the files
Jonathan Abourbih - author of 2% of the files
Dan Dascalescu - author of 1% of the files
Armen Darabyan - author of 1% of the files
Werner Mollentze - author of 1% of the files
kraz - author of 1% of the files
kaushik gandhi - author of 1% of the files
vajradog - author of 1% of the files
jbleduigou - author of 1% of the files
Nedim Cholich - author of 1% of the files
Petr Bela - author of 1% of the files
Anatoly Mironov - author of 1% of the files
Robert Allen - author of 1% of the files
MadMG - author of 1% of the files
Aggelos Karalias - author of 1% of the files

To validate our results, we would like to ask **Moment** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Moment**?

(b) Do you agree that **Moment** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Moment** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by mj1856** [comment]
Sooo... Are you just spamming every GitHub project you can find? Or did you have some criteria as a basis for your project?

Your results look like they were gathered by automated code rather than a human.

Also, you're only considering code contributors, rather than [project collaborators](https://github.com/orgs/moment/people).  A lot more goes into a successful project than just code.  

Take me as an example. I contribute to moment mostly with respect to tracking issues, answering questions (both on GitHub and StackOverflow), evaluating feature requests, updating documentation, evangelizing, etc.  I contribute code to many other projects, but I rarely contribute to the code here because others are much more versed in the internals of the design.  Your study doesn't take this into account, so it's flawed in principle.

**Comment by mj1856** [comment]
Consider also that many of the contributors you listed as 1% were just those that submitted a PR or two, and haven't necessarily been deeply involved in the project.
