### ISSUE TITLE
isValid() works incorrect for 'MM-DD-YYYY' when day is invalid

### ISSUE THREAD

**Issue by alexkravets** [moment/moment#2561]
Seems like day limit is missing:

```javascript
    > moment('05-118-2015', ['MM-DD-YYYY']).isValid()
    true
```

**Comment by alburthoffman** [comment]
this is somehow by design. Inside moment, it uses regular expression to mathc two digits for DD in this case. In the above example, the day value will be 11 instead of 118, that's why the isValid() function returns true.

But when checking, function getParsingFlags(config) can tell u if there are any skipped letters.

**Comment by alexkravets** [comment]
If this is by design, maybe the function name should be different?

**Comment by sennett** [comment]
@alexkravets I just found this one.  There is a strict option when parsing:  http://stackoverflow.com/a/32355901/614523

**Comment by alexkravets** [comment]
@sennett thank you! this is helpful.
