### ISSUE TITLE
Different results for different invocations

### ISSUE THREAD

**Issue by apandichi** [moment/moment#2564]
Is the following behaviour correct? I expected these two to have the same result.

    moment(new Date("2015-07-08")).toDate()
    Wed Jul 08 2015 03:00:00 GMT+0300 (EEST)

    moment("08/07/2015", "DD/MM/YYYY").toDate()
    Wed Jul 08 2015 00:00:00 GMT+0300 (EEST)

Taking the UTC mode into consideration:

    moment.utc(new Date("2015-07-08")).toDate()
    Wed Jul 08 2015 03:00:00 GMT+0300 (EEST)

    moment.utc("08/07/2015", "DD/MM/YYYY").toDate()
    Wed Jul 08 2015 03:00:00 GMT+0300 (EEST)

Is this by any chance related to https://github.com/moment/moment/issues/1407 (Be careful when falling back to Date constructor)?

**Comment by friday** [comment]
Yes it's correct.

 `new Date("yyyy-MM-dd")` isn't a complete date format, since it missing time. JS adds _UTC_ 00:00. If you want to wrap your time format with `new Date()` it doesn't matter if you use `moment.utc()`. The parsing is already done, and all moment is getting is a JS date.

If you need to use `new Date()` for local time `new Date("2015-07-08 00:00")` behaves that way.

**Comment by mj1856** [comment]
@friday - That doesn't necessarily work in all browsers.  Some will still interpret it as UTC, some might fail with invalid format.

Also, ES5 says an ISO date without a zone is UTC, while ES6 says it's local.  So at some point, the behavior will change - as browsers adopt ES6.

Better to not use the `Date` constructor for parsing.  If moment is loaded, then there's probably not a good reason to anyway.

**Comment by mj1856** [comment]
(But yes, you were correct)  :smile:

**Comment by friday** [comment]
@mj1856 Good to know about ES6 changing to local :)
