### ISSUE TITLE
Does not support ISO 8601 comma separator

### ISSUE THREAD

**Issue by jinder** [moment/moment#2580]
I was debugging a problem with parsing the following date string, which moment was calling invalid:

```
2015-08-09T12:10:51,555
```

According to the [WP article](https://en.wikipedia.org/wiki/ISO_8601), this is valid and the preferred millisecond separator in the standard:

> A decimal mark, either a comma or a dot (without any preference as stated in resolution 10 of the 22nd General Conference CGPM in 2003,[14] but with a preference for a comma according to ISO 8601:2004)[15] is used as a separator between the time element and its fraction. 

Should moment support this?

**Comment by mj1856** [comment]
Yes, it's true that ISO-8601 spec states that a comma is prefered, but in practice - that bit of advice is almost never implemented.  Just about every ISO-8601 parser I've worked with only accepts a period.  Though some will use a period or a decimal depending on what culture settings are in place.  Given that ISO-8601 strings are used as a common interchange format, and you don't always know what's interpreting it, I recommend only using periods (despite the spec).

Though, since it's in the spec, we should probably support it anyway.

Edited #2450 to include this.  Closing this in favor of #2450.
