### ISSUE TITLE
Potential Bug - Phone numbers being seen as valid dates

### ISSUE THREAD

**Issue by jklaus** [moment/moment#2585]
First let me start by saying I don't know whether or not this is intentional or not.. off the top of my head I don't see a reason why you'd want an array of numbers in this format to a valid date but I could be wrong..

First I'll give you the set of circumstances where things work as I'd expect then I'll give you all of the other cases where it does not work as expected.

Correct - moment(#-###-####).isValid() = false
  Moment version: 2.2.1 with..
  IE version: 11.0.9600.17914 / Update version: 11.0.21

Incorrect - moment(#-###-####).isValid() = true
  Moment version: 2.2.1 with..
  IE version: >11.0.9600.17914 / Update version: >11.0.21
  OR
  Moment version: 2.10.6 (current) with
  All versions of IE tested... and all chrome/firefox versions we currently have installed across my team.
  

If I don't hear back from anyone telling me this is actually how it is planned to function I can dig into why its occurring and propose a resolution after work.. Like I said, I'm not familiar with that number format being a standard for date and/or time but I could be wrong.

**Comment by mj1856** [comment]
Any time you parse a string without providing a format, you're relying on the browser to do the parsing.  The only exceptions are the standard ISO-8601 formats that are supported by moment (and a few oddballs, such as the ASP.NET JSON Date format).  If it's something strange (like the phone number), you may or may not get a date out of it - it just depends on what the particular browser does when you call `new Date(string)`.

You will get a deprecation warning from moment in your debug console, because it's not a good idea to rely on this functionality.  If you expect a particular format, you should provide that format.  You may also consider using "strict mode", as in `moment(string, format, true)`.

Read: http://momentjs.com/docs/#/parsing/string/
