### ISSUE TITLE
Wrong `.diff` for days calculation while i need moment base on `days`

### ISSUE THREAD

**Issue by gordomium** [moment/moment#2590]
### Try

```js
moment('2015-08-31').diff('2015-09-01', 'days')
```
```js
-1  // Awesome
```

### Then

```js
moment('2015-08-31 07:43:00').diff('2015-09-01', 'days')
```
```js
-0 // -1 Expected
```

Of cause the diff is not one day enough. But i wanna the diff of **days** as 2nd param of `.diff`. It should return `-1`.

**Comment by mj1856** [comment]
This is by design.  A date without a time is interpreted as the start of the day, which is usually midnight.  Since not a full day has passed, then there are zero days.  Since the first value is still less than the second, you get a negative zero.  See also #2503 

If you want to ignore the time, you can use `startOf('day')` before computing the difference.
