### ISSUE TITLE
Add [at] to localisations

### ISSUE THREAD

**Issue by mrmckeb** [moment/moment#2600]
A few times now I've used moment for projects where there was a need to display "Date [at] Time". This is fine when we're only working with English languages, but gets complex with foreign languages.

Moment's calendar feature partially covers this off - could we add support for localising the word 'at' for appointments and edited times, etc?

**Comment by ichernev** [comment]
You're right in one thing: "its complicated". The thing is some languages don't have `an "at" word`, they use comma, or space, or something else. In order to customize you need to know the language.

If you want your site to work well in fixed number of languages, then get translators to tell you proper formats and use them directly.

If you want your code to work in all moment supported languages, then you have to accept whatever it does now.

**Comment by mrmckeb** [comment]
Thanks for the feedback. I agree that proper translation needs translators, I just thought this may have been a common enough scenarios that it warranted being a feature.
