### ISSUE TITLE
momentjs avalonjs conflict

### ISSUE THREAD

**Issue by ystyle** [moment/moment#2601]
momentjs avalonjs conflict

Uncaught Error: http://localhost:8181/static/momentjs/moment.js模块与之前的模块存在循环依赖，请不要直接用script标签引入http://localhost:8181/static/momentjs/moment.js模块
avalon.mix.error 
@ avalon.min.js:34g.delay 
@ avalon.min.js:127C.define 
@ avalon.min.js:128(anonymous function) 
@ moment.js:9(anonymous function) 
@ moment.js:11

**Comment by ystyle** [comment]
moment.js Modules with the previous module circular dependency,Please do not use the script tag to introduce moment.js module

**Comment by mj1856** [comment]
Please provide code to reproduce.  Otherwise it's difficult to help.  Thanks.

**Comment by ystyle** [comment]
<script src="${ctxStatic}/avalon/1.3.8/min/avalon.min.js" type="text/javascript"></script>
<script src="${ctxStatic}/momentjs/moment.js" type="text/javascript"></script>

**Comment by ichernev** [comment]
Avalon's home page is written in Non-English. If it redefines methods that moment uses to export itself, I can only suggest that the issue is within avalon, not moment. Ask at avalon's bug tracker. Exporting a global `define` function is not great, so its either done for a reason in which case they should help you, or its just a "bug" on their end (or not a very good feature at least).

Feel free to reopen if you have any new data suggesting its moment's fault. Keep in mind we have to export ourselves to AMD and CommonJS and every other guy's module system.
