### ISSUE TITLE
moment("05-03-1997").isValid() in chrome returns true but at firefox returns False!

### ISSUE THREAD

**Issue by amera7md** [moment/moment#2604]
i used latest moment .js but still the issue exist , basically moment("05-03-1997").isValid() at chorme returns true , at fire fox retuns false , and for all "-" dates 

i used moment("05-03-1997". replace(/-/g , "/") ).isValid()  as a work around , 

kindly i would like to participate on its fix , can anyone tell me form where i begin trace at momentjs repositoy ? 

thanks in advance

**Comment by mj1856** [comment]
Please review these docs: http://momentjs.com/docs/#/parsing/string/

If you aren't using one of the listed formats (ex, `YYYY-MM-DD`), then you *must* supply a format string.  Otherwise the value is passed down to the browser (where the behavior varies wildly) and you get a deprecation warning also.

Example:

```javascript
moment("05-03-1997","DD-MM-YYYY").isValid()
```
