### ISSUE TITLE
Incorrect strict parsing behavior for Day of Week (dd/ddd/dddd)

### ISSUE THREAD

**Issue by wmnnd** [moment/moment#2614]
With strict parsing enabled, I would expect all the following calls to return an invalid date:

````js
moment("monday", "dd", true)
// => Mon Dec 29 2014 00:00:00
// Expected: invalid date


moment("monday", "ddd", true)
// => Mon Dec 29 2014 00:00:00
// Expected: invalid date


moment("mon", "dddd", true)
// => Mon Dec 29 2014 00:00:00
// Expected: invalid date
````

Now, it wouldn’t be so bad if `"dd"` were to match results for `"ddd"` and `"dddd"` as well. Unfortunately, even with strict parsing enabled, also completely different strings are matched:

````js
moment("month", "dd", true)
// => Mon Dec 29 2014 00:00:00
// Expected: invalid date
````

I tested this with moment.js 2.10.6.

**Comment by mj1856** [comment]
This is because [the regex defined in `localeWeekdaysParse`](https://github.com/moment/moment/blob/cd49a734350193a244c596a02167221cbca2c06f/src/lib/units/day-of-week.js#L102) scans `weekdays`, `weekdaysShort`, and `weekdaysMin`, and doesn't accept any input other than the string it is scanning for.

**Comment by ichernev** [comment]
@mj1856 I don't think so. The problem is 
```javascript
> /^Monday|^Mon|^Mo/.test("Month")
true
> /^(Monday|Mon|Mo)$/.test("Month")
false
```
We basically have to put parenthesis and add `$` in the end. Other than that it is working fine. If we want to be extra strict and check difference between `dd`, `ddd` and `dddd` t/^(Monday|Mon|Mo)$/.test("Month")
falsehat is a different thing.

@wmnnd so you were unfortunate enough to try with a word that starts the same as a weekday name. I agree its a bug though, but a very subtle one :)

**Comment by mj1856** [comment]
My point was more about being strict with regard to number of characters in total, rather than just number of characters matched.

    moment("monday", "dd", true)

Should be invalid because we're in strict mode and we expected the input to be two characters, not six.
