### ISSUE TITLE
Subtracting days doesn't account for DST changes

### ISSUE THREAD

**Issue by kusold** [moment/moment#2632]
We recently had some tests start blowing up, and I tracked it down to an issue with Moment's handling of DST. In order to get the results I expected, we need to first convert to UTC, then subtract.

Testcase:
```
var moment = require('moment');

// Specifically chosen because DST ends on Nov 1st this year
var endDSTDate = moment('2015-11-02 10:22:33');
var clonedDSTDate = moment(endDSTDate)
console.log(endDSTDate.subtract(3, 'days').toDate())
console.log(clonedDSTDate.utc().subtract(3, 'days').toDate())

```

Actual Run:
```
❯ node moment-testcase.js
Fri Oct 30 2015 10:22:33 GMT-0600 (MDT)
Fri Oct 30 2015 11:22:33 GMT-0600 (MDT)
```

[Fiddle](http://jsfiddle.net/dxt3pfwv/) -- note HTTPS breaks the fiddle since it imports moment as an http resource

I believe that moment should always be doing day/month/year operations on UTC values.

**Comment by mj1856** [comment]
This is by design.  A "day" is not always 24 hours, and moment takes that into consideration.  If you are working with either the default "local mode" (taking on the time zone of the runtime environment), or if you are using moment-timezone and have set a time zone explicitly, then adding a day means adding a "calendar day", which could be 23, 23.5, 24, 24.5 or 25 hours, depending on the time zone and whether you're crossing a DST transition when you do the adding.

Consider the following, in US Pacific Time:

```javascript
var m = moment('2015-11-01 00:00:00');
var a = m.format();  // "2015-11-01T00:00:00-07:00"
m.add(1, 'days');
var b = m.format();  // "2015-11-02T00:00:00-08:00"
```

Note the local time stays the same, though the offset has changed.  25 hours have passed between `a` and `b`.

If instead I did this:

```javascript
var m = moment('2015-11-01 00:00:00');
var a = m.format();  // "2015-11-01T00:00:00-07:00"
m.add(24, 'hours');
var b = m.format();  // "2015-11-01T23:00:00-08:00"
```

Notice that `a` and `b` are 24 hours apart, but the time of day has changed, because of the hour difference in offsets.

A day in UTC is *always* 24 hours, so that is another way to do it.

```javascript
var m = moment('2015-11-01 00:00:00');
var a = m.format();  // "2015-11-01T00:00:00-07:00"
m.utc().add(1, 'days').local();
var b = m.format();  // "2015-11-01T23:00:00-08:00"
```

**Comment by mj1856** [comment]
Oh, in case you were wondering, the 23.5 and 24.5 hour days only occur in the `America/Lord_Howe` time zone.  This is for Lord Howe Island, Australia, which adjusts their clocks by 30 minutes for DST.  For the rest of the world, those that have DST adjust their clocks by one hour.
