### ISSUE TITLE
Calendar reference date ignored.

### ISSUE THREAD

**Issue by mikeljames** [moment/moment#2647]
Hi I've been trying to set the output of the .calendar() method to 'DD/MM/YYYY' for dates that are more than a week ago, 

So tried various ways to do this. See image attached from my console. It appears the referenceDate in the .calendar method is completely ignored...

![image](https://cloud.githubusercontent.com/assets/2983327/10279726/de826794-6b5f-11e5-88c1-c7e63315229e.png)

**Comment by alburthoffman** [comment]
Not sure what your environment is. It does work for me:
```javascript
moment().calendar("2015-09-29T13:38:02.151Z", 'DD/MM/YYYY')
"10/06/2015"
```

**Comment by mikeljames** [comment]
That's not correct either. It should say: 29/09/2015. not 10/06/2015

I'm using requirejs. 
       ` 'moment': 'application/libs/bower/moment/min/moment.min',`

not setting any locale. simply running the method: 
`moment().calendar("2015-09-29T13:38:02.151Z", 'DD/MM/YYYY')`

**Comment by mikeljames** [comment]
Any ideas on what could be causing this? Areas of the code? 

I might have a chance at fixing this.

**Comment by mikeljames** [comment]
It appears the tests on this area of the code doesn't cover this scenario. see: https://github.com/moment/moment/blob/develop/src/test/moment/format.js#L313

**Comment by mikeljames** [comment]
Highlighted the bug in qunit. https://github.com/mikeljames/moment 
https://github.com/mikeljames/moment/blob/develop/src/test/moment/format.js#L318

**Comment by mj1856** [comment]
I think you misunderstand the purpose of the `referenceTime` parameter.  It is there only to be used as a comparison when using outputs similar to "Today as 2:30 AM".  in that string, "Today" matches the reference date, which is why it defaults to the actual current date.

Your code `moment().calendar("2015-09-29T13:38:02.151Z", 'DD/MM/YYYY')` doesn't provide that date as an input - it just uses it as the reference to determine format.  Your input is the actual current date, since you use `moment()`.

Also, the second parameter does not just take a single format string.  If you want that, use the `format` function instead.  On the `calendar` function, this takes an object with a list of overrides from the locale's default calendar formats.

If you just want to change the format when it's not near the reference time, then do this:

```javascript
moment("2015-09-29T13:38:02.151Z").calendar(null, {sameElse : 'DD/MM/YYYY' })
```

BTW, this defaults to `L` (the localized short-date format), so you might just consider changing the locale, rather than customizing the format.

**Comment by mikeljames** [comment]
@mj1856 Thanks for your help this wasn't very clear to me.

**Comment by mj1856** [comment]
Glad to help!
