### ISSUE TITLE
Provide a function that would tell whether a date fragment value is implicit or explicit

### ISSUE THREAD

**Issue by gajus** [moment/moment#2672]
The original question: http://stackoverflow.com/questions/33085487/how-to-tell-if-moment-date-object-date-fragment-value-is-implicit-or-explicit

``` js
// In the following example, month and day are explicit values. Year is implicit value.
// "2015-03-23"
moment('23 March', 'DD MMMM').format('YYYY-MM-DD');

// In the following example, month is an explicit value. Year and month are implicit.
// "2015-01-01"
moment('January', 'MMMM').format('YYYY-MM-DD');
```

In the above examples, how to programmatically tell whether the values of month, day and year are implicit or explicit?

**Comment by mj1856** [comment]
Well, we do retain the input in `_i`, so if the input was parsed from a string or an array then we could possible determine this.  However, if the input was a numeric timestamp or a `Date` object, then that would not be possible.

**Comment by mj1856** [comment]
This might also be handled by producing additional data in response to `.parsingFlags()`

**Comment by icambron** [comment]
I've long wanted to just provide two objects in parsing flags: `mapping` that shows what tokens got matched to what inputs (e.g. `{YYYY: 2015, MMM: "01", ...}`) and `defaulted` that returns a similar map with the default values. I haven't implemented it because at the time I wrote parsingFlags() we were concerned about how much data it took up in every Moment and all its clones. I suspect the right thing to do is to rewrite the whole way we do parsing flags so that everything except `empty` and `overflow` are just regenerated on the call to `parsingFlags()` by reusing `_i` and `_f` to retry the parse. Then we can make it as verbose as we please. But no one has bothered to do that.

**Comment by gajus** [comment]
> I've long wanted to just provide two objects in parsing flags: mapping that shows what tokens got matched to what inputs (e.g. {YYYY: 2015, MMM: "01", ...}) and defaulted that returns a similar map with the default values.

That would be amazing.

**Comment by icambron** [comment]
PRs accepted :)

**Comment by gajus** [comment]
You have 33 PRs that are open without a response. Thats very discouraging for any open-source contributor.

**Comment by icambron** [comment]
So is having 33 PRs to go through and people complaining about it.

**Comment by mvolz** [comment]
I am having a similar issue. I am using chrono-node dates https://github.com/wanasit/chrono and this library internally represents implicit and explicit values. 

However, I would like to format these dates, and they suggested moment.js for formatting: https://github.com/wanasit/chrono/issues/42

However, in order to export the dates, I have to export a Date(), which imputes the missing value. Which I don't want. So it would nice if moment provided this explicit/implicit format internally and then allowed us to format the explicit components alone. 

Ultimately I want to be able to turn an ISO 8601 date like "2010-05" into "May 2014" or "Mayo de 2014" or "Май 2010 г." and vice versa but thus far I've been unable to find any library that can do that.

**Comment by aaronmgdr** [comment]
Is this still open? I see the discussion is from 2015 but the up-for-grabs label was added more recently. Id love to help out on it .

**Comment by shawnchenxmu** [comment]
Need help? I'd like to take the task.

**Comment by marwahaha** [comment]
Sure, this may be a good place to start:
https://github.com/moment/moment/issues/2672#issuecomment-159919602

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
