### ISSUE TITLE
moment.duration does not produce same values when converting units

### ISSUE THREAD

**Issue by furkanmustafa** [moment/moment#2688]
I think I have found an inconsistency, converting a year to seconds, and then those seconds into years doesn't produce the expected value (1).

``` javascript
var duration_1year = moment.duration(1, 'year');
var seconds_1year = duration_1year.asSeconds();

var newDuration = moment.duration(seconds_1year, 'seconds');
var newDurationAsYears = newDuration.asYears();
console.log(
  "Moment",moment.version,
  "says that a year is", seconds_1year, "seconds, but again it claims that\n",
  seconds_1year, "seconds is", newDurationAsYears, "years");
```

This code produces the following output;

```
Moment 2.10.6 says that a year is 31536000 seconds, but,
31536000 seconds is 0.9993360575508053 years
```

**Comment by furkanmustafa** [comment]
Just confirmed the result is same with `month` as in `year`.
Tested in Firefox and Chromium.

**Comment by furkanmustafa** [comment]
This also looks like highly similar to #1867

**Comment by AyanGhatak** [comment]
The problem lies in calculating the ratios to convert days to months in ./src/lib/duration/bubble.js. Currently we assume there are 146097 days(taking in account the leap years), and thereby 12*400 = 4800 days in 400 years. So the conversion ratio for days to months = 4800/146097.

Say we have 365 days as days, then months = days * (4800/146097) = 11.992032690609664 and not 12.

So, on a deeper thought, it may be evident that when we are counting the number of days in 400 years we include 97 extra days due to leap years, but we neglect them in month calculation. This creates the issue because 97 days in itself add some quantity to the month total.

The question is how many months is 97 days?
If 30 days = 1 month, then as per the example above,
365 days = 365*(4800+(97/30))/146097 = 12.000110657074867 which is not again equal 12.Not only that, making this change leads to failures of 23 test cases defined out of 2514 tests.

**Comment by icambron** [comment]
I think we can call this a bug, but yeah, it's not obvious exactly what to do here.

**Comment by marwahaha** [comment]
there was a proposal to change the duration calculation here: https://github.com/moment/moment/issues/3209#issuecomment-248367814

Open to comments.

**Comment by marwahaha** [comment]
I think we will not make changes here. See https://momentjs.com/docs/#/-project-status/

**Comment by megasyl** [comment]
365.2425 * (4800/146097)
