### ISSUE TITLE
Time Setter

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2707]
It would be useful to have a function to set the time as a string.  Currently we only have functions for setting each individual component of time.

Examples:

```javascript
var m = // some moment object
m.time("23:55");
m.time("23:55:00");
m.time("23:55:00.1234567");
m.time("11:55 PM", "h:mm A");
```

Currently, one has to do something like this to achieve the same effect:

```javascript
moment(m.format("YYYY-MM-DD") + ' ' + timeString, "YYYY-MM-DD " + formatOfTimeString)
```

Parsing and  reformatting is not good, as it ignores any subtleties such as the utc/local mode, offset, or time zone.

**Comment by debopamsengupta** [comment]
Would like to contribute on this

**Comment by mj1856** [comment]
Go for it! :)

**Comment by mj1856** [comment]
@debopamsengupta - Any update for us?  If not, someone else feel free to grab it.  We'll go by first to submit a PR, or best implementation if there's a close tie. :)

**Comment by maggiepint** [comment]
I'm willing to look at this if it's not being worked on.

**Comment by maggiepint** [comment]
Slight API design concern - I would argue that this function should be called setTime(), not time(). All of the similarly named functions to time (hour, minute, second, date) both get and set, and they set with a single numeric parameter. Calling it time(), to me implies that this function also does these things. 
One could of course explore the alternative of making the function both get and set, but this API is even messier as it cannot use a parameterless constructor (unknown format for date), and would return a string where everything else returns a number.

An argument could be made that time() is more intuitive because it's similar to other setters and thereby is more appropriate, even though there is no get. I wouldn't argue if that's how you wanted it to be, and it hardly matters to the implementation. Just thought I would point this out. I have never contributed to this library before, so I may well be missing something.

**Comment by mj1856** [comment]
Good points, and welcome to Moment!

I suppose it could return the current time as a string, but then it might get conflated with `format`.  Probably better not to have a getter, and then it deviates in convention from the other functions.

I'm fine with `setTime`.  We might want to consider integer input also, probably in units of minutes (whole or decimal).

**Comment by mj1856** [comment]
PR underway with #2914

**Comment by mj1856** [comment]
Reopening for visibility until a new PR is ready.

**Comment by mj1856** [comment]
Now tracking in PR #2938
