### ISSUE TITLE
moment().format does not alert when passed in undefined!

### ISSUE THREAD

**Issue by yinrong** [moment/moment#2729]
moment().format can take zero arguments, but when the first argument is undefined, it should throw or return null.

The reason is: One time I happened to passed a undefined variable. It formats to wrong result leading the following procedure got wrong result, which I discover this a long time after.

Hiding exception is dangerous

**Comment by icambron** [comment]
No, that's not quite how JS works: calling a function with no arguments is the same as calling it with all those arguments undefined; that's actually what `undefined` is meant to mean. From my Node repl:

```
> var foo = function(bar, baz){
... return {bar: bar, baz: baz}
... }
undefined
> foo(1, 2)
{ bar: 1, baz: 2 }
> foo(1)
{ bar: 1, baz: undefined }
> foo()
{ bar: undefined, baz: undefined }
```

It's possible to detect the difference between passing `undefined` in explicitly and calling it with no args by inspecting the `arguments` magic var, but it's a bad idea because it's a) not standard JS practice and b) makes it annoying for callers who *want* to pass in undefined.
