### ISSUE TITLE
moment cannot always parse moment default formatted negative years

### ISSUE THREAD

**Issue by gautaz** [moment/moment#2730]
Hello,

The following is perhaps off-limits, but seems an issue:

``` javascript
var min = moment('-271821-04-20 02:00');
console.log(min.format());
// -271821-04-20T02:00:00+02:00

var tsm = moment(min.format());
console.log(tsm.format());
// -271821-04-20T02:00:00+02:00

var ts1 = moment('-000001-01-01 00:00');
console.log(ts1.format());
// -0001-01-01T00:00:00+01:00

var ts2 = moment(ts1.format());
console.log(ts2.format());
// Invalid date

var ts3 = moment('-000002-12-31T23:00:00.000Z');
console.log(ts3.format());
// -0001-01-01T00:00:00+01:00

var ts4 = moment(ts3.format());
console.log(ts4.format());
// Invalid date
```

I know it is better to tell moment the format while parsing but shouldn't moment at least be able to parse the format it produces by default ?

**Comment by icambron** [comment]
Yeah, there's probably a bug in the ISO parser there. Would be happy to take a fix.

**Comment by ichernev** [comment]
That is a weird one. If you use `toISOString()`, then it correctly outputs `-000001`, which can then be correctly parsed.

`format()` uses a default format with `YYYY`, that would then output `-0001`, which can then not be strictly parsed into ISO, because ISO forbids 4 digits with a sign, and states you should use more (and in moment we stick with 6 digits in this case).

On the other hand there is the problem that `YYYY` does not parse any leading signs, so if you have year : `y < 0 || y > 9999` it won't be parsed correctly with `YYYY`, even though it was formatted with `YYYY`.

If we change the way `YYYY` parsing works, it will break for cases like `'20151209', 'YYYYMMDD'`, because `YYYY` can in theory consume more than 4 digits (if the input was bigger), and this case is far more likely than the case with an year bigger than `9999` or negative. Only supporting negative is going to fix the issue presented here, but won't fix years above `9999`, or below `-9999`.

* So if the concern is `format() produces something unparsable` we can fix format to use `YYYYYY` instead for weird years.
* If the issue is that format('YYYY') can not be parsed with 'YYYY', then we can only (maybe) fix that for `y in (-9999, -1)`, because the other option is impossible.
* If the issue is that `-0001-...` is not valid ISO ... not sure what to do here, as the docs don't really specify anything about years below 1583, except "the parties should reach an agreement". So if the agreement was to use ISO string (`toISOString` not `format`), this is a non-issue.

**Comment by marwahaha** [comment]
I think both 1 and 2 are important. I feel like being able to parse whatever the default to `format` is an important guideline. Plus, the symmetry is important (format->YYYY should parse with YYYY).

**Comment by MichaelYogar** [comment]
Hi, I'm looking to make my first open source contribution. If nobody is working on this, I can try to solve this issue.

**Comment by okatarismet** [comment]
Hi, Is anyone still working on this ?

**Comment by gautaz** [comment]
As Moment.js is now considered legacy, I am closing this issue, feel free to reopen it in case you are actively working on it.
