### ISSUE TITLE
days difference broken in some timezones

### ISSUE THREAD

**Issue by stilltorik** [moment/moment#2756]
I reproduced this issue in Asuncion (Paraguay, UTC-4), but I think it happens in any timezone where the time-change occurs at midnight.

So in this timezone,
`moment(new Date(2016, 9, 3)).diff(new Date(2016, 9, 2), "d")` returns 0 instead of 1.

**Comment by mj1856** [comment]
Yes, this is a known problem, and not one we can fix.

The problem occurs any time you reference a civil time that does not exist, which is always on the day of the spring-forward transition.  The `Date` object will adjust the value to a civil time that *does* exist.

![image](https://cloud.githubusercontent.com/assets/1396388/11284127/03afb7d0-8ebd-11e5-8233-428f8be32c41.png)

Most implementations skip forward by the DST bias (usually 1 hr), which is reasonable, but some actually skip *backward*, which is not good.

Recognize that the `Date` object is always a date+time object.  If you don't specify a time, it uses `0`, which is midnight, which may or may not exist.

If you don't care about time, and are just working with date, the safest workaround is to explicitly choose a time that is not near a DST transition.  In other words, choose *noon* instead of *midnight*.

```javascript
moment(new Date(2016, 9, 3, 12)).diff(new Date(2016, 9, 2, 12), "d")
```

**Comment by mj1856** [comment]
Also, you don't really need the `Date` object here.

```javascript
moment([2016, 9, 3, 12]).diff([2016, 9, 2, 12], "d")
// or
moment('2016-10-03 12:00').diff('2016-10-02 12:00', "d")
```
