### ISSUE TITLE
Parse String + Format issue

### ISSUE THREAD

**Issue by bms270** [moment/moment#2758]
The following date parse results in a wrong date:

testDate = moment('20151114240833','YYYYMMDDHHmmss',true);
//Results is: Nov, 15, 2015 00:08 am   (should be Nov 14)

It looks like the parser adds 1 day to the date when the hour value is 24.

**Comment by MartynDavis** [comment]
Um - hours has range 0..23.  The extra hour is causing the date to roll over.
Try using a value of '20151114230833', and the date won't roll over.

**Comment by bms270** [comment]
Thanks for the reply. I understand but the issue is most other date libraries consider the midnight hour as 24 instead of 0. My data is coming from Apple iOS date function and Android (Java.Util.Date) and both use 24 as midnight hour. I can wrap the parse function in my own script to check this every time in and update the string if the hour is 24 but considering different format it would be almost re-writing the parse function. I believe this should be handled in the library in the parse function.

**Comment by MartynDavis** [comment]
'k' is used to display the number of the hour of the day (1..24), as in 1st hour of the day 000000..005959 (using your format HHmmss), 2nd hour 010000..015959, ..., 24th hour 230000..235959".
With each second of the day being represented in the HHmmss sequence 000000..235959, which of these seconds in the day should 240833 match?
moment will wrap around lower values (hour in your case), increment higher values (day in your case).
So moments takes 240833 and returns a time of 000833 plus one day.
I think you need to go back and review why you are using 1..24 as the hour values rather than the standard 0..23.

**Comment by mj1856** [comment]
The current functionality is working correctly in that we can *parse* a 24, and it correctly identifies it as midnight at the end of the day, which is the same moment in time as midnight at the beginning of the next day.

However, you are correct that we do not currently have a formatting token to emit hours 01-24.  Adding one would be tricky, as it would affect the output of all the other tokens as well.  You'd basically have to subtract a day if and only if that token was present *and* the corresponding hour was midnight.  It's doable, but I'm not sure how useful it would be.

There's certainly no chance of us changing `HH` such that it used 24 instead of 00 just because an input string also contained 24.  You'd have to explicitly use the new token (`kk` or whatever).

**Comment by mj1856** [comment]
Close in favor of #2762
