### ISSUE TITLE
isValid() returns true for random Strings

### ISSUE THREAD

**Issue by gillerr** [moment/moment#2789]
I'm trying to validate a user input that should be a date with following format: `12:30 PM`.
Unfortunately, following code yields `true`
```
moment("not a real date", "h:mm A").isValid();
```

But if you remove the "A" (Post or ante meridiem) from the format, it returns the expected `false` result:
```
moment("not a real date", "h:mm").isValid();
```

**Comment by SwamWithTurtles** [comment]
I've had a look at this issue, and it is *technically* (and I mean that tenuously) correct. The big problem is that you haven't put strict mode on, so it's being really permissive. It's recognising the 'a' from your input as the 'A', noticing that at least one thing has been recognised and since 'isValid' is very permissive, it just says 'yup, that's fine!' 

For your purposes, the solution is to just use strict mode (i.e. moment(foo, "h:mm A", true)).

However, on the larger scale, I assume that this is clearly not intended, and therefore there's a small number of ways this can be solved:

* The meridien (i.e. am or pm) currently supports single letter inputs (a or p) which is making this behave particularly oddly. Changing them to match only double letter inputs will make this behave slightly more rationally, but will still claim (e.g.) "I am Spartacus" is a valid date/time.
* We could make the isValid syntax slightly more rigorous by rejecting anything that has left over tokens - i.e. "It is 7:52" wouldn't match "h:mm" any more.
* We could make the isValid syntax slightly more rigorous by rejected anything that doesn't use all of the tokens provided in the time - i.e. "7:52" wouldn't match "h:mm A".

Do people have a preference as to which solution we use? I'm happy to put a pull request in put they do all break current tests. Now, I'm not necessarily convinced by the test cases, and may just be there to test the (at times bizarre) implementation, but I'm aware we don't necessarily want to break the underlying test as a developer may have made a contract to it.

Thoughts?

**Comment by gillerr** [comment]
Thanks for your reply.

Actually I solved the issue with `moment(string, "h:mm A") == string`. But I will change this to use strict mode.

I am not convinced but your 3 solutions. As you say they do break some tests. Moreover the change of behavior is likely to break actual implementations. As it is not a critical issue and can easily be solved with strict mode, I wouldn't recommend a change there.
But I think a note in the documentation on the `isValid()` function in non-strict mode would be nice.

**Comment by SwamWithTurtles** [comment]
Agreed- made a pull request in to the documentation:

https://github.com/moment/momentjs.com/pull/252
