### ISSUE TITLE
Standalone localized time ago statements 

### ISSUE THREAD

**Issue by kirkstrobeck** [moment/moment#2791]
I’d like [Time from now](http://momentjs.com/docs/#/displaying/fromnow/) and [Time to now](http://momentjs.com/docs/#/displaying/tonow/) to have a standalone flag.

    in a day
    a few seconds ago

would be

    In a day
    A few seconds ago

**Comment by mj1856** [comment]
Couldn't you just apply the casing yourself?

FWIW, it wouldn't be valid English to capitalize like that, since they are not complete sentences.

**Comment by kirkstrobeck** [comment]
- I don’ know the [capitalization rules](https://www.youtube.com/watch?v=0j74jcxSunY) of every language
- I didn’t assert that it needs to be grammatically correct.

**Comment by icambron** [comment]
See also #2710 (opposite problem with `.calendar()`), #2192 (similar discussion), #1201 (long similar discussion, though again about `.calendar()`).

I'll say three things:

 1. We don't know the capitalization rules for all languages either.
 2. The conclusion of #1201 was that this wasn't a good idea.
 3. Given those, this lower case setup seems best

Unless @ichernev has changed his mind since #1201, we wouldn't even accept a PR that did this. But if he has changed his mind, then we'd need a PR that a) added a way to capitalize differently in different in different languages and b) an implementation of it for every locale we support.

Since none of that seems likely, I'm closing this.
