### ISSUE TITLE
AM/PM not localized

### ISSUE THREAD

**Issue by danielgindi** [moment/moment#2795]
Hello!

Is there a reason that I'm missing that AM/PM strings are not localized?

**Comment by icambron** [comment]
They are:

```js
moment().locale('ru').format('a')
"вечера"
```

However, Moment doesn't require locales to override it because many languages don't really have that concept, and if so we just default to the AM/PM strings (You can see the defaulting [here](https://github.com/moment/moment/blob/develop/src/lib/locale/prototype.js#L70). If you know of a locale that has mediem terminology but doesn't have them set in the locale file, please create a PR that overrides the default for the location.

**Comment by danielgindi** [comment]
OK so it just that the languages I checked didn't have them... I will, thanks :-)

**Comment by alonsourbano** [comment]
This does not work with Finnish. If I put `moment().locale('fi').format('a')` it shows `pm`, which is wrong, since it should be `ip`
