### ISSUE TITLE
Date format bug

### ISSUE THREAD

**Issue by MHakvoort** [moment/moment#2802]
Moment.js seems to have a problem formatting 29-02-2015. It's not a leap year so I expect it to be an invalid date, but instead it returns me 29-02-2020.

I created a small fiddle to reproduce the bug : http://jsfiddle.net/r42jg/1183/

**Comment by mj1856** [comment]
There's no bug in `format`, but there's a few things wrong in your fiddle:

1. You're referencing version 2.2.1 of moment.js.  The current version is 2.10.6.  Many bugs have been fixed since then.  Please update.

2. When you specify an array of formats, they should be in order from most restrictive to least restrictive.  Instead of ` ['DD-MM-YY', 'DD-MM-YYYY', 'DD-MM']` you should pass ` ['DD-MM-YYYY', 'DD-MM-YY', 'DD-MM']`.  Otherwise, the first one matches the `YY` on `20` in the year, thus making the year 2020 which is indeed a leap year.

3. You also need to be parsing in *strict mode* to make this work.  Pass `true` as a third parameter, as in: ` moment(dateString, formats, true)`.
