### ISSUE TITLE
moment('2015-12-27') == year 2015, week 1

### ISSUE THREAD

**Issue by FallenMax** [moment/moment#2853]
```javascript
console.log(moment().format())  // this test is produced on: 2016-01-03T23:47:51+08:00

var date = moment('2015-12-27')
console.log('year:', date.year())  // 2015
console.log('week:', date.week())  // 1
```
pen: http://codepen.io/anon/pen/yegPoY

Is this a problem or am I misunderstanding how `.week()` works?

relevant issue: #2834

**Comment by icambron** [comment]
Well, you want to check the weekYear, not the year, which just gives you the calendar year.

```js
var date = moment('2015-12-27')
console.log('year:', date.weekYear())  // 2016
console.log('week:', date.week())  // 1
```

i.e. it's part of the first week of the 2016 week year.

Weeks are a bit confusing around new year, and it's different from locale to locale if you use `week` instead of `isoWeek`. In the US, I _think_ the first week of the year is the Sun-Sat period that has a Thursday in the new calendar year. However, that definition would make 12-27 part of the last week of 2015 because the relevant Thursday is the 31st. So...I'm not sure.

**Comment by icambron** [comment]
@ichernev is this related to #2702? Or am I just misunderstanding how we define the start of the week year?

**Comment by FallenMax** [comment]
@icambron Thanks for your explanation!  I misunderstood `year` and `weekYear`. 
So `(iso)week` and `(iso)weekYear` should be used together to uniquely determine a date.
