### ISSUE TITLE
timezone is wrong in version 2.4.0 and subtract month function throws error in version 2.11.0

### ISSUE THREAD

**Issue by visvak** [moment/moment#2860]
Hi,

We are using the momentjs version 2.4.0
we are getting wrong timezone when the date-time is converted to moment.
for example 
  var momentNow = moment(nowNew).format('MM/DD/YYYY h:mm A ZZ');
"01/04/2016 9:42 PM +0530" 
 is wrongly shows as "01/04/2016 9:42 PM +0550"	
 
I tried to update the latest version () of moment.min.js bit i am getting the below error
when we try to subtract 6 months it gives the below error.
 moment(momentNow).subtract('months', 6)
0x800a1391 - JavaScript runtime error: 'console' is undefined

attached the screenshot of the error
please give me a solution.

![error](https://cloud.githubusercontent.com/assets/16287275/12094191/43c79c36-b32d-11e5-9552-c638a0bb356e.PNG)

**Comment by icambron** [comment]
What browser (or other environment) is this running in?

**Comment by visvak** [comment]
We are using visual studio ultimate 2013.
when we try to use the subract function
we are getting error message 
"moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.\nArguments: [object Object]\nundefined""

**Comment by icambron** [comment]
That's not an error; it's just a deprecation warning from the `moment` constructor. It's what the `console.warn()` statement is trying to tell you. What's confusing me is that you got an error about `console` itself being undefined. That's both surprising in itself (why isn't console defined?) and seemingly impossible (Moment [checks](https://github.com/moment/moment/blob/develop/moment.js#L765) whether `console` is defined before using it).

I take it you defined `console` in order to see the error?

**Comment by mj1856** [comment]
@visvak - your `momentNow` variable is a *string*, which you created via the `format` function.  When you pass this string into the moment constructor, since it's not in one of the standardized formats shown [in the docs](http://momentjs.com/docs/#/parsing/string/), you get the error.  That is expected.

You should not be creating a moment, formatting it to a string, then parsing it back as a moment again.  If you could explain why you thought you needed to do that, and what you were trying to achieve, we can offer the correct solution.  Thanks.

**Comment by mj1856** [comment]
@icambron that may be a side effect of the IDE.  Looks like Visual Studio to me.  Not sure how specifically it's being loaded or invoked, so hard to say.  I don't think it's worth worrying about.

**Comment by mj1856** [comment]
@visvak  - Just guessing from looking at your code, you probably wanted something like:

```javascript
var today = moment().startOf('day');
var maxDateMom = moment(today).subtract(6, 'months');
```

Though I'm not sure what you're doing from there because the screenshot doesn't show any code where the moment-based values are used.

**Comment by visvak** [comment]
we are displaying the time with time zone in text box. 

how can i do it . i need to subtract 6 months from the current date.
