### ISSUE TITLE
Russian months and days of week capitalization

### ISSUE THREAD

**Issue by SukharevAndrey** [moment/moment#2882]
Months and days of week in russian language should not be capitalized.
Examples:
* January 1st = 1-го января
* Next Monday = В следующий понедельник
* Fri, January 1st = 1-го января, пт.

Reference: [rules of Russian language](http://new.gramota.ru/spravka/rules/139-prop)
It was suddenly capitalized in c74a101d549b8b443b72d9a470839eaffea852c2

**Comment by mj1856** [comment]
They were specifically requested to be capitalized in #2369 and done in #2579.

@ichernev  - It seems we can't win. Some want capitalization and some do not.  Perhaps we should support both in every locale with an option flag?

**Comment by ichernev** [comment]
One way is to have flags to configure each locale, or have different locales, or make functions accept the flag at use time (not very simple with format function).

**Comment by pycbouh** [comment]
I have to support @SukharevAndrey on that one. We were surprised to find newly added capitalization, because when using moment for date formation it is wrong to capitalize names. I understand, that for calendar context these changes needed to happen. But the situation is not cut and clean.

I would suggest you not to introduce a new flag, but rather support both variants and interchange them depending on context. You will need to introduce a set of cases, but it can work out for everyone. You must as well keep in mind that we want to use the same formatting mask for different languages, so *14 January 2016* becomes *14 января 2016* without any code changes.

Also, I would guess that this is not Russian-specific and is similar in other cyrillic languages such as Ukrainian.

**Comment by syrnick** [comment]
+1. They shouldn't be capitalized by default.

**Comment by polkovnikov-ph** [comment]
:+1:

I don't see it written anywhere, but we _would_ like to capitalize it if it's a first word of a sentence (i.e. a title of calendar). But I think `moment` has nothing to do with that, and it's done in an easy and correct way via simple regex replacement or String.properCase function.

**Comment by socketpair** [comment]
Ну я пофиксил вроде. Заметил сам, и только потом нашёл эту "иззую"

**Comment by socketpair** [comment]
@ichernev different languages have different rules about capitalisation.

**Comment by timeking** [comment]
Please merge https://github.com/moment/moment/pull/2907 
it fixes this problem

**Comment by socketpair** [comment]
Закрывайте. Пофикшено.
