### ISSUE TITLE
isDSTShifted fails after hours are set

### ISSUE THREAD

**Issue by maggiepint** [moment/moment#2942]
I noticed while playing with the parser that the isDSTShifted function will not work correctly if one of the set functions is called on the date. The following unit tests fail on a computer set to US central time where DST shift did happen on that day of that year at that time - I realize they don't work in the general case.

```javascript
assert.ok(!moment('2013-03-10 2:30', 'YYYY-MM-DD HH:mm').hours(3).isDSTShifted(), 'DST is no longer shifted, date was moved to 3:30');
assert.ok(moment('2013-03-10 3:30', 'YYYY-MM-DD HH:mm').hours(2).isDSTShifted(), 'DST is now shifted as date was moved to nonexistent time');
```

This is because the isDSTShifted function simply re-parses the original input and format to make it's determination of whether DST is shifted:

```javascript
export function isDaylightSavingTimeShifted () {
    if (!isUndefined(this._isDSTShifted)) {
        return this._isDSTShifted;
    }

    var c = {};

    copyConfig(c, this);
    c = prepareConfig(c);

    if (c._a) {
        var other = c._isUTC ? createUTC(c._a) : createLocal(c._a);
        this._isDSTShifted = this.isValid() &&
            compareArrays(c._a, other.toArray()) > 0;
    } else {
        this._isDSTShifted = false;
    }

    return this._isDSTShifted;
}
```

This function also doesn't have test coverage. This may be because there isn't a great way to mock clock behavior in this situation.

I can get to this after I finish the set time request. I just wanted to document it. Also, let me know if I am misinterpreting the intent of the code.

**Comment by mj1856** [comment]
Definitely a bug, but I'm wondering if the real problem is that `_a` is not updated when `hours` is called.  

@timrwood @ichernev - should it be?

Presumably the other setters have the same issue.

```javascript
var a = moment('2013-03-10 2:30', 'YYYY-MM-DD HH:mm');
var b = moment('2013-03-10 3:30', 'YYYY-MM-DD HH:mm').hours(2);

a.format() // "2013-03-10T03:30:00-07:00"
b.format() // "2013-03-10T03:30:00-07:00"
a._a       // [2013, 2, 10, 2, 30, 0, 0]
b._a       // [2013, 2, 10, 3, 30, 0, 0]
```

Is `_a` supposed to be consistent with the current state at all times, or just represent the input?  If so, why do we care about the input? And related, why do we sometimes track `_i` anyway?

**Comment by mj1856** [comment]
@maggiepint - FYI, there are other issues with `isDSTShifted`, but I don't think they're the cause here.  See #2618 and moment/moment-timezone#131.  Past issues include #2141, but that was presumably fixed with #2476.

**Comment by maggiepint** [comment]
FWIW this also fails, and I think it should pass, as the resultant date is '2013-03-10 1:30'
    assert.ok(moment('2013-03-09 2:30', 'YYYY-MM-DD HH:mm').add(1, 'days').isDSTShifted(), 'add a day to make dst shift');

I'm starting by fixing the setters though.

**Comment by icambron** [comment]
Ooh, I know this one. Some things:

 0. I agree that the setters should get this right.
 1. Yeah, there's no attempt to update `_a` on mutation.
 2. [This might no longer be true] but sometimes, we don't even create `_a`. See, e.g. #2476, so any fix that makes the setters do it would have to be able to generate `_a`. It might make more sense to just have the setters check themselves with the getter to make sure it matches instead of trying to go back through `_a`, but I am not sure.
 3. Adding shouldn't make that flag true; the flag is supposed to only mean "that time doesn't mean what you asked it to mean", not "DST was involved in this calculation".

**Comment by maggiepint** [comment]
You are correct that sometimes _a is never constructed. I'm half way through constructing it manually in my code.

I kinda like your check selves with the getter idea though - that is going to really reduce the likelihood of forgetting to change the _a value everywhere the date can be changed. Trying to think if there is a disadvantage to this, or if there is some yet unseen advantage to maintaining _a's value.

**Comment by icambron** [comment]
@maggiepint I think it mostly boils down to how ugly the code is in the two options, so you're def in the best position to say. That said, I'm a little suspicious of my idea, because it needs to differentiate overflow cases (`m.hour(25)`) that also don't match the setter, which all that logic with `_a` already handles.

**Comment by maggiepint** [comment]
Taking into consideration the overflow issue mentioned above, this situation is heading into very non-trivial territory. 
Whether one decides to maintain the value of _a as the time changes (to avoid the re-parsing of the original input as happens now), or to try to check the setter against the getter, the overflow matters. I'm not aware of a way to get around having to normalize the overflow data, potentially incrementing multiple parts (or even all of the parts) of the date along the way. This becomes an incredible pain:

***js
>moment('2012-12-01T02:30:00').date(100).format()
<"2013-03-10T03:30:00-05:00"
***

If we're going to start doing everything to get the above calculation correct, then ultimately I wonder if the right thing is to regroup on how DST is done in general, and try to fix #2618 

I'm hoping someone will point out something obvious I missed here - but I'm not seeing a good way around handing that overflow.

**Comment by maggiepint** [comment]
Follow up thought - we could simply choose to handle overflows by assuming that the user was trying to add or subtract, not set, and that isDSTShifted should therefore be false under Isaac's logic about the meaning of this indicator.
That solution would be reasonable to implement as one wouldn't have to worry about changing all the date parts.

**Comment by icambron** [comment]
I think we should forbid setting to overflowed dates. That's actually how the constructor works already:

```js
> moment({h: 100}).format()
'Invalid date'
```

just not the setters:

```
> moment().hour(100).format()
'2016-02-29T04:29:54-05:00'
```

I think that's kinda silly on its own, but salient here because fixing it makes this `isDSTShifted` business easier.

I think that if you keep `_a` up to date, that will work itself out naturally. `isValid` calls `checkOverflow()` which will look at the (now updated) `_a` and return false. Then `isDSTShifted`, which checks `isValid()` for precisely that reason, will never return true on overflows, and we're good to go.

**Comment by maggiepint** [comment]
We deprecated this.
