### ISSUE TITLE
Parse input with time zone offset in separate field

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2945]
`moment.parseZone` is good when the input string contains the time zone offset, however sometimes the offset is in a separate field, as either a string or in terms of whole minutes.  This can lead to code like:

``` javascript
var input = "2014-01-08 8:00 AM";
var offset = 300;
var m = moment.utc(input, "YYYY-MM-DD h:mm A").add(offset, 'minutes').utcOffset(offset);
console.log(m.format()); // "2014-01-08T18:00:00+05:00"
```

It would be better if the offset could be passed as a parameter to `parseZone`.

See moment/momentjs.com#97

**Comment by suisha** [comment]
Hey, I'd like to work on this, but I have a question about how this would work.

It looks like `parseZone` currently has four parameters since it defers to [`local__createLocal`](https://github.com/moment/moment/blob/develop/moment.js#L1508-L1510). Should I be adding a fifth parameter to handle the offset here? That seems like it could potentially be messy to use, eg:

`moment.parseZone('2014-01-08T18:00:00', null, null ,null, '+05:00').utcOffset() // 300`

**Comment by mj1856** [comment]
Good question!

It should mimic the style of the `moment.tz` function (from moment-timezone).  If the *last* parameter is parseable as an offset, then use it.  So, all of the following should work:

```javascript
moment.parseZone("2015-01-01 00:00:00", "-05:00")
moment.parseZone("2015-01-01 00:00:00", "YYYY-MM-DD HH:mm:ss", "-05:00")
moment.parseZone("2015-01-01 00:00:00", "YYYY-MM-DD HH:mm:ss", "fr", "-05:00")
moment.parseZone("2015-01-01 00:00:00", "YYYY-MM-DD HH:mm:ss", true, "-05:00")
moment.parseZone("2015-01-01 00:00:00", "YYYY-MM-DD HH:mm:ss", "fr", true, "-05:00")
```

(and of course, it should work with offsets of either numeric form (in minutes), or as strings in `+-HH:mm`, `+-HHmm`, or `+-HH` format.

**Comment by suisha** [comment]
Regarding strict parsing:

Currently, `moment.parseZone("2015-01-01 00:00:00-05:00", "YYYY-MM-DD HH:mm:ss", true)` will return `NaN` because (I'm assuming) strict parsing does not recognize the offset. Is this expected behavior, and if it is, should the new version of `parseZone` also work this way?

**Comment by maggiepint** [comment]
What you're seeing here is because you haven't specified Z in your format string, so the parser is not expecting the offset and sees it as unused input. The following would be the right way to parse that string:
```js
moment.parseZone("2015-01-01 00:00:00-05:00", "YYYY-MM-DD HH:mm:ssZ", true).format()
```
So basically yes, the behavior is expected and should continue to work that way.
That does raise an interesting question though - what happens if parse zone has both an offset in the date and an offset parameter? I'm honestly not sure what the right behavior is. Probably just take the date's offset I suppose.

**Comment by Jokero** [comment]
This is really needed feature. For example, I have a local date like `2016-06-15` which I get from user and offset `360` in minutes which I store in DB for user. I want to get the following formatted string `2016-06-15T00:00:00+06:00`, but I can't do this in a simple manner

**Comment by Jokero** [comment]
@mj1856 I don't understand why do you use `add` instead of `subtract` in your example?
```js
var input = "2014-01-08 8:00 AM";
var offset = 300;
var m = moment.utc(input, "YYYY-MM-DD h:mm A").add(offset, 'minutes').utcOffset(offset);
console.log(m.format()); // "2014-01-08T18:00:00+05:00"
```
If input contains local to timezone with offset time the correct result is `2014-01-08T08:00:00+05:00`

**Comment by jamespedid** [comment]
I'm confused why the _tzm field isn't used to automatically set the utcOffset. We found use in using this.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
