### ISSUE TITLE
Returns wrong year 2020, instead of 2016

### ISSUE THREAD

**Issue by laukstein** [moment/moment#2948]
`moment("01/25/2016", "MMDDYY")._d`

returns 

`Sat Jan 25 2020 00:00:00 GMT+0200`

while expected

`Sat Jan 25 2016 00:00:00 GMT+0200`

I think in this case format `MMDDYY` must be validated as `MMDDYYYY`.
Format `MMDD` returns fine results.

**Comment by mj1856** [comment]
Provide separators in the format string:

```JavaScript
 moment("01/25/2016", "MM/DD/YYYY")
```

Also, do not use `_d` or other underscore prefixed fields.  Use `format` and other functions described in the docs instead.

**Comment by laukstein** [comment]
@mj1856, `moment("01/25/2016", "MM/DD/YY")` still will return 2020 instead of 2016.

**Comment by mj1856** [comment]
Correct, because you're telling it to look only at the first two characters, `[20]16`.  If you want to test multiple formats, you must test the four-digit `YYYY` before testing two digit `YY`.  The order in array of formats matters.

Also note that moment already has this functionality (passing in an array of formats), so you don't have to write it yourself.

Additionally, if you test `YYYY` first, you don't need to test `YY` at all.  In other words, `moment("01/25/16", "MM/DD/YYYY")` will catch both.
