### ISSUE TITLE
moment().isoWeekday(1) not working

### ISSUE THREAD

**Issue by TrySpace** [moment/moment#2961]
I'm trying to print out the weekday like `Tuesday`:

`moment().isoWeekday(1)
`

But all I'm getting is an object:
```

d: Fri Feb 12 2016 12:03:33 GMT+0100 (W. Europe Standard Time)
_isAMomentObject: true
_isUTC: false
_isValid: true
_locale: Locale
_pf: Object
__proto__: Moment
```

I'm doing: 

`day = moment(new Date(parseInt(ts))).weekday()`
then:
`moment().isoWeekday(day)
`
But it outputs an object

I've tried `moment().day(1)`, same result

And `moment().isoWeekday(day).format()` outputs `2016-02-12T12:09:06+01:00`

I use browserify and used `moment.locale('cs')` as well after require.

Wat DOES work however is doing:

`moment(new Date(parseInt(ts))).format('dddd')`

I'm curious why the other way doesn't work. Why would I need `.isoWeekday` when simply formatting works...?

But with `.format()` I don't get things like `last Friday` or `next Tuesday`, and I need that, with `.day` or `.weekday`. But doing like the example in the docs:

`moment().weekday(7); // next Sunday`

Outputs an `Object` not a `String` 

And for example doing:

```
    now = moment(parseInt(ts))
    day  = now.day()
    date = now.date()
```

outputs `Numbers` and not the promised `String` of the day (ie last Tuesday etc.)

I must be missing something from the docs, or it is a weird `Browserify` bug.

**Comment by mj1856** [comment]
When you pass the `1` to the `isoWeekday` function, you're *setting* the week day.  It takes the moment object you created with `moment()` and shifts it to Monday.  Then, the original moment object is returned, such that you can chain functions fluently if desired.

If you called the function without passing a parameter, that would return the numerical week day on the ISO calendar.

It seems you are just looking for the formatted name of the weekday of your timestamp, as a string, in the current locale and local time zone.

From your examples, I'll assume your `ts` variable is a string, and that it contains the number of milliseconds since midnight 1970-01-01 UTC.  (If it's something else, please give an example.)

```javascript
moment(ts, 'x').format('dddd')
```

For example:
```javascript
var ts = "1455301115486";
var dow = moment(ts, 'x').format('dddd');  // "Friday"
```

If instead you actually have a number and not a string, then just:

```javascript
var ts = 1455301115486;
var dow = moment(ts).format('dddd');  // "Friday"
```

**Comment by mj1856** [comment]
You also asked about getting things like `last Friday` or next `Tuesday`.  For that, use the `.calendar()` function.  See http://momentjs.com/docs/#/displaying/calendar-time/

In general, read through the docs carefully.  You seem to have a lot of incorrect assumptions about which functions are supposed to do what.
