### ISSUE TITLE
Using UTC format Z

### ISSUE THREAD

**Issue by felipem775** [moment/moment#2966]
v2.11.2:
Input: moment("20160216120000", "YYYYMMDDHHmmss Z").toDate()
Result: Date {Tue Feb 16 2016 **12**:00:00 GMT+0100}

v2.8.3: 
Input: moment("20160216120000", "YYYYMMDDHHmmss Z").toDate()
Result: Date {Tue Feb 16 2016 **13**:00:00 GMT+0100}

Using moment.utc() is OK in both:
Input: moment.utc("20160216120000", "YYYYMMDDHHmmss").toDate()
Result: Date {Tue Feb 16 2016 13:00:00 GMT+0100}

**Comment by mj1856** [comment]
`Z` in a format string is intended as a placeholder to match either on offset in `+-HH:mm` or `+-HHmm` format, or as a literal `Z`.  Since the input string doesn't provide any offset at all, then I'd say the 2.8.3 behavior was a bug, and it's good that it's fixed in 2.11.2.  I'm not sure exactly which issue or release fixed it, but the new behavior is preferred.

Of course, your example showing `moment.utc` is the correct way, if your input value is indeed UTC-based.
