### ISSUE TITLE
Issue with duration add fraction of day

### ISSUE THREAD

**Issue by gionkunz** [moment/moment#2975]
I can use fractions in duration when using hours or minutes when using the add function. However, for days the fraction is somehow floored.

This works as expected:
```javascript
add(0.5, 'hours')
add(0.2, 'minutes');
```

However this doesn't:
```javascript
add(0.5, 'days') // 0
add(1.2, 'days') // 1;
```

**Comment by maggiepint** [comment]
The library does not support adding fractional values in days, due to differences between time math and date math.
See #2430 for an extensive explanation.

**Comment by gionkunz** [comment]
I don't agree with the explanation of @mj1856 in #2430. I agree that there's no uniform way to declare the duration of a month and year but there is certainly for a hour and week. I agree there's a confusion between linear time and formatted time. However, a timestamp, which is an amount of linear time added to a time origin declared as 0, is the data behind all time calculations and formatting of linear time into calendar time. I believe the explanation in #2430 is confusion time math with time formatting and localization.

We switched DST 29. March 2015 at 02:00 local time in Switzerland +1 hour. The UTC timestamp in milliseconds for 29. March 2015 at 01:00 Swiss time is 1427587200000. If I now want to add 1 day, I don't want to add 23 hours just because there's a DST change. If I'm talking about 1 day, I always talk about 24 hours. If I talk about 1 week, then I mean 7 * 24 hours. The DST calculation is never considered in timestamps. This is a task for the formatting of time.

Given the following example:
```javascript
new Date(1427587200000).toLocaleString();
//"29.3.2015, 01:00:00"
new Date(1427587200000 + 23 * 60 * 60 * 1000).toLocaleString();
//"30.3.2015, 01:00:00"
new Date(1427587200000 + 24 * 60 * 60 * 1000).toLocaleString();
//"30.3.2015, 02:00:00"
```

You can see that modifying the timestamp +24 hours is resulting in the expected formatted time, where adding +23 hours is resulting in the next day at the same time as the time before adding 23 hours. 

I can't see a reason why adding 1 day should increase the date and not modify the time, this is absurde. If I add 1 day I wan't to add 24 hours. Formatting / localization is a whole different story. I expect all operations with duration to happen on the timestamp rather than on a formatted date. Did I miss something here?

**Comment by maggiepint** [comment]
I understand where you are coming from, but this is not how we have chosen to have our library work. We are not alone in this design decision. For example NodaTime only supports integer values for adding days, and also increments the date value in the same way that moment does. Because we believe we have made the right design decision, and because our users rely on this working the way it does, we will not be making a change. 
I believe you would get the result you are trying to achieve by multiplying your value by 24 and adding hours instead of days.

**Comment by mj1856** [comment]
I agree with Maggie, but I'll add a few things as well:

- I think you meant "for a day and week" instead of "for a hour and week".  Hours and smaller are always considered a unit of *absolute time*.  (We intentionally don't track or account for leap seconds.)

- Weeks and larger are certainly a unit of *civil time*, and thus they follow date-math, not time-math.

- Days could be considered *either* civil time or absolute time, depending on context.  In the case of a `moment` object, we've intentionally modeled it as *civil time* because it is usually used in that context.  This allows for correct adding of years and months, and thus extends to days as well.  This is not something we are going to change.

- If you really want to add fractional *absolute* days, then as Maggie suggested:

        var daysToAdd = 0.5;
        var m = // your moment object;
        m.add(daysToAdd * 24, 'hours');

- Formatting and localization are not relevant to this.  Local time reflects the time zone, which includes DST, but has nothing to do with the arrangement of the string output or the language or culture being used.  This is a common misunderstanding, so you are not alone.  However, experience and history have shown that APIs that try to make time zone a localization concern are often problematic in other more serious ways, and we don't intend to make those same mistakes here.

- For the example you gave, I'd argue that by starting with timestamps, you're already working in the context of absolute time.  When working in civil time, one would find it equally absurd that adding 1 day to 1:00 AM on March 29, 2015 would not be 1:00 AM on March 30, 2015.

- I'd also argue that it's common with the `Date` object to see:

        var d = new Date(2015, 2, 29, 1, 0, 0);
        d.setDate(d.getDate() + 1);

  This is moving in civil time, which is what adding days in moment is also doing.  While this API allows for fractional days, the ambiguity around DST handling is handled in various *different* ways across implementations, because it's not defined in the ECMAScript spec.  Moment aims for consistency, and thus chooses not to support adding fractional days through the `add` function.

**Comment by gionkunz** [comment]
@mj1856 @maggiepint I can see where you're coming from and your arguments make sense to me. Thanks for elaborating once more, as I see you've been arguing about this many times ;-)

I was maybe thinking of time too mathematically rather than from the perspective of civil time.

Within my application, I'm only concerned about time as a distance on a timeline and I was already multiplying my days to hours by a full absolute day.

Cheers!
