### ISSUE TITLE
Replace Esparanto with Babel / Rollup

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2981]
We're currently using [Esperanto](https://github.com/esperantojs/esperanto) to do the ES6 to ES5 transpile, but Esperanto has been officially deprecated as of August 16, 2015.

We should update to [Babel](http://babeljs.io/)

**Comment by socketpair** [comment]
@breeeew Can you help with this ?

**Comment by icambron** [comment]
+1 I've been using Babel in one of my fool-around projects and it's really nice.

**Comment by mj1856** [comment]
There's also [Rollup](http://rollupjs.org), though I'm not quite sure of the differences or if they solve different problems.  I also found [a Babel plugin for Rollup](https://github.com/rollup/rollup-plugin-babel).  I'm a bit out of my element here.  Perhaps someone else more knowledgeable in this area could help.  Thanks.

**Comment by icambron** [comment]
Yeah, I played around with this stuff a few weeks ago. The short of it is:

 * Babel is the ES6 compiler that targets other JS versions
 * Rollup is the thing that can combine modules into one output file (i.e. follow the modules around)

Turns out those two things have some complicated interplay, so the easiest way to compile-and-combine stuff is to let Rollup run the show and give it a Babel compiler. Hence the plugin.

**Comment by socketpair** [comment]
I know, that WebPack can be used [instead of Babel] and work vey well with babel.

**Comment by niftymonkey** [comment]
I'd be happy to pick this one up if nobody else is going to.

**Comment by mj1856** [comment]
@niftymonkey - Go ahead.  We'll keep this open until someone submits a reasonable PR.  And Thanks!

**Comment by mj1856** [comment]
@timrwood is going to work on this soon.  Thanks.

**Comment by niftymonkey** [comment]
Ah ok cool ... sorry about that, I have a WIP but not ready for PR.  Distractions :stuck_out_tongue:

**Comment by mj1856** [comment]
WIP #3090.  We'll track there.  Thanks.
