### ISSUE TITLE
Unable to parse date

### ISSUE THREAD

**Issue by Daxito** [moment/moment#2983]
I am getting this format from some service
"2016-02-23 11:31:23 AM"
How can I parse it?? it says this is not supported format or something like that, is there a way I can set this valid format somewhere? 
Or, lets say we did not have AM or PM, how can you tell this date is AM or PM?

**Comment by icambron** [comment]
> How can I parse it?

You need to tell Moment the format:

```js
> moment("2016-02-23 11:31:23 AM", "YYYY-MM-DD hh:mm:ss A", true).format()
'2016-02-23T11:31:23-05:00'
```

> Or, lets say we did not have AM or PM, how can you tell this date is AM or PM?

Meaning it's in 24-hour time?

```js
> moment("2016-02-23 20:31:23", "YYYY-MM-DD HH:mm:ss", true).hour() > 12
true
```

Note the "HH" instead of the "hh". If you don't know whether it's in 24-hour time or 12-hour time with an AM/PM, just pass both:

```
> isPM = function(s){return moment(s, ["YYYY-MM-DD HH:mm:ss", "YYYY-MM-DD hh:mm:ss A"], true).hour() > 12;};
[Function]
> isPM("2016-02-23 11:31:23 PM")
true
> isPM("2016-02-23 20:31:23")
true
```

**Comment by maggiepint** [comment]
@icambron  - minor note related to this. The format being passed here will, on the current version of moment, match ISO 8601 in error:

moment('2016-02-23 11:31:23 PM').format() = "2016-02-23T11:31:23-06:00"

This is because 2016-02-23 11:31:23 by itself technically is ISO 8601.

Do we consider this a bug, or just an unavoidable collision?
It seems like even if in general we ignore extra tokens if not in strict mode, the library would work more correctly if we looked for a meridiem indicator and fell back to js date if we found it.

**Comment by Daxito** [comment]
The thing is that using this approach I have to pass in the possible format every time, I need to set it like once, globally, so that every single call to moment() uses that format.

**Comment by icambron** [comment]
@maggiepint I agree; we should make the is-this-iso check in the one-arg constructor stricter.

@Daxito Why not abstract it into a function and call that function instead of `moment()` directly?

**Comment by Daxito** [comment]
@icambron , yes, I can do that, thank you!
