### ISSUE TITLE
Week function returns NaN after changing first day of week.

### ISSUE THREAD

**Issue by WizzieP** [moment/moment#2990]
After I set the first day of week to Monday, like this:

    moment.locale('pl', {
	    week: {
		    dow : 1
	    }
    });

`moment().week()` returns NaN. Is that a bug or am I doing something wrong?

**Comment by Oire** [comment]
@WizzieP, but in Polish Monday is already the first day of the week. But the effect is interesting, yes. @ichernev, @mj1856, any thoughts about why can it be so?

**Comment by maggiepint** [comment]
I believe this is because the entire week property is being overridden, but the doy part is not being specified.
```js
    week : {
        dow : 1, // Monday is the first day of the week.
        doy : 4  // The week that contains Jan 4th is the first week of the year.
    }
```
Because doy isn't included, the week calculation ends up getting NaN.
Specify the doy property as well and things start to work.
DOY should be the day of the year that always falls in the first week of the year.

Someone else can decide whether this is as-designed or not.

**Comment by icambron** [comment]
Tempted to consider that a bug. It's certainly unintuitive.

**Comment by maggiepint** [comment]
As of 2.12.0, this is basically fixed.
The new updateLocale function achieves the desired result:
```js
moment.updateLocale('pl', {
    week: {
        dow : 1
    }
}); 
moment.locale('pl'); 
moment().week();
```

**Comment by JADurham909** [comment]
This is also occurring with format('ww')

**Comment by maggiepint** [comment]
@JADurham909 you would have to tell me a little bit more. Are you using v 2.12 with updateLocale and this is still happening? If so, can I see your update locale code?
