### ISSUE TITLE
moment().add(1, 'month') changes timezone (offset from UTC)

### ISSUE THREAD

**Issue by joeltello** [moment/moment#3000]
Why does moment change the timezone from `8:00` to `7:00`?

![image](https://cloud.githubusercontent.com/assets/6600095/13515188/40b6b68e-e164-11e5-8a02-58336e3959f5.png)

Note: it doesn't change when I add a year

Am I not understanding how it works?

**Comment by maggiepint** [comment]
It looks like you are in Pacific time. 
You are seeing the result of the Daylight Saving Time transition. DST transition occurs on March 13th this year, at which point the Pacific time zone moves from -08:00 to -07:00. Since April 3rd is after March 13th, you see the change in the offset.
Alternately, when you add one year, the west coast would be back on standard time (-08:00), and so you see no offset change.
If you are looking for a fixed offset, you can accomplish that by manually setting the UTC offset on the moment:
```js
var a = moment().utcOffset(-480); 
a.format();
"2016-03-04T05:46:03-08:00"
a.add(1, 'month'); 
a.format()
"2016-04-04T05:46:57-08:00"
```

**Comment by joeltello** [comment]
that fixed it...thank you!
