### ISSUE TITLE
18 month diff returning 17 months

### ISSUE THREAD

**Issue by JacobReynolds** [moment/moment#3050]
# Diff errors when subtracting months

When subtracting 18 months from the current day and then doing a diff, 17 months is given inconsistently.

<a href="http://codepen.io/JacobReynolds/pen/PNWePj?editors=1010">Example codepen</a>

#### Example output
<img src="http://s11.postimg.org/b0sy9oztf/momentjsexample.png"/>

If example is not reproducing error, try refreshing page.

**Comment by mj1856** [comment]
This is because your start and end values are both taken with `moment()`, which gets the current time from the system clock.  Often they will be the same value because they are so close together, but occasionally things may line up just right and the values will be a millisecond or so apart.

You can see this if you log the `.valueOf()` timestamp of both `start` and `end` when the result is 17.

You could fix it in a few different ways:

```javascript
var end = moment();
var start = moment(end).subtract(18, 'months');
```

```javascript
var end = moment();
var start = end.clone().subtract(18, 'months');
```

```javascript
var end = moment().startOf('day');
var start = moment().startOf('day').subtract(18, 'months');
```

Any of these will work.  Though I suppose with the last one it might fail right at the stroke of midnight if timing is just right.  ;)
