### ISSUE TITLE
Dates without time parse incorrectly for early dates in Windows vs Linux

### ISSUE THREAD

**Issue by 321ckatz123** [moment/moment#3051]
We use Windows to run our local machines, but our build server and environments are Linux. As such, we have one very particular unit test that is failing, but only on Linux. I've already validated that the times are the same, same UTC offset, etc. on both local and build server.

```javascript
describe('getDateWithoutTimeSinceEpoch', () => {
    it('Returns a date value from YYYY-DD-MM in 2015', () => {
      expect(moment('2015-12-15', 'YYYY-MM-DD').valueOf()).to.equal(1450159200000);
    });

    it('Returns a date value from YYYY-DD-MM in 1985', () => {
      expect(moment('1985-04-09', 'YYYY-MM-DD').valueOf()).to.equal(481870800000);
    });
  });
```

In both Windows and Linux, the top unit test passes. However, the bottom one passes in Windows, but not in Linux. Linux is trying to set it to 481874400000 (one hour in the future). I already tried appending the T00:00:00 to mimic the ISO_8601 format, but that did the same thing. 

I'm sure I'm just doing something dumb, but I don't see it, so I kinda think this is a bug.

**Comment by mj1856** [comment]
This is a time zone issue. Windows doesn't have good historical data with regard to time zones.  You shouldn't expect it to line up with Linux in local mode.

You should probably not have local moments in unit tests tied back to specific UTC-based timestamps anyway.  Otherwise your tests will fail when running on a machine in a different time zone, even if they are more current.  Just use UTC instead.

Also, the test here just tests out moment itself.  We do have a comprehensive test suite.  You can probably omit tests like these from your own code.

**Comment by mj1856** [comment]
Out of curiosity, what are your time zone settings in each environment?

**Comment by 321ckatz123** [comment]
I am UTC -5, currently US CDT. Also, I am not actually testing moments code. I had narrowed down our build failures to that line and for ease I put that in the issue.

Just to be clear, you are saying doing moment.utc(...) should work or forcing the date to be ISO_8601 + moment.utc(...) or literally specifying the timezone as +0?

**Comment by mj1856** [comment]
The following will be true on any system, regardless of OS or time zone.

```javascript
moment.utc('2015-12-15', 'YYYY-MM-DD').valueOf() === 1450137600000;
moment.utc('1985-04-09', 'YYYY-MM-DD').valueOf() === 481852800000;
```

For most American time zones, Windows knows about the last change that occurred in 2007, but it doesn't know about anything before that.  The US also changed their DST rules in 1987.  Linux knows about this, because it uses the IANA tz database.

See:
https://en.wikipedia.org/wiki/Daylight_saving_time_in_the_United_States
https://en.wikipedia.org/wiki/Tz_database

**Comment by 321ckatz123** [comment]
Thanks for the really in depth answer! Sorry to have had a bug for a misunderstanding.

**Comment by mj1856** [comment]
No problem!  We're here to help!
