### ISSUE TITLE
add() method not working after BST change

### ISSUE THREAD

**Issue by mauricezuhlke** [moment/moment#3073]
Using the add() method with dates pre and **post BST change** is inconsistent.
`moment('2016-01-01').add(1, 'months').subtract(1, 'days').toDate().toISOString()`
`2016-01-31T00:00:00.000Z`
gives the correct outcome, whereas...

`moment('2016-09-01').add(1, 'months').subtract(1, 'days').toDate().toISOString()`
`2016-09-29T23:00:00.000Z`

...does not.

**Comment by maggiepint** [comment]
The issue that you are seeing here is that when Britain is on standard time, the offset is the same as UTC. When it's on summer time, the offset is +1.

The toISOString() method on the date object always returns the value of the date in UTC, hence the Z at the end. Thus, the date is going back to 1 hour before the time you expect, because it is UTC.

If you were to use Moment's built in format everything would be fine:
```js
moment.tz('2016-09-01','Europe/London').add(1, 'months').subtract(1, 'days').format()
"2016-09-30T00:00:00+01:00"
```

Note that I'm using the timezone constructor to get myself in your timezone. You would not need to do that.

Additionally, moment has an endOf function. That might come in handy here:
```js
oment.tz('2016-09-01','Europe/London').endOf('month').format()
"2016-09-30T23:59:59+01:00"
```

**Comment by bajanReece** [comment]
Thanks Maggie! I'll update my code to match your suggestions.
