### ISSUE TITLE
Issue with strictly parsing a formatted date

### ISSUE THREAD

**Issue by rafeememon** [moment/moment#3088]
I'm running into an issue where a formatted date outputted by moment cannot be strictly parsed when passed back into moment.  Specifically, I'm using the format `ll`, which appears to work with the `en` locale but doesn't work when the locale is `fr`.  (Not sure if this affects all locales, but a unit test in one of my projects shows it's an issue with at least `de` as well.)

Fiddle: https://jsfiddle.net/pph91sz1/

**Comment by maggiepint** [comment]
Yes, this is one of our favorite bugs these days! Cultures that use . in their short month names don't work so well. 

Pull request #3078 is work in progress to fix this.

Pull requests #3060 and #2977 can't be merged until we fix this.

If you don't mind, I'm going to close this since we already have quite a few issues open related to this problem.

**Comment by rafeememon** [comment]
Sounds good -- sorry for not finding the existing issues/PRs.  Thanks for the great work!
