### ISSUE TITLE
13-03-2016 is behaving strangely on addition and substractions

### ISSUE THREAD

**Issue by Abhivendra** [moment/moment#3097]
[
<img width="589" alt="screen shot 2016-04-07 at 6 46 08 pm" src="https://cloud.githubusercontent.com/assets/8620274/14352269/478c16b8-fcf1-11e5-9a5d-3fe4f7926cae.png">
](url)

<img width="466" alt="screen shot 2016-04-07 at 6 48 56 pm" src="https://cloud.githubusercontent.com/assets/8620274/14352296/6e75ec4a-fcf1-11e5-97fb-7a9127f5ad3c.png">

<img width="641" alt="screen shot 2016-04-07 at 6 50 00 pm" src="https://cloud.githubusercontent.com/assets/8620274/14352334/9bf16c4e-fcf1-11e5-8c52-ffa85abcba5d.png">

**Comment by maggiepint** [comment]
Is the issue here the DST transition you are seeing in your code?
A couple things to keep in mind:
- When you use the default moment constructor, it converts the date passed to it to local time.
- When you use the default moment constructor, all arithmetic operations are done in local time.
- When you use ``.toISOString()`` it outputs the time in UTC
- Presumably whatever machine you are using to run your code is set to a US time zone. We know this because the US DST transition was on March 13 this year.
- When you subtract 1 day in moment, it puts you at the same time on the previous day. This may not be the same as subtracting 24 hours due to DST transitions.

Putting it all together in code:
```js
//time is converted from UTC to my local because I'm using default moment constructor
moment('2016-03-13T18:30:00Z').format()
"2016-03-13T13:30:00-05:00"

//I subtract 1 day, crossing the DST transition
moment('2016-03-13T18:30:00Z').subtract(1, 'day').format()
"2016-03-12T13:30:00-06:00"
//Note that I am at 13:30 on the previous day. This is 23 hours earlier

//Calling .toISOString() puts "2016-03-12T13:30:00-06:00" into UTC
moment('2016-03-13T18:30:00Z').subtract(1, 'day').toISOString()
"2016-03-12T19:30:00.000Z"
//again, it's 23 hours earlier, but it is the same local time on the previous day
```

Hope that helps.
