### ISSUE TITLE
Moment returns 18 hours when the value passed is 0, instead of 0

### ISSUE THREAD

**Issue by thethp** [moment/moment#3113]
When passed in 0 instead of returning a 0 value, the moment library returns 18 hours.

I could be incorrect, my knowledge of this kind of math isn't the best, but it definitely seems like this is a situation where the user would expect to get a 0 back.

If I am wrong I'd love to know why this returns 18 :) thanks!

![image](https://cloud.githubusercontent.com/assets/2047962/14575743/6ec5b34a-0329-11e6-9ae4-25f259797973.png)

**Comment by maggiepint** [comment]
When you pass a number to the moment constructor, it interprets it as a unix timestap in milliseconds. Because of this, passing zero to the constructor will set the time in UTC to the unix epoch. Then, when you call hours, it's converting to what the hours would have been in your local time. I'm UTC - 6 right now so when I pass zero to moment you can observe that I get the following:

```js
moment(0).format()
"1969-12-31T18:00:00-06:00"
```

If I call .toISOString(), which returns a UTC date, you can see that I get the unix epoch:
```js
moment(0).toISOString()
"1970-01-01T00:00:00.000Z"
```

**Comment by thethp** [comment]
<3 thanks for the explanation!
