### ISSUE TITLE
Overflow with 12h format.

### ISSUE THREAD

**Issue by MichMich** [moment/moment#3116]
Not sure if it's allowed to ask for some help in the github issues this way. If not, feel free to close this issue immediately.

Moment.js is being used in the MagicMirror project. Some users report an issue with the formatting of the time when using a 12 hour format. It gives an overflow issue, printing out a long string of numbers.

It only happens in with the 12 hour format: `.format("hh:mm")` and only when running on a Raspberry Pi. 

See this example: ![example](https://cloud.githubusercontent.com/assets/18503539/14582992/e3a85904-03da-11e6-8940-b74ce75b6ddc.png)

The full issue is described here: https://github.com/MichMich/MagicMirror/issues/181

Any help, or pointers would be welcome! Thanks in advance!

**Comment by maggiepint** [comment]
This is interesting, and I'm happy to try to help you, but I'm not sure what we're going to be able to offer.
This is the entire code-path that would be different for the `h` token than for the 'H' token:

```js
function hFormat() {
    return this.hours() % 12 || 12;
}
```

The `H` token just invokes this.hours() directly.

When you use 24 hour format, are you using `H` or `HH`? 
The code to do the zero-fill (to create the leading zero) with the `hh` and `HH` tokens is a little more interesting:
```js
function zeroFill(number, targetLength, forceSign) {
    var absNumber = '' + Math.abs(number),
        zerosToFill = targetLength - absNumber.length,
        sign = number >= 0;
    return (sign ? (forceSign ? '+' : '') : '-') +
        Math.pow(10, Math.max(0, zerosToFill)).toString().substr(1) + absNumber;
}
```
 Maybe this is causing the problem and you just don't know it because when you use `HH` it's always in the evening and that for some reason makes things different? Again, no idea why. I'm just thinking through the possibilities.

My honest opinion is that you are more likely seeing a bug in the underlying JavaScript implementation than in moment. We have, of late, seen a few bugs in the environment when it comes to IoT, since these devices are often running less often used OS and JavaScript implementations.

If you were able to tell me more about OS and JS Engine, again, I could try to be of more help. But start by playing with alternating the `H`, `HH`, `h` and `hh` tokens. Let's see if that gets us some more information.

**Comment by MichMich** [comment]
Hi @maggiepint, thanks for your reply. The problem only occurs with the twelve hour format (`hh`) I'll check if it makes a difference when i just use `h` to see if it's a problem with `zeroFill()`. 

Since the overflow number is posted in front the time, is might be logical that it has something to do with the string concatenation happening in this function.

I'll keep you posted!

**Comment by MichMich** [comment]
Ok, so after experimentation, it turns out it has nothing to do with the `zeroFill()` method. 
It really all comes down to the following function:

````javascript
function hFormat() {
    return this.hours() % 12 || 12;
}
````
Maybe the modulo operator gives the issue. As as I find a solution, I'll let you know.

**Comment by MichMich** [comment]
I replaced the following code:

````javascript
    var timeString = moment().format('h:mm a');
````
with:
````javascript
    var now = new Date();
    var hours = now.getHours() % 12 || 12;
    var timeString = hours + moment(now).format(':mm a');
````

And this seems to solve the issue. So it really appears this issue is caused by moment.js.

**Comment by cadred48** [comment]
+1
I'm experiencing the exact same issue with moment and raspberry pi.

**Comment by MichMich** [comment]
@maggiepint Could this be marked as a bug? Since this really appears to be a Moment.js issue?

**Comment by EngMatt** [comment]
+1
I have same issue with moment and raspberry pi for 12 hour format

**Comment by maggiepint** [comment]
So, three of us have looked at this issue, and we honestly don't know what would cause it. We all do agree that it is interesting.
Given that this is a very popular feature of Moment, we can only think that there is a specific issue with the way Moment interacts with this environment. I presume this is NodeJS for ARM?

Truthfully, nobody on the Moment team has an environment set up to debug this sort of issue. We would have to get our unit tests running on a Pi. If you can find this and fix it, we would most likely accept a pull request.

**Comment by MichMich** [comment]
It doesn't happen immediately. It happens after a while (with a script refreshing the content...) and I've only tested it in an electron browser. Will test it in an other browser as well. It might be a good idea to mark this as a bug since others experience the same.

**Comment by MichMich** [comment]
Ok, so I've run a small test with the default Epiphany browser (left) and the Electron app (right). The issue only appears in the Electron app (Which is AFAIK Chromium).

There a simple way I can run the test in the (Electron) browser? 

![screen shot 2016-05-03 at 20 46 58](https://cloud.githubusercontent.com/assets/210954/14994460/5f7feb6c-1170-11e6-898b-db135665427f.png)

**Comment by icambron** [comment]
I'm almost sure that this is caused by `Math.pow(10, 1)` not returning 10 in your environment. I think the real solution is to not use real math to figure our the padding. I think we should just grab some code from the now totally infamous [left pad](https://github.com/stevemao/left-pad/blob/master/index.js) instead of `Math.pow` in that padding function.

**Comment by MichMich** [comment]
@icambron One thing to note is that it initially works (the clock refreshes every second). But after about a minute, it starts going wonky. Could this be caused by the `Math.pow(10,1)` function?

**Comment by icambron** [comment]
Seems weird, right? I just can't find a way through the code that could give you this result without that `Math.pow()` line returning something wacky.

**Comment by MichMich** [comment]
@icambron The issue doesn't occur when using 24-hour format. Doesn't the HH format use the `zeroFill()` method (which uses the `Math.pow()` function)?

**Comment by MichMich** [comment]
Ok, I've removed the` Math.pow()` function. (By just letting the `zeroFill()` function return the number without any modifications) and the issue is still there. So the issue is not caused by `Math.pow()`.

**Comment by MichMich** [comment]
I seem to have a temporary fix ...

If I change the following method:
```javascript
function hFormat() {
    return this.hours() % 12 || 12;
}
```

To:
```javascript
function hFormat() {
    if (this.hours() === 0) {
        return 12;
    }

    if (this.hours() > 12) {
        return this.hours() - 12;
    }

    return this.hours();
}
```

The problem seems to be solved.

Also, while testing, I noticed that the issue starts occurring when this method is called more than 130 times. I have absolutely no explanation for this weird number.

**Comment by MichMich** [comment]
Multiple users tested the above solution and it seems to solve the issue ... Any idea why % 12 doesn't work?

**Comment by icambron** [comment]
Hmm,  I still want to understand where 2.2e-308 came from.

I'm not surprised that seemingly random futzing with the number fixes things. In Node on my Mac:

```js
> 1e-308 === 0
false
> 1e-308 % 12
1e-308
> 1e-308 + 0
1e-308

//but

> 1e-308 + 12 - 12
0
```

So sometimes V8 just throws away stuff (which makes sense; it's the 308th decimal place). I think you have a code path that happens to do that, so the problem is hidden from the output through floating point goofiness.

But the root causes is that somehow you're getting this crazy floating point number to begin with. If it's not `pow()`, I guess it's either `%` or something else inside of `hours`. It's hard to say, but whatever it is, it's super weird. I think if you use a fix like the one you have, though, you'll just see the same issue later through some other code path.

**Comment by mj1856** [comment]
I've got a Raspberry Pi 2 now - so I'll see if I can get to the bottom of this.

@MichMich - Any particulars about setup I need to know? Environment, versions, etc.?

**Comment by MichMich** [comment]
The environment is just a regular Jessie installation. The app is running in an electron wrapper. 

Check out http://github.com/michmich/magicmirror 

The moment.js in the vendor folder is currently a custom modified version to hot fix the issue. Replace it with a default version to see the problem (after 130 seconds)

**Comment by MichMich** [comment]
Also note that the issue only occurs with the 12 hour setting. (See config/config.js)

**Comment by mj1856** [comment]
I've successfully reproduced the bug.  Now to work towards a root cause. :)

**Comment by MichMich** [comment]
Awesome!

**Comment by icambron** [comment]
Since Matt reproduced this, I'm switching it over to a bug to avoid my close-all-the-troubleshooting-tickets dragnet.
