### ISSUE TITLE
object is not extensible error

### ISSUE THREAD

**Issue by fricke** [moment/moment#3118]
We've been recently getting this error on both of these particular lines: 

moment: 2.12.0
moment.js 2677
this._weekdaysParse = [];

moment.js 2694
this._weekdaysParse[i] = new RegExp(regex.replace('.', ''), 'i');

Both complain w/ the following: 
Uncaught TypeError: Can't add property _weekdaysParse, object is not extensible

called like so:

moment.utc('Sat Apr 18 2015 04:10:07 GMT+0000', 'ddd MMM DD YYYY hh:mm:ss ZZ').format('YYYY-MM-DD')

What's really strange about this particular bug is that in our SPA, this error doesn't occur if we initially go to the page that this error is occurring, but if we start from a different page and then navigate to here the error always occurs.  Somehow the object is being frozen and it's not extensible from some point forward that I'm not sure about.  

However, if I take out the second param to moment.utc function, the ddd MMM DD YYYY hh:mm:ss ZZ, we do not get the error (just the warning of deprecation).  

Anyone run into any error like this before?

**Comment by SudoPlz** [comment]
Did you figur ethis out @fricke ?

**Comment by simeyla** [comment]
I'm getting this too on the following line of code:

     function longDateFormat (key) {
        var format = this._longDateFormat[key],
            formatUpper = this._longDateFormat[key.toUpperCase()];

        if (format || !formatUpper) {
            return format;
        }

        // *****  I get "ERROR TypeError: Cannot add property l, object is not extensible" ****

        this._longDateFormat[key] = formatUpper.replace(/MMMM|MM|DD|dddd/g, function (val) {
            return val.slice(1);
        });

        return this._longDateFormat[key];
    }

It's trying to set the key `'l'` onto `_longDateFormat` which somehow has been marked as not extensible.

In fact if I run `Object.isExtensible(this._longDateFormat)` it does indeed come back as `false`.

So why is it trying to set this? Well angular is using `l` for a date format whereas the correct value is `L`. The method above is trying to be an efficient way of handling this situation instead of just doing .toUpperCase() every time. Fair enough I suppose.

I *think* what may be happening is I'm using a 'redux' style store (akita) and putting moment objects into it. It's possible it may be 'freezing' this unintentionally.

The quick fix is to provide an `'L'` value instead of an `'l'` so this doesn't occur - but I'm still investigating other solutions and consequences.

**Comment by najibla** [comment]
I am having the exact same issue. Why is this closed?

**Comment by jaco-terbraak** [comment]
Still having this issue with moment.js 2.27.0

**Comment by sugarflux** [comment]
Still having this same issue with moment.js 2.28.0

**Comment by ahansen1** [comment]
Wanted to share in case somebody else stumbles across this defect while facing this issue using an Angular application.  I was seeing the same and was able to track down the root cause by overriding the Object.freeze to determine the point at which the Locale#_longDateFormat was frozen. 

I added this snippet to my app.component.ts

```
const orig = Object.freeze;

Object.freeze = function<T>(a: T[]): readonly T[] {
  if (!!a._longDateFormat) {
    debugger;
  }
  const extensible = Object.isExtensible(moment.localeData()._longDateFormat);
  if (!extensible) {
    console.error('frozen after freezing', a);
  } else {
    console.error('extensible', a);
  }
  return orig(a);
};
```

This led me to discover that the issue was that I was using a moment object as a parameter into an ngrx action which would in turn freeze the moment object and then later cause this issue to occur.  So though the problem manifested itself as an error in moment, however the error was in using moment within the ngrx action rather than the issue being with moment itself.

A similar approach could be used to find the culprit on non-angular applications.

Hope this saves someone else some time.

**Comment by PankajPrakashh** [comment]
@ahansen1 That works. Just to help others if they doing something similar with ngxs too. Don't have moment instance in your (ngrx or ngxs) store and actions.

**Comment by DaveSussman** [comment]
I know it's years later, but I just want to thank @ahansen1 for that code block, which led me to find the source of the same problem. Thanks.
