### ISSUE TITLE
Using `updateLocale` with `relativeTime` doesn't merge default local.

### ISSUE THREAD

**Issue by joshuapinter** [moment/moment#3137]
For example, I just want to adjust a single `relativeTime` handler, like so: 

```js
moment.updateLocale('en', {
  relativeTime : {
    dd: 'only %d days'
  }
});
```

But this gives a `Cannot read property 'replace' of undefined` exception. 

My guess is that this isn't overriding just the `dd` object but instead it overrides the entire `relativeTime` object.

You can get around this by providing all of the default locales, like so: 

```js
moment.updateLocale('en', {
  relativeTime : {
    future: 'in %s',
    past:   '%s ago',
    s:      'a few seconds',
    m:      'a minute',
    mm:     '%d minutes',
    h:      'an hour',
    hh:     '%d hours',
    d:      'a day',
    dd:     'only %d days',
    M:      'a month',
    MM:     '%d months',
    y:      'a year',
    yy:     '%d years'
  }
});
```

I can see from #2774 that there was an intention to use the default locale values and just update what you provide but I'm not sure if it made it as deep as the individual objects of `relativeTime`. 

Any feedback on this would be great. I'd be happy to write up a PR if this is of interest to anybody as well.

Thanks!

Josh

**Comment by maggiepint** [comment]
The actual issue here is that the code doesn't work on the `en` default locale. I think it actually works fine with any other locale, which is why this was missed in the unit tests.
This is because the ``en`` locale isn't actually defined in the locale files - instead it is comprised of a bunch of defaults.
You would notice that @ichernev actually has a todo on that pull request that you referenced to make a proper English base locale. If anything, I think that is what needs to happen to solve this issue. I think we would accept a pull request that does that, but I'd appreciate it if @ichernev chipped in with how he intended that to work.

This bug is actually a duplicate of #3121 that is manifesting in a different way.

**Comment by joshuapinter** [comment]
@maggiepint Thanks for the reply Maggie (and on a Saturday evening, no less)! :) 

I'll hang tight to see what the verdict is but based on some Stack Overflow Q&As, I think it would be a welcomed mod.

**Comment by maggiepint** [comment]
Out of plain curiosity, where is that coming up on Stack Overflow? Matt and I watch the Moment tag pretty closely and we would have raised this issue if we saw it.

**Comment by joshuapinter** [comment]
Nothing major but I ran into this one: http://stackoverflow.com/questions/11448340/how-to-get-duration-in-weeks-with-moment-js

**Comment by ichernev** [comment]
@maggiepint you are right. If the whole system was based on the inheritance I added in the recent release it would work. But now its a bit of a mess still.

**Comment by NKjoep** [comment]
I am using `"moment": "^2.18.1"` and `updateLocale()` doesn't work as expected.

I am still not able to replace only one property of the `moment.LocaleSpecification`.

Am I doing something wrong or this bug is still a bug?

**Comment by laurent1** [comment]
I don't think you do anything wrong. I have a similar experience.

- This code `moment.updateLocale('en', this.customize('en'));` was merging the updates and all the dates were in English as expected.

- This code `moment.updateLocale('fr', this.customize('fr'));` was merging the updates in French, but the rest of display was in English instead of the expected French.

- So, I thought I should be specifying the language as followed `moment.locale('fr);` before customizing with `moment.updateLocale('fr', this.customize('fr'));`. The result was that everything was in French, but no merging occurred.

So, there is definitely a bug here.
