### ISSUE TITLE
Not understanding how this is converting

### ISSUE THREAD

**Issue by robmburke** [moment/moment#3141]
https://i.imgur.com/uATTJYc.png

I have my code above in a picture so that you can see the values of the moment object.  I am giving it one day and it is converting it to a day earlier when I do the output.

I honestly don't know what is going on so I don't even know where to start or what to ask.

**Comment by maggiepint** [comment]
The value of ``_d`` will not reflect the actual time you are dealing with when you are using moment timezone. There is actually a pull request from Moment's author that does some even more interesting things with the value of ``_d`` that will make it so that it is virtually meaningless if you don't understand the internals of moment. As such, I suggest that you ignore it.

What is the result of calling ``.format()`` on the moment, and what do you think it should be?

It is worth noting that newer versions of moment timezone have a ``.guess`` function, so you may be able to get rid of the jstz detect dependency.

**Comment by maggiepint** [comment]
I'm going to close this since I haven't heard from you, but feel free to reopen if you need something else.
