### ISSUE TITLE
IE11 validating invalid dates.

### ISSUE THREAD

**Issue by harish2rock** [moment/moment#3148]
moment(new Date('45/45/4545')).format('MM/DD/YYYY') in chrome or firefox throws 'Invalid Date', while IE11 parses this as a valid date. It turns it into 10/15/4548.

**Comment by maggiepint** [comment]
Because you are passing a string directly to the date constructor, you are not using moment's date validation at all. Instead, you are using the date parsing built into the browser. Apparently, IE11 thinks this is a valid date - but that has nothing to do with moment.

I would suggest that you instead use Moment's parser to validate this date, as follows:

moment('45/45/4545', 'MM/DD/YYYY')

This will evaluate as an invalid date in every browser.

**Comment by harish2rock** [comment]
That helped. Thanks!
