### ISSUE TITLE
What is the .format() pattern standard?

### ISSUE THREAD

**Issue by ashleydw** [moment/moment#3150]
Whilst building a react-native module, I am getting date formats (patterns) from ios and android. ios uses the UTS 35 (http://www.unicode.org/reports/tr35/tr35-19.html#Date_Format_Patterns), and android is in ISO 8601. 

I want to take these two formats and convert them to the format used by momentjs. However, the docs don't state what standard they follow (if they do?). It looks like ISO, but a confirmation is needed.

As a side topic, anyone know of an existing format conversion?

**Comment by maggiepint** [comment]
Moment's default format is ISO8601, though you can produce virtually any format with the .format function. Moment also parses ISO8601 formats by default without having to specify a format.

If you are getting UTS 35 formatted dates, they can be parsed by explicitly specifying a format. There are multiple format options for UTS 35. Are you getting one of the possible formats or several?

The one issue you will have with UTS35 is the timezone information. Moment doesn't provide a good  tool for parsing formats like CST or PDT because they are ambiguous identifiers. If you gave me the exact UTS35 format(s) that you are working with, I could better help you figure out how to parse.

**Comment by maggiepint** [comment]
Closing since I haven't heard from you. Let me know if you still need help.
