### ISSUE TITLE
show countdown

### ISSUE THREAD

**Issue by nasr18** [moment/moment#3162]
I need to show a countdown in my project like "30 minutes remaining", "29 minutes remaining", and so on for everty 1 minute. How do i achieve this via momentjs??

**Comment by gregor-srdic** [comment]
moment.duration(finishDate-nowDate).humanize() will give you a string like "30 minutes" - add "remaining" and you are good to go :)

Nevertheless, I also have a problem with this - it does not work ok in my locale (slovenian- sl) because form of remaining duration is 
one minute remaining: "še eno minut**o**" 
while duration humanize returns 
one minute: "ena minuta"
using prefixes with humanize returns correct form, but the preposition is not correct for remaining duration, either
"**pred **eno minuto" or "**čez **eno minuto"
i think a separate operation for remaining duration would be required

**Comment by nasr18** [comment]
@gregor-srdic  its returning me "a few seconds". but i set time delay upto 10mins, i mean the output would be "10 minutes remaning". So bad luck.

**Comment by icambron** [comment]
@nasr18 Can you provide some minimal code showing the issue?

@gregor-srdic Yeah, internationalization is hard. Getting the grammar right viz-a-viz a variety of contexts is tricky stuff.

**Comment by nasr18** [comment]
@icambron I got what i want using `moment().fromNow()`. Anyway thanks for your reply.
