### ISSUE TITLE
moment("0(0,0)") is valid ?!?

### ISSUE THREAD

**Issue by streamnsight** [moment/moment#3171]
`moment("0(0,0)").isValid()`  is `true`

and return 

`Sat Jan 01 2000 00:00:00 GMT-0800 (PST)`

it's not even a number, how comes it is considered a valid date?

**Comment by joelalejandro** [comment]
@streamnsight Apparently, this is a JavaScript thing.

<pre><code>new Date("0(0,0)")
&gt; Sat Jan 01 2000 00:00:00 GMT-0300 (Hora estándar de Argentina)
</code></pre>

According to the [ECMA-262 specification](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.4.2):

> The `parse` function applies the _ToString_ operator to its argument and interprets the resulting String as a date and time; it returns a Number, the UTC time value corresponding to the date and time. T**he String may be interpreted as a local time, a UTC time, or a time in some other time zone, depending on the contents of the String. The function first attempts to parse the format of the String according to the rules called out in [Date Time String Format (15.9.1.15)](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15).** If the String does not conform to that format the function may fall back to any implementation-specific heuristics or implementation-specific date formats. Unrecognisable Strings or dates containing illegal element values in the format String shall cause `Date.parse` to return `NaN`.

For what I can tell based on experimentation, the only value determining a date on this case is the `0` before the parenthesis. If you try multiple different values such as `0(0,1)` or `0(0,9)`, it'll return the same date. I believe that a single zero translates to 2000-01-01 because it is evaluated as a year between 0000 and 9999, and in the absence of a month and date, the value is set to 01 and 01 by default.

**Comment by streamnsight** [comment]
@joelalejandro so... is there any way to avoid this? how can i tell the difference?

**Comment by joelalejandro** [comment]
@streamnsight, The docs have a warning about this:

> **Warning:** Browser support for parsing strings is inconsistent. Because there is no specification on which formats should be supported, what works in some browsers will not work in other browsers. For consistent results parsing anything other than ISO 8601 strings, you should use String + Format.

As mentioned further in the [docs](http://momentjs.com/docs/#/parsing/string-format/), you can enforce format with something like this

<pre><code>moment('0(0,0)', 'YYYY-MM-DD', true);
&gt; false</code></pre>

The boolean argument in this method signature allows to apply strict parsing; however, you should restrict your date processing to a single formate in order to implement this approach.

**Comment by streamnsight** [comment]
@joelalejandro 
thanks...
what i'm trying to do is find if a string can be parsed as a date... but avoid those bogus cases.

**Comment by maggiepint** [comment]
@joelalejandro , strict parsing will work with multiple formats. It actually significantly improves multiple format parsing by generating better matches.

@streamnsight you are not the first person to try to use moment to figure out whether a string is a date. You can try this, and depending on your use case you may be able to succeed, but ultimately there are just a whole darn lot of date formats. If you can't pick out a finite number of formats that you may be expecting (for example 5-15 specific formats), then you're going to struggle validating them with Moment. Ultimately if enough formats are possible, it almost becomes a natural language processing problem, which is out of scope of a date parsing library.

If you give me a better idea of the kids of inputs you are expecting, I can try to guide you to an acceptable solution.

**Comment by joelalejandro** [comment]
@maggiepint Good to know, just read in Stack Overflow about passing an array of formats. Nice feature, heh.

**Comment by streamnsight** [comment]
@maggiepint sounds reasonable to me. thanks for chiming in!

**Comment by maggiepint** [comment]
Both of you should be aware that when you use multiple formats, it loops through each format and evaluates it, trying to come up with the closest match based on a heuristic. This is usually not a big deal, but with sufficient formats or sufficient moments, it can slow a program down.

**Comment by streamnsight** [comment]
So... following up on this.
I still have a problem, and I'm not sure how to solve it.
If the data I'm trying to parse, I have this `0(0,0)` type of input that parses as a date unless strict checking is `true`.

Problem is: in this data, I also have dates in the format: `14.05.2016 12:03:50:029 (Pacific Standard Time)` and the time zone information is not parsing when I use `DD.MM.YYYY HH:mm:ss.SSS` format.

What format would be matching this date pattern?

**Comment by streamnsight** [comment]
btw, if I use the `parseData()` function like
```
let dateFormats = ["DD.MM.YYYY HH:mm:ss:SSS","YYYY-MM-DDTHH:mm:ss"];
console.log(moment(content, dateFormats, true).creationData());
```

i get

```
{input: "14.05.2016 12:03:50:029 (Pacific Standard Time)", format: "YYYY-MM-DDTHH:mm:ss", locale: Locale, isUTC: false, strict: true}
format:"YYYY-MM-DDTHH:mm:ss"
input:"14.05.2016 12:03:50:029 (Pacific Standard Time)"
isUTC:false
locale:Locale
_abbr:"en"
_config:_ordinalParse:/\d{1,2}(th|st|nd|rd)/
_ordinalParseLenient:/\d{1,2}(th|st|nd|rd)|\d{1,2}/
ordinal:(number)
strict:true}
```

which seems to indicate it used the 1st of the array formats.
