### ISSUE TITLE
Moment get('day') is not correct. 

### ISSUE THREAD

**Issue by kentonbmax** [moment/moment#3173]
![image](https://cloud.githubusercontent.com/assets/15804484/15146768/281f4878-168b-11e6-996d-130695e00af1.png)

calling .get('day') on this date returns 2 not 10.

**Comment by maggiepint** [comment]
Day gets the day of the week, which is in fact Tuesday (2). Use ``.date()``. http://momentjs.com/docs/#/get-set/date/

In addition, be very cautious of the data that dumps to the console. You are looking at internal properties and they may not be what you expect: http://momentjs.com/guides/#/lib-concepts/internal-properties/

**Comment by kentonbmax** [comment]
Ty. Writing to console was solely for testing client side. I'm concerned that the current moment object which is of date 2016-10-05 does not provide a property implementation for day. I would think following the C# DateTime object would be preferable. Anyways just a suggestion.

**Comment by maggiepint** [comment]
I guess I'm not sure what you mean. ``.day()`` will give you day of week, ``.date()`` will give you date of the month. This is different than BCL datetime in C#, but it's the same as the built in JavaScript Date object : 
```js
new Date().getDay()
2
new Date().getDate()
10
```

Doesn't it make more sense for a JavaScript library to mirror JavaScript Date than C# DateTime?

If you are saying that you want it to work like moment().date (as a property instead of a function) - we would have to use a getter: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get
We can't do that until we do a major version release, because we would have to drop support for IE 8.

**Comment by kentonbmax** [comment]
Ideally an interface where a moment object had properties for year, month, day, hour, etc. and utc, would be preferable (out of the box understanding). Please, remove support for IE 8... IE 11 support as an internal web developer is literally the most frustrating thing I have ever dealt with. Thankfully there is babel. Cheers!
