### ISSUE TITLE
moment(undefined) returns the current date (i.e. equivalent to moment())

### ISSUE THREAD

**Issue by mjrister** [moment/moment#3180]
Is this really expected behavior? This makes it difficult to determine that an undefined variable is the source of an invalid date rather than an incorrect signal coming from an API on the server for example.

**Comment by maggiepint** [comment]
I suppose we could explicitly check arguments.length for whether an undefined argument was passed or no argument was passed. This represents a major behavioral change for the library though. I'm honestly not sure if that's something we would be able to do in a minor release.

**Comment by mjrister** [comment]
I'm not aware of the internals of moment.js. It seems like a fairly straightforward fix from an outside perspective. Just check arguments.length and if the length is greater than 0, check each argument against typeof === "undefined"

**Comment by maggiepint** [comment]
Yes, it is a straightforward change. However, there is no way to know how many people are relying on the library working the way that it does - thus we can't just make that kind of change without analysis.

**Comment by icambron** [comment]
Strong 👎 . See also #2729. I just don't think that checking `arguments.length` at the top of every Javascript function is the way JS is supposed to work. There's a reason that `null` and `undefined` are different things; perhaps that distinction was unwise on the part of JS's designers, but it's how it works, and why it's so troublesome to try to "fix".

Consider, for example, the caller who wants to choose which arguments to pass `moment()`:

```js
moment(needsAnArg() ? something : undefined);
```

I'd certainly expect that in the case where `needsAnArg()` returns false, the code ought to be equivalent to just `moment()`. That's what `undefined` is sort of *for*: "It's not that I have any empty value; it's that I don't have one at all."

If your code treats `undefined` as a sort of lazy programmer's `null`, I submit that those undefined vars are bugs in your program: you should define your variables!

**Comment by mjrister** [comment]
Issac, I'm sorry, but I don't agree with your perspective. The successful design of a library is strongly coupled with the APIs it exposes. From an outside perspective, moment(undefined) should at the very lease return an invalid date. It's, in my opinion, nonsensical that undefined somehow means the current date.

With that said, I understand your point in the difficulty that this requirement would impose on the existing design of the library. Perhaps there is an alternative implementation other than checking arguments.length at the beginning of every function. I'm sure some refactoring (not taken lightly in JS) would solve this problem.

Thirdly, I would argue that it makes much more sense to call `moment(needsAnArg() ? something : new Date())` if that really was my intention.

Finally, the discovery of this was not due to lazy programming. It was due to an idiosyncrasy with using Typescript. I build object definitions to match the object model coming in from an API on the Server. I unfortunately added a typo and the variable was always undefined. In trying to find this bug, I first thought it was a bug with Typescript. It turns out, it was the result of a type-o. I spent several hours on trying to find the source of this bug. It would have saved me a lot of grief if moment reported an invalid date or threw an exception.

**Comment by icambron** [comment]
It's unfortunate that typos in JS can cause vars to be undefined, and perhaps it would be best if JS just exploded when you try to use an undefined var.

But your case that `moment(undefined)` should behave in a special way is a complaint about JS, not about Moment. It really is the case that JS is supposed to work by making `foo()` and `foo(undefined)` equivalent. That's why `foo`'s first parameter gets bound to `undefined` when you don't provide it. If we start doing this thing where we say "JS works this way but it should really work this other way so we're coding around it" we're swimming upstream.

Do you think it is the case that most JS libraries with optional arguments check the `arguments` count and throw as your suggesting? I don't believe it is. Here's a built-into-your-browser one I just happened to be playing with recently:

```js
new Intl.NumberFormat().format(1) //=> "1"
new Intl.NumberFormat(undefined).format(1); //=> "1", just like above
new Intl.NumberFormat("ar").format(1) //=> "١", how this arg is meant to be used
new Intl.NumberFormat(null).format(1); //error
```

So it's doing what we do. (There are some interesting places where built-in JS APIs *do* treat `undefined` differently and they always trip me up.)

>  I would argue that it makes much more sense to call moment(needsAnArg() ? something : new Date()) if that really was my intention.

That may be, but the question is what the user's expectations are when doing what I wrote.

**Comment by maggiepint** [comment]
I'm going to agree with @icambron on this one. Trying to work around the language doesn't seem right. Checking arguments.length at the start of every function is the definition of a code smell.
