### ISSUE TITLE
Incorrect display of localized date

### ISSUE THREAD

**Issue by easyest** [moment/moment#3195]
In lithuanian language when the month is used standalone, or with year, it's name is used in nominative case. When there is a day of month nearby, the case of the month name is used in genitive case. Current locale file has both - nominative in "standalone" property and genitive in "format" property. But, when using moment().format('LL') it returns incorrect case:
`"2016 m. gegužė 24 d."`

The correct value should be:
`"2016 m. gegužės 24 d."`

**Comment by erickponce** [comment]
Problem in locale, with PT-BR:

moment().format('LLLL');
"DD \\de MMM \\de YYYY" On pt-br should be "DD \\d\\e MMM \\d\\e YYYY", because problably regex is changing the "e" with a number. Example: 2 d2 Junho d2 2016.

I have modified the locale with \\d\\e and the problem was solved.

**Comment by easyest** [comment]
@erickponce, is it related to my reported problem in any way?

**Comment by maggiepint** [comment]
As far as the Lithuanian goes, I think there's an issue here with the fact that the language likes to lead with years. This regular expression will control toggling between between standalone and format:

```
D[oD]?(\[[^\[\]]*\]|\s+)+MMMM?
```

That Regex is expecting that the format start with day, not year, in order to toggle to the genitive. As such, we can observe the following:

```js
moment('2016-05-05').locale('lt').format('D MMMM')
"5 gegužės" //lead with day and you get genitive
moment('2016-05-05').locale('lt').format('YYYY MMMM')
"2016 gegužė" //lead with year and you get nominative
```

For Lithuanian at least, I think that regex would be more appropriately something like this:
```
[Y]{1,4}(\[[^\[\]]*\]|\s+)+MMMM?
```

I honestly don't know if this applies only to this locale or should apply to more locales. My instinct though, is that the way to fix that is to make that regular expression customizable on a per-locale basis.

So, two things:
@mmozuras - is this how Lithuanian should work?
@icambron - you love regular expressions. Does what I just said seem right to you?

**Comment by icambron** [comment]
Haha, that'll teach me to boast about stuff.

That regex is good for what you intend, though you don't need brackets around the Y. However, my understanding is that it's the presence of the day that matters here (for the record, I don't know anything about Lithuanian or any of the other languages with multiple cases, but that's my hazy understanding: it takes a different case because it's telling you what month it's the 24th *of* instead of just telling you what month it is). So I'm guessing that "YYYY MMMM" actually *shouldn't* take the genitive case, though I'd quickly cede to someone telling me otherwise. It's "MMMM DD" that needs it.

It's sort of tempting to just have the regex look for D or Do anywhere in the format (except, annoyingly, in brackets). But since the existing regex does a lot of work to ensure that there's nothing but whitespace and bracketed stuff between day and the month, I bet that doesn't work (which makes sense -- "it was day 5 in the month known as 'June'" is probably different than 'June 5'). So I suspect we need a locale-specific regex like this for Lithuanian:

```
MMMM?(\[[^\[\]]*\]|\s+)+D[oD]?
```

This stuff where we introspect the format and make guesses about the grammatical structure of the intended output sucks. I'm starting to agree with the CLDR folks who start with the "LL" type stuff instead of building things from their pieces and hoping the grammar works out.

**Comment by mmozuras** [comment]
@maggiepint yes, the issue pointed out by @easyest is accurate. The regex solution you suggest seem viable, but I'm not familiar enough to be a good judge 😄

**Comment by easyest** [comment]
@icambron yes, You are right - it is the presence of the day, that makes difference. If it is only the month, then it is "2016 gegužė", but if it is the day, then it is "2016 gegužės 6 d." The rough translation would be "May of 2016" and "6th day OF May OF 2016", but in Lithuanian all parts are in reverse order.
It is similar in Russian - "6 мая 2016 г." and "май 2016 г.", but the order here is different.

**Comment by maggiepint** [comment]
Have added bug label and up for grabs.

Basically, the locale files need to be able to override the regular expression for determining month format.

While this work is being done, it would probably be best to do the same for week day format.

Have we played with week days with regard to Lithuanian? It may be the case that we need to come up with a regex for that too.

**Comment by easyest** [comment]
@maggiepint I am not a language specialist, but it seems for me, that in Lithuanian, weekdays are always nominative. Yes, if we are talking about intervals "from-to" using weekdays like "from Montay to Friday", then weekday will be in genitive, but I don't think it is so important.

**Comment by ichernev** [comment]
This is easy to do, we already have a customizable format for the weekday cases.
