### ISSUE TITLE
Moment not reading JS variable

### ISSUE THREAD

**Issue by mcpenchel** [moment/moment#3197]
Hi guys,

I'm stuck with a problem inside my jade template when using moment. I have a json value which I can read with mustache, and I simply can't use it with moment.

Example (inside my jade template):

- var teste = "{{myDate}}";

{{myDate}} - #{teste} - #{moment("2016-05-24T17:39:28.000Z", "YYYY-MM-DD HH:mm").format("DD[/]MM[/]YYYY HH:mm")} - #{moment(teste.toString(), "YYYY-MM-DD HH:mm").format("DD[/]MM[/]YYYY HH:mm")} - #{moment(teste, "YYYY-MM-DD HH:mm").format("DD[/]MM[/]YYYY HH:mm")}

This returns me: 2016-05-24T17:39:28.000Z - 2016-05-24T17:39:28.000Z - 24/05/2016 17:39 - Invalid date - Invalid date

Can anyone help?

Cheers

**Comment by icambron** [comment]
Can you try this out on the JS console and show us exactly? You should be able to do something like:

```
moment("some string").format("DD[/]MM[/]YYYY HH:mm") //=> Invalid date
```

That'll make it easier for us to help without thinking about Jade templates and such.

**Comment by icambron** [comment]
Oops, didn't mean to close that.

**Comment by mcpenchel** [comment]
Ok, I think my original post wasn't clear enough.

moment("2016-05-24T17:39:28.000Z", "YYYY-MM-DD HH:mm").format("DD[/]MM[/]YYYY HH:mm") //=> 24/05/2016 17:39

That's just fine. It's working as expected. But if I create a JavaScript's variable and try to use it with moment, it doesn't work.

As in:

- var myTestDate = "2016-05-24T17:39:28.000Z";
moment(myTestDate, "YYYY-MM-DD HH:mm").format("DD[/]MM[/]YYYY HH:mm") //=> Invalid Date

**Comment by icambron** [comment]
I just pasted those last two lines into my JS console and it printed "24/05/2016 17:39". I bet it will for you too (navigate momentjs.com, open your JS console and just paste them in). Moment doesn't even know if it's in a variable or is just a string literal; it just takes a parameter.

I suspect that in your application, the variable doesn't contain quite what you think it contains. That's why I want you to isolate the problem to two lines of code. I strongly suspect that in the process, you'll find out what's wrong with your code.

**Comment by mcpenchel** [comment]
Ok, you got me there. So maybe the problem only occurs when using moment with jade.

I'm iterating over some data inside a table. For each table row, I've got this:

https://gist.github.com/mcpenchel/37de96b6009bd3e9aa88f8ef6e259925

This returns me, in the first row, for example, the following:

<td class="text-right">2016-05-24T17:39:28.000Z - Invalid date</td>

This is bugging me. The problem isn't with mustache, because the myTestDate variable is printed accordingly. But it simply isn't evaluated by moment when inside the #{}.

**Comment by icambron** [comment]
It's been a long time since I've used Jade, so I don't know how helpful I can be. Maybe try switching it to a `console.log()` and see if it prints what you expect?

I just know this works:

```js
var myTestDate = '2016-05-24T17:39:28.000Z';
moment(myTestDate, "YYYY-MM-DD HH:mm").format("DD[/]MM[/]YYYY HH:mm")
"24/05/2016 17:39"
```

Not the problem here, but it's also worth noting that you're not really using the right parsing string; the date you're passing in doesn't look like "YYYY-MM-DD HH:mm", but it's working because the parser is pretty liberal. Because the string is ISO-8601, you can actually just do `moment(myTestDate)`.

Since I can't figure out how to help, and because I'm confident there's no Moment issue here, i'm going to  close this out. You might have more luck on SO where people more familiar with Jade can pitch in.
