### ISSUE TITLE
Handling no-time-zone use case

### ISSUE THREAD

**Issue by sdebaun** [moment/moment#3200]
Hello! We ran into a prob with our use of moment, I'm wondering if theres a better solution than to what we did and if its something we could help with a PR.

We have a web app that doesnt need the automagic time zone stuff that moment has. I.e. a user in PST picks 8AM, it should show up as 8AM for everyone no matter what TZ they are in. Our current hacky solution is:

```
export const localTime = t => //1p
  moment(t).utc().add(moment.parseZone(t).utcOffset(),'m')
```

My questions are:
* is there a better way to do this
* if there isnt, could we submit a PR for a convenience method to do this?

Thanks!

**Comment by maggiepint** [comment]
I assume that you are passing in an ISO 8601 date with offset. Because of this, when you use the default moment constructor, it will convert the date from that point in absolute time to the user's local time. If you ignore the offset, then the time will be interpreted as local. The best way to do this is to not have your back end system send the offset, and instead sent the time in the format '2016-01-01T13:00:00' or whatever. 
If that is impossible, then you could use a parse format that ignores the offset.

I explain this pretty extensively in this blog post: https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/

In particular, this section may be of use: https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/#doNotWant

Does that cover what you're looking for?

**Comment by icambron** [comment]
Closing for lack of response. I suspect @maggiepint's answer is just what the OP wants anyway.
