### ISSUE TITLE
Different behave in Chrome and Mozilla

### ISSUE THREAD

**Issue by kirylandruski** [moment/moment#3203]
"Fri Apr 22 09:38:20 +0000 2016Z" is valid in Google Chrome 50 and not valid in Mozilla Firefox 46

`moment("Fri Apr 22 09:38:20 +0000 2016Z").toString();`

Thanks!

**Comment by maggiepint** [comment]
This is not an issue with moment. Because you are using a non-ISO8601 format date, and you have not specified a format for the parser to interpret it with, moment is falling back to the JS Date constructor. That constructor has browser specific behavior, which is why you see a difference between chrome and firefox. In both browsers you should be seeing the following warning:

>Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.

If you specify a format, then moment will know how to parse your date, and you won't have this problem. I think the format you want is as follows:

```js
moment("Fri Apr 22 09:38:20 +0000 2016Z", 'ddd MMM DD HH:mm:ss Z YYYY').toString()
```js

This format doesn't make much sense to me that you have both the +0000 and the Z. The code I wrote will interpret the +0000 as meaning UTC + 0, and ignore the Z (which also means UTC). If the +0000 can actually be other numbers as well though, then your format makes no sense. It seems to have two offset indicators. I would look into why the system is returning this format, and make sure that you are interpreting it correctly.
