### ISSUE TITLE
can i use HH-mm-ss format for isBetween clause 

### ISSUE THREAD

**Issue by osamabari** [moment/moment#3207]
i want to use this type of condition 
`moment('08:00:00').isBetween('12:00:00', '14:00:00', null, '[)');`

**Comment by maggiepint** [comment]
You can make this work, with some caveats. Remember, every moment is inherently a reference to a point on the global timeline. There is no such thing as a moment that is just a time, or just a date. Every moment is both. That said, what happens when you parse just a time, is that today's date gets filled in. So, you could use the following code:

```js
moment.utc('08:00:00', 'HH:mm:ss').isBetween(moment.utc('12:00:00', 'HH:mm:ss'), moment.utc('14:00:00', 'HH:mm:ss'), null, '[)')
false
moment.utc('13:00:00', 'HH:mm:ss').isBetween(moment.utc('12:00:00', 'HH:mm:ss'), moment.utc('14:00:00', 'HH:mm:ss'), null, '[)')
true
moment.utc('12:00:00', 'HH:mm:ss').isBetween(moment.utc('12:00:00', 'HH:mm:ss'), moment.utc('14:00:00', 'HH:mm:ss'), null, '[)')
true
```

Note that this is equivalent to:
```js
moment.utc('2016-06-02T12:00:00').isBetween(moment.utc('2016-06-02T12:00:00'), moment.utc('2016-06-02T14:00:00'), null, '[)')
true
```

Moment is filling in with today's date.

This means that this code may or may not work the way you want it to:
```js
moment.utc('13:00:00', 'HH:mm:ss').isBetween(moment.utc('12:00:00', 'HH:mm:ss'), moment.utc('01:00:00', 'HH:mm:ss'), null, '[)')
false
```

Because it is equivalent to:
```js
moment.utc('2016-06-02T13:00:00').isBetween(moment.utc('2016-06-02T12:00:00'), moment.utc('2016-06-02T01:00:00'), null, '[)')
false
```

Moment automatically fills in the current day. It has no concept of crossing into the next day.

I have used UTC mode, because if I were to use local time, I might see issues with DST transitions if a nonexistent or repeated time were used.

I have also specified a format ('HH:mm:ss') because the behavior of the date parser will be much more reliable if I do so.
