### ISSUE TITLE
endOf('month') not returning the expected value

### ISSUE THREAD

**Issue by djdavisdt** [moment/moment#3226]
Code:

`moment('2016-06-09').endOf('month').unix();`

I would expect this to return `1467331199` (June 30th) but it instead returns `1467349199` (July 1st).

**Comment by maggiepint** [comment]
When you use the default moment constructor, you are telling moment to do all of it's computations in local time. Because of this, moment is giving you a Unix timestamp that reflects the end of the day on June 9th in the time zone local to the machine you are using. I would guess that your timezone is UTC -4 (maybe US eastern?). As such, you are getting the timestamp that you are getting.

If you were to parse in UTC mode, then you would get the timestamp that you expect:

```js
moment.utc('2016-06-09').endOf('month').unix()
1467331199
```

Be careful. Do you mean the end of the month on the global timeline, or the end of the month local to the user? These will be two different timestamps.
