### ISSUE TITLE
durations of less than 1 second e.g. 500ms get humanized as 'a few seconds' rather than 'less than a second'

### ISSUE THREAD

**Issue by CZEMacLeod** [moment/moment#3239]
This is probably related to other duration / humanize issues regarding rounding but it would be nice if the default implementation handled fractions of a second rather better.

**Comment by icambron** [comment]
I agree in principle, but I'm a little curious about the use case here; when does a human user need that level of humanized precision?

**Comment by maggiepint** [comment]
If we try to add 'less than a second' to duration.humanize we end up with a locale nightmare, because we have to call in every locale author to translate it. If there's a strong use case for it that would be used by lots of people, it might be worth it, but I'm not sure what that is.

Instead, I would suggest that you look at trying to do something similar to #3175 where you create an extension point. We would take a pull request for that I think, but probably not for just adding 'less than a second' because of the pain in translations.

Disclaimer: haven't dug through the code. This may or may not be possible.
