### ISSUE TITLE
isAfter Validation

### ISSUE THREAD

**Issue by medelasri** [moment/moment#3277]
Hi,

```
 var test = moment("04-05-2016", "DD-MM-YYYY", true).isAfter("04-07-2016");
 var test = moment("04/05/2016", "DD/MM/YYYY", true).isAfter("04/07/2016");
```
test return TRUE! 

with "YYYY-MM-DD" works. 

Please can someone tell me what the issue! 

Thanks

**Comment by maggiepint** [comment]
This is because your second date, in your after, is not specifying a format. You should be getting a deprecation warning about construction falling back to JS date. What this means is that the browser is interpreting that string however it wants. Moment has no control over this. 
In this case, the browser is probably interpreting ``04-07-2016`` as April 7 2016 (US Style), instead of the European style you wanted it interpreted as. Since May is in fact after April, you get the result you are seeing.

Instead, just change to the following:

```js
moment("04-05-2016", "DD-MM-YYYY", true).isAfter(moment("04-07-2016", 'DD-MM-YYYY'))
false

moment("04-05-2016", "DD-MM-YYYY", true).isAfter(moment("04/07/2016", 'DD/MM/YYYY'))
false
```
