### ISSUE TITLE
Incorrect date conversion of ASP.NET JSON dates

### ISSUE THREAD

**Issue by gvar369** [moment/moment#3291]
I seem to notice a slight difference in the date when converting a ASP.NET JSON date.
As per the docs the JSON conversion would return date as follows.

> moment("/Date(1198908717056-0700)/"); // 2007-12-28T23:11:57.056-07:00

When i run the same on my local, it return as shown in the screenshot below.
![image](https://cloud.githubusercontent.com/assets/6510724/16625300/66a13f74-4369-11e6-9ce4-97c735723d1c.png)

[JSFiddle](https://jsfiddle.net/6jcwrqh8/)

**Comment by mj1856** [comment]
In this particular case, the offset given in the input is irrelevant.  It will create a moment in local mode, using the time zone of the local computer.

If you want to keep the offset provided, use `parseZone` instead.

```javascript
moment.parseZone("/Date(1198908717056-0700)/")
```

This is by design, but perhaps the docs could be updated to show using `parseZone`.

The downside to this is that now the moment is using a fixed offset.  If, for example, you add time to it that should place it into a daylight saving time period, it will not recognize that.
