### ISSUE TITLE
Split localization

### ISSUE THREAD

**Issue by hueniverse** [moment/moment#3293]
Is there a reason why the core module includes all the localization features? Would it make sense to split it out the same way timezones are handled? We use moment in multiple projects (open and closed) and the cost of upgrading to newer versions is high because I need to perform a security review on every change and 95% are localization changes. I don't really mind the module size as my work is largely server-side.

If this was discussed in the past and voted against, would love to see a link to that discussion.

Thanks!

**Comment by maggiepint** [comment]
We offer a built file of Moment that doesn't include the locale files. Then you can include in your project only the locale files you need. Is there a reason that this does not meet your needs?

**Comment by icambron** [comment]
@hueniverse also, please clarify if this is Node or in a browser, since those are pretty different cases in terms of packaging.

**Comment by hueniverse** [comment]
My needs are node only. moment is used by joi which is a core component of hapi. Because hapi is targeting sensitive use cases, I code review every dependency in the chain. moment is one of 3 modules hapi depends on that is not part of our community. We are very satisfied with it but every time you release a new version, I have to do a full code review on the diff between the latest version and the last one we've used. It's very labor intensive, mostly because of the localizations.

It would be great to depend on something like moment-core instead.

**Comment by icambron** [comment]
I think this is a reasonable request, but it's not immediately obvious how it would be done, given that we definitely do want a build with all the locales included. If there were a reasonably easy way to create an alternative npm package in the same repo that simply limited the set of files in it, that seems preferable to me than trying to split the repositories.

**Comment by hueniverse** [comment]
Why is the timezone approach not applicable here?

**Comment by icambron** [comment]
It's not inapplicable, just painful to switch to.

**Comment by hueniverse** [comment]
If I gave it a shot, what would be the best process? branch off what?

**Comment by icambron** [comment]
Some things to think about:

 1. Moment is the process of switching from Esperanto to Babel/Rollup to generate its builds. So this is a thorny time to do a bunch of complicated build stuff.
 2. We aren't willing to go back to our users and say "hey, I broke your app; you now need to install and require this other thing for your locales to work." So the existing NPM can't break; this needs to be a new package that only has the core stuff, not a replacement + a new plugin.
 3. Same goes for generating the `moments-and-locales.js` build used by client-side apps.
 4. You probably need buy-in from more than just me. I'm not in charge around here.

That's why I think the best way to do it would be to just build a stripped down NPM with an alternative name like `moment-core`. That saves you a lot of coordination and decreases the chances we tell you "no, this is too big of a change" after you do a ton of work.

Always branch off `develop`.

**Comment by hueniverse** [comment]
I think the least painful approach is to fork and just keep the core as a new different module (with a name that doesn't mislead people to think it's affiliated with the moment org). It's unfortunate, but given your concerns and build requirements, I don't see this happening any other way. Maybe of the fork gets some interest, that will serve as useful feedback here to reconsider in the future. Thanks for the feedback!
