### ISSUE TITLE
moment.locale(Name) does not change week localization in formatting of the day of week in moment.format

### ISSUE THREAD

**Issue by github-polymer-user** [moment/moment#3294]
Currently, **moment.weekdays** is actually localized, but switching locales does not change formatting fo the day of week in **moment.forma**t using week format specifier **dddd**:

moment.locale('ru');
date.format('dddd DD.MM.YYYY');
moment.locale('fr');
date.format('dddd DD.MM.YYYY');

Temp workaround:

moment.weekdays(parseInt(date.format('E'))) + ' ' + date.format('DD.MM.YYYY');

**Comment by icambron** [comment]
It doesn't change because the global locale settings don't update already-existing moment objects. That's on purpose, because it's often confusing to have global settings like that yank around your objects, and because many people want multiple instances with different locale settings. From the docs:

> As of 2.8.0, changing the global locale doesn't affect existing instances.

Your workaround works by going back to the static `moment.weekdays()` to get the current global setting instead of the differently-localized instance. You have two other options to fix this:

First, you can avoid using the global setting and just set it locally on the object:

```js
> date.locale('fr').format('dddd DD.MM.YYYY');
'vendredi 08.07.2016'
```

Alternatively, new instances reflect the global setting:

```js
> moment.locale('ru');
'ru'
> moment().format('dddd DD.MM.YYYY');
'пятница 08.07.2016'
> moment.locale('fr');
'fr'
> moment().format('dddd DD.MM.YYYY');
'vendredi 08.07.2016'
```

**Comment by icambron** [comment]
See #1797
