### ISSUE TITLE
Number 0 converted to space while doing .toUTCString()

### ISSUE THREAD

**Issue by amarzavery** [moment/moment#3296]
`moment.utc('Mon, 01 Jan 0001 00:00:00 GMT', 'ddd, DD MMM YYYY HH:mm:ss').toDate().toUTCString()` results in "Mon, 01 Jan    1 00:00:00 GMT". notice the 4 spaces after Jan and before 1. The second third and the fourth space are for 3 zeros. This was working well with 4.x version of node.js. However with 6.3 version of node.js 0 (zero) is converted to empty space during serialization. This breaks our tests. It works well with 4.x version of node.js

**Comment by amarzavery** [comment]
Please click the edit button in the above description to see the spaces, as github markdown removes it.

**Comment by icambron** [comment]
We can't fix this. `toDate()` returns a native JS Date object. Thus `toUTCString()` is a native method being called on a native object. The bug happens without any reference to Moment:

```js
> new Date('0001-01-01T00:00:00.000Z').toUTCString()
'Mon, 01 Jan    1 00:00:00 GMT'
```

So you'll have to take it up with the Node folks. But you can work around it easily enough by just using Moment to do the formatting instead of converting it to a native date first:

```js
> moment.utc('Mon, 01 Jan 0001 00:00:00 GMT', 'ddd, DD MMM YYYY HH:mm:ss').format('ddd, DD MMM YYYY HH:mm:ssZ')
'Mon, 01 Jan 0001 00:00:00+00:00'
```
