### ISSUE TITLE
Can't compare current time to two time intervals

### ISSUE THREAD

**Issue by HamzaLJ** [moment/moment#3307]
I am trying to compare the current time **timeNow** and check if it falls between a time range opening and closing, but I can't do so especially if the current time and closing time is above midnight.

I tried also to convert all the time formats to minutes, but also it didn't worked

```
    var timeFormat2 = "HH:mm:ss";
    var timeNow = "23:12:00"; //(11:12:00 pm)
    var opening = "08:00:00"; //(08:00:00 am) morning time
    var closing = "00:12:00"; //midnight time (i.e 12:12:00 am)

    var isAvailable = moment(timeNow, timeFormat2).isBetween(moment(opening, timeFormat2), moment(closing, timeFormat2));

    console.log("will show false >>>> ", isAvailable); //it shows 'false'

    var closing1 = "23:45:00";
    var isAvailable1 = moment("23:12:00", timeFormat2).isBetween(moment(opening, timeFormat2), moment(closing1, timeFormat2));

    console.log("Should show true >>>> ", isAvailable1);

```

> Here is a JSfiddle: https://jsfiddle.net/1wuf0rzg/8/

**Comment by icambron** [comment]
Moment doesn't parse "00:12:00" into a standalone time; it parses it into a really specific datetime, defaulting the unspecified date part to today. But "00:12" was actually in the morning, 8 hours before the opening time. So 23:12 is not in that range. You'll have to specify a date so that Moment knows that you mean just after midnight *tomorrow*.
