### ISSUE TITLE
Add Quarter is not using the last day of the month for resulting date

### ISSUE THREAD

**Issue by dereklin** [moment/moment#3331]
The last day of Quarter 4 should be 12/31.  But moment.js using using 12/30 as the Quarter 4 date.

Same problem for 3/30 (should be 3/31)

Here is my plunker: 
https://embed.plnkr.co/fkGneTsz2OGWjMvrGzLI/

![adding-quarter-with-moment js](https://cloud.githubusercontent.com/assets/2231799/17184688/7200902a-53e2-11e6-8b06-bd16beb52da5.png)

**Comment by dereklin** [comment]
I have have to add this line to make it work as expected:
```
startQuarterDate = startQuarterDate.endOf("Q");
```

https://plnkr.co/edit/B8MMX0XR5KehxObicO27?p=preview

**Comment by icambron** [comment]
I don't think Moment can reasonably be expected to behave like you're suggesting. For example, Moment's behavior with quarters is the same as with months:

```js
moment("2016-04-30").add(1, 'M').format("LL"); //=> May 30, not May 31
```

Moment doesn't know you're trying to "pin" your date to the end of whatever quarter you're in just because the day in question happens to be last one. Should the second-to-last day of a quarter plus one quarter be the second-to-last of the next? How about the 93rd from the last? You can see where quarters being different lengths doesn't allow us to be consistent counting both forwards and backwards.

Alternatively, if you're suggesting we specifically special case the last day in the addition rules, I'll say that just sounds confusing.

I think you did the right thing: if you mean "the end of the next quarter", you should use `endOf`.

**Comment by dereklin** [comment]
I can see there is some complexity.  But if someone gives me a date which is the last day of the quarter and ask me what is the corresponding date for the next quarter, I would answer the last day of the next quarter.  So 09/30 goes to 12/31, not 12/30.  It would be nice if the library can do that.  If not, endOf would have to do :)

**Comment by icambron** [comment]
I see what you mean, but that would be a weird thing for the library to decide for you.

**Comment by dereklin** [comment]
I think it's complexity not weirdness.  Before performing the addition, the library can check to see if the start date is at the end of the quarter, if so, (with logic) make sure the resulting date is also at the end of the quarter.

It's intuitive to think that adding 1 quarter to 09/30/2015 should give you 12/31/2015.
On the other hand, adding 1 quarter to 09/30/2015 and receiving 12/30/2015 in return is not expected, at least for me.

This use case may interfere with existing use cases, thus the complexity.
