### ISSUE TITLE
moment('2/31/2016').isValid() returns true

### ISSUE THREAD

**Issue by sandbochs** [moment/moment#3332]
It also returns true for the other months with less than 31 days.

- February
- April
- June
- November

`moment('2/32/2016').isValid() returns false.

**Comment by icambron** [comment]
When you parse a non-ISO8601 date string with Moment, you need specify the format (in this case "MM/DD/YYYY"), it's getting parsed by the native date parser instead of Moment's parser. You should have gotten a deprecation warning about that.

But, because that native date constructor is returning valid date for that, Moment doesn't have a chance to know you really meant this non-existent date.

```js
//passing in just the date like that is the equivalent of passing into new Date(). 
//Chrome is tolerant of 2/31 for reasons all their own
new Date('2/31/2016').toString(); //=> "Wed Mar 02 2016 00:00:00 GMT-0500 (EST)"

//Since March 2 *is* a new date, Moment accepts it, just like it would this
moment(new Date('2/31/2016')).isValid(); //=> true

//Chrome is not tolerant of 2/32, which is why the other date behaved 
//like you expected
new Date('2/32/2016').toString(); //=> "Invalid Date"

//OTOH, if you let Moment parse it, it knows that 2 means Feb and 31 means the day, 
//so it can mark it invalid
moment('2/31/2016', 'M/DD/YYYY').isValid(); //=> false

//ISO-8601 works too, because Moment knows to parse it explicitly instead of 
//passing it to the native constructor
moment("2016-02-31").isValid(); //=> false
```

This behavior is confusing, which is part of why we deprecated the fallthrough native parsing.

**Comment by sandbochs** [comment]
@icambron Thank you for clarifying that. I should have RTFM.
