### ISSUE TITLE
Use duck typing for testing input format

### ISSUE THREAD

**Issue by murillo128** [moment/moment#3343]
I am having an issue with my app when I upgraded to latest moment library. It is not a bug in moment, but something I would be very glad if it could be considered:

In our application we are using Proxies for templating/reactive programming. One of the issues with proxies is that Date type is not transparently proxied, so we have to create a small wrapper to make it work seamlessly.

https://github.com/eface2face/object-observable/blob/master/index.js

The proxied object is exactly the same as the Date object, except of the prototype name (which is `[object Object]` instead of `[object Date]`).

That is causing that when managing it via moment, the input date is emptied:

``` javascript
 function createLocalOrUTC (input, format, locale, strict, isUTC) {
        var c = {};

        if (typeof(locale) === 'boolean') {
            strict = locale;
            locale = undefined;
        }

        if ((isObject(input) && isObjectEmpty(input)) ||
                (isArray(input) && input.length === 0)) {
            input = undefined; //<----- HERE
        }
```

Not sure how prone you  would be for performing some kind of duck typing on the input object instead of checking the prototype (via `getTime`for example). (Note that in our case new Date(proxy) works perfectly).

**Comment by icambron** [comment]
I'm going to push this in a bit of a different direction and consider this a feature request for calling `valueOf` on unknown objects and using its result as a millisecond count.

Lots of things could have a `getTime` and it could return just about anything. `valueOf` will always return the right kind of thing, but we don't know whether that thing is supposed to be a time. So instead of thinking of this as finding out if something is datetimeish, we should instead of think of this request is asking for a *cast* to a number. That number might or might not be semantically a date, but that's how Moment would treat it, just like it treats `moment(1470194374225)`.

In fact, that same idea is also why `new Date(proxy)` works for you; the native date constructor does what I'm proposing:

```js
> Foo = function(){}
[Function]
> Foo.prototype.valueOf = function(){return 1470194374225;}
[Function]
> new Date(new Foo()).toString();
'2016-08-03T03:19:34.225Z'
```

E.g.`getTime` doesn't do it:

```js
> Bar = function(){}
[Function]
> Bar.prototype.getTime = function(){return 1470194374225;}
[Function]
> new Date(new Bar()).toString();
'Invalid Date'
``` 

Anyway, with this reframed this way, I'm a mild +1.

**Comment by not-an-aardvark** [comment]
As a workaround, you could add `Symbol.toStringTag` to your proxies so that they would have the `[object Date]` tag.

```js
var myCustomObject = {
  valueOf: () => 1470346458795,
  getTime: () => 1470346458795,
  [Symbol.toStringTag]: 'Date'
};

moment.utc(myCustomObject).format()
// --> '2016-08-04T21:34:18Z'
```

**Comment by murillo128** [comment]
Hi, sorry for the late replay.

The ```[Symbol.toStringTag]``` did the treick , thank you very much!

Also I think that the valueof approach would be a good enhancement.

Again, thank you very much for your support

**Comment by murillo128** [comment]
Well, correcting myself:

When  adding the ```[Symbol.toStringTag]``` does not work for me, indeed :

```javascript
input instanceof Date === true
```
but this check fails

```
if ((isObject(input) && isObjectEmpty(input)) ||
                (isArray(input) && input.length === 0)) {
            input = undefined;
        }
```
because 
``` function isObject(input) {
        return Object.prototype.toString.call(input) === '[object Object]';
    }
```` 
And the object is "empty", that is, has no iterable properties.

**Comment by marwahaha** [comment]
Cool idea. Unfortunately we will not take new features.

See https://momentjs.com/docs/#/-project-status/
