### ISSUE TITLE
Inconsistency in start of week definition between calendar's 'lastWeek' and startOf('week')

### ISSUE THREAD

**Issue by tedswag** [moment/moment#3353]
startOf('week') gives the start of the previous Sunday, however calendar will place the previous Saturday in 'lastWeek':

```javascript
var prevSunday    = moment().startOf('week');                    // Previous Sunday
var prevSaturday  = moment().startOf('week').subtract(1, 'day'); // Previous Saturday
var prevFriday    = moment().startOf('week').subtract(2, 'day'); // Previous Friday

console.log(prevSunday.calendar());   // (lastWeek)
console.log(prevSaturday.calendar()); // (lastWeek should be sameElse for consistency with startOf('week'))
console.log(prevFriday.calendar());   // (sameElse)
```

**Comment by tedswag** [comment]
To fix on line 2894:

    - return diff < -6 ? 'sameElse' :
    + return diff < -5 ? 'sameElse' :

**Comment by icambron** [comment]
First, sorry for the slow response.

I don't think that's the right interpretation of "Last Sunday", etc. It just means the previous one. It's unfortunate that we call the case `lastWeek` in the code because it's misleading.

Let's make it not about week borders at all: for example, try this one (assuming it's currently Wednesday or later), where the day is unambiguously in the current week:

```js
console.log(moment().startOf('week').add(1, 'day').calendar());
Last Monday at 12:00 AM
```

That's just using "last" to mean "previous". English has terribly vague standards on this stuff: does "last Monday" mean the one just gone by or the one in the last week? Depending on context, you might have just said "Monday", but only if you're talking about something that's assumed to have been in the past. Moment doesn't have that context, so it sticks with "last Monday". There may be regional difference in usage for this too.

For what it's worth, CLDR--the closest thing we have to an authority--[agrees](http://cldr.unicode.org/translation/date-time-names#TOC-Relative-Day-of-the-Week-Names) with our interpretation.
