### ISSUE TITLE
Single digit month/day parsing giving false negative

### ISSUE THREAD

**Issue by YourDeveloperFriend** [moment/moment#3359]
This problem occurs if I use the pattern `MDYY`:

```javascript
moment().format('MDYY'); // '8816'
moment('8816', 'MDYY').isValid(); // false and it should be true
```

You can find the conflicting function `getParseRegexForToken` [here](https://github.com/moment/moment/blob/b135bf1a6d58ff94287f0a21455bfa6a1ddc7226/src/lib/parse/regex.js#L37).

```javascript
getParseRegexForToken('M') === /\d\d/;
```

The `M` token is gobbling up both `8`'s at the beginning of our string, when it should only grab one. Maybe a better approach is to create a more specific regex `/(1[0-2]|[1-9])/` for months and `/(3[0-1]|[1-2]\d|[1-9])/` for days.

A stronger approach may even be to construct an entire regex for the entire string. For example, MDYY would create the regex: `/(1[0-2]|[1-9])(3[0-1]|[1-2]\d|[1-9])(\d\d)/`, which could be used with `string.match(regex)` to immediately parse out the important pieces of the pattern.

**Comment by icambron** [comment]
See #2418 and #677

Yeah, this is a design flaw in the parser. It's actually `\d\d?` (see [here](https://github.com/moment/moment/blob/470490a6970b0664064908921976bd6a08ff818c/src/lib/units/month.js#L44)), but the way the parser works, it eats one token at a time and doesn't backtrack. One big regex would definitely handle that better by allowing it to backtrack on the greedy `\d?` match when the whole thing failed, which would be great. You'll have to trust me that it made sense to do it this eat-tokens-as-you-go way when we did it.

The parser is up for a rewrite where we drop non-strict parsing and I suspect it would support this case. But since I have no idea when that will be, I'm closing this as wont-fix.
