### ISSUE TITLE
Constants for Time

### ISSUE THREAD

**Issue by merlinpatt** [moment/moment#3368]
It would be useful to have constants that I can use in various calculations that moment does not supply.

Constants would be things like
- HOURS_PER_DAY
- MINUTES_PER_HOUR
- HOURS_IN_MINUTES
- MILLIS_PER_SECOND
- SECOND_IN_MILLIS

**Comment by mj1856** [comment]
Worth considering.  Though in some cases we have to be careful about how we apply large numbers due to JavaScript's floating point math issues.

**Comment by icambron** [comment]
-1 overall. Two cases:

 1. Debatable constants that Moment's conventions use in conversions, like DAYS_PER_MONTH
 2. Unambiguous constants that everyone knows, like MINUTES_PER_HOUR

Both are useful in principle: the first is useful because it documents Moment and allows users to impedance-match their calculations with Moment's. The latter is useful in that it allows the user to communicate their intentions in some calculation, like `MINUTES_PER_HOUR * SECONDS_PER_MINUTE * MILLIS_PER_SECOND`. But on the latter, I don't think we're really providing the user very much. They know the number, obviously, and it will never ever change so we're just saving them typing the const def at the top of their file.

So +1 for case 1 and -1 for case 2. Since all the examples you gave are case 2, I assume that's the case you're trying to solve, so I'm -1.

**Comment by marwahaha** [comment]
I guess, the useful part of case 2 is to not have magic numbers if you're computing time-based events. You could define these variables, but it'd be `nice-to-have` if Moment.js did it..

I think we should come to a conclusion & resolve this issue (either close/wontfix or do it).

**Comment by icambron** [comment]
I agree we should do something with it. I vote `wontfix`

**Comment by marwahaha** [comment]
@mj1856

**Comment by mj1856** [comment]
Closing.  Thanks for the idea, but we'll pass on this for the reasons @icambron described.
