### ISSUE TITLE
Localized date with day of week without time

### ISSUE THREAD

**Issue by dustinsmith1024** [moment/moment#3399]
Is there plans or ability to add a localized date with the day of the week that does not include the time?

Thanks!

**Comment by maggiepint** [comment]
This is a bit easier said than done. This is because all of our locale files are hand made by someone who speaks the language. In order for us to know how to properly structure the formats, we would need to call all of those locale authors in to get their opinion. In this specific case though, I think one could go through all of the locale files and add a new format that is a modified version of the LLLL format, just removing the time. We would probably accept that.

In this specific case though, we might be willing to take a pull request that adds this format, by using what already exists in the ``LLLL`` format, and simply removing the time tokens.

**Comment by maggiepint** [comment]
Closed #4074

**Comment by marwahaha** [comment]
I'm going to re-open, since the PR hasn't merged.

**Comment by marwahaha** [comment]
duplciate of https://github.com/moment/moment/issues/2505
