### ISSUE TITLE
Add Days daylight savings time issue

### ISSUE THREAD

**Issue by KamalAman** [moment/moment#3413]
One would expect that 

adding 200 days to utc 0 should yield the 200th day of 1970 at midnight UTC
```
moment(0).add(200, 'day').toISOString()
"1970-07-20T00:00:00.000Z"
```

however the following yields the 199th day at the 23rd hour. 
```
moment(0).add(200, 'day').toISOString()
"1970-07-19T23:00:00.000Z"
```
I believe adding 200 days to moment(0) is not equivalent to adding 24*200 hours since daylight savings has an effect on the command.

**Comment by mj1856** [comment]
`moment(0)` creates a moment at the Unix epoch, but leaves the resulting moment object in *local mode*.  In my time zone (US Pacific):

```javascript
moment(0).format() // "1969-12-31T16:00:00-08:00"
```

Then when you add 200 days, those are 200 days by the local time zone, which includes DST.  See [Date Math vs Time Math](http://momentjs.com/guides/#/lib-concepts/date-time-math/) in the user guide.

Calling `toISOString` displays the result as the UTC equivalent, so you see `23:00Z` instead of `00:00Z`.

If you place the moment object in UTC mode before adding days, then you will get the result you expected.  Either of the following will work:

```javascript
moment.utc(0).add(200,'day').toISOString()   // "1970-07-20T00:00:00.000Z"
moment(0).utc().add(200,'day').toISOString() // "1970-07-20T00:00:00.000Z"
```

**Comment by KamalAman** [comment]
Thanks for you're support, and damn you Geroge Hudson.
