### ISSUE TITLE
Why `moment(null)` works different from `moment()` or `moment(undefined)`

### ISSUE THREAD

**Issue by JounQin** [moment/moment#3415]
I'm writing some utils codes in my project, then I find that `moment(null)` works different from `moment()` or `moment(undefined)`.

I'm wondering why they are different or is there a global option to treat them alike?

**Comment by maggiepint** [comment]
This isn't exactly the same as #3180 but it's worth reading that thread. As you will see there, typically invoking a function with no parameters, and invoking a function with undefined, will by convention have the same result in JS.

As far as why null causes an invalid date - that's because null IS a value, and it's a value that doesn't create any meaningful date. Personally, I don't see a reason to change this. I understand why it has some utility in certain coding scenarios, but I think it serves to make the API confusing.

**Comment by conceptdeluxe** [comment]
Quite annoying ...

    console.log(moment(null).toDate()); // Invalid Date
    console.log(moment(undefined).toDate()); // Date
    console.log(moment(null, 'YYYY-MM-DD').toDate()); // Invalid Date
    console.log(moment(undefined, 'YYYY-MM-DD').toDate()); // Invalid Date
