### ISSUE TITLE
Unexpected behavior in NodeJS: moment.utc().unix() == moment().unix()

### ISSUE THREAD

**Issue by ergoithz** [moment/moment#3444]
NodeJS, on CET:
```js
> const moment = require('moment');
> moment().unix() == moment.utc().unix()
true
> moment().unix() == moment().tz('utc').unix()
true
> moment().format() == moment.utc().format() // obvious, I know
false
```
Returned unix value is not UTC, checked using a more reliable source.
valueOf is also broken in the same way.

I know MDN and standard says Date.getTime() should return always UTC time, and NodeJS does not complies this standard, so it should be NodeJS's fault, but as nobody complies this standard (it's also violated by most browsers) its correctness shouldn't be assumed.

**Comment by icambron** [comment]
`unix()` always returns what we believe to be the UTC epoch time--same as Unix does--so those equalities are expected. So I think your complain is that *neither* values are the real UTC time?

It may be the case that Node on your platform is *wrong* about the current time. That's not the norm; browsers, Node, and your OS all keep time in UTC; otherwise we'd have hundreds of bug reports to this effect. For example, I just tried it in my Node REPL. Moreover, Moment doesn't have access to some external source of truth here; the best it can do is ask its environment what time it is.

I believe you should double check that:

1. Your computer has the right UTC time on the system clock
2. You checked the right external source

For example, compare `moment().unix()` to what your shell prints for `date +%s`. If not, there's probably something seriously wrong with your Node installation or something.

**Comment by icambron** [comment]
I'm going to go ahead and close this, since the ticket may cause confusion and I'm confident there's no issue with Moment here. But I will respond to any follow-ups you have if you explicitly mention me.

**Comment by KES777** [comment]
>unix() always returns what we believe to be the UTC epoch time--same as Unix does--so those equalities are expected. 

![_](https://user-images.githubusercontent.com/799021/57318529-36d0b980-7103-11e9-8efd-6c602100e825.jpg)
