### ISSUE TITLE
isSameOrBefore Error

### ISSUE THREAD

**Issue by joques** [moment/moment#3458]
**moment().isSameOrBefore('2016-09-20)**

*On September 20 2016 I tried the call above and got false while I was expecting true. Note that passing the same date as a string to moment does return true*

**NodeJS 6.3.1 on Mac OS and Ubuntu**

**Other information that may be helpful:**
* Time zone: West African Time
* 11 AM on September 20 2016
* Other libraries in use none

Below is the output of the date testing code
Tue Sep 20 2016 12:03:00 GMT+0200 (WAST)
9/20/2016, 12:03:00 PM
-120
2.13.0

**Comment by icambron** [comment]
Moment only represents specific millisecond-granular instances in time. So `moment('2016-09-20')` gets parsed to midnight on that day. Since the current time is after that, Moment dutifully answers `false`. It doesn't know you really want know if the *date* is the same or before the current date. Fortunately, `isSameOrBefore` accepts argument for telling it just that:

```js
moment().isSameOrBefore('2016-09-21', 'day'); //=> true
```
