### ISSUE TITLE
Problem with 'subtract' method

### ISSUE THREAD

**Issue by leonardo031195** [moment/moment#3507]
**Description of the Issue and Steps to Reproduce:**
When it is used a combination of subtract(1, 'days) and startOf('day') methods, the given variable has a inconsistent value. (It will have one more hour). Subtracting 2 days gives a correct value.

*Please include the values of all variables used.*
var today = moment().startOf('day); //Mon Oct 17 2016 00:00:00 GMT-0200
today.subtract(1, 'days').toDate(); //Mon Oct 16 2016 01:00:00 GMT-0200
today.subtract(2, 'days').toDate(); //Mon Oct 15 2016 00:00:00 GMT-0200

**Environment:**

Chrome 53 - Windows 10

**Other information that may be helpful:**
Timezone - GMT -0200 (Brazilian Summer Time)
Angular.JS is being used

**Comment by maggiepint** [comment]
This is correct. There was no midnight in Brazil on October 16th due to DST transition, so Moment is moving to the start of the day, which was in fact at 01:00.

For more information about the WHY of this, you can see me speaking at JSMN a few months ago. https://www.youtube.com/watch?v=ieIzNP6gKqU
This exact scenario is explained at 35 minutes in, but I would start at about 33 minutes for context.
