### ISSUE TITLE
Issue with only passing in time...

### ISSUE THREAD

**Issue by giantsrg1** [moment/moment#3527]
So i am trying to take a time(only) and then format it out.

I know I can use string split... but i want to keep it moment. 

I see that there is a weird bug where if the time is after 10 this will work but anything before it will not...

Picture shown below shows this odd behavior:
![image](https://cloud.githubusercontent.com/assets/12544363/19649159/c0830c38-99d2-11e6-9116-56b5329c4534.png)

Am i doing something wrong or is this not intended to do this and only works for strange use cases?

**Comment by johncrisostomo** [comment]
Just make your inputs a String by putting quotes around them. 

The reason why anything below 10 is failing is because of the leading zero. 

Doing it like your examples above removes the 0 in front of 8 upon variable assignment to `config._i`. That makes it an Invalid Date when parsed and tokenized by Moment.

**Comment by giantsrg1** [comment]
John,

What about this example?

![image](https://cloud.githubusercontent.com/assets/12544363/19778619/99242b06-9c4b-11e6-9b82-7654abe127c5.png)

Looks like if i just have 8 characters and convert it to a string still have the same issue.

**Comment by johncrisostomo** [comment]
I believe it has something to do with the ISO time format. If you check this file:

https://github.com/moment/moment/blob/develop/src/lib/create/from-string.js

`H` is not a valid format, hence the Invalid Date. So there should always be always a zero before single digit hours to match HH.

**Comment by maggiepint** [comment]
So, if you look at some of the parse metadata you get the story on this:

```js
moment('63008000', 'HmmssSSS').parsingFlags().parsedDateParts;
// [undefined × 3, 63, 0, 80, 0]
```

Basically you're getting parsed as hour 63, which is of course invalid. I would agree that a single H token should accept single digit so for the moment I"ll let this be a bug. One of the others might disagree.

**Comment by butterflyhug** [comment]
In the general case, I don't think it's actually possible to parse all-numeric strings using a format that has more than one variable-length token.  And so I'm not sure we really want to support parsing with this pattern at all with our standard parser.

For example, consider something like `moment('12345000', 'HmmssSSS')`.  Should that parse as `[,,,12,34,50,0]` or `[,,,1,23,45,0]`?  Given our current parsing API, I think either interpretation is defensible -- especially since our docs explicitly say "Note that the number of S characters provided is only relevant when parsing in strict mode. In standard mode, S, SS, SSS, SSSS are all equivalent, and interpreted as fractions of a second."

I do think ideally we would try to support this in strict mode, but I bet that currently fails too.  Fixing it would require a lookahead parser, so it's a pretty huge change to implement.

**Comment by maggiepint** [comment]
Right, I see the same complexities. To me, this is almost a bug/won't fix. If you specify an `H` token you should be able to use a single digit. That you can't, from an API standpoint, is wrong. It doesn't mean it's reasonable to fix. I hate things like this but it is what it is.

**Comment by icambron** [comment]
We used to get this more right in the strict parser by building one big regex and applying it, which meant it would do backtracking. We tossed that to allow ourselves to share code between the two parser modes. Probably a mistake (by me!)

We should probably rewrite the parser once we've tossed out non-strict parsing for good. In the meantime, that seems silly, so I've been marking these as wontfix. Related issues: #1401, #677, #3359, and #2418
