### ISSUE TITLE
bug isBefore() function with same timestamp in version 2.15.2

### ISSUE THREAD

**Issue by jadeHuang** [moment/moment#3540]
the now date is 2016-10-28

`a = moment().hours(0).minutes(0).seconds(0);
b = moment("2016-10-28",'YYYY-MM-DD');

console.log(a.isBefore(b))
console.log(b.isBefore(a))`

the first output is correct and the second output true which should be false

**Comment by johncrisostomo** [comment]
You have to specify set `a`'s millisecond to 0 for this to work. Like so:

`a = moment().hours(0).minutes(0).seconds(0).milliseconds(0)`

If you check `a.valueOf()` and `b.valueOf()`, you will see that `a` is leading with a few milliseconds because it was not set to 0, check this example:

https://jsfiddle.net/omg5wer5/

Likewise, on your example, running `console.log(a.isSame(b))` will result to false.

**Comment by jadeHuang** [comment]
thanks, seems I forget to set milliseconds(0),going to close the issue.
