### ISSUE TITLE
Slightly strangeness on moment 

### ISSUE THREAD

**Issue by callumacrae** [moment/moment#3557]
I don't fully understand why this is happening—I'm not even sure it's an issue—but I figured I'd post it here anyway.

We just changed the clocks back in England, which meant we had a day that was 25 hours long. The next day, we had a day appearing twice in the calendar on our site.

Basically:

```js
moment.duration(-moment('2016-10-30').diff('2016-10-31')).asDays();
// -> 1.041666

moment('2016-10-31').diff('2016-10-30', 'days');
// -> 1
```

We were originally using the former, but switched to the latter to fix the issue. The former remains recommended in many places across the internet.

Is this expected / known? (also, does this happen with leap seconds too?)

**Comment by butterflyhug** [comment]
Thanks for asking!  This behavior is expected and intended.  `moment#diff` without a units argument returns a number of milliseconds, so that's representing 25 hours stripped from any context of where those 25 hours came from.  Then you create a duration from that value, and of course 25 hours generally is more than a day, so it gets handled accordingly.  Your issue is exactly why the team added that second parameter to `diff` so you can get accurate results in other units.

**Comment by callumacrae** [comment]
Great, thanks for the explanation! (and sorry for the title gore: didn't notice until I reread it just now)
