### ISSUE TITLE
Add half year as format

### ISSUE THREAD

**Issue by Spenhouet** [moment/moment#3582]
It would be nice to have a format that shows the half year.

For example:

Format: **"hj"** => 1, 2

Additionaly a localized format **"hhj"** => H1, H2 would be nice.

**Comment by mj1856** [comment]
Something similar was suggested previously (#1998) and rejected.  If there's enough interest we'll reconsider.  I'll leave this open for commentary from the community.  Thanks.

**Comment by icambron** [comment]
-1 for simple default-to-less reasons.

**Comment by Spenhouet** [comment]
@icambron What do you mean by `default-to-less reason`?

**Comment by icambron** [comment]
@Spenhouet Less features is good. Makes the library smaller, easier to understand, and easier to maintain. We try to balance that with the usefulness of features. Here the feature doesn't seem very useful, so I think the countervailing argument for simplicity carries the day.

**Comment by Spenhouet** [comment]
A half year is often used in business for example to compare data from one half year to the half year of following year. Sure, you can say "this library is not meant for companys" but is this true?

**Comment by maggiepint** [comment]
I'm closing, for the reasons already stated by @icambron. At the end of the day, the work to get this included in all the locale files wouldn't be worth it.

**Comment by kylethebaker** [comment]
I understand this is already closed, but I figured I'd add my two cents anyways. I think this would be a useful feature to add, we are doing a fair bit of work to work around halves. Getting the actually half is trivial:

```js
const half = (date.get('quarter') < 3) ? 1 : 2`)
```

Where it gets frustrating it having dynamic calendar periods for everything except halves when generating 'to-date' ranges. For example, a month-to-date filter can be specified as `mtd` and we can create a range from `date.startOf('month')` to `date`. We can use the same simple logic for quarters, days, weeks, and years, where we just need to map a 'to-date' filter slug (`day`, `wtd`, `mtd`, `qtd`, `ytd`) to the corresponding momentjs period string (`day`, `week`, `month`, `quarter`, `year`). This is also trivial to do comparisons with 'this period last year', 'last period this year', etc, since we can extrapolate by doing `date.subtract('year', 1).startOf(period)` to get a comparison to last year or `date.subtract(period, 1).startOf(period)` to get a comparison to last period;

With `htd`/`half` we end up having to add additional logic to extrapolate the current/previous/next half based on year/quarters. We have a separate code path to fill in the gaps, even though we are just using this idea of `1 half == 2 quarters`.

Do halves have any 'gotchas' when it comes to locales, timezone, daylights savings, etc? I think the first half can be reliably found using `date.startOf('year')` to `date.set('quarter', 2).endOf('quarter')` and the second half using `date.set('quarter', 3).startOf('quarter') to date.endOf('year')` (where `date` is just some arbitrary date to anchor these ranges to).

I guess my point is that it seems like as though getters/setters for the necessary anchor points are already there that is seems like it should be included. Though it can be extrapolated with a little bit of work (and thus the argument can be made that it's unnecessary, opting for simplicity), you can make the same argument about quarters (they are reliably start of month 1 to end of month 3, start of month 4 to end end of month 6, etc).
