### ISSUE TITLE
add func to tell if current locale supports meridien

### ISSUE THREAD

**Issue by mh-cbon** [moment/moment#3590]
**Description of the Issue and Steps to Reproduce:**
Would be great if locale config could tell if the current locale uses meridien to display the time.

Currently, calling `moment().localeData().meridiem(1, 1, true);` for a language like `fr` will return am/pm, which somehow is incorrect, but more importantly, it can t help to tell if the current locale uses meridien.

This is an useful information to display UI adequately.

**Environment:**

```sh
npm ls moment
md-date-time-picker@2.2.0 /home/mh-cbon/projects/md-date-time-picker
└── moment@2.16.0 
```

**Comment by maggiepint** [comment]
I can see some advantages to this, but in practice why couldn't one just rely on the locale based formats? If `LT` doesn't have an `a` token, then it stands to reason that the locale doesn't use meridiem.

**Comment by mh-cbon** [comment]
do you mean [this](https://github.com/moment/moment/blob/develop/locale/af.js#L31) ?
Indeed it seems to be a good idea. Is it safe to assume `config.locale.LL.indexOf('A')>-1` will do the correct job ?

**Comment by maggiepint** [comment]
You would need to look for both `A` and `a` (or just call toLowerCase on the format) but otherwise yes. 
It is possible that the given locale may have a concept of meridiem that isn't commonly used and thus isn't in the LT format, and of course checking that value wouldn't help you if this were the case. I think you want to know if meridiem is commonly used though.

**Comment by icambron** [comment]
I agree with where this ended up: if you want to check if a locale commonly uses meridiems, you should check the locale formats; it's a mistake to check if the meridiem is defined at all. Since that means @maggiepint and I both think there isn't a good enhancement to make here, I'm going to close this.

**Comment by lebesnec** [comment]
this seems to work:

```
useMeridiem: function(locale) {
    var localeData = moment.localeData(locale);
    return localeData.longDateFormat('LT').toLowerCase().indexOf('a') > -1;
}
```

`useMeridiem('en') => true`
`useMeridiem('fr') => false`

Some UI framework have an option for time picker to use 24h or AM/PM format, like https://vuetifyjs.com/en/components/time-pickers#example-time24h-format
It would be helpful to have add this to the library.

**Comment by Tinoooo** [comment]
@lebesnec Your approach works great. I have the exact same use case (vuetify's time picker). :+1:
