### ISSUE TITLE
match moment's hebrew/israel locale (he-IL) to java's alternate locale code (iw-IL)

### ISSUE THREAD

**Issue by armyofda12mnkeys** [moment/moment#3609]
When I pass the locale which i get from our back-end java web-service to our client-side app (which uses moment), the locale 'iw-IL' doesn't get mapped to hebrew but chinese instead in moment.js.
So for example when i use something like this:
moment( '25/12/1960', 'DD/MM/YYYY' ).locale( 'iw-IL').format( 'LL' );
I get back chinese formatting, when it should have the same result as hebrew-Israeli formatting:
moment( '25/12/1960', 'DD/MM/YYYY' ).locale( 'he-IL').format( 'LL' );

Can we also support iw (and ji and in) to support java's backwards-compatible locales?
(I can put custom code in my app that passes 'he' instead to my moment formatting calls like above, but thought we could just handle from moment's supported locales).

Applicable info:
https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html
"Locale's constructor has always converted three language codes to their earlier, obsoleted forms: he maps to iw, yi maps to ji, and id maps to in. This continues to be the case, in order to not break backwards compatibility."

**Comment by icambron** [comment]
I can't reproduce this:

```js
moment( '25/12/1960', 'DD/MM/YYYY' ).locale( 'iw-IL').format( 'LL' );
"December 25, 1960"
```

"iw-IL" isn't mapped to Hebrew or any other language. Is it possible you just had Chinese set before and had that left over when `locale("iw-IL")` nooped?

If we have support aliases for locales (@ichernev - we never did that, right?) then we could make `iw` into an alias for `he`. In the meantime, we're not going to add whole locales for defunct ISO 639 codes just because Java likes them. I recommend you just check the codes coming back from the server and map them to their modern equivalents.

**Comment by butterflyhug** [comment]
For locale aliases, I suppose we could just use `parentLocale` without overriding anything.

**Comment by armyofda12mnkeys** [comment]
@icambron hey i guess it was an older version I am using in app where the chinese showed up (2.10.2):
https://jsfiddle.net/god358j9/

>I recommend you just check the codes coming back from the server and map them to their modern equivalents.
Yes, I can do this.

**Comment by icambron** [comment]
> For locale aliases, I suppose we could just use parentLocale without overriding anything.

That's true. Like a little stub that just inherits.
