### ISSUE TITLE
Handling of 'touchmove' input event was delayed for 111 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by ruant** [moment/moment#3635]
**Description of the Issue and Steps to Reproduce:**
```
Handling of 'touchmove' input event was delayed for 111 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive. moment.min.js:7
```
It's random when this is triggered. Sometime I can go through the entire form (the webapp) without it showing up, but some times it does. 
When it does, the app doesn't responde properly and you have to keep tapping stuff until it does responde.

**Environment:**
AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/54.0.2840.85 Safari/537.36
On a Samsung Tab 4 10" device, page running in WebView through an app called "Android Kiosk" (https://www.android-kiosk.com/)

**Other information that may be helpful:**
* Other libraries in use (TypeScript, Immutable.js, etc)
Typescript, Angular JS, Angular Material

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
2016-12-02 15:16:48.741 Fri Dec 02 2016 15:16:48 GMT+0100 (CET) VM306:1
2016-12-02 15:16:48.809 02/12/2016, 15:16:48 VM306:2 
2016-12-02 15:16:48.813 -60 VM306:3
2016-12-02 15:16:48.816 Mozilla/5.0 (Linux; Android 5.0.2; SM-T530 Build/LRX22G; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/54.0.2840.85 Safari/537.36 VM306:4
2016-12-02 15:16:48.818 2.12.0 VM306:5
undefined
```

Not sure if this is a moment issue, but the Chrome console mentions moment.min.js on line 7.

**Comment by icambron** [comment]
We can't help with this without more details. If you're unfamiliar with this class of problem, it's the browser thinking you've spent too much time in your script without giving control back. That might be an issue with Moment, or how you're using it, or it may just be that your code does a lot Momenty stuff and that's where it usually happens to be when Chrome spikes your thread.

Your event handler needs do less work -- try profiling to see why it's working so hard. If you did into its performance and it turns out that there's a Moment call that's unreasonably slow, you can report an issue with Moment in the form of: "I'm calling moment.xxxx() with inputs a, b, c. It's taking 70ms when I expect it should take much less. Here's a JSFiddle demonstrating the issue in isolation."

I'm going to close this ticket -- you can open a new one once you've sufficiently isolated the problem for us to help.
