### ISSUE TITLE
moment.duration().asDays() return a Float

### ISSUE THREAD

**Issue by dievardump** [moment/moment#3637]
**Description of the Issue and Steps to Reproduce:**

duration calculation between a diff of two dates return a Float

```js
var start = moment('2017-03-12');
var end = moment('2017-03-28');
moment.duration(end.diff(start)).asDays(); // 15.958333333333334;
```
**Environment:**

Firefox 50.0 Ubuntu 16.04

---

Sat Dec 03 2016 18:15:07 GMT+0100 (CET) 
03/12/2016 à 18:15:07 
-60 
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0 
2.17.0

**Comment by icambron** [comment]
Yeah, that's expected; you have a DST change in there in there. Moment knows how to handle DSTs, but the way you wrote your code hides that from Moment. Your code broken up:

```js
> diff = end.diff(start); //how many milliseconds are between these times?
1378800000
> var d = moment.duration(diff); //create a duration that many milliseconds long
> d.asDays(); //how many days is that?
15.958333333333334
```

So it think it's not quite 16 days because that number of milliseconds is...not quite 16 days. But you can tell Moment what you're really asking:

```js
> days = end.diff(start, 'days');
16
> moment.duration(days, 'days').asDays();
16
```
