### ISSUE TITLE
Problem getting exact date using year-week-day_of_week format

### ISSUE THREAD

**Issue by jayanthrajpramuk** [moment/moment#3648]
I am facing issue in fetching exact date when i specify the format (YYYY-WW-d) format.
it always resets to first day of the week which i have specified.

I have configured 'Monday' to be the first day of the week.

Examples:
moment({ year:2016, week:49, day:4}).toISOString();
"2016-01-05T18:30:00.000Z"
** But ideally i need it to be 2016-01-08T18:30:00.000Z

---------------------------------------------------------------------------------------------------
Environment and version:

console.log( (new Date()).toString()) :Wed Dec 07 2016 06:55:35 GMT+0530 (India Standard Time)
console.log((new Date()).toLocaleString()) :12/7/2016, 6:55:35 AM
console.log(moment.version) :2.10.6

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

**Comment by icambron** [comment]
First, it doesn't make much sense to combine `years` with weeks; instead you want `weekYear`. Second, from the docs:

> day and date key both mean day-of-the-month.

So in an ideal world, you'd have something like this:

```js
moment({ weekYear:2016, week:49, day:4}).toISOString();
```

That doesn't work because Moment's create-from-object functionality doesn't support those keys. You can see that code [here](https://github.com/moment/moment/blob/develop/src/lib/create/from-object.js#L11). I suppose we'd take a PR that handled that.

Instead try this:

```js
moment().weekYear(2016).week(49).weekday(4).toISOString()
"2016-12-01T12:30:19.315Z"
```

That doesn't appear to be what you want either, but I think it's right. Also worth knowing:

```js
moment().isoWeekYear(2016).isoWeek(49).isoWeekday(4).toISOString()
"2016-12-08T12:32:26.239Z"
```
