### ISSUE TITLE
The length of a duration in months is not 30 days.

### ISSUE THREAD

**Issue by connection-reset** [moment/moment#3653]
**Description of the Issue and Steps to Reproduce:**
Length of a duration in months is not 30 days like the docs state, same goes for years (365 days). [link to docs](http://momentjs.com/docs/#/durations/months/)
```js
> moment.version
'2.17.0'
> moment.duration({days: 30}).asMonths()
0.9856465225158627 // should be 1
> moment.duration({days: 365}).asYears()
0.9993360575508053 // should be 1
```

**Environment:**
Node.JS v7.2.1 on Arch Linux

**Comment by connection-reset** [comment]
Tests are inconsistent
[30 days is not 1 month](https://github.com/moment/moment/blob/develop/src/test/moment/duration.js#L421)
[1 month is 30 days](https://github.com/moment/moment/blob/develop/src/test/moment/duration.js#L484)
[1 month is 30 days, but 2 months is 61](https://github.com/moment/moment/blob/develop/src/test/moment/duration.js#L485)
[Tests not what it says it tests](https://github.com/moment/moment/blob/develop/src/test/moment/duration.js#L458)
[1 year is 365 days](https://github.com/moment/moment/blob/develop/src/test/moment/duration.js#L470)
[4 years is 1461 days](https://github.com/moment/moment/blob/develop/src/test/moment/duration.js#L473) because of leap year? Not mentioned in docs

**Comment by icambron** [comment]
cc @ichernev. I think you reworked this recently. I forget what decisions you made on it.

**Comment by ichernev** [comment]
The docs are wrong. We did a lot of rewriting, so that day->month->year mappings are more accurate for longer intervals. If you type in google how many days are in a month, it gives 30.4167, so we're using something similar.

If you give a large number of days and convert to years, it needs to be reasonably accurate (not off by years), and the current implementation is. Given that 30 days is not really a month, the fact that moment is a bit "inconsistent" from this perspective doesn't bother me. With time durations, the only thing that is certain, is that if you take a duration between two moments m1 and m2 -> d, and then add it to m1, you'll get m2 ;-)

I'll spend some time to update the docs.

**Comment by marwahaha** [comment]
I'm slightly biased towards symmetrical conversions.

**Comment by marwahaha** [comment]
related to https://github.com/moment/moment/issues/2688
related to https://github.com/moment/moment/issues/3209

**Comment by marwahaha** [comment]
This is a useful thread, but the docs are updated in [5966b024](https://github.com/moment/momentjs.com/commit/5966b024b3da8238eecd2af53db8af8884b6ee42) and [b61584472](https://github.com/moment/momentjs.com/commit/b61584472dfb4d20acc4ae1ec99f76788aece1b2)
