### ISSUE TITLE
npm package size vs. moment.min.js size

### ISSUE THREAD

**Issue by spflow** [moment/moment#3656]
I'm looking at 60kb for the minified moment file, but when I included it via npm package my bundle increased by hundreds of kb. Does that sound right? Just curious.
Thanks, moment is great!

**Comment by butterflyhug** [comment]
What are you using to build your bundle?

There's been a lot of discussion about large package sizes for webpack users, because the bundle pulls in all of our locales.  This has resulted in a conversation with the webpack team:  https://github.com/webpack/webpack/issues/3128

I don't think we've really heard much about this from folks using other bundlers.

In general, Moment's packaging code was written with the expectation that CommonJS modules are for Node, where ease of use has historically been more important than file size.

**Comment by spflow** [comment]
ah that makes sense! Yes, I'm using webpack as my bundler. I'll check out that thread, thanks for the response.

**Comment by maggiepint** [comment]
Closing as webpack concern.
