### ISSUE TITLE
Short months and days in current locale without trailing period

### ISSUE THREAD

**Issue by Tklaversma** [moment/moment#3662]
`moment.monthsShort()` returns an array of the months in short. But when the locale is for example Dutch, it will return an array of months in short **with a trailing period**.

How do I use `moment.monthsShort()` to get a list of the months in the current locale without any trailing dot (or any other character)?

The same goes for the days of the week.
`moment.weekdaysShort()` returns the days of the week in short in the current locale with a trailing period when the current local is Dutch.

The documentation said something about:
`moment.monthsShort('-MMM-')`
`moment.weekdaysShort('-DD-')`

But this isn't working...

Any idea? Hope you guys can help me out.

Regards,
TK

**Comment by antonama** [comment]
You could update locale using moment's built-in method **updateLocale** http://momentjs.com/docs/#/customization/month-abbreviations/

moment.updateLocale('nl', {
    monthsShort: moment.monthsShort('-MMM-')
});

**Comment by icambron** [comment]
The question of whether short months should have dots or not for various locales is a constant issue around here. The maintainers of those language files decided they always need them, never needthem, or need them in specific grammatical contexts and coded accordingly. For whether specific languages should or shouldn't have them, I'll let that debate happen on an individual locale level, so that it can involve Dutch experts. For the top-down question of whether we want to support a way of "degrammerizing" locales for the purposes of listing abbreviations, I can give a firm no for simple cost/benefit reasons.

So my recommendation is to list them and strip the periods with `map` and a regex.
