### ISSUE TITLE
Firefox not handling the same moment("2016-11-06 01") that the other browser

### ISSUE THREAD

**Issue by sebtardif-iso-ne** [moment/moment#3672]
Firefox: moment("2016-11-06 01") .format() == "2016-11-06T01:00:00-05:00"
Chrome: moment("2016-11-06 01") .format() ==  "2016-11-06T01:00:00-04:00"

Tested on Windows 7, with OS configured with Eastern TimeZone.

**Comment by mj1856** [comment]
Check your debug console output.  You will find a deprecation warning because it's falling-back to the `Date` constructor internally, and implementations of that vary across browsers.

Basically, choose one:

- Use a format moment understands without help, which are either the [Supported ISO 8601 Strings](http://momentjs.com/docs/#/parsing/string/), or the [ASP.NET JSON Date](http://momentjs.com/docs/#/parsing/asp-net-json-date/)

- Tell moment what format your input is in, using formatting tokens as the second parameter, [as described here](http://momentjs.com/docs/#/parsing/string-format/).

In this case, I'd choose:

```js
moment("2016-11-06 01", "YYYY-MM-DD HH")
```

**Comment by sebtardif-iso-ne** [comment]
Basically, both options doesn't work:
Extract from: http://momentjs.com/docs/#/parsing/string/ 

> Supported ISO 8601 strings
> A time part can also be included, separated from the date part by a space or a uppercase T.
> 2013-02-08 09

chrome: moment("2016-11-06 01", "YYYY-MM-DD HH").format() == "2016-11-06T01:00:00-04:00"
firefox: moment("2016-11-06 01", "YYYY-MM-DD HH").format() == "2016-11-06T01:00:00-05:00"

I also see no warning in both browsers.

**Comment by maggiepint** [comment]
Matt was quite correct in telling you to specify a format initially - the date you have is not valid ISO 8601 date as it omits minutes. Now that you have a format string you see no deprecation warning and from Moment's perspective everything is fine. 

That said, this is a DST transition date and time. The problem that you are now observing is that browsers do not agree on what to do with ambiguous times, so the result ant time of a parsed local time that occurs twice, like that one, varies across browsers. This is a nuanced topic, but it's explained fairly well on Matt's blog here: http://codeofmatt.com/2013/06/07/javascript-date-type-is-horribly-broken/
I also go over it in a talk here: https://www.youtube.com/watch?v=ieIzNP6gKqU (it's at 36 minutes in)

**Comment by sebtardif-iso-ne** [comment]
We all know javascript is broken, it was that fact making me starting to use moment.js. It seems I was expecting wrongly that moment.js would do like so many other libraries, to remove browser differences by handling the differences.

It's working better if I use the moment.tz. What I get from that use case, is that any software that may end-up dealing with a timezone having some kind of DST, should always use the moment.tz syntax.
