### ISSUE TITLE
moment(inputValue).parseZone() can't get hour with offset added

### ISSUE THREAD

**Issue by MooUser** [moment/moment#3739]
Hi everybody, 
i need help about using the parseZone method of moment.js.
As you can see in the title, i have _moment(inputValue).parseZone()_ , where inputValue is something like /Date(1485974700000+0100)/.  In this case, the Hour in inputValue is 19:45, but i need to return 20:45, so i apply parseZone(): that's fine until i try to get this "updated" Hour value, because the method format("HH:mm") returns always the original hour (19:45), instead of 20:45. 
How can i do to fix this and get Hour with the offset incorporated? 
Thanks for helping!

**Comment by icambron** [comment]
I'm not really clear on what you're trying to do, but I think you're misunderstanding a few things. For example, `Date(1485974700000+0100)` is just adding 100 ms to your time, not setting an offset. Also, 1485974700000 is 18:45 in UTC and 19:45 in +1:00, so I'm not sure where you're getting 20:45. `parseZone()` doesn't make much sense in combination with an epoch date and parsing an epoch time as if it were an expression of another zone's MS count doesn't work in Moment anyway. And finally, that would set the time to 17:45 anyway.

I'm going to close this because I don't understand it. You can reopen, but please fill out the relevant parts of the issue template we provide. For example, what zone are you in?
