### ISSUE TITLE
Probably incorrect zone parsing/display behavior

### ISSUE THREAD

**Issue by blackxored** [moment/moment#3756]
**Description of the Issue and Steps to Reproduce:**

1. Set timezone to America/Los_Angeles
2. Run `moment('1938-05-28T16:00:00.000-08:00').format()`
3. Incorrectly it seems, returns `1938-05-28T17:00:00-07:00`

**Environment:**

Existing project, brand new node project, jsbin, etc.

I would expect it to return the same ISO8601 string since I'm on that timezone.
The only way to fix this appears to be adding `moment-timezone` (which is a dep I don't need for anything else atm), and works like this:

`moment('1938-05-28T16:00:00.000-08:00').tz(moment.tz.guess()).format()`
correctly returns: `'1938-05-28T16:00:00-08:00'`

Why is this happening?

**Comment by icambron** [comment]
This should be in the [moment-timezone repository](https://github.com/moment/moment-timezone). But before you add it:

> I would expect it to return the same ISO8601 string since I'm on that timezone.

Well, kind of. In recent times America/Los_Angeles is in a UTC-7 DST in May and I'm sure that's the rule moment-timezone is applying. Perhaps DST wasn't observed in 1938 and moment-timezone just doesn't know that. I have no idea what the policy is there about historic stuff like that, but if it's not in the TZ database the plugin uses to generate the data, there probably isn't much to be done. So by all means ask there, but be aware of the context of your request.

**Comment by blackxored** [comment]
Does this mean that `moment-timezone` is required for this to have a chance to work properly? I'm sorry, I'm no expert in timezones but this seems like a bug in moment (or at least counter-intuitive) and adding an additional dep when I need no other timezone support seems cumbersome. 

It's not only about old dates, see:
```javascript
date = moment('2016-05-09T17:30:00-08:00').format() // "2016-05-09T18:30:00-07:00"
(new Date).getTimezoneOffset() // 480
date.toDate().getTimezoneOffset() // 420
```

**Comment by icambron** [comment]
When you say you've set your system to -8:00, are you really saying you've set it to UTC-8, or are you saying you've set it to America/Los_Angeles or similar?

**Comment by blackxored** [comment]
I've set to America/Los_Angeles. Other implementations confirm that this is -8:00 at the moment and behave as expected. Take a look at this ruby snippet (which ends up using ActiveSupport's timezone support) with the same date, in the same system, and with the same timezone:

``` ruby
2.4.0 (main):0 > require 'active_support/all'
2.4.0 (main):0 > Time.parse('2016-05-09T17:30:00-08:00').iso8601
=> "2016-05-09T17:30:00-08:00"
```

And I'd rule out browser behavior sine the previous snippet was run on node as well.

**Comment by icambron** [comment]
It's UTC-8 in Los Angeles *now*. But it is UTC-7 from March to September, which includes the date you're parsing. Think of it not as a library detail but as an actual fact: the ISO string you're providing unambiguously represents a specific instant in time. At that instant in time, the clocks in Los Angeles showed 18:30, not 17:30, and the offset was -7, not -8. If you give people PST times during PDT you're just off by an hour.

The Ruby in your example simply isn't converting the instant to a local time. You may also choose to do that in Moment using `parseZone`; it will keep the date in the offset you expect. But note that's the opposite of the behavior you implied you need, namely that the date be expressed in the zone your system is set to.

**Comment by blackxored** [comment]
Bare with me, this is obviously tricky for me.
Here's the issue, shouldn't moment (using local time) represent the current timezone (-08:00), even if it had to change the hour in that string?
> At that instant in time, the clocks in Los Angeles showed 18:30, not 17:30, and the offset was -7, not -8
Isn't the string specifically telling that the offset was 8? There's no mention of Los Angeles in those strings, just timezone offsets of sorts and it's giving -08:00 explicitly.

**Comment by icambron** [comment]
I think you've been conflating "the current offset in the local zone" and "the offset specified by the ISO string". I mean, they happen to both be -8 in your case, but let's assume they're not. You can represent an instant in time in any offset, so let's assume for a second that the string is actually "2016-05-09T16:30:00-09:00". Then we can separate out the cases of how Moment could interpret that.

Also, as some additional preamble, [zone != offset](https://spin.atomicobject.com/2016/07/06/time-zones-offsets/). I don't know if that is a genuine point of confusion for you or if it's just a matter of terminology.

So still assuming that your system is set to LA, here are the possibilities you're alternately suggesting:

 1. Moment could assume you're somewhere that's always in UTC-9, because the string says so. This isn't unreasonable, but it's not a local date; the fact that you're in SoCal no longer matters and your users are getting their dates formatted as if they lived in the middle of the Pacific. Regardless of the string's offset, it represents a specific, universal, and unambiguous instant in time and your zone has rules about how that time is rendered in hours and minutes. So there are two things agains this: a) it's not usually what anyone wants; there's a reason their location is set to LA: they want their dates expressed there. b) "UTC-9" doesn't tell Moment whether it needs to make any DST-adjustments when, say, adding a week to the current date. The zone would tell us that and it's the thing we're ignoring in favor of a simple offset. Nevertheless, it's a valid use case and that's why we have `parseZone`. Just keep in mind that the underlying time isn't what's in question--it's the same in either case--it's how the time is rendered and mathed, and that by using `parseZone` you're privileging some data in a string over the system's (and perhaps user's) preferences.

 2. Moment could apply UTC-8 even though the right local time is in UTC-7 because it's UTC-8 now. This behavior would be strange for a few reasons, the leading of which is that your code will have different results based on when you run it. What do you want this code to do in May? It shouldn't matter at all what the offset is *now*. To get a little abstract, the whole point of zones is that they're a function that maps a specific time to an offset. Not applying the zone's rules to the particular date is the same as ignoring the zone. If you really want this behavior, take the current offset (like `var o = moment().utcOffset()`) and apply it (`moment(yourStr).utcOffset(o)`). But in all the time I've been doing this stuff, I've never seen anyone do that.

What Moment does instead of either of those is to faithfully take the specified time (taking into account the offset in the string when computing it) and sets up the metadata to render it as the corresponding local time. This is a good default, I promise.
