### ISSUE TITLE
Cannot parse valid ISO 8601 date with a leap second

### ISSUE THREAD

**Issue by GeorgeSapkin** [moment/moment#3809]
**Description of the Issue and Steps to Reproduce:**

```js
moment('2016-12-31T23:59:60Z')
// moment.invalid(/* 2016-12-31T23:59:60Z */)

moment('2016-12-31T23:59:60Z', 'YYYY-MM-DDTHH:mm:ssZ')
// moment.invalid(/* 2016-12-31T23:59:60Z */)
```

This should be parsed correctly since this is a valid [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Times) date with a [leap second](https://en.wikipedia.org/wiki/Leap_second).

**Environment:**

Node.js v6.10.0
Moment v2.17.1

**References:**

ISO 8601:2004[E] section 2.2.2 leap second

**Comment by GeorgeSapkin** [comment]
Looks like Node.js `Date` cannot parse/handle leap seconds as well.

**Comment by maggiepint** [comment]
Yeah, because JS Date is unix time based, this issue goes all the way down the stack - it's inherent in ECMAScript. I'm a delegate to TC39, and I'm actually working to fix this, but obviously this is only a stage 0 proposal right now, so that's a long way down the road. 

In the mean time, I'm not sure if there's an appropriate solution to this problem. We can't exactly write validation code that accepts 60 in the seconds place as-appropriate, since leap seconds are intermittent. There would be no formula and we would have to manually add each one as it came - lots of weird stuff.

Do you have a solution to this problem that you think would be reasonable?

**Comment by icambron** [comment]
Right, we could make the parser accept this, but we couldn't represent the date after we did so:

```js
> new Date(1483228799000)
2016-12-31T23:59:59.000Z
> new Date(1483228799000 + 1000)
2017-01-01T00:00:00.000Z
```

I think the way it works is that the underlying system is responsible for making an abrupt time change later, such as repeating the first second of 2017. So the leap second is implemented as a break between the neat visible-to-JS timeline and reality. In theory, you could create a userspace library that knows when leap seconds happened or will happen and has its own representation of the date, and then does the appropriate work to translate things back into the JS non-leaped timeline, presumably by doing its own version of repeating seconds. Not only does that sound complicated, but it's very far from how Moment works or is likely to ever work. If JS is going to put its head in the sand about leap seconds, we're going to too.
