### ISSUE TITLE
1 January

### ISSUE THREAD

**Issue by alkoval** [moment/moment#3811]
Hello, when trying to get a date, it returns a different year depending on the format.
![screenshot_1632](https://cloud.githubusercontent.com/assets/14341571/23625237/4af2f3d2-02ca-11e7-9a9e-63e0b1abd554.png)

**Comment by TracyGJG** [comment]
This looks to me to be functioning as designed. By having GGGG in your format string you are asking for the Week Year to be returned, ans 1st January 2017 was in the last week of 2016. Without knowing exactly what you were after, I think the result you might have been expecting (2017) would require YYYY rather than GGGG in the format string.

**Comment by marwahaha** [comment]
I agree with @TracyGJG .

You can learn more about "week year" here:
https://en.wikipedia.org/wiki/ISO_week_date#Last_week

But probably you want the "YYYY" token: 
https://momentjs.com/docs/#/parsing/string-format/
