### ISSUE TITLE
React/Redux would throw A state mutation was detected

### ISSUE THREAD

**Issue by MihaMarkic** [moment/moment#3824]
**Description of the Issue and Steps to Reproduce:**

When assigning moment() to a state the second time (first the the stateVariable is undefined), react/redux would complain that 

>  Invariant Violation: A state mutation was detected between dispatches, in the path `stateVariable.momentVariable._locale._longDateFormat.l`. This may cause incorrect behavior. (http://redux.js.org/docs/Troubleshooting.html#never-mutate-reducer-arguments)

Where state is something like 
```
{
   stateVariable: { 
       momentVariable: {}
   }
}
```

I guess this exception is thrown by (develepoment time) redux-immutable-state-invariant.

*Please include the values of all variables used.*

**Environment:**
TypeScript 2.2, React 15.4.2, Redux 3.6.0, redux-immutable-state-invariant 1.2.4, Webpack 2.2.1,
Windows 10, Chrome 56, moment 2.17.1

**Comment by icambron** [comment]
So, I don't think we're likely to be able to help you, a) because it's so Redux-specific and b) because it lacks a reproduceable example. But here are some things you should know:

 1. Moment is mutable, so things like `moment.locale('en-gb')` actually mutate the object. This is something [we're working on](https://maggiepint.com/2016/07/16/immutability-its-happening/)

 2. The message, as I understand it, is that the Moment object mutated. Moment doesn't manage any execution on its own; it just does what you tell it. So it sounds like somewhere or another you really are holding on to a reference to the Moment variable in your state and mutating it, presumably by calling a method on it that mutates it. I'd track down where that is happening. Another way to handle that is to `clone()` the Moment before providing it to your state object.

Armed with that information, you might have more luck asking people with Redux experience on SO or elsewhere.

**Comment by MihaMarkic** [comment]
Just to make sure, moment() creates a new instance, right?
Perhaps Immutability checker checks on assigned moment instance and sees that locale() yields a new result or something and thinks it mutated.

**Comment by icambron** [comment]
> Just to make sure, moment() creates a new instance, right?

Correct

> Perhaps Immutability checker checks on assigned moment instance and sees that locale() yields a new result or something and thinks it mutated.

I don't think it, like, inspects the `locale()` function. It just looks at the object's state and notices that it's different now. I'm assuming a call to `locale()` is why though.
