### ISSUE TITLE
Parse strict with "ignore" characters?

### ISSUE THREAD

**Issue by glittle** [moment/moment#3831]
Is it possible to tell the strict parser to ignore certain characters by specifying an "ignore" placeholder in the format string?

This would allow something like this to work:

    moment('Feb 27 – Mar 12, 2017', 'MMM D _ _ _ YYYY', true);

If it is not currently possible, could it be added?

**Comment by icambron** [comment]
Not currently possible, no. Although I don't see it documented anywhere, we do support fixed ignore strings, like this:

```js
moment('Feb 27 yoddle, 2017', 'MMM D [yoddle], YYYY', true)
```

But there's no way to specify N characters or tokens. It seems unlikely that we ever will. I think it makes more sense to strip out your tokens with a regex before parsing, like this:

```js
> 'Feb 27 – Mar 12, 2017'.replace(/ – \w+ \d+/, ''); //=> 'Feb 27, 2017'
```

Since you're parsing in strict, you already know the format, so this kind of preprocessing should always be possible.
