### ISSUE TITLE
v2.18.0 may have a breaking change

### ISSUE THREAD

**Issue by ljharb** [moment/moment#3849]
Greenkeeper [warned](https://github.com/airbnb/react-dates/issues/381) us of `react-dates` breaking when moment is updated to v2.18.0.

When [pinned to v2.17.1](https://travis-ci.org/airbnb/react-dates/builds/212552663), tests pass.

I don't have time right now to investigate further, but whatever changed in v2.18.0 that caused this breakage, could you please revert and publish? The test failures imply it might be locale-related.

**Comment by butterflyhug** [comment]
Thanks for the heads-up!

It looks like your test failures are due to [v2.18.0's improvements](https://gist.github.com/ichernev/78920c5a1e419fb28c6e4546d1b7235c#locale-improvements) in the 'L' formats for the [Thai](https://github.com/moment/moment/pull/3695) and [Chinese](https://github.com/moment/moment/pull/3608) locales.  We generally do not consider locale data updates like this to be a major version breaking change.

IMO, most of the point of using the 'L' formats is that you're wanting to adopt improvements in our locale data, so I think it's strange that you're making such strict assertions about the exact string formats.  If you actually care about getting an exact set of localized strings in each locale (as implied by your test assertions), then IMO you should really be maintaining your own formatting strings for each locale.  Otherwise I'd suggest that you move away from expecting a particular set of exact localized strings in your tests.

**Comment by butterflyhug** [comment]
Closing since this doesn't seem to be an actual breaking change on our end.  Feel free to re-open this (or to file a new issue) if you uncover anything else in 2.18.0 that we need to investigate further.

**Comment by ljharb** [comment]
Interesting, OK - typically any observable change like this would be considered breaking. Thanks for clarifying your policy.

**Comment by ichernev** [comment]
More than half of all moment changes are locale "improvements". Saying that those are breaking is a bit extreme. If we just bumped the major with every single release everyone will be happy.

**Comment by butterflyhug** [comment]
Also, I'm not convinced that "typically any obsesrvable change **like this** would be considered breaking" (emphasis added).  Approximately zero other JS libraries are willing to maintain their own localization data -- most libraries that can generate localized strings use external data sources that may or may not be bundled with their library in certain distributions.  AFAICT, those libraries generally don't change their major version number every time somebody else changes the data that they depend upon, even if their generated strings change as a result.

**Comment by ljharb** [comment]
I haven't yet had a chance to investigate the failures, but it seems like some of them are actually fixing the ordering of month/day/year in some locales - these i'd consider a patch - but others cause dates that previously parsed in a locale to stop parsing as valid at all - and that's what i suspect i'd consider breaking.

**Comment by butterflyhug** [comment]
If you have examples of parse failures in your tests I'd be somewhat interested to see that -- I thought they were all formatting errors when I looked at your Travis output.

That said, does this mean that you're trying to parse with 'L'?  That isn't documented or supported -- that token is only intended for formatting, not parsing.

**Comment by ljharb** [comment]
Looking at #3608, I'm now pretty convinced this was a patch; sorry for the noise.

If we find a new parsing failure when fixing the tests I'll follow up here.

**Comment by butterflyhug** [comment]
Sounds good, thanks!
