### ISSUE TITLE
Difference with months is not calculated correctly 

### ISSUE THREAD

**Issue by heikkijuntunen** [moment/moment#3851]
According the Moment.js documentation moment#diff "is optimized to ensure that two months with the same date are always a whole number apart".

But if I compare moment 2017-03-01 with 2016-10-01 diff gives difference 4 months but it should be 5 months:

var FIRST_OF_OCTOBER = moment([2016, 9, 1]).utc();
var FIRST_OF_MARCH = moment([2017, 2, 1]).utc();

var diffBetweenOctoberAndMarch = FIRST_OF_MARCH.diff(FIRST_OF_OCTOBER, 'months');

here diffBetweenOctoberAndMarch gets value 4

I have created also JSFiddle for this: https://jsfiddle.net/heikkij/024b82o4/

Tested with Chrome Version 56.0.2924.87 (64-bit) on OSX and Firefox 51.0.1 (64-bit) on OSX

My laptop is in Eastern Europe Timezone

console.log( (new Date()).toString())
Mon Mar 20 2017 11:06:08 GMT+0200 (EET)

console.log((new Date()).toLocaleString())
20/03/2017, 11:06:08

console.log( (new Date()).getTimezoneOffset())
-120

console.log( navigator.userAgent)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

console.log(moment.version)
2.17.1

(tested also with 2.10.6 and it has same issue)

**Comment by icambron** [comment]
On my laptop (Chrome 58 in US EDT), that fiddle gives the right results. But here's why it's happening for you:

```js
moment([2016, 9, 1]).utc();
```

This does not mean `2016-10-01T00:00:00.000Z`. It means "take the local time and express it in UTC", so for you `2016-09-30T21:00:00.000Z`. Like this:

```js
-> TZ=Europe/Bucharest node
> var moment = require("moment")
> moment([2016, 9, 1]).utc().format();
"2016-09-30T21:00:00.000+00:00"
```

If I tell Moment not to round (using the third argument), you can see what's happening:

```js
moment("2017-02-28T22:00:00.000Z").diff("2016-09-30T21:00:00.000Z", "months", true)
4.9319444444444445
```

That's because those end-of-the-months dates, *as expressed in UTC*, aren't actually 5 months apart. So you would have been fine in local, or fine in UTC, but not when setting up the beginning of the month in the local zone and then converting them UTC. That isn't happening in my zone because I'm in a trailing offset so diff rounding down happens to give the right answer.

But at any rate I think what you really wanted was this:

```js
var FIRST_OF_OCTOBER = moment.utc([2016, 9, 1]);
var FIRST_OF_MARCH = moment.utc([2017, 2, 1]);
```

Those are actually the beginnings of those months in UTC.
