### ISSUE TITLE
React v15 upgrade branch using moment().format() would fail BDD test on Travis CI

### ISSUE THREAD

**Issue by jimmyzhen** [moment/moment#3861]
**Description of the Issue and Steps to Reproduce:**
*I previously reported this issue in the **moment** channel on **Gitter**. Although I've found a workaround, I still wish to understand the real cause of the issue.*

When upgrading ReactJS from v0.14 to v15 in our app, one particular Python BDD browser test had consistently failed on Travis CI (in both Chrome and Firefox), while this very same BDD test passed both locally and directly piped to Sauce Labs.

The assertion was to test a JavaScript functionality by passing a string value in a <input> element and expect it to invoke the onChange event handler. This assertion had no failures on Travis CI prior to the ReactJS v15 upgrade branch.

Eventually I’d found that the failing test was related to `moment` (well, together with React v15 and Travis CI). The instances of `moment(utc_date_string).format(‘YYYY MMM DD’)` appeared to be causing JavaScript to fail on Travis CI. Another unique thing about the failing test is that it only happened on pages in which `moment().format()` is used in a loop within the `render()` method, similar to the following:
```
render() {
  return (
    <div>
      {items.map(item => {
        <div>{item.status} - {moment(item.timestamp).format(‘YYYY MMM DD’)}</div>
      })}
    </div>
  );
}
```

We've had the code (similar to the above) in our app all along to display the local time in the UI, and it hasn't been an issue until now with the React v15 upgrade.

Purely for debugging attempts, the following would allow the test to pass on Travis CI:
1. Removed the instances of `moment(item.timestamp).format(‘YYYY MMM DD’)` in the loop.
2. Added `utc()` into `moment(item.timestamp).format(‘YYYY MMM DD’)`, such as `moment(item.timestamp).utc().format(‘YYYY MMM DD’)`.
3. Changed `moment(item.timestamp).format(‘YYYY MMM DD’)` to `JSON.stringify(moment(item.timestamp))`.

**The workaround**
I found this **stackoverflow** post (http://stackoverflow.com/questions/38251763/moment-js-to-convert-date-string-into-date) and had tried passing the date string into the `new Date(utc_date_string)` first and the passed it to `moment()`, such as the following:
```
render() {
  return (
    <div>
      {items.map(item => {
        let date = new Date(item.timestamp);
        <div>{item.status} - {moment(date).format(‘YYYY MMM DD’)}</div>
      })}
    </div>
  );
}
```

Unfortunately, the above attempt alone still didn't allow the BDD test to pass on Travis CI. So eventually, I took the date parsing and formatting out of the loop in the `render()` method and put them into a function which returns a JSON object for the `render()` method to consume. With that, the BDD test passed on Travis CI.

**Environment:**
React 15.4.2, moment 2.18, Node.JS 6.10.1, Python 3.4.2, Chrome 48, Chrome Driver 2.21, Linux 3.13, Ubuntu 12.04

**Other information:**
* Travis CI server runs on UTC.
* Example date string to be passed into `moment()`: `2015-05-04T08:11:18.000000+00:00`

**Comment by maggiepint** [comment]
Is the timestamp you are dealing with in ISO8601 format? If it isn't, then you could simply be getting different results for your formatted time depending on the browser.

**Comment by jimmyzhen** [comment]
Yes, the timestamp I am dealing with is in ISO 8601 format (see the **Example date string** I provided above under **Other information**).

The issue I was having problem with has nothing to do with the results of time formatting (if I am not mistaken). It has to do with calling the `moment(...).format(...)` in a loop when rendering the DOM. The result was seemingly some script error that prevented the event handler from being invoked in a BDD test on Travis CI.

**Comment by icambron** [comment]
This is hard to debug from where we're sitting. If I understand correctly, you're *not* actually suggesting that this...

```js
moment('2015-05-04T08:11:18.000000+00:00').format('YYYY MMM DD');
```

...returns the wrong string in your tests. That makes sense, because Moment does not know that it's being run by React, not to mention by a specific version being run by Travis. I think you're saying that there's some other, unspecified (or perhaps invisible?) error.

Now, I could guess: maybe React sets a timeout for each iteration of its loop and Travis is kind of slow, for example. But I don't know how I could do better than guess, because I don't have any special knowledge of React and because Moment is a comparatively simple library that is--as far as anyone can tell--not actually doing anything unexpected here.

I know nebulous things-aren't-working errors are frustrating, especially from fickle CI tools, but I don't see if how there's a path forward from Moment's end. If you *do* find a way in which Moment is misbehaving, I will be eager to know about it and help.
