### ISSUE TITLE
isoWeekday returns wrong day

### ISSUE THREAD

**Issue by nirvana74v** [moment/moment#3862]
isoWeekday doesn't reliably return weekday

Steps to reproduce:

Create a function in NodeJS application,
```javascript
function checkDay() {
        var fdate = moment().isoWeekday(3); // Returns Tuesday
        var fdt = fdate.tz("America/Winnipeg").format("MM-DD-YYYY");
        var dtStart = moment(fdt + " 17:00","MM-DD-YYYY HH:mm"); 
        var pastdate = moment().isoWeekday(6); // Returns Friday
        var pastdt = pastdate.tz("America/Winnipeg").format("MM-DD-YYYY");
        var dtEnd = moment(pastdt + " 23:59:59","MM-DD-YYYY HH:mm:ss");

        console.log(logTag + "Start Date :" + dtStart + " - End Date :" + dtEnd);
        console.log(JSON.stringify(data));
}
```
**Output on Server:** checkNextdate:Start Date :1490115600000 - End Date :1490486399000
{"start":"03-21-2017 17:00","end":"03-24-2017 23:59"}

**NodeJS:** v7.2.1

**OS:** Linux ip-172-31-43-97 4.4.30-32.54.amzn1.x86_64 #1 SMP Thu Nov 10 15:52:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Date executed:** 03/24/2017

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
*  - Sat Mar 25 2017 02:28:28 GMT+0000 (UTC)*
console.log((new Date()).toLocaleString())
*  - 3/25/2017, 2:28:28 AM*
console.log( (new Date()).getTimezoneOffset())
*  - 0*
console.log( navigator.userAgent)
* - NodeJS app so no value*
console.log(moment.version)
*- 2.18.1*
```

**Comment by icambron** [comment]
So, I don't totally understand what you expect that code to do, but here's some hopefully helpful stuff:

```js
>  moment().isoWeekday(3).isoWeekday()
3
>  moment().isoWeekday(6).isoWeekday()
6
```

So we know those work.

```js
       var fdate = moment().isoWeekday(3); 
       var fdt = fdate.tz("America/Winnipeg").format("MM-DD-YYYY");
       var dtStart = moment(fdt + " 17:00","MM-DD-YYYY HH:mm"); 
```

I don't know if this does what you think it does. Unless otherwise specified, values passed into the parser are interpreted as local time, in this case UTC. Remember that `dstStart` is just a string; it doesn't know it's in Winnipeg time. Thus neither does the parser.

So for example, let's say it's currently 2:00 in the morning UTC. You switch the day of the week Tuesday so now the time is 2:00 on Tuesday UTC.  In Winnipeg time that's 20:00  on Monday so your format string gives that date. Reparsing that date in UTC but with 17:00 tacked on that's 17:00 on Monday UTC, which is 11:00 on Monday in Winnipeg.

You didn't say what you were trying to do, but my guess is that's not it. In general, using the parser to set the time will lead to mistakes. If I were guessing what you were trying to do, I'd say something like this:

```js
var start = moment()
  .tz("America/Winnipeg")
  .isoWeekday(3)
  .hour(17)
  .minute(0)
  .second(0)
  .millisecond(0);
var end = moment()
  .tz("America/Winnipeg")
  .isoWeekday(6)
  .endOf('day');
```

If that's not what you were trying to do, @ me with your specific expectations for the return values of specific calls to Moment and I will reopen the issue.
