### ISSUE TITLE
Cannot resolve 'file' or 'directory' ./locale

### ISSUE THREAD

**Issue by unix112** [moment/moment#3864]
**Description of the Issue and Steps to Reproduce:**
`
WARNING in ./\~/.2.13.0@moment/min/moment.min.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./locale in /Users/hero/git/kibana-5.2/node_modules/.2.13.0@moment/min
     @ ./\~/.2.13.0@moment/min/moment.min.js 6:3763-3785
`
*Please include the values of all variables used.*

**Environment:**
mac os, node 6.9.0

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by icambron** [comment]
These aren't steps to reproduce. Moment works for most people most of the time, so simply pasting the error doesn't tell me the unique--or at least unusual--circumstances that lead to your error. You need to provide information that allows me to reproduce your error on my computer so that I can help determine what went wrong.
