### ISSUE TITLE
Moment date parsing is incorrect when using custom format "ddd MMM DD YYYY H:mm:ss GMTZ"

### ISSUE THREAD

**Issue by idanb11** [moment/moment#3870]
I'm using moment and moment-parseformat (strict mode) in Node.js environment

steps to reproduce:
```
var x = "Thu Feb 04 2016 16:14:40 GMT+0700";
var format = parseFormat(x);
console.log(moment(x,[format],true).format());
```
executing the following will produce the error: ` Invalid date `

my environment :
```
console.log( (new Date()).toString())
Tue Mar 28 2017 16:32:48 GMT+0700 (SE Asia Standard Time)
console.log((new Date()).toLocaleString())
3/28/2017, 4:32:48 PM
console.log( (new Date()).getTimezoneOffset())
-420
```

Thanks,

**Comment by icambron** [comment]
I'm not sure how to follow those steps to reproduce. Can you replace `parseFormat(x)` with its return value?

**Comment by idanb11** [comment]
This is the output of parseFormat(x) - `ddd MMM DD YYYY H:mm:ss GMTZ`

It is very easy to reproduce it, 
create a new file with this content:

```
var moment = require('moment');
var parseFormat = require('moment-parseformat');

var x = "Thu Feb 04 2016 16:14:40 GMT+0700";
var format = parseFormat(x);
console.log(format);
console.log(moment(x,[format],true).format());
```

and run this in the terminal after changing directory to the same folder where the above content reside: 
- `$ sudo npm install  moment moment-parseformat`

**Comment by idanb11** [comment]
I would expect that running this will work and not produce `Invalid date`

**Comment by icambron** [comment]
The parsing format is incorrect. "GMT" is a literal, not a series of tokens (G = ISO week year, M=month, T = ?), so it can't parse that. It's often helpful to use `parsingFlags` to see what went wrong:

```js
moment(x, "ddd MMM DD YYYY H:mm:ss GMTZ", true).parsingFlags()
```

Anyway, changing the format to this works:

```js
moment(x, "ddd MMM DD YYYY H:mm:ss [GMT]Z", true).isValid() // => true
```

It sounds like there might be a bug in the moment-parseformat plugin that causes it to return the wrong string? I'm pretty unfamiliar with how it works or what guarantees it makes, which is why I wanted to cut it out of the steps to reproduce. I recommend filing a ticket [there](https://github.com/gr2m/moment-parseformat).
