### ISSUE TITLE
object parsing auto adjusting?

### ISSUE THREAD

**Issue by c0b** [moment/moment#3881]
the Date support to construct a Date when input is out of range,

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
> Parameters
> Note: Where Date is called as a constructor with more than one argument, if values are greater than their logical range (e.g. 13 is provided as the month value or 70 for the minute value), the adjacent value will be adjusted. E.g. new Date(2013, 13, 1) is equivalent to new Date(2014, 1, 1), both create a date for 2014-02-01 (note that the month is 0-based). Similarly for other values: new Date(2013, 2, 1, 0, 70) is equivalent to new Date(2013, 2, 1, 1, 10) which both create a date for 2013-03-01T01:10:00.

but momentjs' Object parsing syntax seems not supporting that, `moment.utc({minute:-1})` gives invalid date, however, I found the set interface support that auto adjusting, so a workaround is to constructor a valid date first, and set with the out of range values

```js
> moment.utc({minute:-1}).toDate()
Invalid Date
> moment.utc().set({minute:-1}).toDate()
2017-04-03T04:59:37.643Z
> moment.utc({minute:0}).set({minute:-1}).toDate()
2017-04-02T23:59:00.000Z
> moment.utc({minute:0}).set({millisecond:-1}).toDate()
2017-04-02T23:59:59.999Z
> moment.version
'2.18.1'
```

in NodeJS v6.

**Comment by icambron** [comment]
Yeah, Moment doesn't support that, since a lot of times Moment is being used to validate user input and that kind of "wrapping" behavior is unexpected. It's a reasonable thing to disagree about, but it seems like the current behavior (creation doesn't support it but `set()` does) is a good compromise. At any rate, it seems unlikely that we'll change this.
