### ISSUE TITLE
Cannot use a locale defined with parent

### ISSUE THREAD

**Issue by vincent-tr** [moment/moment#3883]
**Description of the Issue and Steps to Reproduce:**

```
const moment = require('moment');

moment.defineLocale('absoluta', {
  parentLocale : 'fr',
  monthsShort  : ['Jan', 'Fev', 'Mar', 'Avr', 'Mai', 'Jui', 'Jul', 'Aou', 'Sep', 'Oct', 'Nov', 'Dec']
});

// unset globally set locale
moment.locale(false);

// uncomment to fix
// moment.localeData('fr');

console.log(moment('08:00:00 01/Avr/17', 'HH:mm:ss DD/MMM/YY', 'absoluta'));
```

This code is throwing the follwing exception:

```
TypeError: Cannot read property 'preparse' of null
    at prepareConfig (.../node_modules/moment/moment.js:2518:43)
    at createFromConfig (.../node_modules/moment/moment.js:2497:40)
    at createLocalOrUTC (.../node_modules/moment/moment.js:2584:12)
    at createLocal (.../node_modules/moment/moment.js:2588:12)
    at hooks (.../node_modules/moment/moment.js:16:25)
    at Object.<anonymous> (.../bin/moment-test.js:13:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

If I uncomment the line `moment.localeData('fr');`, it seems to be fixed.

**Environment:**
Moment 2.18.1
NodeJS 7.7.4 on OSX

**Comment by maggiepint** [comment]
The following code just ran totally fine for me in chrome console on momentjs.com:
```js
moment.defineLocale('absoluta', {
  parentLocale : 'fr',
  monthsShort  : ['Jan', 'Fev', 'Mar', 'Avr', 'Mai', 'Jui', 'Jul', 'Aou', 'Sep', 'Oct', 'Nov', 'Dec']
});
moment.locale(false);
moment('08:00:00 01/Avr/17', 'HH:mm:ss DD/MMM/YY', 'absoluta').format('MMM')
```
The only thing I can think is that you don't have the french locale loaded. If that's the case, parenting to it won't work. If you're using a default node.js configuration though, I can't see why that would happen. We load all locales by default in node.

**Comment by vincent-tr** [comment]
I have a "standard" nodejs installation, from brew on osx.
Let me know how to provide more information about that.

**Comment by icambron** [comment]
Yeah, I can reproduce this in Node. It must be that we're failing to lazy load in the parent lang in Node. I don't remember quite how that stuff works, so I'm not sure where the bug and fix would be exactly, though.

**Comment by cmyers** [comment]
Currently looking at this as it's similar to #3626 which I've submitted a PR for. defineLocale returns null if the parent locale is not found. A potential fix would be to lazy load the locale if the parent locale can't be found (see referenced commit). However, this would still fail with the same error this bug details if the parent locale doesn't exist.

If the parent locale can't be found, localeFamilies is populated which would be later used to define further locales, but returns null before this occurs. Given this, would some further handling be required if a parent locale can't found/loaded? Currently studying the logic around locale loading, so may revisit with further commits, or if the fix is sufficient I can submit a PR.
