### ISSUE TITLE
2 tests failed. create:parsing RFC 2822 (2642.7) create:parsing RFC 2822 (2642.8) 

### ISSUE THREAD

**Issue by FCGF** [moment/moment#3886]
### Client info
```
Date String   : Tue Apr 04 2017 09:41:10 GMT-0300 (Hora oficial do Brasil)
Locale String : 04/04/2017 09:41:10
Offset        : 180
User Agent    : Mozilla/5.0 (Windows NT 10.0; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Moment Version: 2.18.1
```

====

### create:parsing RFC 2822 (2642.7) 

Invalid date

```javascript
// Expected true
// Actual   false
false === true
```

====

### create:parsing RFC 2822 (2642.8) 

NaN - rfc2822 parsingFlag

```javascript
// Expected true
// Actual   false
false === true
```

**Comment by TracyGJG** [comment]
I have attempted to reproduce the issues but failed. My unit tests all pass, which means I am not running the tests under the same circumstances as @FCGF. I have been running the tests against 2.18.1 development, is this correct. I think I require more information in order to reproduce the fault please.

**Comment by VictoriqueMoe** [comment]
I am encountering the same problem on the test page. However i used Edge 

`2 tests failed. create:parsing RFC 2822 (2642.7) create:parsing RFC 2822 (2642.8) `
`### Client info
```
Date String   : Fri Jun 09 2017 14:10:17 GMT+0100 (GMT Summer Time)
Locale String : ‎09‎/‎06‎/‎2017‎ ‎02‎:‎10‎:‎17‎ ‎PM
Offset        : -60
User Agent    : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
Moment Version: 2.18.1
```

====

### create:parsing RFC 2822 (2642.7) 

Invalid date

```javascript
// Expected true
// Actual   false
false === true
```

====

### create:parsing RFC 2822 (2642.8) 

NaN - rfc2822 parsingFlag

```javascript
// Expected true
// Actual   false
false === true
````

This passed for both Chrome and Firefox in my environment.

I am using Windows 10  (Version 1703 Build 15063.332) the latest possible at the time or writing this.

This issue occurs every time 

I am using Microsoft Edge version 40.15063.0.0

Hope this helps ☺ :)

**Comment by TracyGJG** [comment]
Can you please document how you went about testing, not just the results. I am sure you have found an issue but as i am unable to reproduce the conditions, discovering the cause is very difficult.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: VictoriqueMoe <notifications@github.com> Date: 09/06/2017  14:17  (GMT+00:00) To: moment/moment <moment@noreply.github.com> Cc: TGJ Gilmore <tracyg.gilmore@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [moment/moment] 2 tests failed. create:parsing RFC 2822 (2642.7) create:parsing RFC 2822 (2642.8) (#3886) 
I am encountering the same problem on the test page. However i used Edge
2 tests failed. create:parsing RFC 2822 (2642.7) create:parsing RFC 2822 (2642.8)

`### Client info
Date String   : Fri Jun 09 2017 14:10:17 GMT+0100 (GMT Summer Time)
Locale String : ‎09‎/‎06‎/‎2017‎ ‎02‎:‎10‎:‎17‎ ‎PM
Offset        : -60
User Agent    : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
Moment Version: 2.18.1

====
create:parsing RFC 2822 (2642.7)
Invalid date
// Expected true
// Actual   false
false === true
====
create:parsing RFC 2822 (2642.8)
NaN - rfc2822 parsingFlag
// Expected true
// Actual   false
false === true
This passed for both Chrome and Firefox in my environment.
I am using Windows 10  (Version 1703 Build 15063.332) the latest possible at the time or writing this.
This issue occurs every time
I am using Microsoft Edge version 40.15063.0.0
Hope this helps ☺ :)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/moment/moment","title":"moment/moment","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/moment/moment"}},"updates":{"snippets":[{"icon":"PERSON","message":"@VictoriqueMoe in #3886: I am encountering the same problem on the test page. However i used Edge \r\n\r\n`2 tests failed. create:parsing RFC 2822 (2642.7) create:parsing RFC 2822 (2642.8) `\r\n`### Client info\r\n```\r\nDate String   : Fri Jun 09 2017 14:10:17 GMT+0100 (GMT Summer Time)\r\nLocale String : ‎09‎/‎06‎/‎2017‎ ‎02‎:‎10‎:‎17‎ ‎PM\r\nOffset        : -60\r\nUser Agent    : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063\r\nMoment Version: 2.18.1\r\n```\r\n\r\n====\r\n\r\n### create:parsing RFC 2822 (2642.7) \r\n\r\nInvalid date\r\n\r\n```javascript\r\n// Expected true\r\n// Actual   false\r\nfalse === true\r\n```\r\n\r\n====\r\n\r\n### create:parsing RFC 2822 (2642.8) \r\n\r\nNaN - rfc2822 parsingFlag\r\n\r\n```javascript\r\n// Expected true\r\n// Actual   false\r\nfalse === true\r\n````\r\n\r\nThis passed for both Chrome and Firefox in my environment.\r\n\r\nI am using Windows 10  (Version 1703 Build 15063.332) the latest possible at the time or writing this.\r\n\r\nThis issue occurs every time \r\n\r\nI am using Microsoft Edge version 40.15063.0.0\r\n\r\nHope this helps ☺ :)"}],"action":{"name":"View Issue","url":"https://github.com/moment/moment/issues/3886#issuecomment-307385728"}}}

**Comment by pangratz** [comment]
I've stumbled over this just now, basically with the `Microsoft Edge on Win10 (x64) Stable (15.15063)` VM downloaded at https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/.

After I added it to VirtualBox, I ran the tests on http://momentjs.com/tests/ and the 2 failing tests appeared. I hope that helps. The client info:

### Client info
```
Date String   : Mon Jul 03 2017 07:19:34 GMT-0700 (Pacific Daylight Time)
Locale String : ‎7‎/‎3‎/‎2017‎ ‎7‎:‎19‎:‎34‎ ‎AM
Offset        : 420
User Agent    : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
Moment Version: 2.18.1
```

**Comment by TracyGJG** [comment]
Thank you @pangratz for the additional information. I have not found the fault yet but I have managed to reproduce it, which is half the battle. There is something odd here in that it is fine on V8 (Chrome and Node) but fails on IE11 and Edge. Thank you to all who provided input to this issue; I will continue to investigate the cause.

**Comment by TracyGJG** [comment]
I have a candidate solution but my repo is out of date and has a pending PR. The change needs to be made only to the moment/src/lib/create/from-string.js file in the _configFromRFC2822_ function.

The lines 123-126:


    if (match) {

        dayFormat = match[1] ? 'ddd' + ((match[1].length === 5) ? ', ' : ' ') : '';

        dateFormat = 'D MMM ' + ((match[2].length > 10) ? 'YYYY ' : 'YY ');

        timeFormat = 'HH:mm' + (match[4] ? ':ss' : '');


need to be replaced with the following.


    if (match) {

        dayFormat = match[1] ? 'ddd' + ((match[1].length === 5) ? ', ' : ' ') : '';

        dateFormat = 'D MMM YYYY ';

        timeFormat = 'HH:mm' + (match[4] ? ':ss' : '');

        if (match[2].length <= 10) {

          var dateLength = match[2].length - 3;

          var expandYear = parseInt(match[2].substr(dateLength,2), 10);
	            
          var preYear = match[2].substr(0,dateLength);

          expandYear += (expandYear < 50) ? 2000 : 1900;

          match[2] = preYear + expandYear + ' ';

          config._i = match.slice(1).join('');

        }


The approach expands the 2-digit year to a 4-digit year using the approach stipulated by section 4.3 of the specification. The existing test cases are sufficient but you can never have too many.

We could add the following to the suite of 'parsing RFC 2822' test cases:

	'clean RFC2822 datetime without century, single digit DoM': 'Tue, 1 Nov 16 04:23:45 Z',

	'clean RFC2822 datetime with century, single digit DoM': 'Tue, 1 Nov 2016 04:23:45 Z',

**Comment by TracyGJG** [comment]
Candidate solution submitted under Pull Request #4065.

**Comment by marwahaha** [comment]
@TracyGJG - what was the solution here?

**Comment by TracyGJG** [comment]
See the comments on the PR. The problem was that IE/Edge consider some 2-digit years invalid. Solution is to trap 2DYs and convert them to 4DY.

**Comment by marwahaha** [comment]
Please re-open if folks still have issues.
