### ISSUE TITLE
Ambiguous two letter months accepted as valid

### ISSUE THREAD

**Issue by CJDennis** [moment/moment#3892]
```
moment("5 Ma 2017").isValid() // True (5 May 2017)
moment("5 Ju 2017").isValid() // True (5 July 2017)
```

"Ma" could be either March or May. "Ju" could be either June or July. All two-letter moths should be invalid in English.

Moment 2.18.1

**Comment by maggiepint** [comment]
Right now, you are getting a warning in the console that says 'Moment construction falls back to JS date'. Because you are not specifying a format, you are instead bypassing the parser for moment and using the notoriously unreliable browser built in one. Moment's parser doesn't support two letter months at all. Instead, your code should read:
```js
moment("5 Ma 2017", 'DD MMM YYYY').isValid() //false
```
