### ISSUE TITLE
Wrong language code for Serbian language

### ISSUE THREAD

**Issue by vlada-j** [moment/moment#3899]
We use wrong language code for Serbian cyrillic and Serbian latin. SR is by default cyrillic, not latin
Currently:
sr-cyrl  ->  Serbian cyrillic
sr         ->  Serbian latin

Correct codes:
sr  ->  Serbian  (cyrillic)
sh  -> Serbo-Croatian (latin)

Source: [w3schools](https://www.w3schools.com/tags/ref_language_codes.asp)

Please can someone confirm or correct.
Thanks

**Comment by darkgnostic** [comment]
There is no such a code as sh. Serbo-Croatian language doesn't exist. However, default Serbian code is Cyrillic.

**Comment by mj1856** [comment]
Like most other languages and platforms, we have adopted [IETF Language Tags](https://en.wikipedia.org/wiki/IETF_language_tag), as defined by [bcp47](https://tools.ietf.org/html/bcp47).

Language tags can be made up of several parts, each covered by their own standard.

`sr` is the correct language code, defined by ISO639.  We prefer two-letter 639-1 codes, but will use three-letter codes from 639-2 when there isn't an appropriate two-letter code.

`sh` *used* to reference "Serbo-Croatian", but it was deprecated in year 2000.  Refer to the comments in [the changes list here](https://www.loc.gov/standards/iso639-2/php/code_changes.php).

`cyrl` is the correct *script* tag for Cyrillic.  Script tags are defined by ISO15924.  Unicode has a good list of them [here](http://unicode.org/iso15924/iso15924-codes.html).

`latn` would be the script tag for Latin script, making `sr-latn` and `sr-cyrl` the two variants of Serbian.  However, the use of script tags is entirely optional in bcp47, and Moment requires we choose some default to use when we only have the language.  The developer who implemented these in Moment chose the Latin script as the default, so that's what we have.

[This article](http://symbolcodes.tlt.psu.edu/bylanguage/serbocroatian.html) is pretty interesting on this subject.  Section 5 covers the variants in the language tags.

**Comment by mj1856** [comment]
Also - W3Schools is not the best reference, IMHO.  Always seek out something more authoritative.
