### ISSUE TITLE
moment("MM/DD/YY") returns different results in Chrome/IE

### ISSUE THREAD

**Issue by adamstevencotner** [moment/moment#3901]
**Description of the Issue and Steps to Reproduce:**
Using `moment("MM/DD/YY")` sometimes produces different results in IE/Edge and Chrome/Firefox. Namely, the `moment` created in IE may refer to `"MM/DD/19YY"` while Chrome produces a `moment` referring to `"MM/DD/20YY"`

*Please include the values of all variables used.*
The date string I used to produce this inconsistency was `"04/29/17"`
IE/Edge created a moment referring to April 29, 1917.
Chrome created a moment referring to April 29, 2017.

**Environment:**
IE11/Windows 7, Edge/Windows 10, Chrome56/Windows 10, Firefox(?)/Windows 7

**Other information that may be helpful:**
* Using `moment 2.15.1` with `react 15.3.2`
* Javascript `new Date("04/29/17")` refers to April 29, 2017 in all browsers

**Comment by maggiepint** [comment]
You are getting a deprecation warning in the console that says 'moment construction falls back to JS date' and gives a link to the docs. The reason you are experiencing this problem is because you aren't specifying the format you are using, and the format is not ISO8601, so the date constructor can do whatever it wants with it. In order for Moment to control the behavior, you need to specify a format:

```js
moment('04/29/2017', 'MM/DD/YYYY')
```
