### ISSUE TITLE
Abbreviation of longDateFormat in actual language

### ISSUE THREAD

**Issue by darkgnostic** [moment/moment#3903]
Question:

Is there a possibility to update a locale date format to reflect the actual language set?

Like for 'de' locale instead of DD.MM.YYYY for a long format to use TT.MM.JJJJ?

I can use:

```js
moment.updateLocale('en-gb', { longDateFormat: { L: 'DD/MM/YYYY' } });
moment.updateLocale('de', { longDateFormat: { L: 'TT.MM.JJJJ' } });
moment.updateLocale('es', { longDateFormat: { L: 'DD/MM/AAAA' } });
```
which works as it should. Is there any function that will do this automatically (as I don't know all abbreviation for a year, month and day).

Also there is a bug in code above. If you use code as:

```js
moment.locale('de');
moment.updateLocale('en-gb', { longDateFormat: { L: 'DD/MM/YYYY' } });
moment.updateLocale('de', { longDateFormat: { L: 'TT.MM.JJJJ' } });
moment.updateLocale('es', { longDateFormat: { L: 'DD/MM/AAAA' } });
```

moment()._locale._longDateFormat.L will always return last set format. In example above it will be DD/MM/AAAA even is locale is 'de'.

If I put moment.locale('de') AFTER last call to updateLocale, everything is fine.

**Environment:**

 Chrome 57.0.29871222 on Windows 10

**Comment by icambron** [comment]
The easy part first:

> moment()._locale._longDateFormat.L will always return last set format

Try this:

```js
moment.localeData('de')._longDateFormat.L
```

Now for the hard part: I don't understand what you're trying to do. The point of `longDateFormat` is to provide Moment with locale-specific ways of formatting and parsing long dates. Like this:

```js
moment().locale('en').format('L'); //=> "04/11/2017"
moment().locale('en-gb').format('L'); //=> "11/04/2017"
moment().locale('de').format('L'); //=> "11.04.2017"
```

IOW, the following means "in England, they format dates as like DD/MM/YYYY":

```js
moment.updateLocale('en-gb', { longDateFormat: { L: 'DD/MM/YYYY' } });
```

So you can't specify tokens Moment doesn't understand. If you do, you get this:

```js
moment.updateLocale('de', { longDateFormat: { L: 'TT.MM.JJJJ' } });
moment().locale('de').format('L'); //=> "TT.04.JJJJ"
```

because Moment has no idea what T and J mean. I guess you're trying to use it as some way to provide users with documentation about expect formats? But that's not what it's for and you'll just break Moment doing that.

**Comment by darkgnostic** [comment]
I see.

I have used longDateFormat to put one placeholder text in input field, for user to know what kind of format page expects. Moreover that text was translated to locale's language, but I see now that it is a dead end.

Thank you for clarifying it to me.
