### ISSUE TITLE
moment().toObject() returns incorrect month number

### ISSUE THREAD

**Issue by TotallyInformation** [moment/moment#3910]
```
var moment = require('moment-timezone')
var mDT = moment()
console.dir(mDT.toObject())
console.dir(mDT.toJSON())
console.dir(mDT.toISOString())
```
returns:
```
{ years: 2017,
  months: 3,
  date: 13,
  hours: 11,
  minutes: 1,
  seconds: 24,
  milliseconds: 820 }
'2017-04-13T10:01:24.820Z'
'2017-04-13T10:01:24.820Z'
```
which is wrong because the "months" entry should be 4 right now and not 3.

In other words all the outputs are 1-based except for "months" which is 0-based.

Version installed: moment@2.18.0
Platforms: Linux and Windows

Also note that the toJSON() output also seems wrong or at least it doesn't match the documentation which suggests it should return:

```
{ postDate: '2017-04-13T10:01:24.820Z' }
```

**Comment by butterflyhug** [comment]
Months are intentionally 0-indexed to be consistent with the native JS `Date` object.  http://momentjs.com/docs/#/get-set/month/

The toJSON example with `postDate` in the docs is explicitly adding that `postDate` wrapper, because it is intended to show how a moment instance will be serialized by `JSON.stringify` when the moment is a property of a larger object.  If this could be clearer, feel free to submit a documentation update PR.

Feel free to tag me on a reply if you still have concerns.

**Comment by tandrewnichols** [comment]
@butterflyhug I mentioned this in another thread, but I wasn't sure where it would actually get traction. Is there _any possible way_ of convincing the moment team to make month 1 indexed? I understand that it's 0-indexed in the native JS Date object, but I think everyone who has ever used Date objects would agree that that was a design flaw. There's no reason moment can smooth that over and make dates more predictable/logically. Part of the reason people use moment is so they _don't have to use Date objects_. No one _ever_ in the history of humanity has wanted a 0-indexed month. It just doesn't make sense. (Meaning literally _every_ person calling `momentInstance.month()` is immediately adding 1 to the returned result.)

**Comment by donnyv** [comment]
I can't believe its going to be 2023 and month is still zero based. We use moment because its a utility to fix things like this.
