### ISSUE TITLE
formating the datetime with moment.format is returning an hour short every time.

### ISSUE THREAD

**Issue by rizwanh12** [moment/moment#3926]
formating the datetime with moment.format is returning an hour short every time.

var sd = moment(event.start).format('DD-MM-YYYY HH:mm');

Thu May 04 2017 07:00:00 GMT+0100 (GMT Daylight Time) returns "04-05-2017 06:00"

//! moment.js
 //! version : 2.13.0
window 7
GMT time zone.
All the date and times are displayed fine only when I use format method it subtracts an hour from the time ever time. 
 any suggestion?

thanks

**Comment by rizwanh12** [comment]
Any comments please?

**Comment by icambron** [comment]
It looks like it's working to me. You're in GMT. The time is specified in GMT+1. So your zone it's 6:00, not 7:00. It would be weird if the offset were simply ignored. Some notes:

 * Moment actually doesn't know how to parse that string and it's just passing it to the native Date constructor. That's a deprecated fallthrough.
 * That also means that Moment has no access to the offset specified in the string. Normally, when people run into the dates-specified-in-other-offsets-but-converted-to-local issue, I recommend they look at Moment's `parseZone` method, but in this case that wouldn't help because Moment isn't doing the parsing.
 * If you a) know ahead of time that the string is in GMT+1, b) really do want to parse that string using the native constructor, and c) are sure you want to keep the time in that zone after instantiating it, the easiest thing to do is to just convert it after parsing.
 * Since I don't know what your use case is, I'll just say that my most general advice is: 1) parse and format in ISO-8601, not in the format JS's `toString()` puts it in. 2) Unless you're using Moment Timezone, avoid working with local times in other zones unless you have to (i.e. do what you did: convert it to your timezone and work with it there). 3) If you really do need to work with the time in an offset-aware way, use `parseZone()` to adopt the offset specified in 8601 string.

If the whole issue still confuses you, consider what happens here. No Moment at all and in US Eastern time:

```js
var d = new Date("Thu May 04 2017 07:00:00 GMT+0100 (GMT Daylight Time)");
d; //=> Thu May 04 2017 02:00:00 GMT-0400 (Eastern Daylight Time)
d.getTimezoneOffset(); //=> 240
```
