### ISSUE TITLE
Feature request add custom units

### ISSUE THREAD

**Issue by Guibod** [moment/moment#3929]
As stated in #3582 and #1998, Moment maintainers don't want to support exotic unit of times. That's ok.

I can't help but wonder how someone can extend the current set of known units without forking the whole project. `normalizeUnits` is the method used to achieve that, how can I alter this function behavior safely ? Is there a way to override its default behavior ?

**Comment by icambron** [comment]
I totally understand why you'd want this kind of extensibility, but I think we'd have a really really hard time supporting that kind of patching without some serious engineering. The set of supported units isn't really cleanly coded in one place; that's because there's some subtlety to working with units of non-fixed size and that subtlety shows up in lots of places.

I'll let the rest of the team comment, but my take is basically, sorry, won't do

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
