### ISSUE TITLE
Moment does not parse input string "2014-08-27T09:40:36:857-0600" consistently

### ISSUE THREAD

**Issue by bhovhannes** [moment/moment#3931]
**Description:**
I am trying to parse string `2014-08-27T09:40:36:857-0600` using moment constructor.
In moment version 2.15.2 constructor was returning a valid moment object (`isValid()=true`).
In moment version 2.18.1 constructor returns invalid moment object (`isValid()=false`).

As it is breaking change and major version of moment is the same, I assume that this can be a bug.

Version 2.15.2 is the last version which returns a valid moment object for input string `2014-08-27T09:40:36:857-0600`.

Here is [fiddle](https://jsfiddle.net/hbabayan/02m7e2c9/) demonstrating the difference. In case fiddle will not be available, here is the shorter code demonstrating issue.

```js
requirejs.config({
    paths: {
        'moment-2-15-2': 'https://unpkg.com/moment@2.15.2/moment',
        'moment-2-18-1': 'https://unpkg.com/moment@2.18.1/moment'
    }
})

requirejs(['moment-2-15-2', 'moment-2-18-1'], function(moment1, moment2) {
    var input = '2014-08-27T09:40:36:857-0600'

    var m1 = moment1(input)
    console.log( m1.isValid() )    // true

    var m2 = moment2(input)
    console.log( m2.isValid() )    // false
})
```

**Environment:**
Chrome 58.0.3029.81 (64-bit) on OSX

```js
console.log( (new Date()).toString()) 
// Output: Thu Apr 27 2017 15:56:52 GMT+0400 (AMT)

console.log((new Date()).toLocaleString()) 
// Output: 4/27/2017, 3:56:52 PM

console.log( (new Date()).getTimezoneOffset()) 
// Output: -240

console.log( navigator.userAgent)
// Output: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
```

**Comment by icambron** [comment]
It was a bug that it was valid before. The spec allows for a comma or a dot to delimit the decimal part. Moment supports those but colons aren't in the spec so your string should be invalid. Note that the older version of Moment you have doesn't actually do what you want anyway:

```js
console.log(moment1(input).milliseconds()) //=> 0
console.log(moment1(input).format()) //=> 2014-08-27T09:40:36-04:00
```

What's really happening is that the older Moment is ignoring everything from the colon onward, which means it doesn't see the milliseconds and it ignores the offset, (-4:00 is my computer's local offset, the default). That's just buggy, so we fixed it to tell you that your invalid string is invalid instead of parsing it incorrectly.

**Comment by bhovhannes** [comment]
@icambron thanks for clarification!
