### ISSUE TITLE
weeksInYear() calculates for the year() instead of the weekYear()

### ISSUE THREAD

**Issue by xehpuk** [moment/moment#3942]
**Description of the Issue and Steps to Reproduce:**

In Germany, the year 2015 has 53 weeks while 2016 has 52 weeks.
The 01/01/2016 lies within the 53rd week of 2015. `year()`, `weekYear()` and `week()` all return the expected numbers. But `weeksInYear()` returns 52 (possibly the number of weeks in 2016) instead of 53.

```js
import moment from 'moment'

moment.locale('de')

const date = moment('2016-01-01')

date.year() // 2016
date.weekYear() // 2015
date.week() // 53
date.weeksInYear() // 52; expected: 53

// Workaround:
date.startOf('week').weeksInYear() // 53
```
https://jsfiddle.net/ugy5hmaw/

**Environment:**

Chrome 57, Firefox 52 and Edge 38 on Windows 10

**Other information that may be helpful:**

```
Tue May 02 2017 21:08:56 GMT+0200 (Mitteleuropäische Sommerzeit)
2.5.2017, 21:08:56
-120
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
2.18.1
```

**Comment by icambron** [comment]
> possibly the number of weeks in 2016

Yes, that's what it's doing. See the code [here](https://github.com/moment/moment/blob/497f918515ae6ab900f008f19523b1e4ae5e2450/src/lib/units/week-year.js#L81) and notice it calls `year()` instead of `weekYear`. This probably isn't really a bug; it's more like a very confusing API. 

I do think it would be more useful for it to mean "weeks in this week year" but we'd potentially break a lot of code. @ichernev @maggiepint what do you think? Perhaps we need to (sigh) add `weeksInWeekYear()`? The ISO one has the same problem.

**Comment by xehpuk** [comment]
It's at the very least extremely surprising that `week()` returns 53 while `weeksInYear()` returns 52.

**Comment by icambron** [comment]
I agree
