### ISSUE TITLE
constructor with "Week of Year (ISO)" identifier produces wrong date

### ISSUE THREAD

**Issue by vobujs** [moment/moment#3965]
**Description of the Issue and Steps to Reproduce:**
```javascript
var from = moment("2017-01-01T08:00:00", "YYYY-[W]WWZ");
var to = moment("2017-01-09T08:00:00", "YYYY-[W]WWZ");
console.log(to.diff(from, 'weeks'));
// 0
```
whereas the expected diff would be `1`.

inspecting `from` and `to` also shows:
```javascript
from: 
   _d = Mon Jan 02 2017 02:00:00 GMT+0100 (CET)
to: 
   _d = Mon Jan 02 2017 10:00:00 GMT+0100 (CET)
```
which seems off.

**Environment:**
MomentJS 2.18.1 *with locales* minified version

macOS 10.12.4 with
- Chrome 58.0.3029.110 (64-bit) 
- Safari 10.1 (12603.1.30.0.34)
- node 7.7.1 

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
Tue May 16 2017 23:09:00 GMT+0200 (CEST)

console.log((new Date()).toLocaleString())
2017-5-16 23:09:00

console.log( (new Date()).getTimezoneOffset())
-120

console.log( navigator.userAgent)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

console.log(moment.version)
2.18.1
```

**Comment by icambron** [comment]
This is a combination of things:

1. Your input string looks nothing like the parsing format you're providing. `"2017-01-01T08:00:00"` vs `"YYYY-[W]WWZ"`.
2. Moment's parser is very forgiving in trying to figure out how to fit that string into that format, but its exact degrees of freedom in doing so aren't well-defined. That's why we encourage people to use strict parsing by adding an additional `true` argument which will tell you that Moment can't perfectly match the string to the format.. We'll eventually deprecate and then remove forgiving parsing altogether. So try this: `moment("2017-01-01T08:00:00", "YYYY-[W]WWZ", true).isValid() //=> false`, because the input string doesn't match the format. As it is, you're getting Moment's best guess.
 3. `2017-01-01T08:00:00` *is* a valid ISO-formatted date but assuming it's `YYYY-MM-DDTHH:mm:ss`. If that's what you mean, you can actually just sick Moment on it directly: `moment('2017-01-01T08:00:00')`. I'm going to assume for the remainder that's now what you're going for.
 4. You should use GGGG instead of YYYY with WW because ISO week years are different from Gregorian calendar years.
 5. As far as I know `GGGG-[W]WWZ` is not a valid ISO format because you can't follow the week number directly with an offset. That's totally fine and why we have the parser that takes arbitrary tokens in the first place, but since it's *close* to a valid ISO formats like `GGGG-[W]WW-EZ` or `GGGG-[W]WW` that Moment could just parse without a format string, I thought I'd point it out.
 6. The format you did provide (assuming we replaced the Ys with Gs) would be fulfilled by something like these:

```js
moment("2017-W03Z", "GGGG-[W]03Z", true).isValid() //=> true
moment("2017-W03+06:00", "GGGG-[W]03Z", true).isValid() //=> true
```

**Comment by vobujs** [comment]
thanks a ton for taking the time to go through this in so much well-explained detail!
