### ISSUE TITLE
Support Moment Development / Maintainers

### ISSUE THREAD

**Issue by rockerest** [moment/moment#3979]
I like to show support for projects that I love, and it doesn't seem like Moment is set up to accept donations.

Are there any plans to get Moment on something like https://opencollective.com so those of us who want to see Moment succeed but are mind-boggled by DateTimes can show support?

For something like Open Collective, I think all it requires is a loose concept of "team" and then you can start accepting backers and using funds transparently. If a few backers could help core maintainers go to meetups, speak at conferences, etc., Moment could do even more great work with wider reach and more community input.

*How can I give you my dollars?*

**Comment by maggiepint** [comment]
Hi,

First, I want to thank you a ton for your desire to keep Moment going. We love the library and the value it brings to the JavaScript community, and we're glad you love it too.

It is a unanimous decision of Moment's core contributor team to not take funding, and it has been for quite some time. Since I previously worked full time in the open source policy space, and I continue to be a specialist in the business of open source, I wanted to be the person to give a complete explanation of this choice.

The main reason we don't take funds is pretty simple. Our maintainers team is comprised completely of gainfully employed software developers. A few of us work for big 5 tech companies, others for VCd startups, and others at smaller employers. At the end of the day though, this is a good industry to be in and none of us are hurting for cash. 

In addition, we do not need money coming directly into the project to run it. Our membership in the JS Foundation provides us with legal protection, web hosting, some marketing, and some conference budget. It even provides for me to go to TC39 to champion changes in the spec. There isn't really anything else the project itself needs.

What we are hurting for though, is time. Time with our families, time for vacation from github issues, time to pursue open source passions other than Moment. The money from open collective would mostly likely not be enough of a revenue stream for us to be able to quit our day jobs and get back this time. It would be beer money, or vacation money, but not much more.

To get our time back, we need our employers, and the employers of others, to step up to the plate and allow employees to contribute on company time. We believe projects like Open Collective hurt this argument. When a corporations hear that developers are paid to work on open source projects, then they assume that they do not have an obligation to contribute to the community. Instead, expectations rise (we're being paid after all), without any additional time being allocated. What was once a joy becomes a second job.

We know many open collective project maintainers personally, and we think they're all excellent people with wonderful ideas. The problem of maintainer burnout that they are trying to solve is very real, and we commend them in their attempt to fix. If open collective manages to create a substantial change in corporate culture that causes maintainers to get their time back, we will join. Until then though, we will continue to be unpaid, and continue to pressure our employers and all corporations to be active contributors to the community.

Our biggest ask is for more people with the time and energy to contribute, and more employers willing to contribute back the changes they wish to have. Everything from major code changes to stack overflow answers helps move our project forward. 

Any financial gifts that someone wishes to make can be directed to the wonderful team at <a href="https://js.foundation/about/donate">JS Foundation</a> to help them continue to provide the level of support they currently do.

Again, thank you for your support.

The Moment.js core contributors

**Comment by rockerest** [comment]
Thank you for the thoughtful response, and the perspective I had not considered.

I'll do my best to support the JS foundation and Moment in other ways!

Closing here as I consider this question answered.

**Comment by matthewdordal** [comment]
I know this comment is closed but I found the website https://opensourcefriday.com/ to be really helpful for encouraging employers to give employees some company time to contribute back to the open source projects that they use. I've had success convincing my employer to allow employees to spend Friday mornings contributing to the open source projects we rely on in order to try and help the maintainers of the projects.

I wanted to share this here as it could be another avenue for people who are looking for ways to contribute to open source projects.
