### ISSUE TITLE
import the specific methods that I use

### ISSUE THREAD

**Issue by ikzjfr0** [moment/moment#3984]
does moment allow us to  isolate imports so we only import the specific methods that you use? The background of asking this question is I'm trying to reduce bundle size in my project

**Comment by marwahaha** [comment]
At this time, we don't have a way to split out functions out of the project. You can take core moment without the locales. Because many parts are interconnected, we're having trouble modularizing the codebase. If someone wants to take a crack at it, do try!

I'm going to close this issue in favor of https://github.com/moment/moment/issues/2373
