### ISSUE TITLE
"Invalid date" for RFC 2822 date time format, if changing locale

### ISSUE THREAD

**Issue by cravler** [moment/moment#3985]
Starting from version 1.18, for some locales, proper RFC 2822 date time format shows like "Invalid date"

**Steps to Reproduce:**

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment-with-locales.js"></script>
<script>
    var dateRFC2822 = 'Mon, 06 Mar 2017 21:22:23 +0000';
    var locales = moment.locales();
    for (var index in locales) {
        var locale = locales[index];
        moment.locale(locale);
        console.log(locale + ': ' + moment(dateRFC2822).fromNow());
    }
</script>
```

JS Bin: http://jsbin.com/wepokowuro/edit?html,console,output

**Comment by icambron** [comment]
I suspect this is a bug with the parser trying to use the locale when parsing the months.

cc @TracyGJG

**Comment by TracyGJG** [comment]
@icambron supplying the RFC2822 parser with anything other than English will most likely result in an invalid date message as the standard is mono-lingual. I can only think I need to force the local to English before parsing but does that seem to be a reasonable approach - seems to me to be a little too brute-force.

**Comment by icambron** [comment]
@TracyGJG Right, we should definitely only accept what the spec says, and the spec uses English abbreviations. I also think it's incorrect to set the date on the whole object, since after it's parsed, the resulting Moment object should still be in whatever locale it was supposed to be. The problem is that Moment's parsing machinery inherits the locale and in this specific case, we don't want it to.

A couple of ideas:

 1. Add a new field to `config` that overrides the locale *but only for parsing*. Then the only change to the 2822 code is to set that to English. The downside is that it will require more mucking with Moment's internals.
 2. Actually parse the date in the 2822 function and just pass Moment year/month/day/etc as an array. This is my preferred approach; it seems to me that the RFC parser is already doing enough work to just know the date without having to reuse Moment's parser further. Here's a [completely separate implementation](https://github.com/icambron/luxon/blob/master/src/impl/regexParser.js#L210) of a 2822 parser that uses that approach (its contract is to return a JS object like `{year: 2017, month: 5 ... }` but conceptually it's the same as constructing an array directly and providing it to Moment's `configFromArray`).

I'm not sure which one is an easier path to fixing this though.

**Comment by TracyGJG** [comment]
@icambron, Is there any design documentation that will enable me to understand how moment is assembled? I do not want to start tinkering around in the works (I could be here all year) but I feel I do not know enough about how moment works to formulate a potential solution. This also makes it very difficult to understand the options you proposed and how I apply them.

**Comment by Petrukha** [comment]
Actually I've created a PR #4077 and implemented it directly in from-string.js. The implementation from luxon taken as the basis. Can you please have a look?

**Comment by icambron** [comment]
@TracyGJG Unfortunately, no such docs exist and in general Moment's internals are messier than we'd like them.

@Petrukha That looks like the right direction  to me. I left some comments.
