### ISSUE TITLE
Doesn't read hour correctly on some days?

### ISSUE THREAD

**Issue by theshadow124** [moment/moment#3992]
Hello All,

I am using momentjs to verify date formats on the client side before uploading data to our server(where it is then checked again), but we have found some dates will result in an invalid time being read from the string.

One such example is in the JSfiddle bellow:

http://jsfiddle.net/7jz9oa3e/3/

I have not been able to find a solution, so I am posting here in hopes of it being an obscure problem that it can be fixed.

**Comment by icambron** [comment]
Not a bug - that's the DST change. The example you gave reproduces in my timezone (America/New_York), but it would be different hours in other timezones in the US, and even different days in different countries.

```js
moment("2017-03-12 02:00:00 AM","Y-MM-DD hh:mm:ss a").format() //=> "2017-03-12T03:00:00-04:00"
```

That time does not exist due to daylight saving; on that day, the tick after 1:59:59.999, the clock was advanced to 3:00. You can read more [here](https://www.timeanddate.com/time/change/usa/new-york). DST is confusing and lame, but it's how the world works.

You can see it in the native Date API too:

```js
new Date('2017-03-12T02:00:00').toString()
"Sun Mar 12 2017 03:00:00 GMT-0400 (Eastern Daylight Time)"
```
