### ISSUE TITLE
Inconsistent behaviour of 'endOf' together with utc()

### ISSUE THREAD

**Issue by eBerdnA** [moment/moment#4000]
**Description of the Issue and Steps to Reproduce:**

I'm trying to get the end/start dates including time for weeks. The time should be handled as UTC. For this I'm running the following to get the end date.

    var weekNo = 22;
    var end;
    var pastWeek = moment().isoWeeks(weekNo);
    console.log(pastWeek.endOf('day').utc());
    end = pastWeek.endOf('W').utc();
    console.log(end);

Unfortunately this results in the following output:

    moment.utc("2017-06-01T21:59:59.999+00:00")
    moment.utc("2017-06-04T23:59:59.999+00:00")

From my point of view the time for both moments should be equal which is not the case.

**Environment:**

*Node.JS 7.9.0 on Windows 8.1*

**Other information that may be helpful:**
* TZ is Berlin
* 08.06.2017 16:40

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log(moment.version)
```

Output:

    Thu Jun 08 2017 16:40:55 GMT+0200 (Mitteleuropäische Sommerzeit)
    2017-6-8 16:40:55
    -120
    2.18.1

**Comment by icambron** [comment]
There are a few problems here:

 1. If you want the end of the day *as on a UTC clock* you need to switch the Moment to UTC before asking it to the find the end of the day. Otherwise it's taking the local end of the day and then converting that time to UTC. That's why the first one is off by Berlin's offset; it's the end of the day in Berlin, but *as expressed* in UTC. I think you meant `pastWeek.utc().endOf('day')`. (If I misunderstood you when you said "handled as UTC" then ignore this point, but the next item will still throw you off, so read that one carefully.)
 2. `endOf()` and `utc()` are mutators. I think this is a bad feature of Moment (one we're planning to change soon), but it is how Moment works. Thus `console.log(pastWeek.endOf('day').utc())` is actually modifying `pastWeek`. Thus going into the next line, `pastWeek` is already in UTC "mode" so `endOf('W')` does that operation in UTC, and then gives a correct end-of-the-day time for UTC. So in conjunction, 1 & 2 explain why you end up with different time components. You can call `clone()`.
 3. The `isoWeek` setter sets the date to the current time and--importantly--the current day of the week in the target ISO week number. June 8 is Thursday, so on June 8, calling `moment().isoWeek(22)` makes it Thursday on ISO week 22. That's not the end of the week, so of course going to the end of the week gives you a different date than just going to the end of that day. So even besides the other two issues, you can't expect those Moment's to be equal; they can still be different *date* components.
