### ISSUE TITLE
Last day of year is in week 1 for some years

### ISSUE THREAD

**Issue by hdon** [moment/moment#4019]
**Description of the Issue and Steps to Reproduce:**

```
moment('2017-12-31T00:00:00').get('week')
1
moment('2016-12-31T00:00:00').get('week')
53
moment('2015-12-31T00:00:00').get('week')
1
moment('2014-12-31T00:00:00').get('week')
1
moment('2013-12-31T00:00:00').get('week')
1
moment('2012-12-31T00:00:00').get('week')
1
moment('2011-12-31T00:00:00').get('week')
53
```

*Please include the values of all variables used.*

**Environment:**

Using Chromium 58.0.3029.110 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

Just visit https://momentjs.com/docs/ and open your console and use the version of moment that is there. Apologies if this is actually a bug that has been fixed but hasn't been deployed to the website yet!

My timezone is America/Los_Angeles or PDT

If you are reporting an issue, please run the following code in the environment you are using and include the output (I pasted it into the same inspector window where I produced the first part of my report):
```
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

VM240:1 Thu Jun 15 2017 12:15:47 GMT-0700 (PDT)
VM240:2 6/15/2017, 12:15:47 PM
VM240:3 420
VM240:4 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36
VM240:5 2.18.1
```

**Comment by brlodi** [comment]
This looks accurate per how the US (your locale) numbers weeks, that is the Sunday-Saturday week containing January 1 is week 1 of that year (documented [here](https://momentjs.com/docs/#/get-set/week/)). This doesn't come up in human-to-human interaction much because it's allowed to overlap with the definition for the last week of the previous year, which is the Sunday-Sunday week containing December 31.

For example, based on US week numbering, the week of 12/30/2012–01/05/2013 is both the last week of 2012 and the first week of 2013. Since for storage purposes the computer has to pick one it opts for week 1 of 2013 (I suspect because that's more in line with ISO week numbering). If we check the "week year" we see that 12/31/2012 does in fact fall in the first week of 2013.

```js
moment('2012-12-31T00:00:00').week()
1
moment('2012-12-31T00:00:00').weekYear()
2013
```

You might be interested in the [ISO week](https://momentjs.com/docs/#/get-set/iso-week/) instead, although that will also usually have December 31 falling within the first week of the following year.

**Comment by icambron** [comment]
@brlodi is correct

**Comment by hdon** [comment]
One day, I'll encounter my last timekeeping-related surprise...

Maybe the docs could be updated to state this result more clearly:

> For example, in the United States, Sunday is the first day of the week. The week with January 1st in it is the first week of the year, **including days in the previous year.**

(Emphasis on the proposed addition.)

My application is mapping time intervals to a visual calendar, and this surprise slowed me down.
