### ISSUE TITLE
isBefore returns a different outcome when it is referenced through a variable.

### ISSUE THREAD

**Issue by jrdegroot** [moment/moment#4022]
When a moment is compared to null through a reference it returns an unexpected outcome.

`moment().isBefore(null) -> false `  which is expected in my opinion.

When moment() is assigned to a variable m for instance, isBefore(null) returns true.

```
var m = moment()
m.isBefore(null) -> true
``` 

isSame and isAfter are working correctly
```
moment().isSame(null)  -> false
m.isSame(null) -> false
moment().isAfter(null) -> false
m.isAfter(null) -> false
```

**Comment by haxxxton** [comment]
This appears not to be happening for me on OSX 10.12.5 Chrome 58.0.3029 with moment@2.18.1

**Comment by jrdegroot** [comment]
I've discovered this on Windows 7 with Chrome 58.0.3029 and moment 2.18.1.

**Comment by icambron** [comment]
`isBefore(undefined)` returning true sometimes is expected behavior; not passing an argument is the same as comparing it to now, which may or may not be the same millisecond as your variable. That's also why it's so much easier to reproduce with a variable in a console; it's not about the variable, it's about the time between the moments. See #2697 where we discuss if `moment.isBefore()` using an implicit *now* is desirable behavior.

The `null` case would be a bug, but I can't reproduce it. Looking at the [code](https://github.com/moment/moment/blob/497f918515ae6ab900f008f19523b1e4ae5e2450/src/lib/moment/compare.js#L19) it doesn't seem possible. Granted, I haven't actually tried it in Windows, but since `moment(null).isValid()` returns false, it seems pretty airtight that `moment().isBefore(null)` will return false.

So, if you have further questions about `undefined`, see the other ticket. If you really are sure you're getting `m.isBefore(null)` to return true on the latest Moment, some debugging is in order.
