### ISSUE TITLE
Webpack bundling causing ALL locales to get included

### ISSUE THREAD

**Issue by Andarist** [moment/moment#4025]
https://github.com/moment/moment/blob/b8a7fc310eb3625e83fc0c8f1ea2840fa83c7378/src/lib/locale/locales.js#L55

This line is effectively causing webpack to load ALL locales, thus making bundle quite big by default. 

Webpack would understand if we could make this if a dead path, but as we want to achieve a node detection + dynamic imports I dont know how to tackle this. Any ideas?

**Comment by Andarist** [comment]
It can be solved by a webpack users with https://webpack.js.org/plugins/context-replacement-plugin/

This should be included in moment's docs at least, but anyway it should be explored if anything can be done in moment's code to solve this once and for all.

**Comment by icambron** [comment]
We eventually need to solve to use Babel/Rollup too, but it's been a while since I looked into it. In the meantime, we'd certainly accept a PR to the doc site showing how to use that plugin.

**Comment by ovangle** [comment]
@icambron 

If someone was looking to propose and implement a solution for lazy loading of locales in moment that:

 - worked seamlessly in all module loaders; and
 - allowed you to to export the ES6 `moment.js` by default
 - improved modularity of moment in general.

at the expense of:

 - some small backwards incompatible changes in the locales API (making it async); and
 - requiring a polyfill for the [ES Module Loader] spec.

then how likely would such a proposal be at kicking off a `3.0-develop` branch of this repo?

**Comment by ovangle** [comment]
Actually, could I go one better and say only one thing needs to be changed.

If a locale is not loaded, don't try to load it.

```
    /* src/lib/locale/locales */
    function loadLocale(name) {
      return locales[name];
   }
```

It's not much trouble for a user to just import the locales they want somewhere in their project so they're available statically.

    /* myapp.locales.js */
    // Just side effect imports, to define the locales
    import 'moment/locales/fr.js'
    import 'moment/locales/en-uk.js'
    /* etc */

It's possible to provide a helper class for people to lazy load locales in their own apps.

    /* 
     * asynchronously load the locale from 'moment/modules/name'
     * requires moment.enableLazyLoading
     */
    moment.loadLocale(name) ;

    moment.enableLazyLoading(moduleLoader: ModuleLoader) {}

and that shouldn't be too hard to implement. It would even be possible to make the module loader load from the `modules` directory locales that shouldn't exist.

     //  my-app.ts
    moment.defineLocale('my-custom-app', myConfig);

 Then from your module loader, you would be able to load from `moment/locales/my-custom-app` even though it did't exist in your locales directory.

**Comment by ovangle** [comment]
I was pretty tired when I wrote all that. 

Basically, the problem is that you're trying to do an inherently asynchronous action (import a file that you aren't sure whether exists) in a synchronous way. There's no way to rewrite that `loadLocale` function in a way that works consistently across environments.

My initial thought was that you need to just make the whole locale API async, which means that you'd use locales like

     
     function getLocaleFromUserEnvironment(): Promise<Locale>;
    
     getLocaleFromUserEnvironment().then(locale => {
       // All usage of moment within this async context will be locale specific
       const moment = locale.moment;
     });

But then I realised that in order to support this style, you'd have to do away with globally available locales. A `Moment`s locale would always be one of:

  - The locale of the default `moment(args)` factory, which is always `'en'`.
  - The `moment.locale($locale)(args)` factory used to construct it
  - The `moment._locale` of the moment which it was cloned from.
  
The only real consequence of this change is that `moment().locale(string)` would cease to work. If you needed to change the locale of a moment instance using the locale name, you'd need to call `moment().switchLocale(string)` which would return a promise, to be completed after the context had been loaded.

The only users who are still left out in the cold by these changes would be those that prefer working outside the `en` locale all together. 

This `localeDefault` setter would accept a string locale and return synchronously, but would throw if the locale was not statically available, so somewhere in your 'main.js' you'd have to add

   // Make sure my-default-locale is statically available
    import  'moment/locale/my-default-locale'
    import moment from 'moment';

    moment.localeDefault('my-default-locale');

    // Now moment() will return a moment in 'my-default-locale'
    console.log(moment().format("dddd, MMMM Do YYYY, h:mm:ss a"));



However, my problem is that there's a big red flag in the guidelines for contributing to this repo saying "DON'T SUGGEST ES6 FEATURES PLS (<small>except modules are OK</small>)", so it would all have to be written using callbacks in a new part of the API surface area that is targeting an ES@next feature.

The alternative to all this is to just drop the dynamic call to require immediately and tell users to make their locales available statically, which is the only breaking change you'll need in the short term, then hold off on developing the lazy loading functionality until the project is comfortable with exposing a `Promise` based public API.

**Comment by ichernev** [comment]
Having a sync and async API makes some sense. About ES6 "features" -- doing it with a callback is good enough, you can always wrap it in a future if you want that.

But then -- you have to "fill in" the actual fetching, so it makes little sense. There already is API to ask which locales are loaded, so a plugin that fetches a locale if its not there and provides an async API makes sense (I'm just saying there is no support in core you need, we could make this plugin "standard" if it existed). The only problem left is our Node.js code that does "require", which, if it goes away will break it for all Node users, so webpack people should suggest a way to require on node that doesn't also bring it as a dependency.

**Comment by ovangle** [comment]
Dropping the call to `require` will not break anything on node, it will just require node users to import all the locale modules statically. Since you're running on a server, it doesn't matter if you import everything statically, you're not worried about download overheads or lazy loading.

So the answer is to just include a 'moment/locales/all.js' module, which would be

    import 'moment/locales/af.js';
    import 'moment/locales/ar.js';
    /* etc */

and to tell node users to import that file once somewhere in their application, if they want access to locales.

The problem with webpack, rollup et.al. is that they need to be pessimistic about dynamic calls to `require`. Once it analyses your code and sees `require('moment/locale' + name)`, then they have to to assume that that call could resolve to _any_ of the files in the locale folder, thus including them for every page.

So if nothing else comes out of my rants, that call to `require` needs to go.

But after spending some more time today iterating on the changes I have been making locally in order to better support all the environments your library needs to deploy into, I've come up with the following list of changes that I'd like to make:

- Required locale configurations must be imported statically by the user, `loadModule` will throw by default if the requested locale is not found.
- `loadModule` should be exported by moment as `moment.loadModule`
-  Support for `getLocale(obj)` is removed (replaced by loadModule), `getLocale()` returns the current locale context.
- `defineLocale` and `updateLocale` should never mutate the current locale (already deprecated)
- `moment.lang` should be dropped entirely (already deprecated)
- `moment.locale(name)` should return an entirely new object which is (almost) a complete copy of the `moment' default export, with exported functions being aware of their locale context.

The net effect of these changes is to:

- Get rid of the global locale entirely, the locale is now owned by whichever `moment` object you are currently using.
- Improve support for seamlessly using the moment library across build environments
- Pave a road towards *properly* supporting lazy loading of locales in a 3.1 or 3.2 release.

Let me know what you think...

**Comment by Andarist** [comment]
@ovangle
Thats pretty much the same conclusion ive came to in recent days. Providing a dedicated export for node users who need it its truth to be told the only way we could follow without breaking to much for them to provide a much better experience for the big share of web users.

**Comment by ovangle** [comment]
You already supply a dedicated export for that purpose as `moment-with-locales.js`. However, that's broken for different reasons -- namely `package.json` doesn't provide an option for conditionally loading `moment-with-locales` as the package main if you're running in node afaik. If it does, it's not well supported.

So the solution that supports all environments equally is to finally kill off the part of `defineLocale` that sets the global locale. That way, files in the locales folder can be imported purely for their side effects (registering the locale) and node users can use the same `moment.js` as everyone else, they'll just have to add a single import of `import 'moment/locales/_all.js'` (which can be easily auto generated by your build process) at the top of their `main.js` before they start using any locales except `'en'`.

There are no ES6 features necessary in the `3.0` changes that I've listed at the bottom of my last post. As I said, all that work can be deferred until a `3.x` release where you're finally prepared to start supporting ES6 features.

At that point, and if all the breaking changes I've proposed for 3.0 are implemented, then you'll be able to add the following feature without breaking anything for anyone:

### moment.enableLazyLoading(moduleLoader)

Enables lazy loading for locales. `moduleLoader` is any object conforming to the following interface:

    // The module loader interface as proposed by WHATWG
    interface Loader {
         import(path: string): Promise<ModuleNamespace>;
    }

After the module loader has been set for the first time, calls to `moment.loadLocale(name)` will return a `Promise` which completes once the locale is available for use within moment. All other locale based methods remain synchronous and operate on the set of currently loaded locales.

**Comment by maggiepint** [comment]
@ovangle I haven't spent enough time with the code thinking through your arguments to be sure your plan would work. That said, if you're sure it would work, I am personally fine with the breaking changes.

**Comment by ovangle** [comment]
Sounds good, so a PR for the deprecations against develop and a separate PR for the breaks against 3.0? 

----

Sorry for the flurry of activity from somebody you've never heard before btw. I'm on "holidays" at the moment and was spending some time on a personal project when I had to dive into my `node_modules` folder for the umpteenth time to manually "fix" moment (bad practice but it works), so I'm here now... 

This was the only change I really _needed_ to make, but I'm here now so I'd suggest you make use of me if there's anything you want done while I have some spare time and am interested in doing it (not looking to get into the hairy mess that is the actual date manipulation which you guys are much better than me at, but general issues like improving your bundle size) :)

**Comment by ovangle** [comment]
Hey again, sorry I haven't submitted PRs yet, decided I'm actually going to enjoy my holiday... But I got around to doing some work on it tonight, creating a PR that deprecates the appropriate functionality.

As mentioned above, part of this is change the function `defineLocale` so that it doesn't mutate the current locale, so that locales can be imported predictably. I think this behaviour should instead be treated as a bug and changed without deprecation. It makes no sense, except to make unit tests "easier" to write and the behaviour is not likely to be relied upon in code outside your test environment.

Consider the code:

    moment.locale('en');
    import 'moment/locale/fr';
    // Might print 'fr', might print 'en', depending on how this file was included in `main`.
    console.log(moment.locale());

So should I just fix the functionality and the test suite? Or do you want it properly deprecated?

See #3977 for a potentially related bug.

**Comment by JamesJGoodwin** [comment]
Any ideas on how to fix this? I think, by default moment should load only `en` locale and other locales may be also imported as

`import moment, { locale.kr } from 'moment'`

**Comment by marwahaha** [comment]
I'm open to suggestions here, even if it is just some documentation changes.

It is challenging to maintain open-source code for long periods of time without burning out. Many people have contributed to this library and I thank you for that.

**Comment by dmishh** [comment]
This worked for me
```
      // Moment.js is an extremely popular library that bundles large locale files
      // by default due to how Webpack interprets its code. This is a practical
      // solution that requires the user to opt into importing specific locales.
      // https://github.com/jmblog/how-to-optimize-momentjs-with-webpack
      // You can remove this if you don't use Moment.js:
      new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
```

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
