### ISSUE TITLE
on IE8 , indexOf not defined

### ISSUE THREAD

**Issue by eleven777** [moment/moment#4043]
on IE8 , indexOf not defined;

code 782~797,this

if (Array.prototype.indexOf) {
    indexOf = Array.prototype.indexOf;
} else {
    indexOf = function (o) {
        // I know
        var i;
        for (i = 0; i < this.length; ++i) {
            if (this[i] === o) {
                return i;
            }
        }
        return -1;
    };
}

**Comment by ovangle** [comment]
I'm not a moment contributor, but that looks to me a lot like code deliberately aimed at providing `Array.indexOf` functionality on browsers which don't support it (IE <= 9).

So I'd gamble that whatever your problem is, it's not that 'indexOf' is `undefined`. Could you please describe the problem you're experiencing?

**Comment by icambron** [comment]
Seconding @ovangle; I don't think that code could be the problem, though I admit I haven't tested IE8 in a long time.

**Comment by jeffrey008** [comment]
Which moment version are you using?
Put `moment.version` in your console. You can use an older version of moment if you need IE8 support.

TBH I can't believe people are still using IE8 these days

**Comment by maggiepint** [comment]
Closing as stale.
