### ISSUE TITLE
Calendar function returns incorrect week.

### ISSUE THREAD

**Issue by hifall** [moment/moment#4047]
On June 29th (Thursday), I call moment('2017-06-26T22:16:53.000Z').calendar(), and it returns: 'Last Week Tuesday'. My timezone is China (UTC+8), so it seems to me it should produce 'This Week' or empty string for the week part, rather than 'Last Week'.

Environment:
Chrome 58.0.3029.110 (64-bit) on macOS Sierra 10.12.

console.log( (new Date()).toString())
`Thu Jun 29 2017 12:45:12 GMT+0800 (CST)`
console.log((new Date()).toLocaleString())
`6/29/2017, 12:45:12 PM`
console.log( (new Date()).getTimezoneOffset())
`-480`
console.log( navigator.userAgent)
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36`
console.log(moment.version)
`2.10.5`

**Comment by hifall** [comment]
The version of moment.js appeared 2.10.5, but the issue happened in 2.18.1 as well.

**Comment by icambron** [comment]
When you say it "Last Week Tuesday", do you mean it says than in Chinese with the `zh` locale set?  I ask because by default it actually says "Last Tuesday" (i.e. no "week"). I just tried it in your timezone. In American English, which has very confusing terminology for relative times, "this Tuesday" means the coming Tuesday and the most recent Tuesday is "last Tuesday", even if it's currently, say, Wednesday. "Last week Tuesday" would be wrong, but that's not what it says.

So if what you really mean is that it says that in Chinese (i.e. you've done `moment.locale('zh')`), then I guess there might be a problem with the locale?

**Comment by hifall** [comment]
Thanks for getting back to me.

Actually I meant "Last Week Tuesday" in English. If I set the locale to zh, it says "上周 星期二", which translates to "Last Week Tuesday" verbatim. In both locales, it says the time is from `Last Week` (instead of Last Tuesday), which I think is not correct.

**Comment by hifall** [comment]
Just found during app initialization, I call:

`moment.locale('en', {
        calendar : {
            sameDay: "[Today]",
            nextDay: '[Tomorrow]',
            nextWeek: 'dddd',
            lastDay: '[Yesterday]',
            lastWeek: '[Last Week] dddd',
            sameElse: 'L'
        }
    });`

And it causes the problem. After I removed it, things are fine.

But I still have a question: setting lastWeek to be '[Last Week] dddd' like above seems reasonable enough, but it turns Last Tuesday into Last Week Tuesday -- is this behavior by design?
