### ISSUE TITLE
Moment does not set format _f when using just the year YYYY with ISO 8061

### ISSUE THREAD

**Issue by honestserpent** [moment/moment#4048]
**Description of the Issue and Steps to Reproduce:**

moment.js does not set format `._f` YYYY, which looks to be fine with ISO 8601.
The object is created fine, and it is valid, but the format is undefined.

```
var my_year = moment.utc('2017')
my_year.isValid()
true
my_year._f
undefined <-- expected "YYYY"
```

```
var my_year_month = moment.utc('2017-06')
my_year_month .isValid()
true
my_year_month ._f
"YYYY-MM"
```

It [looks like](https://www.cl.cam.ac.uk/~mgk25/iso-time.html) this should be an accepted and valid format, and infact the created moment object is valid.

**after a rapid inspection, this may be caused by `match = extendedIsoRegex.exec(string) || basicIsoRegex.exec(string)`, [line 2034](https://github.com/moment/moment/blob/develop/moment.js#L2034)**

**Environment:**
Windows 10 64bit
Node.js v7.10.0
moment.js v2.18.1

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
Thu Jun 29 2017 12:09:38 GMT+0200 (ora legale Europa occidentale)
console.log((new Date()).toLocaleString())
2017-6-29 12:09:44
console.log( (new Date()).getTimezoneOffset())
-120
console.log( navigator.userAgent)
not available
console.log(moment.version)
2.18.1
```

**Comment by icambron** [comment]
Notes:

 1. Moment doesn't currently support '2017' as an ISO string. What's happening is that Moment is saying "that's not an ISO string" and passing the string to the native constructor, which in some (all?) browsers returns a valid date. Moment actually issues a deprecation warning for this (which you will see printed if you paste the code into your browser console). Anyway, because the native date parser handles it, Moment has no idea what the format was; it's just an arbitrary string.
2. Asking that Moment parse "2017" as an ISO date seems reasonable and I suspect we'd take that as a PR. We'd like to be as comprehensive with ISO formats as possible. If you filed another ticket asking for the ISO parser to explicitly handle year-only strings, I'd mark as an enhancement request.
3. Please don't use `_f` like that. It's non-public for a reason. We don't support using it and we don't consider issues with it bugs in and of themselves.
