### ISSUE TITLE
Will there be a new release soon?

### ISSUE THREAD

**Issue by stephan-v** [moment/moment#4052]
There are plenty of positive necessary changes that are all pending a new release. This library is huge in the community and there are plenty of people who love using it. 

But I am wondering if we will see a new release soon. For a project of this size is bothers me that releases are not more often. 

Is there anything that could be done? I would love to help out because in terms of development this project seems barely afloat.

**Comment by mj1856** [comment]
The core team is all volunteers.  We have jobs, families, and other commitments.  We all work on Moment when we can, but we do not set a regular schedule for releases because it would be near impossible to commit to.  Nobody is getting paid to do this, and even if we were it would not be enough to quit our day jobs to focus on this instead.

We're happy for the offer of help.  What you can do is to review the open issues and pull requests.  There are many issues that come in regularly that are just people needing help, and many open issues that don't have PRs yet.  We often invite those that are regularly contributing to join the core team, which doesn't mean much - other than that you get some permissions to close issues, etc.

I see you have made one PR (#3961), which is scheduled for the next release.  If this is what you're waiting for, I suggest you use your own copy of the code until the next release - whenever that may be.

In general, despite there being a larger-than-desired number of open items, and a longer-than-desired wait time for new releases, do understand that Moment is used by literally millions of people, including many major websites in production (NPM stats show 9M downloads last month).  We have to choose what we release carefully.  Moving slowly doesn't necessarily mean the project is "barely afloat".

Thanks.
