### ISSUE TITLE
Unreliable when diffing days to today's date

### ISSUE THREAD

**Issue by mankittens** [moment/moment#4087]
**Description of the Issue and Steps to Reproduce:**

(Today's date is 2017/07/26)
Go to https://momentjs.com/
Open dev tools
In the console enter `moment().add(30, 'days').diff(moment(), 'days')`
Run multiple times. Sometimes you'll get 29 instead of 30.

<img width="448" alt="screen shot 2017-07-26 at 10 55 02" src="https://user-images.githubusercontent.com/6647355/28635970-76ddbc3e-71f1-11e7-93c8-c19f6dfd852b.png">

**Environment:**

Chrome 59 on OSX

**Take a Look at This:**

```
// THE FOLLOWING CODE IS UNRELIABLE

main = function() {
    thirtyDaysFromToday = moment().add(30, 'days')
    today = moment()
    differenceInDays = thirtyDaysFromToday.diff(today, 'days')

    if (differenceInDays !== 30) {
        console.log({
            thirtyDaysFromToday: thirtyDaysFromToday,
            today: today,
            differenceInDays: differenceInDays,
        })
    }

    return differenceInDays
}

count = 0
while (count < 1000) {
    main()
    count++
}
```

```
// THE FOLLOWING CODE IS RELIABLE

main = function() {
    thirtyDaysFromToday = moment(moment().add(30, 'days').format('YYYYMMDD'))
    today = moment(moment().format('YYYYMMDD'))
    differenceInDays = thirtyDaysFromToday.diff(today, 'days')

    if (differenceInDays !== 30) {
        console.log({
            thirtyDaysFromToday: thirtyDaysFromToday,
            today: today,
            differenceInDays: differenceInDays,
        })
    }

    return differenceInDays
}

count = 0
while (count < 1000) {
    main()
    count++
}
```

**Comment by andrew-luhring** [comment]
+1 i thought i was going crazy

**Comment by icambron** [comment]
Correct. The rounding behavior is such that if it's a millisecond over two days, you get three days. Like so:

```js
var fakeNow = moment();
fakeNow.clone().add(30, 'days').diff(fakeNow, 'days'); //=> 30
fakeNow.clone().add(30, 'days').subtract(1, 'millisecond').diff(fakeNow, 'days'); //=> 29
```

Since you call `moment()` twice and then compare them, sometimes those will resolve during different milliseconds. Combine that with rounding and you get what you got. You can do what I did above by making sure that the current time is held in a variable instead of re-queried each time, or you can [customize rounding](http://momentjs.com/docs/#/customization/relative-time-rounding/) to suit your needs.
