### ISSUE TITLE
Error to format moment object

### ISSUE THREAD

**Issue by RogerByte** [moment/moment#4090]
**Description of the Issue and Steps to Reproduce:**

*Got a moment object with date 2017-08-13, and  apply .format('YYYYMMDD'), the result is 20170812*

**Environment:**

*Examples: Firefox 54.0.1*
```js
moment('2017-08-13').format('YYYYMMDD'); // "20170812"
```

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString()) // Sat Jul 29 2017 01:52:36 GMT-0400
console.log((new Date()).toLocaleString()) // 29/7/2017 1:52:22
console.log( (new Date()).getTimezoneOffset()) // 240
console.log( navigator.userAgent) // Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
console.log(moment.version) // 2.18.1
```

**Comment by icambron** [comment]
I can't reproduce this at all. Granted I'm on a Mac and you're on Windows, but it would be odd if that were the difference. What is your computer's time zone setting?

**Comment by RogerByte** [comment]
My time zone setting is UTC-04 Santiago.

**Comment by icambron** [comment]
Ah, OK, this is arguably a bug in Firefox. First some quick background: Moment only represents specific times, meaning, for example, that 2017-08-13 is really 2017-08-13T00:00:00.000 and not, like, the abstract idea of August 8.

2017-08-13 at midnight is a funny datetime in that Santiago starts DST just then. So one millisecond after 23:59:59.999, it becomes 1:00 in -3. Firefox has to decide what to do when it's told that it's midnight that day, because midnight literally doesn't exist. Most logically, it would follow the transition forward. That's what Chrome does:

```js
> new Date(2017, 7, 13).toString(); //=> 'Sun Aug 13 2017 01:00:00 GMT-0300 (-03)'
```

But that's not what FF does. Instead it does this:

```js
new Date(2017, 7, 13).toString(); //=> "Sat Aug 12 2017 23:00:00 GMT-0400"
```

That...isn't right. I think a lot of browsers get confused by the direction of DST shifts in the southern hemisphere. Unfortunately, Moment depends on the browser doing the right thing here: when it parses "2017-08-13" into its constituent year, month, and day, it then constructs a native Date object just like in that JS snippet above. That's the internal representation Moment has for the date and thus determines Moment's behavior.

I have good news and bad news. The bad news is that I don't have a workaround for you. The good news is that we're making some changes to how dates will be represented internally that should address this issue. Those will be (I hope) part of the 3.0 release of Moment.

In the meantime, consider filing a bug report with Firefox.
