### ISSUE TITLE
calendar() shows incorrect hours - 4 hours behind.

### ISSUE THREAD

**Issue by RupenAnjaria** [moment/moment#4113]
Application stores date in ISO format, so August 9, 5:36 PM will be stored as 2017-08-09T17:36:00.000Z.

Assuming today is August 9, 5:36 PM.

However, I am facing issues while displaying this using momentjs's calendar parsing method.

Any idea why it takes back to 4 hours?

See this: https://codepen.io/rupenanjaria/pen/NvjeGR?editors=1111

**Environment:**

Chrome on Windows 7 64x

```js
Wed Aug 09 2017 18:44:00 GMT-0400 (Eastern Daylight Time)
VM679:2 8/9/2017, 6:44:00 PM
VM679:3 240
VM679:4 Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
2.10.0
```

**Comment by icambron** [comment]
```js
moment('08/10/2017, 10:36 AM','MM/DD/YYYY, hh:mm A').format() 
console.log('Current Time is ',currentTime)
//See hours in console, it should be 6: 36 PM, however it shows 2:36 PM
```

I think you mean 6:36 AM? Or at least, it seems like you expect Moment to *parse* in UTC and *format* in local time? It actually does print in local. Here's what that console.log gives me (I'm also in EDT):

```
Current Time is  2017-08-10T10:36:00-04:00
```

In other words, it parsed in local and then formatted in local, which is right.  But maybe you changed the codepen? Regardless, Moment doesn't know that this string is meant to be in UTC, so it didn't parse it that way. It's true that if you format it in UTC, you'd get 2:36 PM, because that's the UTC time corresponding to a local time 10:36 AM. So I think the core issue is that you actually wanted something more like this, parsing your local timestamp in UTC but formatting it as a local time?

```js
moment.utc('08/10/2017, 10:36 AM','MM/DD/YYYY, hh:mm A').local().format(); //=> 2017-08-10T06:36:00-04:00
```

I'm going to close this. If I've misunderstood your question, please clarify it and I'll reopen.

**Comment by RupenAnjaria** [comment]
Sorry, I updated Pen. Please see updated : https://codepen.io/rupenanjaria/pen/NvjeGR?editors=1111

**Comment by icambron** [comment]
Just because the input string is in UTC (and Moment understands that), doesn't mean that the Moment is in UTC "mode". It gets the right time 17:36 in UTC and then formats it in local time, which is 13:36. If you want it to format in UTC, do this:

```
var m = moment('2017-08-09T17:36:00.000Z').utc();
```

Then `format()`, `hour()` and so on will behave as you expect. If you're unsure whether a given Moment think it's local or UTC, use the `isUTC()` method.
