### ISSUE TITLE
Invalid dot in Latvian longDateFormat

### ISSUE THREAD

**Issue by rayokao** [moment/moment#4136]
In file 'lv.js':

`L : 'DD.MM.YYYY.',`

should be without the dot in the end:

`L : 'DD.MM.YYYY',`

**Comment by icambron** [comment]
What do you think, @skakri?

**Comment by bernerha** [comment]
We have a validation with this and it's not optimal in front of the customer ;)
This is a bug.
https://en.wikipedia.org/wiki/Date_format_by_country

**Comment by marwahaha** [comment]
@rayokao - please see https://github.com/moment/moment/pull/4137#issuecomment-353659978

**Comment by skakri** [comment]
@icambron I agree with @JanisE

**Comment by icambron** [comment]
Closing this per https://github.com/moment/moment/pull/4137#issuecomment-353659978

**Comment by marwahaha** [comment]
Perhaps someone can make a request to update CLDR, instead.

**Comment by JanisE** [comment]
@marwahaha , do you mean information that is displayed here: https://www.unicode.org/cldr/charts/32/verify/dates/lv.html ? They seem to have the dots all right there. Only the "year monthn day" example has the order incorrect. Do you know where the rules themselves or examples get defined? When I click on "View", I get "Survey Tool is offline.", so maybe I should try later.

BTW, regarding the dot in moment.js. If the format is used for displaying the format correctly, then the dot should be there all right. However, if it is used for validating user's input, it would probably be better to accept also dates without the last dot, like an alternative format for input. Because people really do not know the rules quite often, and it's nice that the software can help them and correct the mistake by itself automatically, not aborting the request and asking the user to realise their mistake and fix it.
