### ISSUE TITLE
Inconsistency adding date that doesn't account for BST ending

### ISSUE THREAD

**Issue by kevbradwick** [moment/moment#4141]
**Description of the Issue and Steps to Reproduce:**

When adding time to a moment instance, using days doesn't appear to account for British Summer Time but adding hours does.

**Environment:** 

Have tested this on Chrome and Firefox (macOS) - doesn't look isolated to any particular environment. The following example can be run in the JavaScript console when on the https://momentjs.com site.

*Examples:*

In the following example (replicated in the browser console), I am adding 90 days to todays date (24 August 2017 08:07). The difference in the two calculations is adding by days (90) or hours (`24 * 90`).

When using `hours`, the correct time is calculated and it accounts for BST ending on 29 October where we lose 1 hour. However adding 90 days doesn't account for BST ending and the hour is not deducted.

```javascript
moment(new Date()).add(2160, 'hours').format('YYYY MM DD hh:mm:ss a')
// "2017 11 22 07:07:16 am"
moment(new Date()).add(90, 'days').format('YYYY MM DD hh:mm:ss a')
// "2017 11 22 08:07:13 am"
```

**Other information that may be helpful:**

```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
===
```
Thu Aug 24 2017 08:18:02 GMT+0100 (BST)
24/08/2017, 08:18:02
-60
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
2.18.1
```

**Comment by icambron** [comment]
That's correct behavior.  See http://momentjs.com/guides/#/lib-concepts/date-time-math/ Users would be pretty annoyed if adding days didn't correct for the DST and put them on a different hour than where they started.

**Comment by kevbradwick** [comment]
@icambron but that's my observation, adding days **doesn't** account for leaving DST and the hour is incorrect. Adding hour's however, **does** account for the 1 hour difference of leaving DST.

**Comment by icambron** [comment]
We're using "account for" in opposite ways. Think of it like this: days are not always the same length. So when you add your day across a DST boundary, one of those days was actually 25 or 23 hours long. *Moment is accounting for that.* It puts quite a bit of effort into making sure that you end up with the same wall time before and after the addition, precisely because it knows there's a DST in there. It's trying to add days in a calendar sense, not 24-hour periods.

By contrast, an hour is an hour. The DSTs don't mean anything at all when adding them; we just add the appropriate number of milliseconds to the current time and figure out what the corresponding local time is.
