### ISSUE TITLE
moment.unix

### ISSUE THREAD

**Issue by chuhanan** [moment/moment#4148]
**unix transform bug**

*Unix timestamp:1504094300*

**Environment:*zh-cn*

*nodejs:any system:any*

**Other information that may be helpful:**
* just install moment and use

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( moment.unix(1504094300).format("YYYY-MM-DD hh:mm:ss"))
```
>  output : 2017-08-30 07:58  but actually it is 2017/8/30 19:58

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by maggiepint** [comment]
This is actually just how JS date handles time zone conversations. Because you used the regular moment constructor, it is going to convert that time stamp to the local time of the machine you are running on upon formatting.

If you want it to output as UTC - which is also not either of the times you displayed, do:
```
console.log( moment.unix(1504094300).utc().format("YYYY-MM-DD hh:mm:ss"))
```
See this blog post for more detail on how moment constructors work: 
https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/

**Comment by chuhanan** [comment]
I use 
> console.log( moment.unix(1504094300).format("YYYY-MM-DD HH:mm:ss"))

solve the problem 
upper case hh ...
thx~
