### ISSUE TITLE
How to load all locales and get back all informations about them?

### ISSUE THREAD

**Issue by antoine-pous** [moment/moment#4150]
Hi !

I'm currently working on a multilingual product and i need to load all locales. Currently i have to import each locale manually, add an `index.d.ts` into the locale directory could let us made a simple `import from "moment/locale`.

For more convenience i would like generate the language selector with the momentjs loaded locales.
Currently the method `moment.locales()` give only the locales without informations like `['fr','en','de'...]` and i would like obtain the language name, like that: `[ {"fr": "french"}, {"en": "english"}, {"de": "deutsch"}] ` etc...

This kind of feature would be really usefull to generate selectors or any other frontend component wich list the availables locales.

Thank you!

**Comment by icambron** [comment]
There's no data field in the locale files that explain the common name for the locale. I *think* we'd accept a pull request that added the locale's name for itself to each locale file. Then you could use `map` to construct the thing you want. Perhaps the right names could be pulled from CLDR. But to take anything, we'd need them all and for all of them to be right (e.g. "french" is wrong for "fr")

**Comment by horodnicdragos** [comment]
Greetings! 

I looked through the locale files and was on my way of adding a name property according to the codes in CLDR. I was looking at tzm.js which seems to have the properties from shi.xml. The ones from tzm.xml seem to be different from the ones on the main repo. 

What should I do about those files in case I run into a similar scenario? I also want this to be my first PR on this library, since I assumed no one was working on it.

**Comment by antoine-pous** [comment]
I think the file should contains more informations, like the name and the list of countries wich use the language natively using ISO codes alpha 2 and 3.

**Comment by marwahaha** [comment]
This may have data you are looking for: https://github.com/moment/momentjs.com/blob/master/data/locale.js
