### ISSUE TITLE
Support for extended ISO8601 date format with optional ZoneID

### ISSUE THREAD

**Issue by pazkooda** [moment/moment#4159]
Question raised due to seeking compatibility between _moment.js_ parsing mechanism and Java 8 `ZonedDateTime` formatter used during serialization.

_Java 8_ documentation [claims](https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html#toString--) ISO8601 compatibility with full _Date_/_Time_ format with _Zone Offset_ and **additional** _Zone ID_.

Example string taken directly from JavaDocs:

```java
    "2007-12-03T10:15:30+01:00[Europe/Paris]"
```

This one is used by serializer which output I use in our front-end client using _moment.js_  

This format though is [not parse-able](https://runkit.com/pazkooda/moment-js---extended-iso8601-format-with-optional-zone-id/1.0.0) by _moment.js_.

For reference below is code used by example provided in above link:

```javascript
    var moment = require('moment') 
    //trying to parse extended version used by Java 8 ZonedDateTime formatter
    //that is claimed to follow ISO8601 standard
    var java8ExampleDate = moment('2007-12-03T10:15:30+01:00[Europe/Paris]');
```

Question is: If _Java 8_ JavaDocs are correct can this be supported by _moment.js_?
If so than this issue should treated as request for such support, thus also remove _[Question]_ from summary.

**Comment by pazkooda** [comment]
[PullReq#4160](https://github.com/moment/moment/pull/4160) with solution provided.

**Comment by icambron** [comment]
Gonna need a better citation that this is part of ISO 8601. I don't think it is; I think Java just added it because it's nice. Even if it was part of the standard, it would be confusing for Moment to claim to support it but then ignore the zone itself, which it would have to do. I mean, if Moment could do it, we'd probably support it for the same reason Java does, but it can't so we don't.
