### ISSUE TITLE
moment([2017,n]).week(39).day(1) giving different results changing n with some locales

### ISSUE THREAD

**Issue by ropel** [moment/moment#4196]
moment([2017,n]).week(39).day(1) gives different results changing n, depending on "dow" setted in locale

```js
// this code is OK with 'en' locale (same result for 0 < n < 11), 
// but gives wrong results with a locale using dow=1 (Oct,3th for 0 < n < 2, Sept, 25th for 2<=n<9, Oct,2th for n=9)
var fwd = moment([2017]).week(39).day(1)
document.body.innerHTML += '<p>' + fwd.format('MMMM Do YYYY'); + '</p>'
for(i=0;i<12;i++){
      fwd = moment([2017,i]).week(39).day(1)
      document.body.innerHTML += '<p>' + fwd.format('MMMM Do YYYY'); + '</p>'
}
```

any browser/OS

O.S. setted to Europe/Rome, tested with any starting date in 2017

// FULL EXAMPLE
https://jsfiddle.net/ropel/c2kzdmjt/5/

**Comment by icambron** [comment]
There are two issues with your code:

 1. You're confusing week years with weeks. Jan 1, 2017 may or may not be in the local week year, depending on the dow. That's why your first entry is October 3 **2016**. You need to make sure you're in the 2017 week year
 2. You're using locale-aware weeks (i.e. `week`) but not locale-aware weekdays. You want `weekday()` not `day()`. These names suck, but they are documented. That causes weirdness when you try to do things from week 39 and it isn't the same local week as you expect.

Try this: https://jsfiddle.net/c2kzdmjt/6/
