### ISSUE TITLE
Truly localized formatting.

### ISSUE THREAD

**Issue by Huulivoide** [moment/moment#4252]
There is an issue with the current localized formats. They lack the really useful formats like _date_ and _date with time_ .

Sure you can use _L_ or _l_ to get a date with correct separators, but there is no way to get a date in the natural format for each locale. Some locales might prefer the _L_ versions while others would prefer to have the _l_ version.

As for date and time, we do have _LLL_ yet it is defined as to use the name of the month which is OK and customary for English but not for all languages.

Thus I propose how redefining the localized formats work or extending it for example with Java style short, medium and long date and time formats.

We could for example have:
LDT: Date and time, in a format that is appropriate for most use cases.
English could be same as current _LLL_ and for example Finnish would be: `D.M.YYYY klo H.m.s`.

Then for simple solution we could have _LLDT_ (long date time), _LMDT_ (medium date time) and _LSMD_ (short date time). Or slightly more complex, yet much more versatile  solution where date and time could be specified individually with _LLD_, _LMD_ and _LSD_ and for time _LLT_, _LMT_ and _LST_.

**Comment by fbonzon** [comment]
The [documentation](https://momentjs.com/docs/#/displaying/format/) defines indeed `LLL` with *month name* explicitly, but I think it happens because the example format in English has month name, and the intent is really to mean just *long localized date and time*.

IMHO, if common usage in a given locale is to display dates with month numeral, then the localized date formats should reflect that as well. I rather suggest to change documentation from:

Description | Token | Example
-- | -- | --
Month numeral, day of month, year | L | 09/04/1986
Month name, day of month, year | LL | September 4, 1986
Month name, day of month, year, time | LLL | September 4, 1986 8:30 PM
Month name, day of month, day of week, year, time | LLLL | Thursday, September 4, 1986 8:30 PM

to:

Description | Token | Example
-- | -- | --
Short localized date time | L | 09/04/1986
Medium localized date time | LL | September 4, 1986
Long localized date time | LLL | September 4, 1986 8:30 PM
Full localized date time | LLLL | Thursday, September 4, 1986 8:30 PM

and then you can change the Finnish configuration for `LLL` to `D.M.YYYY klo H.m.s`.

**Comment by katekourbatova** [comment]
There are some more localized formats that would be useful:

- Month name, day of month (e.g. September 4 / Sept 4 / September 4th)
- Month name, day of month, day of the week (e.g. Monday, September 4th / Monday, September 4 / Mon Sept 4)
- Month name, day of month, time

Are there any plans to expand the existing localized format options?

**Comment by JaSpr** [comment]
Why is there not a fully localized DATE (without time)?  For example `Thursday, September 4, 1986`

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
