### ISSUE TITLE
.diff(x, 'days') doesn't seem to use 24 hour days

### ISSUE THREAD

**Issue by kalleaaltonen** [moment/moment#4279]
**Description of the Issue and Steps to Reproduce:**

There seems to be handling for DST that causes `.diff` to fail when used with days as units

*Please include the values of all variables used.*

```js
> a = moment("2017-10-30T00:00:00Z")
> b = moment("2017-10-29T00:00:00Z")
> a.diff(b, 'hours')
24
> a.diff(b, 'days')
0
>
```

**Environment:**

OS X timezone CET
node v6.11.3

```js
> console.log( (new Date()).toString())
Mon Oct 30 2017 17:59:49 GMT+0100 (CET)
> console.log((new Date()).toLocaleString())
10/30/2017, 5:59:49 PM
> console.log( (new Date()).getTimezoneOffset())
-60
> console.log(moment.version)
2.19.1
```

**Comment by ashsearle** [comment]
I don't see this mentioned in the documentation, but it looks like the diff for days is operating against local time instead of absolute time.  The local time for your first moment is something like 29th Oct at 2AM, and the second moment is 30th Oct at 1AM.  These look like they're less than 1 day apart _in local time_.

If you want the result of a diff to use 24 hour units instead of variable-length days (23..25 hours) I think it's more reliable to use `foo.diff(bar, 'hours') / 24`.

I think the documentation for `diff` would benefit from explicitly discussing how days are treated (as it already calls out the special behaviour for month and year diffs.)

**Comment by icambron** [comment]
The relevant documentation isn't linked to in all the right places, but it's [here](http://momentjs.com/guides/#/lib-concepts/date-time-math/).
