### ISSUE TITLE
month not visible

### ISSUE THREAD

**Issue by hsl1** [moment/moment#4293]
**Description of the Issue and Steps to Reproduce:**

Please see that the month in the calendar is cutting because is opening to up.
Any way to fix the direction of opening?

http://prntscr.com/h6y76s

**Environment:**

*Chrome 62

**Comment by erwinw** [comment]
Thanks for your message. This seems to be an issue with the library you're using for the date selector user interface, rather than with Moment.js (which only concerns itself with date and time manipulation, but not with the user interface.) I would recommend you check the documentation of that user interface library to see if you can have the popup open underneath the field. Good luck!
