### ISSUE TITLE
ISO format. moment construction falls back to js Date()

### ISSUE THREAD

**Issue by shivamanhar** [moment/moment#4294]
**Description of the Issue and Steps to Reproduce:**

**Environment: mozilla firefox 43.0.1*

**Other information that may be helpful:**
* The time zone setting (IST +5:30)
* The time and date :- 2017-11-07 12:12 PM

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
t = moment('18:00', 'HH:mm').format('07-10-2017 HH:mm');

				var d = new Date(t);

				convertStart = d.getTime();
```

**Comment by ashsearle** [comment]
It would be really helpful if you could include 'actual' and 'expected' behaviour when you report a bug.

I'm not sure what bug you're trying to report here: you say moment construction falls back to using the Date constructor.  That's true, and [it's documented](https://momentjs.com/docs/#/parsing/string/)

> When creating a moment from a string, we first check ... before dropping to the fall back of new Date(string) if a known format is not found.
>
> ...
>
> Warning: Browser support for parsing strings is inconsistent. Because there is no specification on which formats should be supported, what works in some browsers will not work in other browsers.

**Comment by icambron** [comment]
I taking it he's saying, though, that he expects it *not* to fall through because the ISO parser will handle it.

But I agree with @ashsearle - you need to provide the code that actually shows what you're passing in. Finally, I don't understand what I'm supposed to do with the code snippet there, which seems unrelated?

I'm going to close this, but if you @ me with an expected/actual for this I can reopen it.
