### ISSUE TITLE
Strict mode with without requiring spaces?

### ISSUE THREAD

**Issue by n9** [moment/moment#4324]
Some locales contain spaces in its formats. For instance, in cs ([`D. M. YYYY`](https://github.com/moment/moment/blob/1f613c2cccdfd2aaeb646247ff22a8361b1cd7dd/src/locale/cs.js#L100)) spaces were added [because it is in cs.wikipedia style](https://github.com/moment/moment/pull/2016#issuecomment-187670054). 

This causes problems when parsing user input in these locales, people tends to write `1.2.2017` instead of `1. 2. 2017`.

What about to add an option to not require spaces in strict mode parsing?

**Comment by marwahaha** [comment]
@ichernev

**Comment by petrbela** [comment]
For a little bit more context, the norm [ČSN 01 6910](http://prirucka.ujc.cas.cz/?id=810) allows either 23. 2. 2016 (with spaces) or 23.02.2016 (with padded 0 without spaces). It's currently implemented so that `format('l')` produces the former, and `format('L')` the latter. It's true, however, that a lot of people use the incorrect form 23.2.2016.

**Comment by ivosh** [comment]
Agreed with @petrbela. Unfortunately, the incorrect form `23.2.2016` is widespread in administration, though.

**Comment by ichernev** [comment]
You could use localeConfig.preparese to tweak the input so it passes strict. Use updateLocale to patch the relevant locales for you locally.

I'm reluctant to merge this in core.
