### ISSUE TITLE
Invalid date not isSame() as another same invalid date

### ISSUE THREAD

**Issue by pandaiolo** [moment/moment#4330]
**Description of the Issue and Steps to Reproduce:**

```js
const invalidDate1 = moment('')
const invalidDate2 = moment('')

invalidDate1.isSame(invalidDate2) 
// => false
```

**Expected**

```js
// => true?
```

Maybe it is expected to return `false` but I did not find any issue about this, nor any mentions about that in `isSame()` documentation, so I wanted to make sure this is not a bug.

Edit: found test case here https://github.com/moment/moment/blob/68a68b8730fbb69515ddbfb1d62bcfe34a484ae1/src/test/moment/is_same.js#L149

But why they 'should not be equal' ? Same rationale as `NaN` ?

**Use case**

Edit: adding a use case FYI

I have a `didChange()` method in a form component, to check if `save` button should be disabled or not. In the case of uninitialized *Moment* values, equality check forces me to also verify that dates can also be both invalid, which I find a bit awkward.

**Environment:**

Chrome OSX - Version 62.0.3202.94 (Official Build) (64-bit)
OSX 10.13.1 (17B48)

**Other information that may be helpful:**

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
Wed Nov 29 2017 10:11:34 GMT+0000 (WET)
29/11/2017, 10:11:34
0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
2.18.1
```

**Comment by marwahaha** [comment]
This is the issue that started most of the conversation. @cwohlman did most of the work to make this happen.
https://github.com/moment/moment/issues/2354

The rationale seems to be similar to `NaN`, that just because a date is invalid does not mean it's the same as another invalid date.

This is already memorialized in our tests, as you point out. If you can, please add to our documentation at momentjs.com (https://github.com/moment/momentjs.com/) in case this is not visible enough.

**Comment by jeffreyleeon** [comment]
Addressed in this [PR](https://github.com/moment/momentjs.com/pull/480)
