### ISSUE TITLE
Add months and then diff doesn't return the same added value

### ISSUE THREAD

**Issue by ivospinheiro** [moment/moment#4331]
**Description of the Issue and Steps to Reproduce:**

var startDate = moment('2016-11-29 13:00:00');
var endDate = startDate.clone().add(3, 'month');
console.log(endDate.diff(startDate, 'month'));

**Expected output
Output should be 3

check url: https://runkit.com/embed/rglhuftgpnvv

**Environment:**
Chrome 61 on on Ubuntu 16.0.4*

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
Wed Nov 29 2017 14:35:45 GMT+0000 (WET)
11/29/2017, 2:35:45 PM
0
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
2.19.1
undefined
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by icambron** [comment]
Not really, no. Adding and subtracting months isn't symmetrical toward the end of months. The specific problem is that 3 months after Nov 29 is Feb 28 because there's no Feb 30. But Feb 28 minus Nov 29 isn't a full three months. So you end up with 2 months.

You can also avoid the truncation if you want:

```js
endDate.diff(startDate, 'months', true) // => 2.966666666666667
```
