### ISSUE TITLE
Incorrect iso week number for 2018-12-31

### ISSUE THREAD

**Issue by Kasheftin** [moment/moment#4407]
I get the incorrect week number for the 2018-12-31 date. That's the end of the year, so it should be 52, or 53, but the result of `moment('2018-12-31').format('WW')` evaluates to 01.

Here's the example, http://jsfiddle.net/kasheftin/pasmo151/1/

Google Chrome Version 63.0.3239.132 (Official Build) (64-bit) Ubuntu 16.0.4

**Comment by ashsearle** [comment]
moment is correct.

ISO weeks run from Monday - Sunday, and ISO week 1 begins on Monday of the week containing 4th January.  This means (up to) the last 3 days of the year can belong to week 1 of the following year.

2018-12-31 is Monday of the week containing 4th Jan 2019, so it's ISO week 2019-W01.

Note: if you want the `2019` for this date, you use the format string `GGGG` instead of `YYYY`:
```js
moment('2018-12-31').format('GGGG-[W]WW'); // returns 2019-W01
```

**Comment by Kasheftin** [comment]
Ok, thanks for the explanation!
