### ISSUE TITLE
Unexpected behavior using .add

### ISSUE THREAD

**Issue by joaoapenas** [moment/moment#4442]
**Description of the Issue and Steps to Reproduce:**
I am tring to create a array of dynamic size, starting from the first hour incrementing by 1 hour each step.
But for some reason that I can't figure out why the function works for some number (a little above the middle of this array).n issue, please run the following code in the environment you are using and include the output:
```js
var start = moment('2018-01-28 00:00:00')

var end = moment('2018-02-28 00:00:00')

var duration = moment.duration(end.diff(start)).asHours()

console.log('start: ' + moment(start).format('YYYY-MM-DD HH:mm:SS'))
console.log('end: ' + moment(start).format('YYYY-MM-DD HH:mm:SS'))

console.log('duration: ' + duration + 'hours')

var arr = [];

arr[0] = start;

for (var i = 1; i < duration-1; i++) {
  arr[i] = moment(arr[i-1]).add(1, 'hour').format('YYYY-MM-DD HH:mm:SS')
}

arr[duration] = end

for (var i = 0; i < duration; i++) {
  console.log(moment(arr[i]).format('YYYY-MM-DD HH:mm:SS'))
}
```
You can find the code here, https://jsbin.com/lehupunure/edit?js,console
Any help would be welcome.

**Comment by ashsearle** [comment]
Which data point do you think has an error, and do you get any better results changing the way you populate `arr` to the below?
```js
for (var i = 1; i < duration-1; i++) {
  arr[i] = moment(start).add(i, 'hour').format('YYYY-MM-DD HH:mm:SS')
}
```

**Comment by joaoapenas** [comment]
in this specific array the error happens at the position 504. The thing is that if you 
![jsbin com_xudutataze_edit_js console](https://user-images.githubusercontent.com/8117041/36054094-c449d4ae-0ddb-11e8-999a-4189fc0bba1b.png)

The code as far as I know has no bugs, all I am trying to do is to create one array that has size equals the duration of hours in certain period of time + 1.

@ashsearle The size of the array is irrelevant for this problem, if duration is set to size 1, 10 or 100 the values stored at each position would be valid anyways. 

In fact if you change the year in the variables ```start``` and ```end``` from ``` '2018-01-28 00:00:00' ``` to ``` '2017-01-28 00:00:00' ``` the position from each the error appears also changes from ```504``` to ```527```.

I spent more time trying to understand this than I am willing to admit...

**Comment by ashsearle** [comment]
@joaoapenas I'll guess: you're in Brazil..?

Your loop get stuck at `2018-02-17 23:00:00` because your array contains strings _without any timezone or offset information_.

You hit the daylight-savings-time change when you try to add one hour to that date/time: the clocks go back  from `2018-02-18 00:00:00` back to `2018-02-17 23:00:00` - which is the same string - again, and again, and again...

You could fix this by storing including the offset in the strings your storing.  This happens naturally if you just use `moment().format()` (formatting the full date/time as an ISO8601 string.)

(one other minor point: I noticed you were using `SS` instead of `ss`, make sure you use the lower-case `ss` when you want to format seconds as `SS` is actually used for fractions of a second.)

**Comment by marwahaha** [comment]
Thanks Ash for the help.

Please reopen or post on [Stack Overflow](stackoverflow.com) if you are still having issues.
