### ISSUE TITLE
moment.format() incorrect for locale='ar'

### ISSUE THREAD

**Issue by eschiebel** [moment/moment#4448]
**Description of the Issue and Steps to Reproduce:**
Go to https://momentjs.com/,
scroll to Multiple Locale Support,
click the 'Arabic' button,
scroll back up to the Format Dates section
see that the result of moment.format() is not a valid ISO8601 string
Note that moment.toISOString() gives the correct result

It is correct for other Arabic variants except for "ar-sa".
It is also correct for other alternate alphabet languages like Hebrew and Russian.
Seems to be limited to these 2 Arabic variants.

*Please include the values of all variables used.*

**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString()) "Thu Feb 15 2018 09:49:39 GMT-0500 (EST)"
console.log((new Date()).toLocaleString()) "2/15/2018, 9:49:23 AM"
console.log( (new Date()).getTimezoneOffset()) 300
console.log( navigator.userAgent) "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36"
console.log(moment.version)  "2.10.6" (but it is also evident on your homepage)
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ashsearle** [comment]
I think this is a documentation issue: I don't think `format()` is guaranteed to produce an ISO formatted string - which is why `toISOString()` exists.

Various locales post-process the internal result of `format(...)`, and replace standard `[0-9]` numerals with alternative numerals if the locale has them.

All of these locales are likely to show the same type of issue: Arabic (Lybia) (ar-ly), Arabic (Saudi Arabia) (ar-sa), Arabic (ar), Bengali (bn), Burmese (my), Gujarati (gu), Hindi (hi), Kannada (kn), Maldivian (dv), Marathi (mr), Nepalese (ne), Persian (fa), Punjabi (India) (pa-in), Sindhi (sd), Tamil (ta), Tibetan (bo), Urdu (ur)

**Comment by eschiebel** [comment]
The documentation clearly states that `format()` with no arguments returns an ISO formatted string. In Arabic you can see that it's attempting to generate the string, but bits and pieces are in Arabic. That doesn't seem like it's useful to anyone. Given that it's been this way for a while, I'd suggest the code is changed to match the docs, and that this is a bug.

**Comment by ichernev** [comment]
@eschiebel you're correct. We need to change the documentation :)

The implementation of `format()` evolved, so that you can plug in a `defaultFormat`. I'd just use `.toISOString()` to make sure its all kosher and make a PR to the docs repo.
