### ISSUE TITLE
Need to display minutes in moment format

### ISSUE THREAD

**Issue by durgeshahire4** [moment/moment#4485]
**Description of the Query.

I need to display some minutes data in HH:mm:ss format
for example: 
var data = 30 (which in minutes)
i want to show this in 'HH:mm:ss' format like '00:30:00'

and if i
data  = 1500 (in minutes)
then it must show this is 'DD HH:mm:ss' format like '01 01:00:00'

Can any body please help.

**Comment by marwahaha** [comment]
Hi, 

The [Moment.js docs](http://momentjs.com/docs/) should have what you're looking for. In particular, I'd look in the duration section.

The closest thing in pure Moment might be:
```
moment.duration({"minutes": 30}).humanize()
```

Or, by using `.hours()`, `.minutes()`, `.seconds()` and making the string yourself.

Otherwise, you can use a plugin like the [moment duration format plugin](https://momentjs.com/docs/#/plugins/duration-format/). 

If you have other questions, [Stack Overflow](https://stackoverflow.com) is a great place to look. Good luck!

**Comment by durgeshahire4** [comment]
@marwahaha Thanks Man
