### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by matejm91** [moment/moment#4486]
Please update your docs, cause I've just spent a few hours trying to figure out why can't I add a timestamp with 'milisecons' to my created moment. Tried 'ms' and it worked, but there is still 'miliseconds' in the documentation

**Comment by lad475** [comment]
Hi there!

Are you referring to logging out the milliseconds in the timestamp using "moment().millisecond();", or are you referring to moment objects, or something else entirely?  I tried to replicate your bug by writing 

let m = moment().millisecond();
let mo = moment({ year :2010, month :3, day :5, hour :15, minute :10, second :3, millisecond: 10 });
console.log(m);
console.log(mo);

and got the following result:

355
moment("2010-04-05T15:10:03.010")

Which is correct.  Please provide me with the exact functionality that wasn't working correctly and I'll do my best to see if I can replicate it.

**Comment by matejm91** [comment]
moment(someItem.startTime).subtract(itemDuration, 'ms');

in docs this should be written like this:
moment(someItem.startTime).subtract(itemDuration, 'miliseconds'); --> and that's not working.

**Comment by lad475** [comment]
I think that the issue is just the spelling here; ms and milliseconds do both work, but in the snippets of code you've provided to me, "milliseconds" is not spelled with 2 'L's, and is instead written as "miliseconds".

With proper spelling, the following code:
const moment = require('moment');

let mo = moment({ year :2010, month :3, day :5, hour :15, minute :10, second :3, millisecond: 10 });
console.log(mo);
mo.subtract(50, 'milliseconds');
console.log(mo);

Yields the same result as:

let mo = moment({ year :2010, month :3, day :5, hour :15, minute :10, second :3, millisecond: 10 });
console.log(mo);
mo.subtract(50, 'ms');
console.log(mo);

The docs also do have information on allowing shorthand to be used instead of the full word.

**Comment by lad475** [comment]
Don't worry about it! :) I'm glad that we could resolve the issue without making any changes.

**Comment by marwahaha** [comment]
Thanks @lad475 ! 

@matejm91 Please re-open if there are still issues.
