### ISSUE TITLE
[BUG] toISOString don't return timestamp in UTC

### ISSUE THREAD

**Issue by workfel** [moment/moment#4511]
Hi all, 
I have some trouble with the `toISOString()` method.
I want to get the UTC of date but the toISOString() method return my local timezone (GMT +1).

This `moment("2018-03-23").toISOString()` should return `2018-03-23T00:00:00.000Z` but when i try it i have `2018-03-22T23:00:00.000Z`.

```js

var date = new Date("2018-03-23").toISOString();
// 2018-03-23T00:00:00.000Z

var dateMoment = moment("2018-03-23").toISOString();
// 2018-03-22T23:00:00.000Z

```

You can access to example here [https://jsbin.com/sozofer/edit?js,console](https://jsbin.com/sozofer/edit?js,console).

### Environment

Tested on Chrome on 65 OSX, also Node 8.6.0 with the Moment 2.21.0 version.

**Comment by ashsearle** [comment]
I don't think it's a bug in `toISOString()`; there's a difference between `moment` and `Date` in the timezone they use when parsing an ISO format date.

You may be able to see this yourself via:
```js
moment('2018-03-26').toDate().valueOf()
new Date('2018-03-26').valueOf();
```

The issue is that native ISO-date parsing will default to UTC, while moment defaults to local timezone.

Two possible ways to be more explicit about this - depending on the outcome you want:
1. Add timezone information when parsing:
 `moment('2018-03-26T00Z').toISOString()` will return `'2018-03-26T00:00:00.000Z'`
2. Parse _and format_ ISO in local timezone:
 `moment('2018-03-26').toISOString(true)` may return `'2018-03-26T00:00:00.000+01:00'` (depending on your timezone)

**Comment by workfel** [comment]
Thank you,

But i one thing i don't understand, i you look the jsbin. when i write
```js
var dateNow = new Date().toISOString();

var momentDateNow = moment().toISOString();
```
The result are the same 
```
"dateNow = 2018-03-29T09:41:34.151Z"
"momentDateNow = 2018-03-29T09:41:34.151Z"
```

But when i give a date to moment is apply the timezone.

https://jsbin.com/sozofer/edit?js,console

**Comment by ashsearle** [comment]
> But when i give a date to moment is apply the timezone.

You're not giving a `Date` to moment, you're giving a `String`.

**Comment by workfel** [comment]
So, with a string `moment` not convert to `utc` this string ? 

It's possible to convert this string to utc value ?

**Comment by workfel** [comment]
Also, if i do this
```js
console.log(moment().startOf('day').toISOString()); // We are the 29/03/2018
```
`Moment` return `2018-03-28T22:00:00.000Z` and i should be `2018-03-29T00:00:00.000Z`

**Comment by ashsearle** [comment]
@workfel said:
> So, with a string `moment` not convert to `utc` this string ?

Exactly - that's what I meant in my [previous comment]((https://github.com/moment/moment/issues/4511#issuecomment-375969504)) when I said:
> The issue is that native ISO-date parsing will default to UTC, while moment defaults to local timezone.

To force moment to parse a ISO formatted date in UTC timezone, add a `T00Z` suffix - e.g. `2018-03-29T00Z`

In your next comment:
> console.log(moment().startOf('day').toISOString()); // We are the 29/03/2018
> Moment return `2018-03-28T22:00:00.000Z` and i should be `2018-03-29T00:00:00.000Z`

Why should it be `2018-03-29T00:00:00.000Z`?  That's not the start of _your_ day, because `Z` isn't _your_ timezone.

I'm guessing, but think you want to see your date and time in an ISO formatted string - so try using`moment().startOf('day').toISOString(true)` and see if that gives you want you want.

**Comment by marwahaha** [comment]
Perhaps, you're looking for 
```
> moment.utc("2018-03-23").toISOString()
'2018-03-23T00:00:00.000Z'
```

if there are other problems, feel free to open a [Stack Overflow](stackoverflow.com) issue.
