### ISSUE TITLE
[Feature request] relativeTimeThreshold for weeks

### ISSUE THREAD

**Issue by WizardPC** [moment/moment#4514]
**Description of the Issue and Steps to Reproduce:**

Feature request : Add a `relativeTimeThreshold` for weeks.

*Please include the values of all variables used.*

```
    moment.relativeTimeThreshold('d', 21);
    moment.relativeTimeThreshold('w', 16); // Doesn't exist yet
    console.log(moment(someDate).toNow(true));
```

**What is the use-case or motivation for changing an existing behavior?**

I want to display age of animals :octocat: 

My problem is for puppy, a veterinary count in days (1 to 21days) AND weeks (4 to 16weeks) because the vaccines (and some other medicines) use this timeline.

**Comment by lad475** [comment]
I'd like to try and tackle this feature: it'd be my first contribution to the project, but I think I have a decent idea of how this would work.  Is there anyone who can lead me in the right direction concerning this?  Thanks :)

**Comment by felixplajer** [comment]
(I'm working with @lad475) So, right now there's a threshold "d" for days to month. In order to implement this feature, would we need to change the "d" threshold to be days to week and add a "w" threshold for weeks to month? It doesn't seem right to get rid of days to months (not everyone wants to use weeks), but I'm not sure how else to go about it - maybe have two thresholds for days to week and days to month? Any ideas / help would be appreciated!

**Comment by marwahaha** [comment]
See 2.25.3
