### ISSUE TITLE
Replace JSCS with ESLint (or Prettier?)

### ISSUE THREAD

**Issue by marwahaha** [moment/moment#4530]
this should be addressed by some version of #4475 

it's important that 
1. code is readable & maintainable by new and old developers
2. code can be automatically fixed when possible (low-effort for developers)
3. automated tools are still being used (i.e., let's get off jscs!)

I like the ESLint approach, but I'm not that familiar to Prettier or JSLint or the others. Would love to open a chat to see what people are using nowadays :)

**Comment by TheDancingCode** [comment]
ESLint is a great tool, but deciding on a configuration can be tedious as there's a [long list of rules](https://eslint.org/docs/rules/). That's why most people adopt popular styleguides and configurations like [Standard JS](https://github.com/standard/standard) or [Airbnb](https://github.com/airbnb/javascript). Standard can be used either as an ESLint config, or as a stand-alone tool.

[Prettier](https://prettier.io/) is another great tool, but only for code formatting. Contrary to ESLint or Standard, it is not concerned with sources of bugs and errors in your code. In a way, you could end up with a beautifully formatted document full of bogus javascript.

My suggestion is to choose one of the following:
- Use Prettier for formatting and ESLint with the [`eslint:recommended`](https://eslint.org/docs/user-guide/configuring#using-eslintrecommended) config to find common sources of problems.
- Use Standard

**Comment by Tom-Bonnike** [comment]
Would you be interested in using `clean-slate` to do that, by any chance? 🙂https://github.com/Tom-Bonnike/clean-slate.

Or would you rather roll your own config? In any case, I strongly recommend you setup a git hook to run ESLint and Prettier on all staged files before every commit, automatically. `husky` and `lint-staged` are great for that. :)

My suggestion would be that you use ESLint-Standard + Prettier while using https://github.com/prettier/eslint-config-prettier to disable all ESLint formatting rules that could conflict with Prettier. That way, only Prettier is responsible of the formatting itself. This is what `clean-slate` does.

**Comment by bencooper222** [comment]
I'm super partial to prettier. FB uses it for all their OSS product so it's battle tested and, importantly, makes reasonable choices for you to eliminate debates over the right style. +1 to `eslint:recommended` or airbnb eslint and prettier with either.

**Comment by marwahaha** [comment]
fixed in https://github.com/moment/moment/pull/5462
