### ISSUE TITLE
TS report a type error about Moment.add method

### ISSUE THREAD

**Issue by ufolux** [moment/moment#4571]
**Environment:**

React-Native 0.55 iOS

* Other libraries in use TypeScript

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```ts
isSameDateWithOffsetFromToday: ( date: Moment, offsetFromToday: number = 0) => {
    const targetDate = moment()
    targetDate.add(offsetFromToday, 'days') //Error:(196, 20) TS2345: Argument of type 'number' is not assignable to parameter of type 'Diff'.
    return date.isSame(targetDate, 'days')
  }
```

When I call method add on a moment object, TS report a type error on the first argument `offsetFromToday` which type is number. But I find the first argument of this method is 

```
type DurationInputArg1 = Duration | number | string | FromTo | DurationInputObject | void;
```

which include type number. So i can't figure out what happened here.

**Comment by renodubois** [comment]
I've also just run into this, and it seems that TypeScript is picking up the deprecated `add` syntax listed [here](https://github.com/moment/moment/blob/develop/moment.d.ts#L425) instead of the expected typings just a few lines above. If I go into `moment.d.ts` and comment out that deprecated version of `add`, I get the expected behavior, which is it not type erroring.

I'm not sure what exactly the issue is/why TS is only picking up that version of the typing, but that seems to be the root issue here.

**Comment by marwahaha** [comment]
I'm assuming this is no longer relevant. 
I could be wrong.
Please re-open if you still have concerns.
