### ISSUE TITLE
Feature Request: Method to Detect and Return Date Format

### ISSUE THREAD

**Issue by CamWalker** [moment/moment#4595]
Dates can be received in different formats. I would like to know the format of the date that was given in order to return the modified dates in the same format in which they are received.

Requirements: 
(1) Detect date format and return string containing the date format as it was received.
```
moment('2017-10-19').getFormat()
// returns 'YYYY-MM-DD'
```
(3) If date is invalid, it will return "Invalid Date".

**Comment by ccorcos** [comment]
You might want to check out chrono for parsing dates: https://github.com/wanasit/chrono

**Comment by ashsearle** [comment]
@CamWalker Do you realise any solution you find is going to be fragile?

What's the date format of "10/10/2018"?  Is it "DD/MM/YYYY", or "MM/DD/YYYY"?

**Comment by ccorcos** [comment]
I’m using `monthFirst = moment(“1990-12-28”).format(“L”).startsWith(“12”)`
to determine the way the user formats dates based on their locale.

**Comment by CamWalker** [comment]
@ccorcos Thanks for the recommendation. I'm not sure this fits my use case. My work involves data from a lot of different sources, time intervals, and locations. Format varies greatly. I want the ability to (1) manipulate the dates as needed and (2) display the dates in the same format in which they were given to me. So I don't need a parser, I need something that tells me the format that the date is in.

@ashsearle I understand. In reality, it will only be as fragile as Moment's ability to parse the date. All Moment has to do is return the date format it detected and used to parse the date. Moment could go with a default when unsure. The user could overwrite that default if needed.

**Comment by eternalharvest** [comment]
@CamWalker

If specified date is formatted in one of ISO standard format, u can detect the format like below.

```javascript
> moment('2017-10')._f
'YYYY-MM'
> moment('2017-10-19')._f
'YYYY-MM-DD'
```

But it if specified date is RFC2822 format or other format which JavaScript native builtin `Date` class accepts, it will be empty string.

**Comment by ichernev** [comment]
@CamWalker currently moment has creationData().format, which gives you the format specified explicitly.

If moment managed to parse via ISO it does include the format used, but if its RFC_2822 it puts a function that returns undefined... I guess this is a bug (patches welcome).

If moment uses Date constructor, there is obviously no way to get the format. This is your case. Sorry -- nothing we can do abou it.

NOTE: @eternalharvest avoid _f, because its not part of the API and can go any time, that is why creationData().format is for.

**Comment by apoorv-mishra** [comment]
Hello @CamWalker , using such a thing in your code is a bit dangerous, due to date ambiguity issues as pointed out [here](https://github.com/moment/moment/issues/4595#issuecomment-385162051)

 I ended up with the same problem of finding a date's format, asked a few people and they suggested that they'd be comfortable with a CLI tool instead, so [here](https://github.com/apoorv-mishra/moment-guess) is one I wrote. Hope you find it useful.
