### ISSUE TITLE
moment.duration().toISOString() is not giving expected output as per PnYnMnDTnHnMnS format

### ISSUE THREAD

**Issue by noorulcompro** [moment/moment#4603]
moment.duration(867896076).toISOString() is giving PT241H4M56.076S as output while it should be
PT10D1H4M56.076S.

**Comment by eternalharvest** [comment]
@noorulcompro

Though I'm not expert of moment.js and duration formatting, I think it's in the specification.
According to the following comment in the `#toISOString()` method, it seems milliseconds value bubble up to until they become hours.
I think it 's because if we consider the leap seconds, it is impossible to calculate exact number of days.

https://github.com/moment/moment/blob/3062ca13cd1cfbcef1c4a0cd5543f5fcd329c1d9/src/lib/duration/iso-string.js#L8-L18

**Comment by ashsearle** [comment]
Bubbling stops at hours because the number of hours in a day _is not always 24 hours_.

In approximately 70 countries that use DST to adjust clocks twice a year, one day a year is 23 hours, one is 25 hours, and the rest are 24.  (Assuming a typical DST going forward/backward by 1-hour.)

**Comment by eternalharvest** [comment]
@ashsearle 



@ashsearle 

I didn't consider about DST...
I'm not sure how the DST is implemented, but i think the value represent utc time offset in milliseconds.
Please correct me if I was wrong.

**Comment by ashsearle** [comment]
@eternalharvest I think the only thing you gain by mentioning UTC in relation to durations is that you can say a minute is always 60 seconds (as UTC doesn't have leap seconds.)

You can reliably convert milliseconds to seconds, minutes, hours.
You can't reliably convert to days, months or years.

**Comment by eternalharvest** [comment]
@ashsearle

> I think the only thing you gain by mentioning UTC in relation to durations is that you can say a minute is always 60 seconds (as UTC doesn't have leap seconds.)

I understand...
But I still thinking duration of the day is 24 hours.
Is this behavior is defined in ISO standard?

@noorulcompro
I think we can add optional arguments for existing '#toISOString()' method to control this bubbling behavior. But we need to discuss about the definition of duration.

**Comment by eternalharvest** [comment]
@ashsearle

I found the following `_buble()` method which is called implicitly.

https://github.com/moment/moment/blob/3062ca13cd1cfbcef1c4a0cd5543f5fcd329c1d9/src/lib/duration/bubble.js#L5-L50

And this code bubbles milliseconds value bubble up until they become day.
u can confirm this behavior like this.

```javascript
> moment.duration(24*60*60*1000).days()
1
```

**Comment by ashsearle** [comment]
Perhaps [this commit comment](https://github.com/moment/moment/commit/bb5135060a1e6a7d077a6b9d65edbe0e8b3b1a17) explains it better than I can.

**Comment by eternalharvest** [comment]
@ashsearle 

Thank u for telling me the commit message.
I'm losing my confidence...

Please help me! @NobodysNightmare

**Comment by NobodysNightmare** [comment]
The DST comment is basically right. I can explain it in two examples. Let's assume it is 13:00 o clock. If I tell you “let's meet in exactly two days“, then that means meeting at 13 o clock, two days from now. Even if there is a DST change, we will meet at 13:00. (At least according to the ISO spec)

If I tell you: let's meet in 48 hours, then that is a different story. Due to clock changes this could very well be 14:00 or 12:00.

This is what the spec says, but we can also try to explain it with common sense: if I take a train at 2:00 which will need an hour to reach its destination, it will either arrive at 3:00 or 2:00 or 4:00, depending on clock changes that night. But it always took one hour.

Disregarding clock change when talking about days makes sense, because we do the same for months. Adding a month to any date will keep me on the same day of the month, regardless if the current month has 28, 30 or 31 days.

Does that make sense?

**Comment by eternalharvest** [comment]
@NobodysNightmare 

Thank u for explain detailed info!
I was confusing internal data with string representation.

It seems there is no proper way to solve this issue...

**Comment by ichernev** [comment]
That is the reason why moment.duration handle milliseconds (up to hours), days and months separately. When you have 13:00 on Monday and you add 2 days, you want to get 13:00 on Wednesday, no matter what DST happens in the mean time (except if 13:00 Wed is invalid, because DST skips over it, of course).

If you add 48 hours though then it could be 12:00 Wed, it could be 14:00 Wed, it could be 13:00 Wed (-1 DST, +1 DST, no DST).
