### ISSUE TITLE
Get granularity for week and month date strings.

### ISSUE THREAD

**Issue by marcusx** [moment/moment#4605]
I have dates for months `('2018-09')` and weeks `('2018-W19')`.  I need the start and end day. How can I get the granularity for the moments to decide if I need `moment().endOf("month");` or `moment().endOf("week");` for getting the end day?

**Comment by ichernev** [comment]
@marcusx I see what you're trying to do, but moment is not that advanced. What you could do instead, if you really only deal with those two is:

1. Just check for `W` inside the string. If you find it use `week` instead of `month`.
2. You could look into moment().parsingFlags()

```javascript
moment('2018-09').parsingFlags()
> { empty: false,
  unusedTokens: [],
  unusedInput: [],
  overflow: -1,
  charsLeftOver: 0,
  nullInput: false,
  invalidMonth: null,
  invalidFormat: false,
  userInvalidated: false,
  iso: true,
  parsedDateParts: [ 2018, 8 ], // HERE <-----------------
  meridiem: undefined,
  rfc2822: false,
  weekdayMismatch: false }
> moment('2018-W19').parsingFlags()
{ empty: false,
  unusedTokens: [],
  unusedInput: [],
  overflow: -1,
  charsLeftOver: 0,
  nullInput: false,
  invalidMonth: null,
  invalidFormat: false,
  userInvalidated: false,
  iso: true,
  parsedDateParts: [],  // HERE <------------------
  meridiem: undefined,
  rfc2822: false,
  weekdayMismatch: false }
```

As you can see in one case you have parsedDateParts.length == 2 and in the other == 0. So you could go that way too.

You could need to use the other parsing flags too, I'm just guessing based on the provided info. Good luck!
