### ISSUE TITLE
Moment is not found after include

### ISSUE THREAD

**Issue by daganox** [moment/moment#4619]
After imported moment in my porject, I used this syntax for TypeScript:
`import * as moment from 'moment';`

but I had an error: "moment not found";

I fixed this bug by modifying the moment.d.ts this way:
change
`export = moment;`
for
```
declare module "moment" {
    export = moment;
}
```

now it works.

does everybody have this issue or I do something wrong?

**Comment by vvs** [comment]
Same here, VS Code can't seem to find moment type definitions when using `import`:

import moment from "moment";

But changing the moment.d.ts file so that (at the end):
```
declare module "moment" {
    export = moment;
}
```

Fixes the problem.

**Comment by vvs** [comment]
@ichernev, just closing the issue without any comment? Is it fixed, is it not going to be fixed, is the issue not an issue at all?

**Comment by Favna** [comment]
Getting back to this waaaaay after it was closed or anything but it should be noted that this is fixed in TypeScript by passing the compiler option `--esModuleInterop`.

I was going through all my packages in my project and found that I applied this "hacky" resolution as proposed by daganox. Simply passing `--esModuleInterop` makes the main lib work fine with `import moment from 'moment'`
