### ISSUE TITLE
isSame terribly slow on mobile browsers

### ISSUE THREAD

**Issue by thom-ek** [moment/moment#4638]
isSame(date, 'day') is terribly slow on Safari on iOS. Used at loop to compare and filter dates is taking many seconds to process. Comparing year, year+month and year+month+day can be fixed by manually comparing each component by calling year(), month() and date() functions.

**Comment by JulianKingman** [comment]
Also slow in react native. A single comparison takes an average of 3400ms
`moment(date1).isSame(date2, 'day')`

**Comment by ichernev** [comment]
Can someone drill this down and figure out exactly which part is slow. These functions are not trivial, because they need to work reliably across moments in different timezones.

You can "hack" a faster function and use it, I don't see any issue with that, but I doubt it will handle all the use cases the current code does.

**Comment by be-ndee** [comment]
I'm having the same issue. It's in an angular-cordova environment, where I use momentJS. Two components of my app, are very slow. I noticed in the Xcode logs the message `[IPC] Connection::waitForSyncReply: Timed-out while waiting for reply, id = 4` always when I open one of these two components. After a while (and with the help of this issue) I found a method with this line in my code, which is called very often:

```
return moment(dateA).isSame(dateB, 'day');
```

When I replace this line with the following code, the app is significantly faster:

```
return dateA.getUTCFullYear() === dateB.getUTCFullYear() &&
    dateA.getUTCMonth() === dateB.getUTCMonth() &&
    dateA.getUTCDate() === dateB.getUTCDate()
;
```

**Comment by be-ndee** [comment]
Is there something happening with this issue?

**Comment by JulianKingman** [comment]
I don't think anything's happening with this atm. If you want to look into the code, here's where it is: https://github.com/moment/moment/blob/master/src/lib/moment/compare.js

I made this package for faster isSame comparisons, and use it when I need to compare dates quickly:
https://github.com/JulianKingman/same-date

**Comment by jskrepnek** [comment]
It seems to have been introduced in a release since `2.20.1`.  Observed this testing a moment upgrade.

**Comment by arusak** [comment]
Couldn't say it's terribly slow. I've built a small test suite to compare isSame performance to Date.getUTCSomething performance. Here: https://arusak-performance.firebaseapp.com/. Feel free to inspect its code.

On my desktop Firefox the native method is 20 times faster. But I think it's reasonable. The library method is universal, the native is suitable only for same date comparison.

On mobile Safari the difference is more dramatic. The native way is about 100 times faster. But it's not because the moment is slower, but because the Date works better than on laptop. Due to some JVM optimizations I guess.

Here's some typical numbers.

**Laptop FF.** Library: 625 ms, native: 29 ms
**Laptop Chromium.** Library: 673 ms, native: 49 ms
**Laptop Edge.** Library: 454 ms, native: 9 ms (OMG!)
**Chromium on Android 8.** Library: 1363 ms, native: 144 ms
**Safari on iOS 12.** Library: 1284 ms, native: **7** ms

@JulianKingman @be-ndee @thom-ek what results do you get with this test? 

@ichernev do you think it needs optimization?

**Comment by marwahaha** [comment]
We probably won't optimize anything, unless it works for all use cases as ichernev mentioned.

See https://momentjs.com/docs/#/-project-status/
