### ISSUE TITLE
en-gb locale does not include ordinal in LL, LLL and LLLL

### ISSUE THREAD

**Issue by Billy-** [moment/moment#4664]
They are defined as so:
```js
{
  LL : 'D MMMM YYYY',
  LLL : 'D MMMM YYYY HH:mm',
  LLLL : 'dddd, D MMMM YYYY HH:mm',
}
```

For en-us, this is correct, but in GB we always write the ordinal on the day of the month when written in full like this.

So, to summarise; in all 3, `D` should be replaced with `Do`

**Comment by ashsearle** [comment]
Do you have any sources to back up your claim that we 'always' do this in GB?

I've checked front covers and websites of the UK's biggest circulating papers and only found 1 website using the ordinal on day of the month: The Sun.

None of them use ordinals on the front page of the print edition.

Checked: Daily Mail, Daily Mirror, Daily Telegraph, The Guardian, Metro, The Sun, The Independent, Daily Express, London Evening Standard, The Times, Daily Record, and The Scotsman

**Comment by Billy-** [comment]
Maybe the word "always" wasn't entirely accurate, however most of the newspaper websites you quote do not use any of the formats that I am proposing above - what I am suggesting only applies when the date is written in full, i.e only the formats listed in the issue (and amended in my PR).

I would consider this "correct" in en-gb, I do not really have any source other than that I was taught this at school, although there is [a wikipedia page on date and time notation in the UK](https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_Kingdom) which notes:
> Writing the day of the month as an ordinal number (for example "31st December") is also very common

**Comment by ashsearle** [comment]
> however most of the newspaper websites you quote do not use any of the formats that I am proposing above

I'm not sure that strengthens your argument: you're observing that none of the leading publications _exactly_ match one of the 'standard' formats from the en-gb locale.  (e.g. _all_ of the papers I mention include the weekday with the date on their front page.)

I see the [HMRC (government) website](https://www.gov.uk/government/latest?departments%5B%5D=hm-revenue-customs) uses the current `LL` format (`D MMMM YYYY`)

I'm not deliberately looking for counter-examples; I can only say that - apart from The Sun - I haven't found any to support your proposed change (FWIW: The moment formats for en-gb have been the same since 2011.)

With respect to what you've been taught at school: I was taught the same thing, and will almost always include the ordinal suffix if hand-writing a date in the middle of a sentence - but not necessarily in table data, by-lines or other forms of free-standing dates / timestamps.

**Comment by ichernev** [comment]
@Billy- look, you have 2 options:

1. Try to convince us that one is more standard than the other. You'd better bring up some heavy stacks of government issued rules. I won't take that route, unless you like pain and no gain.
2. Create a parent locale to en-gb that has your preferable rules and live a happy life.

```javascript
moment.defineLocale('en-gb-better', {
  parentLocale: 'en-gb',
  longDateFormat: {
    LL : 'Do MMMM YYYY'
  }
});
moment.locale('en-gb-better')
moment().format('LL')
> '27th June 2018'
```

http://momentjs.com/docs/#/customization/
