### ISSUE TITLE
moment.relativeTimeThreshold('ss', 0) still displays 'a few seconds' for 0 seconds

### ISSUE THREAD

**Issue by Halt001** [moment/moment#4668]
moment.relativeTimeThreshold('ss', 0) still displays 'a few seconds' for 0 seconds

What I expect is '0 seconds'.

How can I eliminate the 'a few seconds' and always get a specific number?

```
moment.relativeTimeThreshold('ss', 0);

const humanStringZeroSeconds = moment
  .duration(0, 'seconds')
  .humanize();

console.log(humanStringZeroSeconds); // a few seconds;

const humanStringOneSeconds = moment
  .duration(1, 'seconds')
  .humanize();

console.log(humanStringOneSeconds); // 1 seconds;

```

**Comment by ichernev** [comment]
If you read the code, you'll see that we make sure `number || 1` (in `substituteTimeAgo`) to never print `0 anything`, so the question

> How can I eliminate the 'a few seconds' and always get a specific number?

You can't do that for 0 right now. You can write your own humanize function that checks for 0 seconds, prints the right string, otherwise delegates to the original function.

Or you can investigate why is `number || 1` needed, patch the rest of the code so the tests pass (that might be impossible), and submit a patch, but given how crazy this use case is I wouldn't bother.
