### ISSUE TITLE
moment add fractional days is not working properly in Microsoft Edge

### ISSUE THREAD

**Issue by abdul-qadirdeveloper** [moment/moment#4692]
I wanted to add 2.7 days to a moment date in internet explorer it added on 2 days, whereas in Chrome it was adding exactly 2.7 days.
I ran following code in console if Microsoft Edge
moment('01-01-2018').add(2.7,'days').toDate();
in Microsoft Edge it returns 
Wed Jan 03 2018 00:00:00 GMT+0500
whereas in Chrome it is returning
Wed Jan 03 2018 16:48:00 GMT+0500

I am using 
moment.js version : 2.8.3
Microsoft Edge 42.17134.1.0 on windows 10

console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

 Sat Jul 07 2018 18:41:13 GMT+0500 (Pakistan Standard Time)
 ‎07‎/‎07‎/‎2018‎ ‎6‎:‎41‎:‎13‎ ‎PM
 -300
 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
 2.8.3
undefined

**Comment by Eliyas** [comment]
The issue is not with moment but with Edge browser Date API itself.

I have tested the w3school example of setDate() method in both browsers. Edge doesn't work as expected.

try to open the link in both browsers
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_setdate

**Comment by robzenn92** [comment]
@abdul-qadirdeveloper  Not sure if this can help you (I did not use moment version < 2.12.0), however as stated in the [documentation](http://momentjs.com/docs/#/manipulating/add/) for `moment().add(Number, String)`:

> As of 2.12.0 when decimal values are passed for days and months, they are rounded to the nearest integer. Weeks, quarters, and years are converted to days or months, and then rounded to the nearest integer.

Hence:
Testin in Chrome Version 67.0.3396.99 (64 bit)
Moment version: 2.22.2

As expected, decimal values that are passed for days are rounded to the nearest integer. 
```
moment('01-01-2018').add(1.3, 'days').format()
"2018-01-02T00:00:00+01:00"
moment('01-01-2018').add(1.7, 'days').format()
"2018-01-03T00:00:00+01:00"
```
In order to add fractional days you can use duration but keep in mind the following:
Wrong way:
```
const d = moment.duration(2.7, 'days')
moment('01-01-2018').add(d).format()
"2018-01-03T00:00:00+01:00"
```
What you want:
```
const d = moment.duration(2.7, 'days')
moment('01-01-2018').add(d.asSeconds(), 'seconds').format()
"2018-01-02T16:48:00+01:00"
```
Where **seconds** is the **precision** that you want!

Cheers
