### ISSUE TITLE
isValid function is inconsistent for legal string literals

### ISSUE THREAD

**Issue by Amannor** [moment/moment#4693]
**Description of the Issue and Steps to Reproduce:**

When running isValid on various string literals, it returns inconsistent results:
moment("JULY-Sunday", "MMMM-dddd").isValid()); //true
moment("JULY-Monday", "MMMM-dddd").isValid());  //false
moment("JULY-TUESDAY", "MMMM-dddd").isValid());//false
moment("JULY-WEDNESDAY", "MMMM-dddd").isValid());//false
moment("JULY-THURSDAY", "MMMM-dddd").isValid());//false
moment("JULY-FRIDAY", "MMMM-dddd").isValid());//false
moment("JULY-SATURDAY", "MMMM-dddd").isValid());//false

*Also occurs when you try different casing of day\month literals

**Environment:**

Node.JS 8.9.1 on Windows 10 Pro

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString()) Sun Jul 08 2018 18:30:40 GMT+0300 (Jerusalem Daylight Time)
console.log((new Date()).toLocaleString()) 2018-7-8 18:30:40
console.log( (new Date()).getTimezoneOffset()) -180
console.log( navigator.userAgent) - I'm running on a server (nodejs) - there's no browser
console.log(moment.version) 2.22.2
```

jsfiddle:
https://jsfiddle.net/3hnzorm4/5/

**Comment by ashsearle** [comment]
This is predictable behaviour.

You're only providing a partial date (the month), so moment assumes the 1st of the month, in the current year.

It then validates that the day-of-the-week matches the date.

In 2018: July 1st was a Sunday, so that's valid.  No other day of the week is considered valid.

This behaviour is consistent.  e.g. May 1st was a Tuesday, so `moment("MAY-Tuesday", "MMMM-dddd").isValid()` is `true` for Tuesday, but not for any other day of the week.

**Comment by Amannor** [comment]
I see, thank you. Is there a way to check whether a string is valid (i.e. adhering to a moment format) regardless of context?
For example, this: moment(<s1>-<s2>, "MMM-dddd") will be valid for any string of the format:
s1 is a member of moment.monthsShort() and s2 is a member of moment.weekdays()?

**Comment by marwahaha** [comment]
This is a great question for [Stack Overflow](https://stackoverflow.com/).
