### ISSUE TITLE
Adding month

### ISSUE THREAD

**Issue by reposys** [moment/moment#4696]
The addition of one month to the date 2018-02-28 leads to the result of 2018-03-28.
Here, 28 DAYS were added, but it is necessary to add rightly ONE MONTH. As the next month is March, the result should be 2018-03-31.
Isn't it?
```
let d = moment('2018-02-28')
d.add(1, 'month')
alert(d); // Wed Mar 28 2018 00:00:00 GMT+0300
```

**Comment by DavidJohnWilliams** [comment]
This is standard behaviour (same in .Net) see [DateTime.AddMonths](https://msdn.microsoft.com/en-us/library/system.datetime.addmonths%28v=vs.110%29.aspx). What you are asking is to special case the last day of the month, this would result in unexpected behaviour. If you added one month to 2018-02-15 you would expect the result 2018-03-15 (28 days or 29 for a leap year) if you added one month to 2018-03-15 you would expect 2018-04-15 (31 days). Note that the day portion remains the same, however the amount of days added changes (i.e. amount of days on start month). The only case where this is different is when the resulting day is past the end of the month. In this case it is constrained e.g. adding one month to 2018-03-31 results in 2018-04-30 rather than 2018-05-01.

**Comment by marwahaha** [comment]
Agreed. Perhaps there is not documentation -- so improvements to this are helpful!

**Comment by matthewdordal** [comment]
I submitted a PR to the momentjs.com repo. 

https://github.com/moment/momentjs.com/pull/538

**Comment by marwahaha** [comment]
fixed by https://github.com/moment/momentjs.com/pull/538
