### ISSUE TITLE
[ES Modules] Missing js extensions in import statements

### ISSUE THREAD

**Issue by phaux** [moment/moment#4713]
**Description of the Issue and Steps to Reproduce:**

When loading `src/moment.js` with `<script type=module>`:

> Loading failed for the module with source “http://localhost:5000/node_modules/moment/src/lib/utils/hooks”.

**Environment:**

Any browser with support for ES modules.

**Comment by ashsearle** [comment]
Adding the `.js` file extension to all import under `src/` could easily lead to a chain of up to 105-228 HTTP requests (depending on locales)

A more appropriate result might be achieved by adding `esnext` and `module` properties to `package.json`.  From a [series of articles by Axel Rauschmayer trio](http://2ality.com/2017/06/pkg-esnext.html) it seems like you'd want something like:

```json
  "esnext": "src/moment.js",
  "module": "./moment.esm.js",
```

(where `./moment.esm.js` would be a new build target, following ESM instead of CJS module format)

**Comment by chrisdothtml** [comment]
+1 for a new esm build target. For reference, [Ractive.js provides an .mjs dist file](https://www.jsdelivr.com/package/npm/ractive)

**Comment by marwahaha** [comment]
I'll take a PR on documentation about this in https://github.com/moment/momentjs.com

**Comment by brettz9** [comment]
Btw, even with a good number of HTTP requests, it can be convenient to have browser builds for use in demos--where the demos aren't forced to pollute their HTML with global script dependencies (I know it'd just be one script tag if there is an IIFE or UMD build, but a script tag is still out of place from the JS that uses it and cleaner to have a module distribution).

**Comment by marwahaha** [comment]
@brettz9 I'll look at PRs that don't break any existing users.

**Comment by ramonGonzEdu** [comment]
> @brettz9 I'll look at PRs that don't break any existing users.

How could this break users? I can't think of any platform that doesn't support using the .js extension on imports. Even typescript supports it.

Regards
