### ISSUE TITLE
moment constructor.name returns 'p'

### ISSUE THREAD

**Issue by MarcNoob** [moment/moment#4750]
Is it possible to change moment contructor name to 'moment' or something more specific than 'p' ?

`      	let tututu = moment("2000-01-02T00:00:00");
      	alert(tututu.constructor.name);`

**Comment by ashsearle** [comment]
The constructor name in source code is `Moment`, and that's what you'll get if you do `moment().constructor.name` using the non-minified version.

You're seeing `p` because you're either using a minified version of moment, or part of your own build process is minifying moment, therefore renaming the constructor function.

**Comment by MarcNoob** [comment]
thanks
