### ISSUE TITLE
Add minutes over day light saving

### ISSUE THREAD

**Issue by FSondermann** [moment/moment#4838]
When you add minutes to a moment object which is in summer time so that it will be in winter time an extra hour is added.

initalTime: 1540676700000 (ms)
minutesAdd: 420 (minutes)

Code used:
var obj = moment(initalTime);
obj .minutes(obj .minutes() + minutesAdd);

Environment: Chrome 69 on Windows 10

js output:
Mon Oct 29 2018 09:33:16 GMT+0100 (Mitteleuropäische Normalzeit)
29.10.2018, 09:33:16
-60
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
2.19.2

**Comment by MichaelPruefer** [comment]
I'm not sure if this is the same problem but we encountered a similar problem:
![image](https://user-images.githubusercontent.com/217915/47640235-78384900-db63-11e8-8ca0-84f25dc478b3.png)

**Comment by idoodler** [comment]
I just stumbled over the same behaviour. It is a wanted behaviour, check out the documentation: [https://momentjs.com/docs/#/manipulating/add/](https://momentjs.com/docs/#/manipulating/add/)

I am currently working on a "workaround".

**Comment by marwahaha** [comment]
If the documentation is not clear, we will take a PR to that.

**Comment by zshrc** [comment]
I observed an issue on US Daylight saving date (Nov 4):
'''moment('**05:00:00.000**', 'HH:mm:ss.SSS')'''-> 1541332800000 (Sunday, November 4, 2018 **4:00:00 AM** GMT-08:00), which is one hour off.

However if we use '''moment('2018-11-04T05:00:00.000', 'YYYY-MM-DDTHH:mm:ss.SSS') ''' it calculates correctly as 5AM. Could some points me if the first usage is correct?

**Comment by ichernev** [comment]
Wait wait wait. This is by design.

When you add units less than days (minutes, hours), then it works like in UTC. If now is 1:00 and there is DST from 2:00 jumping to 3:00, adding 24 hours will result in 2:00 on the next day (because of the jump).

But if you add 1 day to 1:00, then you'll get 1:00 on the next day (which will actually be 23 hours in the future).

That is why duration objects keep milliseconds, days and months. Days and months -- because you can't convert between the two. And milliseconds and days are separate because of this adding across DST.
