### ISSUE TITLE
Add/subtract should not fail silently if they don't recognize the object

### ISSUE THREAD

**Issue by waldyrious** [moment/moment#4854]
**Description of the Issue and Steps to Reproduce:**

The [documentation of `subtract()`](https://momentjs.com/docs/#/manipulating/subtract/) says that it accepts an object as input, but it does not make it clear what format the object must be in. Coupled with the fact that invalid object contents are simply ignored, that results in unexpected output that may easily be overlooked and cause bugs in code that expects the subtraction to actually happen.

See #410 and #3704 for previous discussion about such silent failures.

Here's a minimal example of the issue:

```js
moment().subtract({ value: 1, unit: 'day' });
// Outputs today's date without any warnings

moment().subtract({ day: 1 });
// Outputs yesterday's date
```

It would be nice if:

1) The [documentation](https://momentjs.com/docs/#/manipulating/subtract/) was clearer about what format it expects the object to be,
  or
2) Input that is not recognized produced a warning, similarly to what happens e.g. with swapped-order parameters:
   ```js
   > console.log(moment().subtract('day', 1));
   Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
   moment("2018-11-07T16:35:20.638")
   ```
...or both :)

**Environment:**

Node v10.11.0 on macOS Mojave

```js
> console.log((new Date()).toString())
// Thu Nov 08 2018 17:16:17 GMT+0000 (Western European Standard Time)
> console.log((new Date()).toLocaleString())
// 11/8/2018, 5:16:17 PM
> console.log((new Date()).getTimezoneOffset())
// 0
> console.log(moment.version)
// 2.20.0
```

**Comment by ichernev** [comment]
This is a javascript library. When you call it with the right arguments nice stuff happens. When you don't -- something happens.

We can not anticipate all wrong ways in which any function can be called. Instead we make sure that if you call it with something reasonable it will do something reasonable.

Not to mention that moment was built in a time when any exception could break you website, so we didn't want to be the one responsible for a website not working just because someone passed on a wrongly formatted date.

**Comment by waldyrious** [comment]
@ichernev if I'm reading you correctly emitting a warning is not an option -- fair enough. But wouldn't making the documentation clearer be a net positive? If you agree, I can submit a PR.
