### ISSUE TITLE
What is the algorithm for exact Month diff()?

### ISSUE THREAD

**Issue by andrewghobrial** [moment/moment#4860]
This is not a bug, but I could not find any documentation for how the precise value of a diff between two dates by month. I looked at the source code, and it there's a calculation for determining whether to define a month as 28/29/30/31 days depending on the starting and ending dates. I understand the algorithm is, but don't understand what the reasoning behind it is, or why it makes sense.

Example: rentalEnd.diff(rentalStart, 'months', true);

https://github.com/moment/moment/blob/develop/src/lib/moment/diff.js#L39

**Comment by ichernev** [comment]
@andrewghobrial hey there!

Well, moment is full of surprises, right! Only in the name of less surprises of course.

Now to the point -- the idea is to have a formula that is linear given the arguments. It is clear when the difference in 2 dates is exactly N months (5th January and 5th May for example -- 4 months). Also its clear that the difference between 5th January and 5th June is 5 months. So now the trick is to make sure that every day in between 5th of May and 5th of June produces a difference that is in between 4 and 5 but also linear. In this case, May has 31 days, so every day will add up to 1/31 of a month (so 5th Jan to 6th May will be 4 months + 1/31 of a month).

In cases of rental property, I'd consult with the user and ask then how exactly they already calculate this (because there are money involved, laws, accounting, angry overpaying users), and just sticking a one-line open source library in the middle will almost definitely not do what all of the above require, even though we had the best intentions of providing a "sane" result. Just my $0.02.

**Comment by marwahaha** [comment]
Please re-open if you have other questions! :-)
