### ISSUE TITLE
Adding a week produces the wrong year.

### ISSUE THREAD

**Issue by Verikon** [moment/moment#4867]
Consider the following:
`new Array(4).fill().map((v,i) => moment('2018W51').add(i, 'weeks').format('YYYYWW'));`

Expected Result `["201851", "201852", "201901", "201902"]`
Actual Result `["201851", "201852", "201801", "201902"]`

hint: element 3 produces 201801, not 201901

To reproduce this simply copy the above code to your clipboard, visit http://momentjs.com in any browser and paste it to the JS console. I've tried it in the latest chrome, firefox and edge.

**Comment by kingston** [comment]
After doing some fun digging into ISO week date specs (https://en.wikipedia.org/wiki/ISO_week_date), it appears that not every day in a particular ISO week may be in the same year (it depends which year the Thursday of that week falls).

A smaller test case would be: `moment('20181231').format('YYYYWW')` resulting in `"201801"`

This happens because the year of the date (YYYY) is indeed 2018, but the ISO week is part of next year (as that week's Thursday lies in 2019). Therefore, you need to use the corresponding ISO week year token, which in moment is GGGG.

Thus, if you correct the format to (GGGG), `moment('20181231').format('GGGGWW')` resulting in `"201901"`

**Comment by Verikon** [comment]
Thank you so much @kingston - great answer.
