### ISSUE TITLE
Some questions about MomentJS implementation

### ISSUE THREAD

**Issue by dpatte** [moment/moment#4872]
Years ago I wrote a similar library for C++, and I wanted to compare the implementations. I am considering rewriting the C++ library to make it align better with the syntax of momentjs.

I have tried to find answers to these questions about moment.js, but have been unable to find anything elsewhere. I'm sorry if this is the wrong place to ask...

What is the minimum supported date-time?
What is the maximum supported date-time?
What date-time does 0 represent? (What is the Epoch)
What is the time resolution (time increment) used internally, milliseconds?
Are all dates assumed to be Gregorian calendar?
Formally, UTC has leap seconds. does moment support leap seconds (23:23:60), or is it more consistent with unix time?
Does is have a way of representing an invalid time, or 'Never' (NAN)?
Does it have a way of representing 'Always', or 'from the beginning of time' (-INF)?
Does it have a way of representing 'Never', or 'at the end of time' (+INF)?

And again, if this in not the best place to ask this, perhaps you can redirect me to a better place to post these questions.

Thanks for your input.

**Comment by ashsearle** [comment]
moment builds on the platform's support for `Date` objects.  Most of your questions are answered in the [ECMAScript 2018 Language Specification](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-date-objects).

Min/max range:
> exactly -100,000,000 days to 100,000,000 days measured relative to midnight at the beginning of 01 January, 1970 UTC. This gives a range of 8,640,000,000,000,000 milliseconds to either side of 01 January, 1970 UTC.

0 represents:
> The exact moment of midnight at the beginning of 01 January, 1970 UTC is represented by the value +0.

Time resolution: basically milliseconds (some methods _may_ allow fractions of a millisecond due to failing to validate/round method arguments, but that's undocumented / a bug.)

Other (non-Gregorian) calendars are implemented with plugins (see docs for [some non-Gregorian calendars](http://momentjs.com/docs/#/plugins/isocalendar/), and some discussion in issue #1454))

Leap seconds are ignored.  If you use moment to calculate difference-in-seconds between two points in time, the answer will never include leap seconds.

An invalid moment will use `NaN` internally (i.e. `new Date(NaN)`)

"Always" and "Never" relate to date ranges. As core moment doesn't deal with ranges, you'd need to look at a plugin for that (e.g. [moment-range is mentioned in docs](https://momentjs.com/docs/#/plugins/range/))

Anything else?

**Comment by ichernev** [comment]
@dpatte well to answer all of those question you could have looked inside moment's code -- it's open source!

@ashsearle wow, that was a very comprehensive answer, thank you :)
