### ISSUE TITLE
Fraction of Day Duration doesn't compute Minutes

### ISSUE THREAD

**Issue by sughodke** [moment/moment#4880]
**Description of the Issue and Steps to Reproduce:**
Create a new duration with fractional days as arguments and get the number of minutes, it will always be 0.

```js
> z = moment.duration(1/5, 'days')
...
> z.asHours()
4.800000000000001
> z.minutes()
0
> .8 * 60
48

// minutes should have been 48
```

Work-around is to go one step more granular, use hours instead of days.

```js
> z = moment.duration(1/5 * 24, 'hours')
...
> z.asHours()
4.800000000000001
> z.minutes()
48

// works
```

**Environment:**
Node v10 LTS on MacOS
Node v11.3.0 on MacOS

**Other information that may be helpful:**
```js
> console.log( (new Date()).toString())
Tue Dec 04 2018 13:28:52 GMT-0800 (Pacific Standard Time)

> console.log((new Date()).toLocaleString())
12/4/2018, 1:28:52 PM

> console.log( (new Date()).getTimezoneOffset())
480

> console.log( navigator.userAgent)
ReferenceError: navigator is not defined

> console.log(moment.version)
2.22.2

```

**Comment by ichernev** [comment]
You called it with `asHours` but then `minutes`. If you used `asMinutes` it would have displayed 288, which you can then do `% 60` on :)

In general the units bubble up, not down, because its less error prone.

There is a bunch of crazy logic in durations, so that most stuff works as expected, bubbling down is not implemented, and it will be extremely tricky, especially for months, because its not clear how many days a month has. For days you might have a point, but in general it is always better to use whole numbers when possible, rather than floating point.

To get what you want, just multiply the day number by the number of milliseconds per day and use that -- it will bubble properly and use whole numbers. I'm not sure I'm in favor of implementing down-bubbling for fractional units.

Just to give you an example -- adding 24 hour duration is not the same as adding 1 day duration. 24 hours will preserve DST timing (it will act as if on UTC time) and 1 day will act as in local time across DST. If you don't really give a crap about any of that -- just use milliseconds, or do `moment.duration(moment.duration(1/5, 'day').as('ms'))`

@mj1856 @marwahaha @maggiepint what do you think?

**Comment by marwahaha** [comment]
I agree with @ichernev 's diagnosis and recommendation.

```
z.asHours()
4.800000000000001
z.asDays()
0.2
z.asMinutes()
288
```

I don't think we should make changes here.

Please re-open if you still have issues.
