### ISSUE TITLE
Different Date being created based on System Date

### ISSUE THREAD

**Issue by ryanab** [moment/moment#4881]
**Description of the Issue and Steps to Reproduce:**
Moment seems to be creating different date based on current system date in certain scenario..
Please see fiddle here: http://jsfiddle.net/rLjQx/158752/
If you set your system Clock to Sunday, December 2, you will get a result different than if you have the current date.

**Environment:**
Tested on both Windows and MAC, Chrome 70

**Comment by ryanab** [comment]
This actually seems rather illogical - I think I am misunderstanding something fundamental about the moment default constructor.

**Comment by ryanab** [comment]
I changed the moment object to use .isoWeekDay() instead of day() and it seems to have resolved my specific issue.  However, I am still a bit confused / uncertain as to why the system date should affect the construction of a new moment object where we set all required details.

**Comment by ashsearle** [comment]
@ryanab You already found the solution, but to explain the root cause: `day()` uses the week definition for your locale (e.g. Sunday-Saturday), while `isoWeekDay()` uses a fixed definition (Monday-Sunday.)

When you change the `day()` moment will ensure the new date is in the same week.  So, if the 'current' date is Sunday, it'll move _forwards_ 1 day to Monday.

For `isoWeekDay()` changing from Sunday to Monday will move the date _backwards_ 6 days.

**Comment by ryanab** [comment]
Ah Thanks @ashsearle - I did not realize calendar/ locale date would affect the moment object via the method I used for construction - but your explanation makes sense.  Closing this out but hopefully it can be good future reference for someone in the future.
