### ISSUE TITLE
how to remove locale from my moment bundle?

### ISSUE THREAD

**Issue by sheikalthaf** [moment/moment#4943]
**Describe the bug**
I'm using moment in my angular projects but it includes all the locale in my main bundle. How to remove them?

**Expected behavior**
I only want to bundle what i want

**Screenshots**
![image](https://user-images.githubusercontent.com/22526247/51017950-d8a02980-159b-11e9-954e-979917722821.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)

Fri Jan 11 2019 12:25:33 GMT+0530 (India Standard Time)
1/11/2019, 12:25:33 PM
-330
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
moment version v2.22.2
```

**Additional context**

**Comment by ichernev** [comment]
We don't bundle moment anywhere, npm and bower packages provide both unbundled and bundled versions, so users can choose. Either you bundled them yourself or someone else did, but its definitely not us.

In case you're using webpack, they like bundling things automatically just because they are require'd in the code, which might explain things, but you never mentioned what your actual environment was. Just google for webpack, moment and locales, and you'll find a solution.

There is even a repo with instructions! https://github.com/jmblog/how-to-optimize-momentjs-with-webpack
