### ISSUE TITLE
Need to access a list of DST-independent timezones

### ISSUE THREAD

**Issue by gopsig** [moment/moment#4960]
We have an app that allows users to select their local timezone. It then allows public users to book appointments with our users. We frequently receive support requests from users who believe that their appointments are "off by an hour". This happens when a user has chosen a timezone that is specific to daylight savings time, such as EST or EDT. We'd like to limit our list of available timezones to those timezones that will automatically change with DST ("US Eastern", rather than EST or EDT). Clearly moment has some way of identifying these time zones, but there's no clear way to filter the list of timezones to eliminate those that ignore DST.

**Comment by ashsearle** [comment]
This would be a good question for [stackoverflow](https://stackoverflow.com/).

You could include a bit more information about your current source of timezones, and whether you're using [moment-timezone](https://momentjs.com/timezone/) or not.

FWIW: it's common these days to choose timezones based on _location_ rather than abbreviation.  e.g. 'Europe/London', rather than choosing BST / GMT (neither of which have 'Daylight' in their unabbreviated form.)
