### ISSUE TITLE
isSameOrBefore not always working

### ISSUE THREAD

**Issue by Dynogic** [moment/moment#4993]
**Describe the bug**
In a for loop between two large times, the last iteration (where isSame should validate to true) is never executed.

**To Reproduce**
```javascript
const a = moment('1928-01-01');
const b = moment('2019-02-10');

for (let m = moment(a); m.isSameOrBefore(b); m.add(1, 'days')) {
  if (m.isSame(b)) {
    console.log('Hit');
  }
}
```
The `console.log` is never hit. It should (isSameOrBefore).

Upon closer inspection, the day before is successfully hit:
```javascript
const a = moment('1928-01-01');
const b = moment('2019-02-10');

for (let m = moment(a); m.isSameOrBefore(b); m.add(1, 'days')) {
  if (m.format('YYYY-MM-DD') === '2019-02-09') {
    console.log('Hit')
  }
}
```

Moreover, using a closer `a` date, the `console.log` is successfully hit.
```javascript
const a = moment('1960-01-01');
const b = moment('2019-02-10');

for (let m = moment(a); m.isSameOrBefore(b); m.add(1, 'days')) {
  if (m.isSame(b)) {
    console.log('Hit');
  }
}
```

**Expected behavior**
In first aforementioned example, `console.log` should be executed, but it is not.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- MacOS Mojave
- Tested on Node v10.15.0
- Tested on Chrome 72.0.3626.96: https://codesandbox.io/s/vr011pqn7
- Moment 2.24.0

**Moment-specific environment**

* Eastern Standard Time - Toronto, ON, Canada
* Monday, 9AM, February 11, 2019

```
Mon Feb 11 2019 09:21:51 GMT-0500 (Eastern Standard Time) 
2/11/2019, 9:21:51 AM 
300
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36 
2.24.0 
```

**Additional context**
N/A

**Comment by ashsearle** [comment]
`moment('1928-01-01')` creates a moment initialised to the start of the day, which is normally midnight.

`m.add(1, 'days')` rolls the date forward by one day, and tries to preserve the time.  Unfortunately, this isn't always possible.

Adding 1 day from April 26th 1947 you hit a problem: DST started at midnight (in America/Toronto timezone) and so your moment represents "1947-04-27T01:00:00.000-04:00" - 1 AM instead of midnight.

Rolling on from this point your date continues to represent 1AM instead of midnight, so never equals midnight on 2019-02-10.

**Comment by Dynogic** [comment]
Thanks! Is there then anyway to roll over the day using `m.add(1, 'days')` without preserving the time?

**Comment by ashsearle** [comment]
Not exactly, but using `m.add(1, 'days').startOf(`day`)` will work for your case.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
