### ISSUE TITLE
moment#isBefore returns wrong result

### ISSUE THREAD

**Issue by Shiko1st** [moment/moment#5012]
**Describe the bug**
moment('2018-06-12T22:05:00.000Z').isBefore('2018-06-13T00:00:00.000Z', 'days')
returns false

**To Reproduce**
use console

**Expected behavior**
Must return true

**Screenshots**
![default](https://user-images.githubusercontent.com/27359019/53056907-19099600-34be-11e9-88b4-c69372f2711d.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - FF
 - Version 65.0.1

**Moment-specific environment**
* The time zone setting of the machine the code is running on -- Moscow time
* The time and date at which the code was run -- at the moment of this post
* Other libraries in use -- Angular, TypeScript

Please run the following code in your environment and include the output:
Wed Feb 20 2019 03:21:58 GMT+0300 (Москва, стандартное время)
20.02.2019, 03:21:58
-180
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
2.23.0

**Comment by kylekatarnls** [comment]
If I well understand the documentation `'days'` as second argument will tell you if the time is before the current day (local hour), so `moment('2018-06-12T22:05:00.000Z').isBefore('2018-06-13T00:00:00.000Z', 'days')` does not return `true` with Moscow time since it's you get `2018-06-13 01:05:00.000` is before `day of 2018-06-13 03:00:00.000` and both are the 13th in Moscow.

**Comment by brunoflmg** [comment]
Easier example:

![image](https://user-images.githubusercontent.com/282629/60113313-7d27b980-973f-11e9-844c-2437f6c93539.png)

Comparing 8am (valueMoment) with 9pm (now), valueMoment.isBefore(now) should return true. However as you can see in the image above... it's returning false.

Now if you compare valueMoment.hour() < now.hour() the result will be true as expected.

That means BUG! Lol

**Comment by ashsearle** [comment]
@brunoflmg Your example doesn't show the full date/time you're using; it's possible `valueMoment` is some point in the future.

**Comment by brunoflmg** [comment]
I was wrong. The problem was the UTC. Even if we setup the timezone we want though, the UTC after 9pm was jumping one day.

One thing I didn't like it was even setting up a timezone we still need to deal with the UTC offset which sucks! Or I didn't get the point yet.

I will dig into this latter on.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
