### ISSUE TITLE
Two different dates returning same timestamp

### ISSUE THREAD

**Issue by albertvazquezm** [moment/moment#5018]
**Describe the bug**
Two different dates, when parsed to timestamp (X), are returning the same exact number

**To Reproduce**
Just open and see the console
https://codepen.io/anon/pen/vPOmaz

**Expected behavior**
The resulting timestamp is different

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser any
 - Version any

**Moment-specific environment**

* The time zone setting of the machine the code is running on GMT+02
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc) none

Please run the following code in your environment and include the output:
```
Wed Feb 27 2019 14:30:26 GMT+0100 (hora estándar de Europa central)
27/2/2019 14:30:26
 -60
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
2.24.0
```

**Additional context**
pen for reproducing: https://codepen.io/anon/pen/vPOmaz

**Comment by kylekatarnls** [comment]
Because it's true! That's the magic of DST, at 2h o'clock the 30/03/2014 (in the country where you run this code), an hour is added (instantly) for the summer time (end of winter time). So you skip the whole hour and at 3h in England (for example), no second elapsed, so same timestamp (as timestamp is always seconds from January 1st 1970 midnight UTC, so it's not influenced by the timezone).

**Comment by kylekatarnls** [comment]
If you want to learn more about this subject, I wrote this article: [Always Use UTC Dates And Times](https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164)

**Comment by albertvazquezm** [comment]
Thanks for your comment! :)
