### ISSUE TITLE
No formatted month for 'cs' locale

### ISSUE THREAD

**Issue by JavaPixelArt** [moment/moment#5074]
There are no formatted month for CS locale as for RU e.g.:

```
    var ru = moment.defineLocale('ru', {
        months : {
            format: 'января_февраля_марта_апреля_мая_июня_июля_августа_сентября_октября_ноября_декабря'.split('_'),
            standalone: 'январь_февраль_март_апрель_май_июнь_июль_август_сентябрь_октябрь_ноябрь_декабрь'.split('_')
        },...
```

**Comment by marwahaha** [comment]
thoughts @petrbela ?

**Comment by petrbela** [comment]
That is correct. I wrote the cs locale long before the `standalone` vs `format` customization was implemented. I believe this change now allows us to fix some of the imperfect Czech inflections but, unfortunately, I don't have much time to work on it. If someone wants to do it, a PR would certainly be welcome.

**Comment by Kartik18g** [comment]
Although regular expressions in Czech locale handle inflected titles really well, there's no loss in implementing format and standalone functionality . I'll create a PR implementing them.

**Comment by Kartik18g** [comment]
#5749  I've updated the "cs" locale by implementing standalone and formats, I was confused why these changes were needed because cs locale code was able to handle inflections like leden - ledna. únor - února březen-března etc without any problems. Then I realized adding format and standalone to 'cs' locale makes the code consistent with other locales like 'hi' and 'ru' .
After making changes to the "cs" locale it's test needed to be updated because of moment expecting standalone values, I also added 'format month case test' for accusations and nominations.

Now, for the most part, cs locale code is consistent with other locales, but if you feel something needs to be changed I can do that.
