### ISSUE TITLE
de locale adds "." in MMM format 

### ISSUE THREAD

**Issue by philipeachille** [moment/moment#5220]
**Describe the bug**
When using the German locale, the format MMM adds a dot

This is not really a bug ...

**To Reproduce**

toggle locale between 'en' and 'de' and compare

moment(new Date().format('MMM DD, YYYY')

**Expected behavior**
This may be due to Germans preferring this formatting, however, I believe for consistency it may be better to have users add the "." like so: format('MMM. DD, YYYY')

**Workaround**

Of cause a workaround is to replace the "." like so: format('MMM DD, YYYY').replace('.','')

**Comment by ashsearle** [comment]
Expected behaviour should match the common convention for that locale.  In this case it looks like `moment` _does_ meet expectations - some month abbreviations end in a '.', and some don't(!)

A couple of ways to check:
1. See the unicode consortium's survey tool for locale data - specifically the [German locale data](https://st.unicode.org/cldr-apps/v#/de/Gregorian/).
2. Check the output of `Intl.DateTimeFormat` for the locale:

```js
new Intl.DateTimeFormat("de", {
  year: "numeric",
  month: "short",
}).format(new Date("2019-06-03"));
// Juni 2019

new Intl.DateTimeFormat("de", {
  year: "numeric",
  month: "short",
}).format(new Date("2019-04-03"));
// Apr. 2019
```

**Comment by kylekatarnls** [comment]
Note that the rule is the same in many European languages: if the word is tool long, only the 3/4 first letters (depending of understanding and possible needed disambiguation) are kept, then a dot is added to mark the word as abbreviated. If the word is short enough, it is used as is for short version: no dot are no letter are missing.
