### ISSUE TITLE
Would be great if the fromNow() function could just return numbers. Positive for future, negative for past... 

### ISSUE THREAD

**Issue by leenbean16** [moment/moment#5221]
This just makes time calculations so complicated when you have to calculate a second ago, a few minutes ago or... in 3 hours...

**Comment by kylekatarnls** [comment]
As you can imagine such change would completely break thousands of applications that rely on `fromNow()` to display date as text like the ones you can see right now above GitHub messages.

You can't expect a library to completely change a method output because it's more convenient for some users.

You would have way more chance to get your feature if you would ask for a new method rather than breaking an existing one.

And this could probably be done using a plugin (maybe it already exist).

Check what already exist and if other methods and plugins are not close enough, describe precisely the expected output (a method cannot send numbers, it can send 1 number or an array/object that can have different content).

**Comment by leenbean16** [comment]
Thanks for that answer? I wasn't suggesting anyone to break anything?? Read my question again. Maybe someone that read my question had a suggestion for me. Don't comment if you have nothing helpful to say. I also did not have any expectations. Don't have anything helpful to say/suggestions, don't comment.

**Comment by kylekatarnls** [comment]
There is no question in your issue. And I didn't suggest you should close it, I suggested you to provide details about the output you expect so you would have a chance to get a relevant answer. First you may base your issue on the [Feature request](https://github.com/moment/moment/issues/new?template=feature_request.md) moment asks. So we can better understand your expectation, and give you answer you would find more helpful.

**Comment by leenbean16** [comment]
Found a way to make this happen. 
This would have been the question: Is there a way in moments.js to only get integers returned when you are calculating how many days are between two dates instead of phrases such as "a month ago", "12 hours ago"?

**Comment by kylekatarnls** [comment]
Yep, recommended way is:
```js
const duration = new moment.duration(moment('2019-08-25').diff('2019-06-14'));

console.log(duration.months());
console.log(duration.days());
```
