### ISSUE TITLE
In Safary browser diff method returns NaN

### ISSUE THREAD

**Issue by logvy-22** [moment/moment#5317]
**Describe the bug**
I use the _diff_ method to count days, and it returns Null for any time period. When I run the same code in another browser, it works correctly

**Expected behavior**
Expect that diff method will work in safari

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 
 - Browser: Safari
 - Version 13.0.4

Logs outputs:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
console.log(moment(start))
console.log(moment(end))
console.log(moment(end).diff(moment(start), "days"))

[Log] Sun Dec 15 2019 11:21:24 GMT+0200 (EET) – "new Date()).toString()" (main.bundle.js, line 14247)
[Log] 12/15/2019, 11:21:24 AM – "new Date()).toLocaleString()" (main.bundle.js, line 14248)
[Log] -120 – "new Date()).getTimezoneOffset()" (main.bundle.js, line 14249)
[Log] Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15 – "navigator.userAgent" (main.bundle.js, line 14250)
[Log] 2.24.0 – "moment.version" (main.bundle.js, line 14251)
[Log]  (2) (main.bundle.js, line 14252)
Moment {_isAMomentObject: true, _i: "2019 12 15", _isUTC: false, _pf: Object, _locale: Locale, …}
"moment(start)"
[Log]  (2) (main.bundle.js, line 14253)
Moment {_isAMomentObject: true, _i: "2019 12 15", _isUTC: false, _pf: Object, _locale: Locale, …}
"moment(end)"
[Log] NaN – "moment(end).diff(moment(start), \"days\")" (main.bundle.js, line 14254)

```
console.log screens:
![image](https://user-images.githubusercontent.com/30704265/70861005-15556d00-1f31-11ea-8c13-942336971d66.png)

![image](https://user-images.githubusercontent.com/30704265/70860672-2ef4b580-1f2d-11ea-9ced-97cb50104463.png)

**Comment by logvy-22** [comment]
I added date format and it works
![image](https://user-images.githubusercontent.com/30704265/70860981-d3c4c200-1f30-11ea-8690-cbe37d96d59f.png)

**Comment by ashsearle** [comment]
@logvy-22 Your screenshots shows you using inputs like `'2019 12 15'`; which isn't a recognised standard format, and moment therefore falls back to browser-dependent behaviour (and will spit out a warning to the console about this.)

Telling moment what format the input is helps; even better if you supply a third argument to put moment into [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/).

In your case parsing in strict mode may fail because your input uses spaces but the format string you supplied uses hyphens (i.e. input is actually 'YYYY MM DD', not 'YYYY-MM-DD'.)

Ironically, if your input really was in YYYY-MM-DD format, it'd be recognised as a valid ISO format date, and you'd have had consistent results across all current browsers without having to supply a date format.  (YYYY-MM-DD is also the default format when reading the `value` of an `<input type="date">` field.)

**Comment by marwahaha** [comment]
Thanks @ashsearle 
Please re-open if you still have issues.
