### ISSUE TITLE
If the date is before 1918, in some time zones, the formatted date shown is a day eariler

### ISSUE THREAD

**Issue by eladt81** [moment/moment#5345]
In case the local computer's time zone is UTC+02:00 (Jeusalem) and you try to get the format a date with a midnight hour, the result shown will be day earlier.

An example can be shown here:
https://codepen.io/eladt/pen/YzPLjGe

**To Reproduce**
1. Change the computer time zone to UTC +02:00 (Jeusalem)
2. Go to https://codepen.io/eladt/pen/YzPLjGe
3. Observe the recent & old dates shown

**Expected behavior**
Both of the dates should be formatted to the same expected result.
The recent date should be: 2001-03-02T00:00:00Z 
and the old date should be: 1917-03-02T00:00:00Z

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - Chrome Version 79.0.3945.88 (Official Build) (64-bit)
 - Version - 2.2.4

**Moment-specific environment**
* The time zone setting of the machine the code is running on: UTC+02:00 (Jerusalem)

**Comment by eladt81** [comment]
Note:
this happens for other time zones, such as:

-  UTC+0300 (Moscow Standard Time)
-  UTC+04:00 (Baku)

**Comment by ashsearle** [comment]
This might be due to Chrome's historic timezone data including _seconds_, but could also be due to the rather odd way you're building your dates.

Can you talk me through the way you're building your display value?
```js
let date = new Date(/* some date */);
let partTime = moment(0, "HH").format('LT');
let partYear = moment(date).format('L');
let combined = moment(partYear + ' ' + partTime,"L LT");
let displayVal = moment(combined).utc().add(combined.utcOffset(),"m").format();
```

Are you trying to achieve something significantly different to the below code?
```js
let date = new Date(/* some date */);
let displayVal = moment(date).startOf('day').format();
```

**Comment by eladt81** [comment]
Hi, the purpose here was not to show that the midnight hour gets disrupted if the date is before 1918.
You can view the example now on my CodePen and see that even if the hour is different (e.g. 2AM), the formatted hour will be different.

**Comment by ashsearle** [comment]
Does the 'Expected behaviour' take into account the fact that the three locations you're talking about have timezone offsets that not only include offsets in hours, but also in minutes and seconds (thanks to Chrome including accurate historic data)?  (Note that historic timezone data may not be available in all browsers, but is in Chrome.)

I quite like the timeanddate website: use the 'Time zone changes for' dropdown to check the timezone offsets in 1900-1924:
* [Jerusalem](https://www.timeanddate.com/time/zone/israel/jerusalem) - +2 hours 20 minutes 40 seconds
* [Moscow](https://www.timeanddate.com/time/zone/russia/moscow) - +2 hours 30 minutes 17 seconds
* [Baku](https://www.timeanddate.com/time/zone/azerbaijan/baku) - +3 hours 19 minutes 24 seconds

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
