### ISSUE TITLE
PL locale returns wrong data structure for months()

### ISSUE THREAD

**Issue by kevinpapst** [moment/moment#5369]
**Describe the bug**

When using the polish locale the [method months()](https://github.com/moment/moment/blob/develop/locale/pl.js#L40) returns:
```
["(stycznia|styczeń)", "(lutego|luty)", "(marca|marzec)", "(kwietnia|kwiecień)", "(maja|maj)", "(czerwca|czerwiec)", "(lipca|lipiec)", "(sierpnia|sierpień)", "(września|wrzesień)", "(października|październik)", "(listopada|listopad)", "(grudnia|grudzień)"]
```
where all other locales I have tested return the plain month names.

This was introduced a long time ago in https://github.com/moment/moment/pull/2278 

According to the documentation (how I read them) this is wrong, as calling the method without a parameter should return an array with month names, see https://momentjs.com/docs/#/i18n/listing-months-weekdays/

The docs at https://momentjs.com/docs/#/customization/month-names/ doesn't say anything else, at least I can't find any reference that this method could return an array of RegExp.

It works when using `moment.localeData('PL').months();` but I wonder if this is intended or a bug.

**Expected behavior**
When initialized with a PL locale, the call to `moment.months();` should returns the same than 
`moment.localeData('PL').months();`

**Comment by marwahaha** [comment]
I feel like it's reasonable for `months()` to return a list of month names, not month RegExp's :)

**Comment by szwacz** [comment]
This bug was introduced by https://github.com/moment/moment/pull/2278 as an attempt to fix https://github.com/moment/moment/issues/2275 (I'm the author of that).
I was looking how I solved it years ago, and it was done by a hack, because I didn't find more sane way of solving the problem. Since the solution actually broke something else (but wasn't reported for 5 years?!) I think the best option is to revert my PR. Locale API implementation in moment after my quick glance doesn't give enough flexibility to implement what I was trying to achieve without adding bugs somewhere else.

Of corese reverting this is a breaking chage.

**Comment by marwahaha** [comment]
Sorry there is an issue.
I would rather not revert the old code, but find some other solution.
Perhaps there are examples in other locales to do what you are asking. Unfortunately I cannot take the time to investigate right now.

**Comment by szwacz** [comment]
Looks like I have free time on the horizon. Will look into it.

**Comment by LocalHeroPro** [comment]
The same scenario here when I try:
```javascript
moment.locale('pl');
console.log(moment.months();
```
```
(12) ["(stycznia|styczeń)", "(lutego|luty)", "(marca|marzec)", "(kwietnia|kwiecień)", "(maja|maj)", "(czerwca|czerwiec)", "(lipca|lipiec)", "(sierpnia|sierpień)", "(września|wrzesień)", "(października|październik)", "(listopada|listopad)", "(grudnia|grudzień)"]
```

**Comment by doper1234** [comment]
@marwahaha could this PR be accepted?
