### ISSUE TITLE
Czech language does not show am/pm information in a 12hr format. 

### ISSUE THREAD

**Issue by arpitharadhakrishna** [moment/moment#5376]
The momentjs instance does not show am/pm information along with the date-time.

Here is the repro for this issue:
1) change the language setting of your browser to Czech language.
2) Open this repro link: https://jsfiddle.net/zaxfhq72/2/ and run the code.

You can see that am/pm information is missing. It does not have this issue with other locales.

**Comment by ashsearle** [comment]
The fiddle uses an old version of moment, and uses `moment().toDate()`, which returns a native `Date` which gets converted to a String by the browser - not moment.

Does `new Date().toString()` show AM/PM as required for you?

**Comment by ArpitaGhattuMicrosoft** [comment]
Hi, 

I updated the following fiddle, and used Date().toString() with the latest version of moment, correct me if I am wrong: https://jsfiddle.net/cywL8nva/. I still see this issue.

**Comment by ashsearle** [comment]
Your updated fiddle shows you're using `moment().toString()` (not `Date`'s `.toString()`, which (based on [the implementation](https://github.com/moment/moment/blob/develop/src/lib/moment/format.js#L9)) always produce a String in English, without an AM/PM indicator.

That's by design.

If you look at the unicode consortium's [survey tool for Czech](https://st.unicode.org/cldr-apps/v#/cs/Gregorian/), the 'winning' format for 'Format - Standard - Time Formats'  indicates that  Czech should be formatted in 24-hours, without AM/PM indicator anyway.

Compare:
```js
moment().locale('en').format('LLL'); // US English: "February 19, 2020 8:57 AM"
moment().locale('en-gb').format('LLL'); // British English: "19 February 2020 08:57"
moment().locale('cs').format('LLL'); // Czech: "19. únor 2020 8:57"
```

**Comment by marwahaha** [comment]
For now, we will not take this change.
Please re-open if you still have concerns.
