### ISSUE TITLE
IE11 date parse issue: moment([20, 9, 25])

### ISSUE THREAD

**Issue by arperry** [moment/moment#5380]
For a very specific date, IE11 parses incorrectly:

`moment([20, 9, 25]).format('L')` -> `"10/24/0020"`

The expectation (as seen in every other browser) is `"10/25/0020"`.

This is reproducible on the momentjs site itself when using the console in IE11. Adjacent dates (`[20, 9, 24]` and `[20, 9, 26]`) parse as expected.

Found in IE11 v11.657.18362.0 running in Windows 10.

```
console.log((new Date()).toString()) -> Thu Feb 13 2020 16:53:38 GMT-0600 (Central Standard Time)
console.log((new Date()).toLocaleString()) -> 2‎/‎13‎/‎2020‎ ‎4‎:‎53‎:‎38‎ ‎PM
console.log((new Date()).getTimezoneOffset()) -> ‎360
console.log(navigator.userAgent) -> Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; Zoom 3.6.0; rv:11.0) like Gecko
console.log(moment.version) -> 2.24.0
```

**Comment by ashsearle** [comment]
This sounds like a locale / DST thing.

Can you show the output of these from IE11:
```js
new Date('0020-10-25').toString();
new Date(420, 9, 25).toString();
```

(Yes, the second example uses the Year 420, not Year 20.)

**Comment by arperry** [comment]
`new Date('0020-10-25').toString()` -> `"Sat Oct 24 20 19:00:00 GMT-0500 (Central Daylight Time)"`
`new Date(420, 9, 25).toString()` -> `"Sat Oct 24 420 23:00:00 GMT-0600 (Central Standard Time)"`

I'm no expert on the Date specification, but that seems a little odd to me.

**Comment by arperry** [comment]
That's IE11. Here's Chrome, for reference:

`new Date('0020-10-25').toString()` -> `"Sat Oct 24 0020 18:09:24 GMT-0550 (Central Daylight Time)"`
`new Date(420, 9, 25).toString()` -> `"Sun Oct 25 0420 00:00:00 GMT-0550 (Central Daylight Time)"`

That doesn't seem any less odd.

**Comment by ashsearle** [comment]
This is all odd, I agree.

What's going on here is that `new Date(isoDateString)` will create a date set to midnight UTC, where as `new Date(year, month, day)` will create a date set to midnight local time.

It's not possible for `new Date(year, month, day)` to create a date in the range Year 0 - 100 because the browser adds 1900 to the year to create a date in the range 1900 to 2000 instead.

`moment` creates a `Date` in the year 0-100 by using knowledge of the Gregorian calendar's 400-year cycle: it'll create `new Date(year + 400, month, day)`, then subtract 400 years to get the required date back.

I think you've found the made-up boundary between CDT/CST adjustments for historic dates (far pre-dating modern time-zone regulations and rules.)

If IE11's not using setting things to an inappropriate time, there's not much moment can do about it, but... it depends what you want to achieve.

Given the 400-year cycle, can you check these dates for consistency:

```js
moment([20, 9, 25]).format('L')
moment([420, 9, 25]).format('L')
moment([820, 9, 25]).format('L')
moment([1220, 9, 25]).format('L')
moment([1620, 9, 25]).format('L')

// vs.
// new Date(20, 9, 25).toString() // not possible
new Date(420, 9, 25).toString();
new Date(820, 9, 25).toString();
new Date(1220, 9, 25).toString();
new Date(1620, 9, 25).toString();
```

Finally, you could try creating dates using `utc`, if you want to avoid the trouble of fantastical time-zone definitions from 2000 years ago:

```js
moment.utc([20, 9, 25]).format('L')
moment.utc([420, 9, 25]).format('L')
moment.utc([820, 9, 25]).format('L')
moment.utc([1220, 9, 25]).format('L')
moment.utc([1620, 9, 25]).format('L')
```

**Comment by arperry** [comment]
In IE11:

`moment([20, 9, 25]).format('L')` -> `10/24/0020`
`moment([420, 9, 25]).format('L')` -> `10/24/0420`
`moment([820, 9, 25]).format('L')` -> `10/24/0820`
`moment([1220, 9, 25]).format('L')` -> `10/24/1220`
`moment([1620, 9, 25]).format('L')` -> `10/25/1620` (!!)

`new Date(420, 9, 25).toString();` -> `"Sat Oct 24 420 23:00:00 GMT-0600 (Central Standard Time)"`
`new Date(820, 9, 25).toString();` -> `"Sat Oct 24 820 23:00:00 GMT-0600 (Central Standard Time)"`
`new Date(1220, 9, 25).toString();` -> `"Sat Oct 24 1220 23:00:00 GMT-0600 (Central Standard Time)"`
`new Date(1620, 9, 25).toString();` -> `"Sun Oct 25 1620 00:00:00 GMT-0500 (Central Daylight Time)"`

The `moment.utc` suggestion is a sensible one; I may have to go that route.

**Comment by marwahaha** [comment]
I'm not sure we can change anything in Moment to prevent this from happening.
Sorry you're experiencing this.
Please re-open if you still have concerns.
