### ISSUE TITLE
format YYYY-M-D is invalid date on iphones

### ISSUE THREAD

**Issue by simonppg** [moment/moment#5392]
I cant create a moment date using this format YYYY-M-D in iphones, I am able to reproduce iit only in a iphone 6s

**To Reproduce**
alert(moment('2020-1-1')); on PC => Wed Jan 01 2020 00:00:00 GMT-0700
alert(moment('2020-1-1')); on iphone  => undefined undefined NaN 0NaN NaN:NaN:NaN GTM+0000

![iphone_moment](https://user-images.githubusercontent.com/3270997/74786707-9c44ff80-526a-11ea-9adb-3d7e081f3979.jpeg)

**Comment by marekwrobel** [comment]
I was able to reproduce the issue - https://jsfiddle.net/y3g19h4n/1/

Indeed it works fine on desktop browsers and fails on mobile browsers (at least both chrome and safari on iOS). 

The reason behind this is that the format itself is not the RFC2822 or ISO recognized format.

You can actually see the **deprecation warning** that gets logged on the console:

> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

Moment does not accept that format (YYYY-M-D) and therefore falls back to js Date which causes issues on mobile browsers. For example this:

```
let date = new Date('2019-1-1')
alert(date);
```

causes the same issue on mobile browsers and does not even use moment.

The fix would be to add such formatting option to moment, but I guess this is not a good idea since it's not the RFC2822 or ISO recognized format.

**Comment by simonppg** [comment]
oh I see, I will change the format then, thank you @marekwrobel, but shouldn't the warning be on the desktop too?, this way I could have detected it earlier.

**Comment by marekwrobel** [comment]
@simonppg There actually is a warning on desktop browsers that shows on the console. 

If you use google chrome - go to that example - https://jsfiddle.net/y3g19h4n/1/ - and open the dev tools and see the console warnings. You should see the message that I quoted in my previous comment.

**Comment by simonppg** [comment]
oh I miss that, sorry for lose your time, I'll close this
