### ISSUE TITLE
moment().diff(Moment|String|Number|Date|Array, String, Boolean);

### ISSUE THREAD

**Issue by jingzhaoxia** [moment/moment#5415]
let start = this.$Moment("2020-01-01");
let end = this.$Moment("2020-12-31");
let y = end.diff(start, 'years', true);
console.log(y); //=>0.9973118279569894

**Comment by sampathBlam** [comment]
@jingzhaoxia : What exactly is the issue here? 
I see that you are trying to find the difference between the first and last day of the year. 
And moment is returning a value less than 1 because, the difference between the first day and last day of the ear is not exactly 1 year but just a day less than that. 

If the code was, 
```
let start = this.$Moment("2020-01-01");
let end = this.$Moment("2021-01-01");
let y = end.diff(start, 'years', true);
```

console.log would have returned 1. 

Kindly let us know if it makes sense.

**Comment by marwahaha** [comment]
I agree with @sampathBlam 
Thanks for opening this request.
Please re-open if you still have issues.
