### ISSUE TITLE
For zh-cn, calendar() uses 24hr clock, format('LLL') uses 12-hour

### ISSUE THREAD

**Issue by radcapitalist** [moment/moment#5416]
**Describe the bug**
It's 4:22 in the afternoon.  If I do:

moment().locale('zh-CN').calendar();

I get back:

今天16:22     (24-hour clock)

If I do:

moment().locale('zh-CN').format('LLL');

I get back:

2020年3月20日下午4点22分      (12-hour clock)

Why the inconsistency?  Our testers in Beijing were the ones who noticed, so I don't think this is okay with the Chinese.

**To Reproduce**
1. Run this JavaScript in node.js

/* eslint-disable no-console */
const moment = require('moment');
console.log(moment().locale('zh-CN').calendar());
console.log(moment().locale('zh-CN').format('LLL'));

2. In the console, see that the first formats with 24-hour clock, the second with 12-hour.

**Expected behavior**
I expect both of these formatting statements to use the same hour format, 12-hour or 24-hour.  They should be consistent with one-another.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Node.js, 10.17
 - Version of moment.js is 2.24.0

**Moment-specific environment**

* Eastern DaylightTime
* March 20, 2020, 4:22 PM (16:22)
* Other libraries in use: None

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
Fri Mar 20 2020 16:40:09 GMT-0400 (Eastern Daylight Time)
3/20/2020, 4:40:09 PM
240
2.24.0

**Comment by Alanscut** [comment]
what  do you think @zenozeng ?

**Comment by marwahaha** [comment]
What do you think @uu109 ?

**Comment by uu109** [comment]
In the current version, `LLL` will output time in 12-hour clock, and if you want a 24-hour, you can use
`moment().locale('zh-CN').format('lll');`

**Comment by marwahaha** [comment]
@uu109 do you recommend a change to `moment().locale('zh-CN').calendar();`?

**Comment by uu109** [comment]
@marwahaha No, `moment().locale('zh-CN').calendar();` running results are correct and appropriate.

**Comment by randallmeeker** [comment]
I wanted to follow up on this. I'm in multiple languages. Some places in my app I just need time so I also see 24 hour, but when using the full date, I see 12 hour format. Changing the format from `LLL` or `lll` will do this for all my locales thus shortening the month on English for example. 

I'm mostly just interested in the discrepancy. Is this how its supposed to be for those speaking the language? Are they used to the full date having a 12h instead of 24h? and both when just time is needed. 

Or is this indeed inconstant and would require a change?
