### ISSUE TITLE
[question]Problems encountered in pl.js

### ISSUE THREAD

**Issue by Alanscut** [moment/moment#5538]
**Describe the issue**
@evoL I encountered a confusing problem when solving an error. Although `grudnia`  and ` grudzień` both represent December, is it reasonable to have inconsistent input and output :)?

**To Reproduce**
```javascript
moment.locale('pl')
console.log('grudnia-MMMM', moment('grudnia', 'MMMM', true).format('MMMM')) // grudzień
```
**Source Code**
https://github.com/moment/moment/blob/develop/src/locale/pl.js#L51
```javascript
// pl.js
months: function (momentToFormat, format) {
        if (!momentToFormat) {
            return monthsNominative;
        } else if (format === '') {
            // Hack: if format empty we know this is used to generate
            // RegExp by moment. Give then back both valid forms of months
            // in RegExp ready format.
            return (
                '(' +
                monthsSubjective[momentToFormat.month()] +
                '|' +
                monthsNominative[momentToFormat.month()] +
                ')'
            );
        } else if (/D MMMM/.test(format)) {
            return monthsSubjective[momentToFormat.month()];
        } else {
            return monthsNominative[momentToFormat.month()];
        }
    },
```
moment@2.25.3

thanks in advance

**Comment by evoL** [comment]
Hello,
It's unclear to me what the issue is here. Could you please elaborate on what you want to achieve?

It's true that the form _grudnia_ isn't correct on its own. It's used only in conjunction with numerals, think "_5. grudnia_". That said, I think it's alright that we're on the loose side when it comes to parsing. Moment can be used to parse user-provided strings and we don't have control over what people are writing :)

Now, when it comes to formatting dates, we can actually strive to make the output grammatically correct. This is exactly what happens here: Moment parses a grammatically incorrect month name (since it lacks a numeral), but recognizes the correct month anyway. When Moment formats the month name, it outputs it in the correct case.

Again, I think this is a good trade-off to make — be forgiving when parsing, strive for correctness when formatting. However, let me know your thoughts on this; I'm all ears :)

**Comment by Alanscut** [comment]
Hi, Thank you very much for your quick reply. I hope the input and output are equal in the same tokens. I may need to change my plan 😿, as you said, we don't have control over what people are writing :).

```javascript
moment('grudnia', 'MMMM', true).format('MMMM') === 'grudnia' // true
```
