### ISSUE TITLE
.format() may reset time of the date

### ISSUE THREAD

**Issue by lundibundi** [moment/moment#5571]
**Describe the bug**
`.format` operation on `moment.js` date may reset time of the date.
Doesn't look like expected behavior to me, perhaps I have missed something in docs?

**To Reproduce**
```js
const m = require('moment');

const start = m(0);

console.log(start.toISOString());
// Prints: 1970-01-01T00:00:00.000Z

start.add(2, 'hour');
console.log(start.toISOString());
// Prints: 1970-01-01T02:00:00.000Z

console.log(start.format('yyyy-MM-DD'));
// Prints: 1970-01-01

console.log(start.toISOString());
// Prints: 1969-12-31T21:00:00.000Z
```
(Same behavior is seen with `moment.utc()`)

**Expected behavior**
The `.format` operation should leave the date unchanged.

**Desktop (please complete the following information):**
 - OS: ArchLinux
`uname -a`:
`Linux zou 5.6.14-arch1-1 #1 SMP PREEMPT Wed, 20 May 2020 20:43:19 +0000 x86_64 GNU/Linux`

**Moment-specific environment**

* The time zone setting of the machine the code is running on `EEST +0300`
* The time and date at which the code was run `Fri May 29 13:35:52 EEST 2020`
* Other libraries in use (TypeScript, Immutable.js, etc) `none`

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
//console.log(navigator.userAgent) run in Node.js
console.log(moment.version)
```
```
Fri May 29 2020 13:37:04 GMT+0300 (Eastern European Summer Time)
5/29/2020, 1:37:04 PM
-180
2.26.0
```

**Comment by marwahaha** [comment]
Thanks for the report. This looks very strange.

**Comment by darklam** [comment]
@marwahaha  I debugged this just now, it looks like when yyyy is used instead of YYYY the getEraYear() function is called which calls this.startOf('day') and manipulates the moment instance. The easiest fix was to change the line 76 in format.js under the moment folder from
`var output = formatMoment(this, inputString);`
to
`var output = formatMoment(this.clone(), inputString);`
However, as I am not familiar with the source code, the getEraYear() function might also be causing issues elsewhere. Any ideas what would be the best fix?
(Sorry if I am completely wrong about something, half an hour ago was the first time I dug in the source code because this issue seemed very weird 😛 )

**Comment by matortheeternal** [comment]
Please merge this PR!

**Comment by pgAdmin** [comment]
The PR has been approved. 
https://github.com/moment/moment/pull/5580
@matortheeternal Once merged, it will fix the issue.
