### ISSUE TITLE
Black Lives Matter

### ISSUE THREAD

**Issue by gevhambarzumyan93** [moment/moment#5644]
and wtf is this Black Lives Matter??

I thought I go to moment.js page, not on a propaganda page

**Comment by TundraFizz** [comment]
I agree. It's so annoying how Americans keep shoving their political problems into my face. It's just obnoxious spam at this point.

**Comment by nikolawan** [comment]
Мир ебанулся

**Comment by reincore** [comment]
This seems to be more of a personal issue, not one with the library.

**Comment by gevhambarzumyan93** [comment]
I haven't any "personal issue" with this "bs". every one feeding us whid it. and now moment js how haven't any connection with this. so maybe it's enough.

**Comment by ken107** [comment]
In the communist country from where I came, students were made to recite slogans of the party, and we could see large banners of those slogans everywhere we go.  The authoritarian government wanted to make sure everyone is on the same page...

For those who wants justice: Equality of opportunity is the only true justice.  Equality of opportunity should be the ONLY type of equality the social justice movement be concerned with.  But as it stands, the movement is something much more sinister.

The social justice movement, if it had been pure in aim, has now been co-opted by radical Marxists.  Marxists are power-craving authoritarians who are obsessed with inequality, and want an authoritarian government to take from the haves and give it to the have-nots, regardless of merit.  That last part is important, because not all inequality is caused by injustice.  The radical Marxists, however, do not care about the distinction.

In the 20th century, the focus was on wealth inequality, and under the guise of compassion they pitted the poor against the rich.  The ensuing class warfare resulted in some 60 million deaths, multiple times the work of Adolf.  And even though their meritless utopian ideal were thoroughly discredited, they did not give up.  Since then they've come up with a new plan.  Now they pit black against white, gay against straight, women against men.  Different players; same game.

The number of unarmed black people killed by police last year can be counted on your fingers.  And it is not out of proportion, demographically, when the crime rate per capita is taken into account.  There is no rational basis at all for the ongoing racial unrest.  There is no data supporting it, and such policy prescriptions as defunding the police are patently insane.  Truth is, the radical Marxists want to defund the police so that their roaming mobs can exert power over your community, like what's happening in Portland and Seattle.  That's what they really mean by "reimagining public safety", as the NYT called it.

As authoritarians, they want to use their power to squash ideological nonconformity.  Instead of earnest debate and open-minded inquiry, they'd rather just shut you down, using mob intimidation and cancel culture.  Last week in Washington a group of BLM protesters entered a restaurant and asked everyone to raise their fist to show their solidarity.  If the reader thinks that that is somehow okay, then the reader does not understand what mob rule is, and has taken for granted the freedom and liberty that millions of your predecessors gave their lives to protect.

**Comment by JasonLandbridge** [comment]
It's pathetic how this propaganda gets pushed into open source projects by weird hair color idiots pretending to give a damn about [insert non-issue here].

**Comment by AlejandroMut** [comment]
Agreed. This is insufferable propaganda that needs to stop. I'm using https://date-fns.org/ from now on.

**Comment by MarcGodard** [comment]
I read this quote that I liked: 

"I don’t think it’s helpful to push the minority population to exaggerate their suffering. I think it’s important to know where the problems are but this hyperbolic approach of decrying systemic racism in every institution, in the entire country, and everyone in it as corrupt and racist...well first off I don’t believe that to be true and second of all that does not admit for any solutions on a practical level."
