### ISSUE TITLE
Can't parse some months in Hindi locale

### ISSUE THREAD

**Issue by altro3** [moment/moment#5692]
**Describe the bug**

Use next parse command:
```
moment(value, ["MMMM DD, YYYY", "MMMM DD YYYY", "DD MMMM YYYY", "DD MMM YYYY", "DD MMM. YYYY", "MMM. DD YYYY", "YYYY/MM/DD", "YYYY/M/DD", "MMM DD YYYY", "MMM DD, YYYY", "MMM. DD, YYYY", "YYYY-MM-DD", "L", "LL", "LLL", "LLLL"], 'hi')
```

Two examples (correct parse and wrong):

1. Try to parse `11 अगस्त 2018` (in ISO format: 2018-08-11). In result we will see Moment object:
```
Moment {
 _isAMomentObject = true
 _i = "11 अगस्त 2018"
 _f = "DD MMMM YYYY"
 _l = "hi"
 _isUTC = false
 _isValid = true
...
```
That is correct, found right date format.

2.  Try to parse `13 फरवरी 2018` (in ISO format: 2018-02-13). In result we will see Moment object:
```
_isAMomentObject = true
_i = "13 फरवरी 2018"
_f = "YYYY/MM/DD"
_l = "hi"
_isUTC = false
_isValid = false
...
```

As you see, found wrong format for this date - "YYYY/MM/DD"

moment lib version: 2.27.0

### **UPDATED**

I wrote jest test for hindi locale:

```
import moment from "moment";

describe('Parse date tests', () => {

    test.each([

        // hindi
        ["11 जनवरी 2018", "hi", new Date(2018, 0, 11)],
        ["11 फरवरी 2018", "hi", new Date(2018, 1, 11)],
        ["11 मार्च 2018", "hi", new Date(2018, 2, 11)],
        ["11 अप्रैल 2018", "hi", new Date(2018, 3, 11)],
        ["11 मई 2018", "hi", new Date(2018, 4, 11)],
        ["11 जून 2018", "hi", new Date(2018, 5, 11)],
        ["11 जुलाई 2018", "hi", new Date(2018, 6, 11)],
        ["11 अगस्त 2018", "hi", new Date(2018, 7, 11)],

        ["11 सितंबर 2018", "hi", new Date(2018, 8, 11)],
        ["11 अक्टूबर 2018", "hi", new Date(2018, 9, 11)],
        ["11 नवंबर 2018", "hi", new Date(2018, 10, 11)],
        ["11 दिसंबर 2018", "hi", new Date(2018, 11, 11)],
    ])('testParseDate %s, %s', (dateStr: string, language: string, mustBe: Date) => {

        var mom = moment(dateStr, ['DD MMMM YYYY'], language);
        var parsed = mom.toDate();
        // console.log(`Parsed: ${parsed}, mustBe: ${mustBe}`);
        // console.log(`Formatted: ${mom.locale('en').format('YYYY-MM-DD')}`);

        expect(parsed.getFullYear())
            .toBe(mustBe.getFullYear());
        expect(parsed.getMonth())
            .toBe(mustBe.getMonth());
        expect(parsed.getDate())
            .toBe(mustBe.getDate());
    });
});
```

Result: moment can't parse next months:

```
फरवरी  - Febrary
सितंबर  - September
नवंबर - November
दिसंबर - December
```

Other months parsed correctly.

**Comment by marwahaha** [comment]
@mayanksinghal ?

**Comment by Kartik18g** [comment]
Hey , i tried
 moment(value, ["MMMM DD, YYYY", "MMMM DD YYYY", "DD MMMM YYYY", "DD MMM YYYY", "DD MMM. YYYY", "MMM. DD YYYY", "YYYY/MM/DD", "YYYY/M/DD", "MMM DD YYYY", "MMM DD, YYYY", "MMM. DD, YYYY", "YYYY-MM-DD", "L", "LL", "LLL", "LLLL"], 'hi')
but it doesn't return an Moment Object

**Comment by PriyaBihani** [comment]
I was able to recreate your issue. I found out that this is because of the inflections that exists in Hindi language. For example :  दिसंबर (what you wrote)can be written as दिसम्बर(what is written in code), 
सितंबर - सितम्बर,
नवंबर - नवम्बर,
फरवरी - फ़रवरी,
So, in order to resolve this issue I added format and standalone feature like in Russian language.  After modifying locale file of Hindi, I also modified the test/locale/hi.js in order to pass all the tests. 
I have created a pull request to fix this issue. Until, this pull request get accepted the work around is to use these months:  दिसम्बर, सितम्बर, नवम्बर, फ़रवरी.
![testCasesPassed](https://user-images.githubusercontent.com/69837339/93898944-6b9dda80-fd11-11ea-9805-4d63c09af1fd.JPG)
