### ISSUE TITLE
Parsing with format DMMYYYY 

### ISSUE THREAD

**Issue by flaushi** [moment/moment#5725]
**Describe the bug**
The result of this should be 1st of September 2006, right?
```
moment('1092006', 'DMMYYYY', true)
```
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser electron
 - Version 8.4

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use TypeScript 3.9.5

Please run the following code in your environment and include the output:
```
  console.log
    Thu Sep 17 2020 16:27:36 GMT+0200 (Mitteleuropäische Sommerzeit)

      at Object.<anonymous> (src/Processors/HLProcessor.test.ts:9:13)

  console.log
    17.9.2020, 16:27:36

      at Object.<anonymous> (src/Processors/HLProcessor.test.ts:10:3)

  console.log
    -120

      at Object.<anonymous> (src/Processors/HLProcessor.test.ts:11:13)

  console.log
    Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/15.2.1

      at Object.<anonymous> (src/Processors/HLProcessor.test.ts:12:13)

  console.log
    2.27.0

      at Object.<anonymous> (src/Processors/HLProcessor.test.ts:13:13)

```

**Comment by MinusFour** [comment]
It's sort of ambiguos. `D` can be double digits, `MM` is always 2 digits. I think `moment` matches `D` and `M` greedily so if there's multiple digits close to each other it will take those even if they are not valid. In this case I believe `D` is matching `10`. `MM` is matching `92` hence invalid and `YYYY` is not matching anything (also makes date invalid).

You can just pad the string with a `0` and use `DD` instead of `D`.
