### ISSUE TITLE
"Status update" feedback

### ISSUE THREAD

**Issue by uripre** [moment/moment#5776]
Hi there, a long time user of momentjs here.

I just read the status update and the recommendation to use other libraries. I just wanted to share my feedback that the status update seems a bit too harsh. At first look it seems very intimidating that this library has been declared as "legacy". Reading more carefully, if maintenance is indeed still happening as mentioned, I'm not sure there is a need in such a bold statement. 

I think the library is well known by millions, the most popular one to date, referenced in numerous StackOverflow discussions, and well tested for many years. Its mutability is already well known by its users, so unless someone cares a lot about the bundle size - I don't see a real reason not to use it. 

Personally, I would maybe include an advice to consider alternatives IF x and y, but would not declare this library as legacy.

**Comment by marwahaha** [comment]
Thanks for the feedback. If you are comfortable with the amount of maintenance Moment.js is getting, feel free to continue to use the library. We tried to explain what we mean by "legacy" in the post, since it has many meanings among developers. We put out this notice in part because:
1. We expect to put in fewer maintenance hours in the future.
2. This library may not update to support new JavaScript features and frameworks.
3. The strongly worded update gets attention of more Moment.js users out there, in case they would like to switch.

A central point of open-source software is that you can use this code if you like, but you cannot necessarily expect support. Quoting from the [license](https://github.com/moment/moment/blob/develop/LICENSE): "Permission is hereby granted, free of charge, to any person..."
