### ISSUE TITLE
moment().calendar() is in lowercase in Dutch

### ISSUE THREAD

**Issue by Bas950** [moment/moment#5881]
**Describe the bug**
moment().calendar()  in Dutch gives `vandaag om xx:xx` (the v is not capitalized), if I do English it has a capitalized T of Today.

**To Reproduce**
1. moment.locale("nl")
2. moment().calendar() 

**Expected behavior**
It to show as `Vandaag` instead of `vandaag`

**Screenshots**
![image](https://user-images.githubusercontent.com/34792838/116831589-9d80f480-abb0-11eb-95b1-caa3f8e038f0.png)
![image](https://user-images.githubusercontent.com/34792838/116831592-a2de3f00-abb0-11eb-9abd-b03266b10ac3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 90.0.4430.93

**Moment-specific environment**

* The time zone setting of the machine the code is running on
UTC+01:00
* The time and date at which the code was run
3-5-2021 01:44:54
* Other libraries in use (TypeScript, Immutable.js, etc)
Typescript + https://www.npmjs.com/package/moment (v2.29.1)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

```
Mon May 03 2021 01:44:54 GMT+0200 (Midden-Europese zomertijd)
3-5-2021 01:44:54
-120
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
2.29.1
```

**Additional context**
N/A

**Comment by Bas950** [comment]
Just noticed pretty much everything is lowercase in the Dutch locale, I will probs make a pr later.

**Comment by Bas950** [comment]
@middagj @jorisroling ik zie dat jullie dit als eerste hebben gemaakt, maar zouden de dagen etc niet in de correct hoofdletters moeten zijn?
(vandaag -> Vandaag, januari -> Januari, etc.)

**Comment by middagj** [comment]
Yes, that is the official spelling. See:
 * [Onze Taal](https://onzetaal.nl/taaladvies/oktober-october/)
 * [Vlaamse overheid](https://www.vlaanderen.be/taaladvies/namen-van-dagen-hoofdletter)
 * [Rails i18n](https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/nl.yml)

In English days of the week and month are capitalized. I don't know about _Today_ and _Tomorrow_. I thought not, but I am not an expert. In Dutch _vandaag_ is not capitalized. If you need capitalization because it is the first word of the sentence, then it should be added by the user I guess as the library cannot infer where you use it in the sentence.

**Comment by Bas950** [comment]
> If you need capitalization because it is the first word of the sentence, then it should be added by the user I guess as the library cannot infer where you use it in the sentence.

Yea I was thinking of that, because of the "Eerste letter in de zin, is een hoofdletter".
That's why I thought "Vandaag" should've been capitalized, but for consistency with the rest you might as well keep it lowercase.
