### ISSUE TITLE
Doing a `dateOf()` of `moment(moment.utc().valueOf())` gets inconsistent results

### ISSUE THREAD

**Issue by ItzaMi** [moment/moment#5916]
**Describe the bug**
Currently I have a project where I need to get a `Date Object` of an `UTC moment`. I even exposed my doubt [here](https://github.com/moment/moment/issues/5915) because what should work really isn't.
Posting my doubts on StackOverflow (can be seen [here](https://stackoverflow.com/questions/68458122/how-do-i-get-a-date-object-on-momentjs-but-as-utc-prevent-todate-from-being/)) showed the following should work:

```javascript
// this logs a Moment object
const date = moment(moment.utc().valueOf())

// This will output something like 2021-07-20T16:14:39.636Z
const dateObj = date.toDate()

console.log("UTC time: ", dateObj)
```

However, locally I'm not getting this result. I'm instead getting my `locale time`.
I tested this on `CodePen` and I got the same results as above on the code but on [CodeSandbox](https://codesandbox.io/s/quizzical-khayyam-xig72?file=/src/index.js:72-102) I have the same results that locally

**To Reproduce**
1. Initialize a project with `momentJS`
2. Insert the code above
3. See the result retrieved and if it's coherent with what's expected

**Expected behavior**
Expected to `log` a `Date object` with `UTC`

**Screenshots**
<img width="432" alt="Screenshot 2021-07-21 at 13 42 38" src="https://user-images.githubusercontent.com/30603437/126490228-f972a00d-8ea7-4072-bc8e-547817492c3b.png">

<img width="1110" alt="Screenshot 2021-07-21 at 13 43 12" src="https://user-images.githubusercontent.com/30603437/126490317-314ade3c-6dec-42a8-9cce-ce5e05e0428d.png">

**Desktop (please complete the following information):**
 - OS: iOS 11.2.3
 - Chrome
 - Version 91.0.4472.114 (Official Build) (arm64)

**Moment-specific environment**

* GMT+1
* Wed Jul 21 2021 13:43:03 GMT+0100 (Western European Summer Time)

Please run the following code in your environment and include the output:
```
Wed Jul 21 2021 13:44:46 GMT+0100 (Western European Summer Time)
21/07/2021, 13:44:46
-60
Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Mobile Safari/537.36
2.29.1
```

**Comment by marwahaha** [comment]
Thanks for opening this request. 

I don't really understand what you are doing. Can you help me understand?

Let me walk through command by command.
* moment.utc() --> makes a Moment object for right now, in UTC mode https://momentjs.com/docs/#/manipulating/utc/
* .valueOf() ->  gets # of milliseconds since unix epoch https://momentjs.com/docs/#/displaying/unix-timestamp-milliseconds/ . *by the way, this should work the same regardless of UTC mode*
* moment( ) -> makes a new moment object *why do you do this? You already had a moment object.*
* const dateObj = date.toDate() -> gets date object from moment https://momentjs.com/docs/#/displaying/as-javascript-date/
https://momentjs.com/docs/#/displaying/as-javascript-date/

* console.log("UTC time: ", dateObj) -> prints out date object. *you are directly printing out the date object. why do you expect this to be in UTC time?*

If you want to print the date object in UTC time, you can use dateObj.toUTCString() .

For example old code:
```
// this logs a Moment object
const date = moment(moment.utc().valueOf())

// This will output something like 2021-07-20T16:14:39.636Z
const dateObj = date.toDate()

console.log("UTC time: ", dateObj)
> UTC time:   Date Sat Aug 14 2021 13:38:08 GMT-0700 (Pacific Daylight Time)
```

New code:
```
// this logs a Moment object
const date = moment(moment.utc().valueOf())

// This will output something like 2021-07-20T16:14:39.636Z
const dateObj = date.toDate()

console.log("UTC time: ", dateObj.toUTCString())
> UTC time:  Sat, 14 Aug 2021 20:39:00 GMT
```


So I think the issues you are facing have to do with the way your browser prints out JavaScript Date objects. Fortunately you can use a date method like toUTCString() to get what you are looking for.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

I hope this answers your question!

**Comment by ItzaMi** [comment]
@marwahaha , my issue here is that on different environments the same logic shows me different results. As you can see from my [CodeSandbox](https://codesandbox.io/s/momentjs-bug-yvjie?file=/src/index.js) and my [StackOverflow question](https://stackoverflow.com/a/68458205/10136219), the same method is `logging` different results and I'm not sure why this actually happens.
This `issue` filed here was intended to understand why this happens

**Comment by marwahaha** [comment]
The `console.log(..., dateObj)` prints the JavaScript Date object. That depends on how the browser decides to print the native JavaScript date (which doesn't have to do with Moment).

When you print an object there are many things that could be printed. So I recommend using a method to always print the same thing on all machines. For example, if you try my new code, does it give the same output everywhere?
