### ISSUE TITLE
Bug `isSame` for granularity `date` or `day` 

### ISSUE THREAD

**Issue by mhenke96** [moment/moment#6040]
**Describe the bug**
Comparing two dates, which are clearly the same day, via the `isSame` function and the granularity `date` or `day` returns `false`.

**To Reproduce**
```js
moment('2022-08-14T22:00:00.000Z').isSame('2022-08-14T16:00:00.000Z', 'date') // => false
moment('2022-08-14T22:00:00.000Z').isSame('2022-08-14T16:00:00.000Z', 'date') // => false
moment('2022-08-14T16:00:00.000Z').isSame('2022-08-14T22:00:00.000Z', 'day') // => false
moment('2022-08-14T16:00:00.000Z').isSame('2022-08-14T22:00:00.000Z', 'day') // => false
```

**Expected behavior**
I expect the to get returned `true`. Or am I missing something regarding the desired outcome of this function?

**Desktop (please complete the following information):**
 - OS: macOS (Sillicon)
 - NodeJS v16.16.0
 - moment v2.29.4

**Moment-specific environment**

* Time zone: GMT+2
* Time and date of test run: 2022-08-14T14:15:34.279Z
* Other libraries: TypeScript

```
new Date().toString():  Sun Aug 14 2022 16:15:34 GMT+0200 (Central European Summer Time)
new Date().toLocaleString():  8/14/2022, 4:15:34 PM
new Date().getTimezoneOffset():  -120
navigator.userAgent: ReferenceError: navigator is not defined
moment.version:  2.29.4
```

**Comment by IvaTsu** [comment]
Hey @mhenke96,

According to the [isSame](https://momentjs.com/docs/#/query/is-same/) docs, it is stated that the first argument will be parsed as a `moment`, if not already so.

If you convert the date string `2022-08-14T22:00:00.000Z` to a moment, it will be `Moment<2022-08-15T00:00:00+02:00>` (likely because of your CEST).

I assume that's why you are getting `false` here: `moment('2022-08-14T22:00:00.000Z').isSame('2022-08-14T16:00:00.000Z', 'date')`.

But if you do `moment.utc('2022-08-14T22:00:00.000Z').isSame('2022-08-14T16:00:00.000Z', 'date')` the output will be `true`.

**Comment by mhenke96** [comment]
Appreciate. Works well!
