### ISSUE TITLE
Texas uses daylight savings all year round

### ISSUE THREAD

**Issue by kylewatkins1202** [moment/moment#6070]
**Describe the bug**
Texas passed a law this past March stating, they will observe Daylight savings all year round. The time getting returned for "America/Houston" is off by an hour.

**To Reproduce**
1. moment.tz("America/Houston").format('MMMM Do YYYY, h:mm:ss a');

**Expected behavior**
The time should be off by one hour

Please run the following code in your environment and include the output:
```
moment.tz("America/Houston").format('MMMM Do YYYY, h:mm:ss a');
```

**Additional context**

**Comment by gilmoreorless** [comment]
> The time getting returned for "America/Houston" is off by an hour.

Moment Timezone doesn't provide any data for `America/Houston`, because that's not a zone that exists in the [IANA tzdb source files](https://data.iana.org/time-zones/data/northamerica). If you're using `America/Houston` as a valid zone, then the data has come from outside this project.

> Texas passed a law this past March stating, they will observe Daylight savings all year round.

No, they didn't. Do you have a source for this? Texas definitely still observes clock changes: https://www.timeanddate.com/time/zone/usa/texas
The only relevant thing that happened in March was the _Federal_ Sunshine Protection Act getting approved by the Senate. But that bill hasn't passed the House of Representatives yet, which means it isn't an enacted law.
* https://www.timeanddate.com/news/time/us-permanent-dst.html
* https://www.timeanddate.com/time/us/daylight-saving-usa.html
