### ISSUE TITLE
Add ability to specify year before parsing, or auto-guess the year

### ISSUE THREAD

**Issue by dmitrygorbenko** [moment/moment#6106]
I need parse string like this:
`moment('Mon Dec 06, 9:30am CST', 'ddd MMM DD, h:mma')`
Today is 2023, and this string is from 2021, so if you try this:
`moment('Mon Dec 06 2021, 9:30am CST', 'ddd MMM DD YYYY, h:mma').isValid()`
it's gonna work.

I'd like to add some ability to specify the year before parsing happens, like
`moment.year(2021).parse('Mon Dec 06, 9:30am CST', 'ddd MMM DD, h:mma')`
Or the moment can try to auto-guess the year by trying 2023, then 2022, and so on (I don't know how far into the past it makes sense to travel, but i guess there can be some limit)

Thanks

**Comment by sanchej** [comment]
Hello @dmitrygorbenko, I am going around checking out issues and I saw your request. I figured out a function but was wondering if you would give me some more context as to what you would like the function to output/do. I currently have it so that it can receive a date with a format beginning in 'ddd MMM DD'. Once the date and format are received, it parses backwards from the year provided or the current year by default until it finds a valid date. It then returns the date. I wanted to know if you wanted it to return the moment object of the date and for clarity it would probably be called like

```
moment.yearguess('Mon Dec 06, 9:30am CST', 'ddd MMM DD, h:mma')
```

or if you want to specify the year:

```
moment.yearguess('Mon Dec 06, 9:30am CST', 'ddd MMM DD, h:mma', 2023)
```

**Comment by dmitrygorbenko** [comment]
Hey, @sanchej , thank you for taking a look at this issue, and sorry for late response. I should set up my notifications.
I find the first option
`moment.yearguess('Mon Dec 06, 9:30am CST', 'ddd MMM DD, h:mma')`
is more generic and this is what I'd like to have, while the second
`moment.yearguess('Mon Dec 06, 9:30am CST', 'ddd MMM DD, h:mma', 2023)`
can be used to specify the starting year to search from. Like, instead of searching from 2023 we can specify 1967.

thanks !

**Comment by ichernev** [comment]
There is no such functionality ATM. There is a function that gets the current year (for filling/guessing purposes) and we have a `new` method to return now. You could add a defaultNow method that returns a date to be used for defaulting, and then overwrite that. You can submit a PR. Or you can try to just change now, if you're not using `moment()` or just wrap a function that replaces now just for the constructor and then restores it.
