### ISSUE TITLE
valueOf() issues

### ISSUE THREAD

**Issue by newboolean** [moment/moment#6188]
**Describe the bug**
Directly obtaining valueOf() and utc(). valueOf() obtains the same value

**To Reproduce**
The timestamp of Dongba District is the same as the timestamp obtained from the zero time zone

**Expected behavior**
The timestamp of Dongba District and the timestamp of Zero Time Zone should be interpolated

**Screenshots**
![image](https://github.com/moment/moment/assets/49263295/fc040de7-b89a-41d6-8092-1ae2c5f6ed28)

**Desktop (please complete the following information):**
 - OS: [window]
 - Browser [chrome]
 - Version [119.0.6045.160]

**Comment by animeshsgit** [comment]
Hi, I believe this is an expected behavior as per the documentation, please refer below link

https://momentjs.com/docs/#/parsing/utc/

![image](https://github.com/moment/moment/assets/108583433/b1441f6d-69d0-4107-ab1c-36666f5d5ff4)

Project owner can confirm on this.

Thanks
Animesh Raj
(Happy to contribute)
