### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by sanderd17** [moment/moment#731]
When you give the format to the Moment.js function, it works in many cases slower than just giving no format.

Compare these tests: http://jsperf.com/moment-js-parse-iso-date/8

Sometimes, the difference is really big.

It looks like, when you don't give a format, moment.js test if it's in ISO format, and calls a native function. If you give a format, it just starts regexing and loses time.

Would it be possible to first test if the given format is an ISO format, and if it is, work with the native function?

**Comment by csvan** [comment]
Out of curiosity, has this performance gap closed in the 2+ years since this issue was opened?

**Comment by csvan** [comment]
To answer my own question, not really. `new Date()` is still about 150x faster than `moment` for unqualified date strings:

http://jsperf.com/moment-js-parse-iso-date/9

@timrwood I unfortunately not too familiar with the parser internals of `moment`, but is there a compelling reason not to user `Date` directly in it? Especially since cross-browser support seems to be rather consistent by now?

**Comment by GeekStocks** [comment]
Long story short, I am here because I was searching about Moment performance being so gawd-awful. I love all the bells and whistles, but I will begin limiting it to small, non-looping loads. I have a need to loop over a CSV file containing 14.8 million records and branch based on date. I was using:

`if (moment(strDate, "YYYY-MM-DD").isSameOrAfter(startDateMoment)) {<snip>}`

This took 530,702ms (8.8 minutes). After crying, I retooled using new Date(). Result: 39836ms (40 seconds). Not even close.

**Comment by lauriro** [comment]
@GeekStocks one nice thing about dates and times in iso format is that they are string comparable.
Next time try just `if (strDate >= "2017-05-29") {<snip>}`

**Comment by codeaid** [comment]
For those coming here in the future - I created a similar but more detailed version of the test above.

I wanted to see the difference in performance between using string dates and timestamps with both, `Date` and Moment.js.

You can find the test [here](https://jsperf.com/moment-js-instantiation-performance-comparison) and you can clearly see that using a timestamp is 4-5 times faster than using an RFC 3339 format string even with `Date`! Moment's performance is pretty shocking with string dates so not even worth thinking about using it. Instead timestamps are yet again faster. Small performance gain can be achieved by instantiating the `Date` object and passing it into Moment.js instead of passing the timestamp straight into Moment.js, which is interesting.
