### ISSUE TITLE
Separate messages for the day before yesterday and the day after tomorrow

### ISSUE THREAD

**Issue by Menelion** [moment/moment#756]
Creating this issue for discussion as suggested by @ichernev.  
In many languages there are separate words for the day before yesterday and for the day after tomorrow:    
- Ukrainian: Позавчора, післязавтра
- Russian: позавчера, послезавтра
- French: Avant-hier, après-demain
- Spanish: Anteayer, Pasado mañana
- Swedish: Förrgår, Övermorgon
- German: Vorgestern, Übermorgen

So do we need this in Moment.js?  
If the answer is "yes", I can code this out as well as modify corresponding languages and unit tests :).

**Comment by yo-less** [comment]
Sorry to reopen the discussion, but has this been somehow implemented in the meantime? 

'moment.js' is running as part of the [MagicMirror](https://github.com/MichMich/MagicMirror) project and in the calendar module it's weird to see that for events that occur tomorrow it gives the German word for tomorrow and in the events that occur the day after tomorrow, it gives the German phrase for "in a day". Now, this is really confusing, because in German "in a day" and "tomorrow" are basically the same thing and the day after tomorrow would be "in two days". 

Ideally, instead of "in a day" it would give the German "übermorgen" (and also "vorgestern" for "the day before yesterday" but since the calendar module only shows events that are coming up, it doesn't really bother me at this stage :smile:). I'm not familiar with the moment.js framework, but is there a quick fix I could code into my local files?

**Comment by maggiepint** [comment]
I think this can be done by extending calendar. See #3175

**Comment by ichernev** [comment]
@yo-less you also wanted to change the german locale? Either use locale inheritance or provide a pr for that https://github.com/moment/moment/pull/2774

**Comment by yo-less** [comment]
Wow, you guys are fast!

@maggiepint which calendar.js file would I be editing? The one in /src/lib/locale or the one in /src/lib/moment?

Well, thanks to both of you. I have tried playing around with the moment.js package but I need to find out first how I can make any adjustments that filter through the node.js installation they're using because as of now, changing each and every translation in the 'de.js' file doesn't change anything on my screen.

**Comment by maggiepint** [comment]
@yo-less you shouldn't need to edit anything in our source. Use the extensibility that I put in there to define moment.calendarFormat in your source code. Then override the 'de' locale with any additional options you need.

**Comment by yo-less** [comment]
@maggiepint Excellent, that's even nicer than I had anticipated, thanks. Will start experimenting with that. And, again, thanks for the great response time, you guys are awesome ^^
