### ISSUE TITLE
EN-GB localization may be wrong

### ISSUE THREAD

**Issue by frapontillo** [moment/moment#774]
I don't know if I'm right, but the `en-gb` localization says that the "L" format is "DD/MM/YYYY". Shouldn't it be "MM/DD/YYYY"?

**Comment by jcmcneal** [comment]
Sorry to bring up an old issue but this is the closest one related to what I'm experiencing. I am simply needing to format dates by locale.

en-US: MM/DD/YYYY
en-GB: DD/MM/YYYY

I get the locale from the HTTP headers on server-side, it returns to front-end and I use moment.locale('string') to set it. It works great! I modify the languages in Chrome and when I get en-GB it formats like it's supposed to above.

I live in the US and the problem is when I talk to people in London they're telling me it's formatting in the US format for them. They even get en-GB from the server-side so this just boggles my mind. Why would it work for me but not for them?
