### ISSUE TITLE
Effects of ECMAScript 15.9.1.8

### ISSUE THREAD

**Issue by mattjohnsonpint** [moment/moment#831]
It's recently come to my attention that there is a flaw in the ECMAScript specification that almost all browsers use for their JavaScript implementation.

This is discussed here:
http://stackoverflow.com/a/16951442/634824

The actual spec is in [ECMAScript 5.1 section 15.9.1.8](http://es5.github.io/#x15.9.1.8)

The troubling part is as follows:

> The implementation of ECMAScript should not try to determine whether the exact time was subject to daylight saving time, but just whether daylight saving time would have been in effect if the current daylight saving time algorithm had been used at the time. This avoids complications such as taking into account the years that the locale observed daylight saving time year round.
> 
> If the host environment provides functionality for determining daylight saving time, the implementation of ECMAScript is free to map the year in question to an equivalent year (same leap-year-ness and same starting week day for the year) for which the host environment provides daylight saving time information. The only restriction is that all equivalent years should produce the same result.

It ends up that Firefox, Chrome, Safari and Node.js all take the "easy route" and apply the current time zone rules to past dates.  Even if the operating system has more data about past dates, they do not pick it up!  Of those tested, only IE is going the route of providing accurate data for past dates (and we all know that Windows time zones are proprietary anyway).

I am really upset with ECMA right now.  This is messed up on so many levels.

That said, there are now many JS libraries I will have to evaluate to see how they are affected by this.  Off-hand, do you know of anything with in moment.js that assumes that the local system time has the correct time zone offset?

Just to restate the severity of the issue another way:  Even if the local operating system has a fully consistent and up-to-date time zone database (regardless of Windows or TZDB zones) - most JavaScript runtimes will only ask for the _current rule_ and then apply that to ALL dates.

My gut says that probably momentjs might only be affected for parsing and formatting, but moment-timezone might be affected more severely - depending on how little or how much it relies on the host environment instead of the raw tzdb data.

Please let me know your thoughts on this subject.  And thanks as always.

**Comment by mj1856** [comment]
FYI - This is starting to be resolved across many browsers, through two spec changes:

In ECMA-262 (ECMAScript 6) :

> **20.3.1.8 Daylight Saving Time Adjustment**
An implementation dependent algorithm using best available information on time zones to determine the local daylight saving time adjustment DaylightSavingTA(t), measured in milliseconds. An implementation of ECMAScript is expected to make its best effort to determine the local daylight saving time adjustment.

> NOTE It is recommended that implementations use the time zone information of the IANA Time Zone Database http://www.iana.org/time-zones/.

In ECMA-402 (ECMAScript Internationalization API) 1.0:

> **12.3.2 Intl.DateTimeFormat.prototype.format**
> ...
> The calculations should use best available information about the specified calendar and time zone. If the calendar is "gregory", then the calculations must match the algorithms specified in ES5, 15.9.1, except that calculations are not bound by the restrictions on the use of best available information on time zones for local time zone adjustment and daylight saving time adjustment imposed by ES5, 15.9.1.7 and 15.9.1.8.

In ECMA-402 (ECMAScript Internationalization API) 2.0:

> **12.3.4 DateTime Format Functions**
> ...
> The calculations should use best available information about the
specified calendar and timeZone, including current and historical information about time zone offsets from UTC and daylight saving time rules. If the calendar is "gregory", then the calculations must match the algorithms specified in ES2015, 20.3.1.

Implementation of ES6 and ECMA-402/2.0 will be slow, but ECMA-402/1.0 is already partially implemented in some browsers.   Checking this specific issue in Chrome 45, and it still isn't fixed.  Though it is fixed in IE11.
