### ISSUE TITLE
Access to original constructor string

### ISSUE THREAD

**Issue by mpeechatt** [moment/moment#945]
When someone creates an invalid date (ex. var a = moment("this is not a date"); ), is there a way to access the original string that was used to create the moment object? If not, could this possibly be added?

**Comment by murphyke** [comment]
I notice that the `_i` property is still going strong here in 2020.

FWIW, I also have a use case where I need both the original string and the moment in order to give the most natural feedback to the user. Being able to obtain the constructor argument from the moment would be (is?) nice to have.

People interested in using `_i` could throw in a unit test and use a fixed/locked version of momentjs.
